# Generated by Django 5.2.6 on 2026-07-29 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAuditRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_key', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('completed', 'completed'), ('failed', 'failed')], db_index=True, default='pending', max_length=16)),
                ('category', models.CharField(blank=True, default='', max_length=64)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('issue_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('failure_message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='audits.productauditrun')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_audit_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('view_product_audits', 'Kan het productauditdashboard bekijken'), ('run_product_audits', 'Kan productaudits uitvoeren'), ('view_product_audit_history', 'Kan audithistorie bekijken')],
            },
        ),
        migrations.CreateModel(
            name='ProductAuditIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=80)),
                ('severity', models.CharField(choices=[('info', 'info'), ('warning', 'warning'), ('error', 'error'), ('critical', 'critical')], db_index=True, max_length=16)),
                ('category', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('product_slug', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('variant_id', models.CharField(blank=True, default='', max_length=120)),
                ('field', models.CharField(blank=True, default='', max_length=120)),
                ('message', models.TextField()),
                ('expected', models.TextField(blank=True, default='')),
                ('actual', models.TextField(blank=True, default='')),
                ('file_path', models.CharField(blank=True, default='', max_length=300)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='audits.productauditrun')),
            ],
            options={
                'ordering': ['severity', 'code', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='productauditrun',
            index=models.Index(fields=['audit_key', '-created_at'], name='audits_prod_audit_k_f64daa_idx'),
        ),
    ]
