# Generated by Django 5.2.6 on 2026-07-29 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productauditrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'running')), fields=('audit_key',), name='unique_running_audit_per_key'),
        ),
    ]
