from .products_koekenpannen import PRODUCTS
TOP10_BY_SIZE = {
    28: [
       PRODUCTS["greenpan_barcelona_pro_28"],
       PRODUCTS["kochstar_essenz_28"],
       PRODUCTS["habonne_hybrid_28"],
       PRODUCTS["greenchef_diamond_28"],
       PRODUCTS["bk_easy_induction_28"],
       PRODUCTS["brabantia_dusk_28"],
       PRODUCTS["tefal_renew_28"],
       PRODUCTS["bk_enjoy_28"],
       PRODUCTS["ibenzoa_rvs_28"],
       PRODUCTS["debuyer_ceranoa_28"],
   ],
   24: [
       PRODUCTS["greenpan_barcelona_pro_24"],
       PRODUCTS["kochstar_essenz_24"],
       PRODUCTS["demeyere_alu_pro_5_ceraforce_24"],
       PRODUCTS["greenchef_diamond_24"],
       PRODUCTS["bk_easy_induction_24"],
       PRODUCTS["greenpan_torino_24"],
       PRODUCTS["tefal_renew_24"],
       PRODUCTS["bk_enjoy_24"],
       PRODUCTS["ikea_hemlagad_keramisch_24"],
       PRODUCTS["habonne_hybrid_24"],
   ],
    26: [
        PRODUCTS["greenpan_barcelona_pro_26"],
        PRODUCTS["greenchef_vintage_26"],
        PRODUCTS["demeyere_alu_pro_5_ceraforce_26"],
        PRODUCTS["bk_easy_induction_26"],
        PRODUCTS["fissler_cenit_ceramic_26"],
        PRODUCTS["greenpan_venice_pro_26"],
        PRODUCTS["scanpan_ceramic_26"],
    ],
    20: [
        PRODUCTS["greenpan_barcelona_pro_20"],
        PRODUCTS["kochstar_essenz_20"],
        PRODUCTS["demeyere_alu_pro_5_ceraforce_20"],
        PRODUCTS["greenchef_diamond_20"],
        PRODUCTS["bk_easy_induction_20"],
        PRODUCTS["greenpan_mayflower_20"],
        PRODUCTS["tefal_renew_20"],
        PRODUCTS["bk_enjoy_20"],
        PRODUCTS["hema_milano_20"],
        PRODUCTS["habonne_hybrid_20"],
    ],
30: [
        PRODUCTS["greenpan_barcelona_pro_30"],
        PRODUCTS["kochstar_stein_30"],
        PRODUCTS["demeyere_alu_pro_5_ceraforce_30"],
        PRODUCTS["greenchef_diamond_30"],
        PRODUCTS["bk_easy_induction_30"],
        PRODUCTS["greenpan_torino_30"],
        PRODUCTS["tefal_renew_30"],
        PRODUCTS["brabantia_indu_plus_r_30"],
        PRODUCTS["scanpan_techniq_30"],
    ],
32: [
        PRODUCTS["greenpan_barcelona_pro_32"],
        PRODUCTS["demeyere_alu_pro_5_ceraforce_32"],
        PRODUCTS["combekk_ceramic_pro_32"],
        PRODUCTS["bk_easy_induction_32"],
        PRODUCTS["greenpan_torino_32"],
        PRODUCTS["tefal_renew_32"],
        PRODUCTS["greenchef_diamond_30"],
        PRODUCTS["ikea_hemlagad_keramisch_32"],
        PRODUCTS["scanpan_ceramic_32"],
    ]
}