SNIJPLANKEN_PRODUCTS = [
    {
        "slug": "boosblocks_pro_maple",
        "name": "BoosBlocks Pro Maple Series – End-grain Esdoorn (51×38×6 cm)",
        "brand": "BoosBlocks",
        "material": "Esdoornhout",
        "image": "snijplank01_boosblocks.jpg",
        "image_path": "images",
        "description": "Professionele end-grain snijplank van Noord-Amerikaans esdoorn, ontworpen voor chefs die dagelijks intensief snijden.",
        "pros": [
            "End-grain oppervlak dat messen spaart",
            "Dik massief esdoornhout voor maximale stabiliteit",
            "Dubbelzijdig bruikbaar en eenvoudig te onderhouden",
        ],
        "cons": [
            "Zwaar door massieve constructie",
            "Regelmatig oliën aanbevolen",
        ],
        "rating": 5,
        "rating_count": 220,
        "price": "323.64",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.boosblocks.de/nl/product/boos-hard-maple-reversible-end-grain-chopping-with-grips-51x38x6cm/",
        "price_range": "€€€€",
        "verdict": "Topkwaliteit voor professionele keukens en intensief dagelijks gebruik.",
        "award": "🏆 Beste keuze",
    },
    {
        "slug": "ikea_aptitlig_bamboe",
        "name": "IKEA APTITLIG Bamboe Snijplank (45×28 cm)",
        "brand": "IKEA",
        "material": "Bamboe",
        "image": "snijplank02_ikea.jpg",
        "image_path": "images",
        "description": "Lichte, duurzame bamboeplank met natuurlijke afwerking – perfect voor dagelijks snijden en serveren.",
        "pros": [
            "Milieuvriendelijk bamboe-materiaal",
            "Dubbelzijdig te gebruiken",
            "Licht en makkelijk te hanteren",
        ],
        "cons": [
            "Gevoelig voor vocht bij verkeerd onderhoud",
            "Niet geschikt voor de vaatwasser",
        ],
        "rating": 3,
        "rating_count": 320,
        "price": "6.99",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.ikea.com/nl/nl/p/aptitlig-snijplank-bamboe-80233430/",
        "price_range": "€",
        "verdict": "Duurzame en voordelige keuze voor de dagelijkse keukenroutine.",
        "award": "💰 Beste budgetoptie",
    },
    {
        "slug": "kaamut_walnoot_endgrain",
        "name": "KAAMUT® Professionele Snijplank Walnoot – End-Grain 40×27,5×3,5 cm",
        "brand": "KAAMUT",
        "material": "Walnoothout",
        "image": "snijplank08_kaamut.jpg",
        "image_path": "images",
        "description": "Massieve professionele snijplank van Noord-Amerikaanse walnoot met kopshouten (end-grain) constructie. Elegant, duurzaam en perfect voor intensief gebruik.",
        "pros": [
            "Kopshout (end-grain) spaart messen en verlengt de levensduur",
            "Massief walnoothout met luxe uitstraling",
            "Voorzien van sapgeul, antislipvoetjes en handgrepen",
            "Geleverd in geschenkdoos – ook geschikt als cadeau",
        ],
        "cons": [
            "Niet vaatwasserbestendig",
            "Regelmatig oliën nodig voor behoud van kwaliteit",
        ],
        "rating": 5,
        "rating_count": 80,
        "price": "129.00",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/kaamut-professionele-snijplank-massief-kopshout-van-zwarte-walnoot-40x27-5x3-5-cm-extra-dik-duurzaam-sapgeul-en-handvaten-bijgeleverde-antislip-voetjes-luxe-geschenkdoos/9300000196972499/",
        "price_range": "€€€€",
        "verdict": "Luxe walnoothouten plank met topafwerking voor de serieuze thuiskok.",
        "award": "💎 Premium keuze",
    },
    {
        "slug": "zwilling_beukenhout_60x40",
        "name": "Zwilling Houten Snijplank (60×40 cm)",
        "brand": "Zwilling",
        "material": "Beukenhout",
        "image": "snijplank04_zwilling.jpg",
        "image_path": "images",
        "description": "Ruime beukenhouten plank van Zwilling – perfect stabiel oppervlak voor groot snijwerk.",
        "pros": [
            "Groot werkoppervlak voor bereidingen",
            "Beukenhout absorbeert minder vocht",
            "Hoogwaardige afwerking van gerenommeerd merk",
        ],
        "cons": [
            "Zwaar bij verplaatsen",
            "Niet vaatwasserbestendig",
        ],
        "rating": 4,
        "rating_count": 160,
        "price": "48.49",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.knivesandtools.nl/nl/pt/-zwilling-twin-snijplank-60x40x3-5-cm-beukenhout-35118-100.htm",
        "price_range": "€€€",
        "verdict": "Betrouwbare hardhouten plank met uitstekende snijstabiliteit.",
        "award": "",
    },
    {
        "slug": "wmf_acacia_40x32",
        "name": "WMF Acacia Snijplank (40×32 cm)",
        "brand": "WMF",
        "material": "Acaciahout",
        "image": "snijplank06_wmf.jpg",
        "image_path": "images",
        "description": "Robuuste plank van acaciahout met natuurlijke olieafwerking – fraai en duurzaam.",
        "pros": [
            "Hard acaciahout met lange levensduur",
            "Mooi donker houtpatroon",
            "Afgeronde randen voor comfort",
        ],
        "cons": [
            "Regelmatig onderhoud nodig",
            "Iets zwaarder dan gemiddelde plank",
        ],
        "rating": 4,
        "rating_count": 90,
        "price": "41.18",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.amazon.nl/WMF-Snijplank-keukenmessen-anti-slip-1879984500/dp/B07TV8S14K/",
        "price_range": "€€",
        "verdict": "Stevige acaciaplak die esthetiek met functionaliteit combineert.",
        "award": "",
    },
    {
        "slug": "namture_premium_olie_45x30",
        "name": "Namture Snijplank Hout Premium Olie – 45×30×4 cm",
        "brand": "Namture",
        "material": "Massief acaciahout",
        "image": "snijplank07_namture.jpg",
        "image_path": "images",
        "description": "Elegante houten snijplank met premium olieafwerking. Het robuuste ontwerp en natuurlijke uitstraling maken dit een uitstekende keuze voor dagelijks gebruik.",
        "pros": [
            "Massief houten constructie met natuurlijke olieafwerking",
            "Ruim formaat voor snijden en serveren",
            "Mesvriendelijk oppervlak voorkomt snel bot worden",
        ],
        "cons": [
            "Niet geschikt voor vaatwasser",
            "Regelmatig oliën nodig om de glans te behouden",
        ],
        "rating": 4,
        "rating_count": 75,
        "price": "69.99",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/namture-hakblok-acacia-classic-snijplank-hout-45x30-cm-extra-dik-4-cm-premium-acaciahout-antislip-snijplank-serveerplank-borrelplank-tapasplank-luxe-geschenkdoos/9300000236075401/",
        "price_range": "€€€",
        "verdict": "Stevige houten plank met premium afwerking en natuurlijk karakter.",
        "award": "",
    },
    {
        "slug": "wooden_amsterdam_walnoot_40x30",
        "name": "Wooden Amsterdam End-Grain Snijplank Walnoot (40×30 cm)",
        "brand": "Wooden Amsterdam",
        "material": "Walnoothout",
        "image": "snijplank03_woodenamsterdam.jpg",
        "image_path": "images",
        "description": "Ambachtelijke end-grain plank van massief walnoothout – stijlvol, mesvriendelijk en uiterst duurzaam.",
        "pros": [
            "Diepe walnoottint met luxueuze uitstraling",
            "End-grain constructie verlengt de levensduur van messen",
            "Met de hand vervaardigd in Nederland",
        ],
        "cons": [
            "Hogere aanschafprijs",
            "Regelmatig onderhoud vereist",
        ],
        "rating": 5,
        "rating_count": 45,
        "price": "219.00",
        "currency": "EUR",
        "availability": "LimitedAvailability",
        "affiliate_url": "https://woodenamsterdam.com/nl/product/end-grain-cutting-board-walnut/",
        "price_range": "€€€€",
        "verdict": "Luxe en vakmanschap in één – de ideale premium snijplank.",
        "award": "",
    },
    {
        "slug": "hema_beukenhout_24x35",
        "name": "HEMA Snijplank Beukenhout (24×35 cm)",
        "brand": "HEMA",
        "material": "Beukenhout",
        "image": "snijplank05_hema.jpg",
        "image_path": "images",
        "description": "Compacte beukenhouten plank – ideaal als serveerplank of tweede snijoppervlak.",
        "pros": [
            "Licht van gewicht en eenvoudig te reinigen",
            "Vlakke randen voor stabiel gebruik",
            "Vervaardigd uit FSC-gecertificeerd hout",
        ],
        "cons": [
            "Minder geschikt voor zwaar hakwerk",
            "Moet droog bewaard worden",
        ],
        "rating": 3,
        "rating_count": 60,
        "price": "9.99",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.hema.nl/koken-tafelen/koken/snijplanken/snijplank-24x35x1.5-beukenhout-80850026.html",
        "price_range": "€",
        "verdict": "Betaalbare keuze voor lichte snijtaken en serveren.",
        "award": "",
    },
    {
        "slug": "continenta_rubberwood_30x25",
        "name": "Continenta Snijplank Rubberwood – 30×25 cm",
        "brand": "Continenta",
        "material": "Rubberwood",
        "image": "snijplank09_continenta.jpg",
        "image_path": "images",
        "description": "Compacte snijplank van duurzaam rubberwood. Perfect voor dagelijks gebruik, fruit en groenten of als stijlvolle serveerplank.",
        "pros": [
            "Duurzaam rubberwood met natuurlijke uitstraling",
            "Mesvriendelijk oppervlak dat snijvlakken spaart",
            "Ideaal formaat voor klein snijwerk en serveren",
        ],
        "cons": [
            "Niet geschikt voor zwaar hakwerk",
            "Regelmatig onderhoud met olie aanbevolen",
        ],
        "rating": 3,
        "rating_count": 55,
        "price": "29.95",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/continenta-snijplank-in-rubberhout-kopshout-35x25xh2cm/9300000021506007/",
        "price_range": "€€",
        "verdict": "Handige en duurzame kleine plank voor dagelijks gebruik.",
        "award": "",
    },
    {
        "slug": "pointvirgule_bamboe_40x30",
        "name": "Point-Virgule Bamboe Snijplank – 40×30×1 cm",
        "brand": "Point-Virgule",
        "material": "Bamboe",
        "image": "snijplank10_pointvirgule.jpg",
        "image_path": "images",
        "description": "Dunne, lichtgewicht snijplank van duurzaam bamboe. Ideaal voor dagelijks gebruik en gemakkelijk te reinigen dankzij het gladde oppervlak.",
        "pros": [
            "Gemaakt van duurzaam bamboe met natuurlijke uitstraling",
            "Licht en handzaam — gemakkelijk op te bergen",
            "Glad oppervlak dat messen spaart",
        ],
        "cons": [
            "Geen sapgeul of handgrepen",
            "Dunnere uitvoering — minder geschikt voor zwaar hakwerk",
        ],
        "rating": 4,
        "rating_count": 85,
        "price": "17.95",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/point-virgule-snijplank-bamboe-large-40x30x1cm/9300000056867854/",
        "price_range": "€€",
        "verdict": "Betaalbare, praktische snijplank van duurzaam bamboe voor dagelijks gebruik.",
        "award": "",
    },
]
