PRODUCTS = {
    # 28CM KOEKENPANNEN
    "greenpan_barcelona_pro_28": {
        "slug": "greenpan-barcelona-pro-28",
        "name": "GreenPan Barcelona Pro",
        "description": "Hoogwaardige keramische PFAS-vrije pan met Thermolon Infinity Pro-coating en inductiebodem.",
        "brand": "GreenPan",
        "diameter": 28,
        "material": "Keramisch",
        "features": ["Inductie", "Ovenbestendig", ],
        "rating": 5,
        "rating_count": 230,
        "price": 88.09,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/greenpan-barcelona-pro-koekenpan-met-keramische-antikleeflaag-28-cm/9300000111189161/",
        "award": "🏆 Beste keuze",
        "price_range": "€€€",
        "image": "koekenpan01_greenpan_barcelona_pro.jpg",
        "image_path": "images/koekenpannen",
        "pros": [
            "PFAS-vrij Thermolon-coating",
            "Uitstekende warmteverdeling",
            "Ovenbestendig tot 220 °C",
        ],
        "cons": [
            "Vrij zwaar",
            "Hogere prijs",
        ],
        "verdict": "De ultieme keuze voor wie dagelijks gezond en PFAS-vrij wil koken.",
    },

    "kochstar_essenz_28": {
        "slug": "kochstar-essenz-28",
        "name": "Kochstar Essenz",
        "description": "Betaalbare PFAS-vrije keramische pan voor dagelijks gebruik.",
        "brand": "Kochstar",
        "diameter": 28,
        "material": "Keramisch",
        "features": ["PFAS-vrij", "Lichtgewicht", ],
        "rating": 4,
        "rating_count": 95,
        "price": 13.99,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/kochstar-essenz-zwart-keramische-koekenpan-28cm-pfas-vrij-inductie-koekenpan-inductie-pan-keramische-anti-aanbaklaag-koelgreep-ovenbestendig-tot-130-c-zwart/9300000231848099/",
        "award": "💰 Budget keuze",
        "price_range": "€",
        "image": "koekenpan02_kochstar_essenz.jpg",
        "image_path": "images/koekenpannen",
        "pros": [
            "Goede prijs-kwaliteit",
            "PFAS-vrij",
            "Snel warm",
        ],
        "cons": [
            "Niet ovenbestendig",
            "Kortere levensduur",
        ],
        "verdict": "Een uitstekende keuze voor wie betaalbaar PFAS-vrij wil koken.",
    },

    "habonne_hybrid_28": {
        "slug": "habonne-hybrid-28",
        "name": "Habonne Hybrid RVS Triply",
        "description": "Professionele RVS-pan met PFAS-vrije hybride laag en triply-bodem.",
        "brand": "Habonne",
        "diameter": 28,
        "material": "RVS (Triply)",
        "features": ["Keramische laag", "Inductie"],
        "rating": 5,
        "rating_count": 110,
        "price": 79.00,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/habonne-hybrid-rvs-triply-koekenpan-pfas-vrij-28cm/9300000239379982/",
        "award": "",
        "price_range": "€€€€",
        "image": "koekenpan03_habonne_hybrid.jpg",
        "image_path": "images/koekenpannen",
        "pros": [
            "Driedubbele bodem",
            "Duurzaam RVS",
            "Inductiegeschikt",
        ],
        "cons": [
            "Relatief zwaar",
            "Hogere prijs",
        ],
        "verdict": "Een hoogwaardige pan voor wie topprestaties en lange levensduur wil.",

    },

    "greenchef_diamond_28": {
        "slug": "greenchef-diamond-28",
        "name": "GreenChef Diamond Induction",
        "description": "PFAS-vrije keramische pan met diamantdeeltjes en hoge slijtvastheid.",
        "brand": "GreenChef",
        "diameter": 28,
        "material": "Keramisch",
        "features": ["Diamantcoating", "Duurzaam"],
        "rating": 4.5,
        "rating_count": 150,
        "price": 27.89,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/greenchef-diamond-koekenpan-28cm-zwart-inductie-pfas-vrij/9200000130094499/?cid=1767514943542-4612498994724&bltgh=a430e429-5227-4b34-ac4d-8d400f4a85b8.ProductList_Middle.0.ProductTitle",
        "price_range": "€€",
        "image": "koekenpan04_greenchef_diamond.jpg",
        "image_path": "images/koekenpannen",
        "pros": [
            "Extra duurzame diamantcoating",
            "Goede hitteverdeling",
            "Gemakkelijk schoon te maken",
        ],
        "cons": [
            "Niet ovenbestendig",
        ],
        "verdict": "Solide keuze voor wie een betrouwbare en duurzame keramische pan zoekt.",
    },

    "bk_easy_induction_28": {
        "slug": "bk-easy-induction-28",
        "name": "BK Easy Induction Ceramic",
        "description": "PFAS-vrije keramische pan met koele greep en stevige bodem.",
        "brand": "BK",
        "diameter": 28,
        "material": "Keramisch",
        "features": ["Koele greep", "Inductie"],
        "rating": 4.5,
        "rating_count": 200,
        "price": 40.99,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/bk-easy-induction-ceramic-koekenpan-28-cm-pfas-vrij-inductie/9300000032109237/",
        "award": "🥇 Meest gekozen",
        "price_range": "€€",
        "image": "koekenpan05_bk_easy_induction.jpg",
        "image_path": "images/koekenpannen",
        "pros": [
            "Goede prijs-kwaliteit",
            "Snelle opwarming",
            "Koele handgreep",
        ],
        "cons": [
            "Niet ovenbestendig",
        ],
        "verdict": "Praktische pan voor dagelijks gebruik met betrouwbare antiaanbaklaag.",
    },

    "brabantia_dusk_28": {
        "slug": "brabantia-dusk-28",
        "name": "Brabantia Dusk",
        "description": "Moderne keramische PFAS-vrije pan met stijlvolle afwerking.",
        "brand": "Brabantia",
        "diameter": 28,
        "material": "Keramisch",
        "features": ["PFAS-vrij", "Stevige bodem"],
        "rating": 4.5,
        "rating_count": 75,
        "price": 44.00,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/brabantia-dusk-r-ns-koekenpan-o-28cm-100-pfas-vrij/9300000225842102/",
        "price_range": "€€",
        "image": "koekenpan06_brabantia_dusk.jpg",
        "image_path": "images/koekenpannen",
        "pros": [
            "PFAS-vrij en krasbestendig",
            "Comfortabele handgreep",
            "Stabiele inductiebodem",
        ],
        "cons": [
            "Niet vaatwasserbestendig",
        ],
        "verdict": "Een stijlvolle keuze voor wie gezond koken combineert met design.",
    },

    "tefal_renew_28": {
        "slug": "tefal-renew-28",
        "name": "Tefal Renew+",
        "description": "Gemaakt van gerecycled aluminium met PFAS-vrije laag.",
        "brand": "Tefal",
        "diameter": 28,
        "material": "Keramisch",
        "features": ["Gerecycled aluminium", "Thermo-Spot"],
        "rating": 4,
        "rating_count": 310,
        "price": 55.78,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/tefal-renew-koekenpan-o28-cm-keramisch-pfas-vrij-geschikt-voor-inductie/9300000118641472/",
        "award": "",
        "price_range": "€€",
        "image": "koekenpan07_tefal_renew.jpg",
        "image_path": "images/koekenpannen",
        "pros": [
            "Duurzaam gerecycled materiaal",
            "Goede warmtegeleiding",
            "Thermo-Spot-hitte-indicator",
        ],
        "cons": [
            "Niet ovenbestendig",
        ],
        "verdict": "Betrouwbare keuze voor milieubewuste gebruiker met modern comfort.",
    },

    "bk_enjoy_28": {
        "slug": "bk-enjoy-28",
        "name": "BK Enjoy",
        "description": "Betaalbare keramische pan met natuurlijke PFAS-vrije coating.",
        "brand": "BK",
        "diameter": 28,
        "material": "Keramisch",
        "features": ["Lichtgewicht", "Eenvoudig schoon te maken"],
        "rating": 4,
        "rating_count": 120,
        "price": 34.90,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://bk.nl/products/enjoy-koekenpan-zwart-28-cm?srsltid=AfmBOoqIJ-LNGVZmMJZThGeFbB_cW7XcZXFB0rnlbkDqbVjERLMNIpFY",
        "price_range": "€€",
        "image": "koekenpan08_bk_enjoy.jpg",
        "image_path": "images/koekenpannen",
        "pros": [
            "Licht van gewicht",
            "Goede warmtegeleiding",
            "Gemakkelijk schoon te maken",
        ],
        "cons": [
            "Niet geschikt voor oven",
        ],
        "verdict": "Een lichte en praktische pan voor dagelijks gezond koken.",
    },

    "demeyere_alu_pro_5_28": {
        "slug": "demeyere_alu_pro_5_28",
        "name": "Demeyere Alu Pro 5 Ceraforce",
        "description": "Hoogwaardige koekenpan van Demeyere met PFAS-vrije Ceraforce® keramische coating en uitstekende warmteverdeling, ideaal voor intensief gebruik.",
        "brand": "Demeyere",
        "diameter": 28,
        "material": "Keramisch (Ceraforce®)",
        "features": [
            "PFAS-vrije Ceraforce® coating",
            "Geschikt voor inductie",
            "Stabiele warmteverdeling",
            "Professionele bouwkwaliteit",
        ],
        "rating": 5,
        "rating_count": 210,
        "price": 92.00,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/demeyere-12628-alu-pro-5-ceraforce-antikleef-bakpan-28-cm/9300000032747130/?cid=1771998087196-2866415484188&bltgh=da336c0f-e059-4d0a-a90c-7bf56546ff60.ProductList_Middle.1.ProductTitle",
        "award": "💎 Premium keuze",
        "price_range": "€€€€",
        "image": "koekenpan_demeyere_alu_pro_5_28.jpg",
        "image_path": "images/koekenpannen",
        "pros": [
            "Zeer gelijkmatige warmteverdeling",
            "Stevige, professionele afwerking",
            "Geschikt voor hoge temperaturen",
        ],
        "cons": [
            "Hogere prijsklasse",
            "Relatief zwaar",
        ],
        "verdict": "Een premium koekenpan voor wie maximale prestaties en duurzaamheid zoekt.",
    },

    "debuyer_ceranoa_28": {
        "slug": "debuyer-ceranoa-28",
        "name": "De Buyer Ceranoa",
        "description": "Hoogwaardige keramische pan zonder PFAS met ergonomische greep.",
        "brand": "De Buyer",
        "diameter": 28,
        "material": "Keramisch",
        "features": ["PFAS-vrij", "Premium afwerking"],
        "rating": 4.5,
        "rating_count": 35,
        "price": 100.83,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/debuyer-ceranoa-koekenpan-28cm/9300000232243696/",
        "price_range": "€€€",
        "image": "koekenpan10_debuyer_ceranoa.jpg",
        "image_path": "images/koekenpannen",
        "pros": [
            "Gelijkmatige warmteverdeling",
            "PFAS-vrije premium keramiek",
            "Ergonomisch handvat",
        ],
        "cons": [
            "Niet vaatwasserbestendig",
        ],
        "verdict": "Een verfijnde keramische pan voor wie comfort en prestaties zoekt.",
    },

    "greenpan_mayflower_28": {
        "slug": "greenpan-mayflower-28",
        "name": "GreenPan Mayflower",
        "description": "Stijlvolle keramische koekenpan met PFAS-vrije Thermolon™ coating en inductiebodem.",
        "brand": "GreenPan",
        "diameter": 28,
        "material": "Keramisch (Thermolon™)",
        "features": [
            "Thermolon™ PFAS-vrije coating",
            "Geschikt voor inductie",
            "Goede warmteverdeling",
        ],
        "rating": 4.5,
        "rating_count": 185,
        "price": 51.99,
        "currency": "EUR",
        "availability": "InStock",
        "award": "",
        "price_range": "€€",
        "image": "greenpan-mayflower-28cm.jpg",
        "image_path": "images/koekenpannen",
        "affiliate_url": "https://www.bol.com/nl/nl/p/greenpan-mayflower-pro-koekenpan-28cm-grijs-inductie-pfas-vrij/9300000091450190/?bltgh=bb8a83e1-c4d4-493f-8870-13e48481468c.BuyBlock_distinctive-feature.0.FeatureListItem",
        "pros": [
            "PFAS-vrije Thermolon™ coating",
            "Goede warmteverdeling",
            "Aantrekkelijk design",
        ],
        "cons": [
            "Minder robuust dan premium GreenPan-lijnen",
            "Geen ovenbestendige greep",
        ],
        "verdict": "Betrouwbare keuze voor milieubewuste gebruiker die stijl en gezond koken combineert.",
    },

    # 24CM KOEKENPANNEN
    "greenpan_barcelona_pro_24": {
        "slug": "greenpan-barcelona-pro-24",
        "name": "GreenPan Barcelona Pro",
        "description": "Hoogwaardige keramische PFAS-vrije pan met Thermolon Infinity Pro-coating en inductiebodem.",
        "brand": "GreenPan",
        "diameter": 24,
        "material": "Keramisch",
        "features": ["Inductie", "Ovenbestendig", ],
        "rating": 5,
        "rating_count": 230,
        "price": 84.95,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/greenpan-barcelona-pro-bakpan-24cm/9300000117606007/?cid=1766001052865-6913292870745&bltgh=466d6737-13a4-4d21-8658-53a2976291d1.ProductList_Middle.3.ProductTitle",
        "award": "🏆 Beste keuze",
        "price_range": "€€€",
        "image": "koekenpan01_greenpan_barcelona_pro_24cm.jpg",
        "image_path": "images/koekenpannen",
        "pros": [
            "PFAS-vrij Thermolon-coating",
            "Uitstekende warmteverdeling",
            "Ovenbestendig tot 220 °C",
        ],
        "cons": [
            "Vrij zwaar",
            "Hogere prijs",
        ],
        "verdict": "De ultieme keuze voor wie dagelijks gezond en PFAS-vrij wil koken.",
    },

    "kochstar_essenz_24": {
        "slug": "kochstar-essenz-24",
        "name": "Kochstar Essenz",
        "description": "Betaalbare PFAS-vrije keramische pan voor dagelijks gebruik.",
        "brand": "Kochstar",
        "diameter": 24,
        "material": "Keramisch",
        "features": ["PFAS-vrij", "Lichtgewicht", ],
        "rating": 4,
        "rating_count": 95,
        "price": 11.99,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/kochstar-essenz-koekenpan-24cm-pfas-vrij-inductie-pan-keramische-anti-aanbaklaag-koelgreep-zwart/9300000231848093/?s2a=&bltgh=oavkqTDK0O-NutZGp0tC8g.4_67_68.70.FeatureOptionButton#productTitle",
        "award": "💰 Budget keuze",
        "price_range": "€",
        "image": "koekenpan02_kochstar_essenz_24cm.jpg",
        "image_path": "images/koekenpannen",
        "pros": [
            "Goede prijs-kwaliteit",
            "PFAS-vrij",
            "Snel warm",
        ],
        "cons": [
            "Niet ovenbestendig",
            "Kortere levensduur",
        ],
        "verdict": "Een uitstekende keuze voor wie betaalbaar PFAS-vrij wil koken.",
    },

    "demeyere_alu_pro_5_ceraforce_24": {
        "slug": "demeyere_alu_pro_5_ceraforce_24",
        "name": "Demeyere Alu Pro 5 Ceraforce",
        "description": "Hoogwaardige premium koekenpan met PFAS-vrije Ceraforce® keramische coating.",
        "brand": "Demeyere",
        "diameter": 24,
        "material": "Keramisch (Ceraforce®)",
        "features": ["Inductie", "PFAS-vrij", "Professionele kwaliteit"],
        "rating": 4.5,
        "rating_count": 180,
        "price": 79.23,
        "price_range": "€€€€",
        "currency": "EUR",
        "availability": "InStock",
        "image": "demeyere-alu-pro-5-ceraforce-24cm.jpg",
        "image_path": "images/koekenpannen",
        "affiliate_url": "https://www.bol.com/nl/nl/p/demeyere-12624-alu-pro-5-ceraforce-bakpan-antikleef-24-cm/9300000032747131/?Referrer=ADVNLGOO002032-S--9300000032747131-PMAX-C-22285073478&gad_source=1&gad_campaignid=22291735154&gclid=Cj0KCQiA6Y7KBhCkARIsAOxhqtNVVMuh1dA0qoxIOaXlKNyUZJE4uYNpa7fVsS_Lz5ApIq6b53em-2EaAqAoEALw_wcB",
        "award": "💎 Premium keuze",
        "pros": [
            "PFAS-vrije Ceraforce® keramische coating",
            "Zeer stabiele en gelijkmatige warmteverdeling",
            "Uitstekend geschikt voor inductie",
        ],
        "cons": [
            "Zwaarder dan gemiddelde keramische pannen",
            "Hoger prijsniveau",
        ],
        "verdict": "De beste premium keuze voor wie een duurzame, PFAS-vrije keramische koekenpan van 24 cm zoekt met professionele prestaties.",
    },

    "greenchef_diamond_24": {
        "slug": "greenchef-diamond-24",
        "name": "GreenChef Diamond Induction",
        "description": "PFAS-vrije keramische pan met diamantdeeltjes en hoge slijtvastheid.",
        "brand": "GreenChef",
        "diameter": 24,
        "material": "Keramisch",
        "features": ["Diamantcoating", "Duurzaam"],
        "rating": 4.5,
        "rating_count": 150,
        "price": 26.99,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/greenchef-diamond-inductie-koekenpan-o24-cm-keramisch-pfas-vrij-best-getest/9200000130094485/?cid=1766001634365-9920851129864&bltgh=c299c631-11a5-413a-90cd-19684dc9676d.ProductList_Middle.0.ProductTitle",
        "price_range": "€€",
        "image": "koekenpan04_greenchef_diamond_24cm.jpg",
        "image_path": "images/koekenpannen",
        "pros": [
            "Extra duurzame diamantcoating",
            "Goede hitteverdeling",
            "Gemakkelijk schoon te maken",
        ],
        "cons": [
            "Niet ovenbestendig",
        ],
        "verdict": "Solide keuze voor wie een betrouwbare en duurzame keramische pan zoekt.",
    },

    "bk_easy_induction_24": {
        "slug": "bk-easy-induction-24",
        "name": "BK Easy Induction Ceramic",
        "description": "PFAS-vrije keramische pan met koele greep en stevige bodem.",
        "brand": "BK",
        "diameter": 24,
        "material": "Keramisch",
        "features": ["Koele greep", "Inductie"],
        "rating": 4.5,
        "rating_count": 200,
        "price": 37.99,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/bk-easy-induction-ceramic-koekenpan-o24-cm-pfas-vrij/9300000032891762/?Referrer=NLGOOFS&utm_source=google&utm_medium=free_shopping",
        "price_range": "€€",
        "award": "🥇 Meest gekozen",
        "image": "koekenpan05_bk_easy_induction_24cm.jpg",
        "image_path": "images/koekenpannen",
        "pros": [
            "Goede prijs-kwaliteit",
            "Snelle opwarming",
            "Koele handgreep",
        ],
        "cons": [
            "Niet ovenbestendig",
        ],
        "verdict": "Praktische pan voor dagelijks gebruik met betrouwbare antiaanbaklaag.",
    },

    "greenpan_torino_24": {
        "slug": "greenpan_torino_24",
        "name": "GreenPan Torino",
        "description": "Betrouwbare PFAS-vrije keramische koekenpan voor dagelijks gebruik.",
        "brand": "GreenPan",
        "diameter": 24,
        "material": "Keramisch",
        "features": ["Inductie", "PFAS-vrij"],
        "rating": 4.5,
        "rating_count": 320,
        "price": 43.00,
        "currency": "EUR",
        "availability": "InStock",
        "price_range": "€€",
        "image": "greenpan-torino-24cm.jpg",
        "image_path": "images/koekenpannen",
        "affiliate_url": "https://www.bol.com/nl/nl/p/greenpan-torino-keramische-koekenpan-24-cm/9300000036288442/?s2a=&bltgh=uLslNvwfpkdgblkATVhJ6A.4_74_75.76.FeatureOptionButton#productTitle",
        "pros": [
            "PFAS-vrije Thermolon™ keramische coating",
            "Lichtgewicht en prettig in gebruik",
            "Geschikt voor inductie en andere warmtebronnen",
        ],
        "cons": [
            "Minder robuust dan premium GreenPan-series",
            "Niet geschikt voor zeer hoge temperaturen",
        ],
        "verdict": "Een uitstekende, betaalbare keuze voor wie een gezonde PFAS-vrije koekenpan van 24 cm zoekt voor dagelijks koken.",
    },

    "tefal_renew_24": {
        "slug": "tefal-renew-24",
        "name": "Tefal Renew+",
        "description": "Gemaakt van gerecycled aluminium met PFAS-vrije laag.",
        "brand": "Tefal",
        "diameter": 24,
        "material": "Keramisch",
        "features": ["Gerecycled aluminium", "Thermo-Spot"],
        "rating": 4,
        "rating_count": 310,
        "price": 29.99,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/tefal-renew-keramische-koekenpan-o-24-cm/9300000118641479/?cid=1766058323820-2566325314987&bltgh=3d6aa0ff-bb29-48f6-b126-fd4c6a85820b.ProductList_Middle.0.ProductImage",
        "price_range": "€€",
        "award": "",
        "image": "koekenpan07_tefal_renew_24cm.jpg",
        "image_path": "images/koekenpannen",
        "pros": [
            "Duurzaam gerecycled materiaal",
            "Goede warmtegeleiding",
            "Thermo-Spot-hitte-indicator",
        ],
        "cons": [
            "Niet ovenbestendig",
        ],
        "verdict": "Betrouwbare keuze voor milieubewuste gebruiker met modern comfort.",
    },

    "bk_enjoy_24": {
        "slug": "bk-enjoy-24",
        "name": "BK Enjoy",
        "description": "Betaalbare keramische pan met natuurlijke PFAS-vrije coating.",
        "brand": "BK",
        "diameter": 24,
        "material": "Keramisch",
        "features": ["Lichtgewicht", "Eenvoudig schoon te maken"],
        "rating": 4,
        "rating_count": 120,
        "price": 29.90,
        "currency": "EUR",
        "availability": "OutOfStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/bk-enjoy-aluminium-koekenpan-o-24cm-deksel-pfas-vrij-zwart-koelgreep-ovenbestendig-tot-160/9300000227277975/?s2a=&bltgh=icgIpF7JsDpvkjY-nmpM9A.4_58_59.60.FeatureOptionButton#productTitle",
        "price_range": "€€",
        "image": "koekenpan08_bk_enjoy_24cm.jpg",
        "image_path": "images/koekenpannen",
        "pros": [
            "Licht van gewicht",
            "Goede warmtegeleiding",
            "Gemakkelijk schoon te maken",
        ],
        "cons": [
            "Niet geschikt voor oven",
        ],
        "verdict": "Een lichte en praktische pan voor dagelijks gezond koken.",
    },

    "ikea_hemlagad_keramisch_24": {
        "slug": "ikea_hemlagad_keramisch_24",
        "name": "IKEA HEMLAGAD",
        "description": " Betaalbare en toegankelijke keramische koekenpan van IKEA met een PTFE- en PFAS-vrije antiaanbaklaag.",
        "brand": "IKEA",
        "diameter": 24,
        "material": "Keramisch",
        "features": [
            "Inductie",
            "PFAS-vrij",
        ],
        "rating": 4,
        "rating_count": 500,
        "price_range": "€",
        "price": 9.99,
        "currency": "EUR",
        "availability": "InStock",
        "image": "ikea_hemlagad_keramisch_24cm.jpg",
        "image_path": "images/koekenpannen",
        "affiliate_url": "https://www.ikea.com/nl/nl/p/hemlagad-koekenpan-antiaanbaklaag-zwart-60580893/",
        "pros": [
            "Keramische coating, expliciet PFAS- en PTFE-vrij",
            "Zeer scherpe prijs",
            "Geschikt voor inductie en andere warmtebronnen",
        ],
        "cons": [
            "Minder duurzaam dan midden- en premium pannen",
            "Warmteverdeling is eenvoudiger",
        ],
        "verdict": "Een goede keuze voor wie een goedkope, PFAS-vrije koekenpan van 24 cm zoekt voor licht en dagelijks gebruik, zonder concessies te doen aan basisveiligheid.",
    },

    "habonne_hybrid_24": {
        "slug": "habonne-hybrid-24",
        "name": "Habonne Hybrid RVS Triply",
        "description": "Professionele RVS-pan met PFAS-vrije hybride laag en triply-bodem.",
        "brand": "Habonne",
        "diameter": 24,
        "material": "RVS (Triply)",
        "features": ["Keramische laag", "Inductie"],
        "rating": 5,
        "rating_count": 110,
        "price": 64.95,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.pannenhuis.nl/products/habonne-hybrid-triply-rvs-koekenpan",
        "price_range": "€€€€",
        "image": "koekenpan10_habonne_hybrid_24cm.jpg",
        "image_path": "images/koekenpannen",
        "pros": [
            "Driedubbele bodem",
            "Duurzaam RVS",
            "Inductiegeschikt",
        ],
        "cons": [
            "Relatief zwaar",
            "Hogere prijs",
        ],
        "verdict": "Een hoogwaardige pan voor wie topprestaties en lange levensduur wil.",

    },

    "berndes_b_green_24": {
        "slug": "berndes-b-green-24",
        "name": "Berndes B.Green",
        "description": "PFAS-vrije keramische koekenpan van 100% gerecycled aluminium met b.nature kwarts-antiaanbaklaag.",
        "brand": "Berndes",
        "diameter": 24,
        "material": "Keramisch (b.nature kwarts)",
        "features": ["b.nature kwarts-coating", "Inductie", "100% gerecycled aluminium", "Ovenbestendig", "Vaatwasserbestendig"],
        "rating": 4.3,
        "rating_count": 65,
        "price": 42.00,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/b-green-koekenpan-24-cm-berndes/9300000006419832/",
        "award": None,
        "price_range": "€€",
        "image": "berndes-b-green-24cm.jpg",
        "image_path": "images/koekenpannen",
        "pros": [
            "100% PFAS-vrije b.nature kwarts-coating",
            "Gemaakt van 100% gerecycled aluminium",
            "Hittebestendig tot 400 °C",
            "Duurzaam Duits merk met meer dan 100 jaar ervaring",
        ],
        "cons": [
            "Minder glanzend bakoppervlak dan sommige keramische alternatieven",
            "Zachte greep minder geschikt voor hoge oventemperaturen",
        ],
        "verdict": "Milieuvriendelijke keuze voor wie echt PFAS-vrij wil koken met een coating van volledig natuurlijke grondstoffen.",
    },

    # 26CM KOEKENPANNEN
    "greenpan_barcelona_pro_26": {
        "slug": "greenpan-barcelona-pro-26",
        "name": "GreenPan Barcelona Pro",
        "description": "Hoogwaardige keramische PFAS-vrije pan met Thermolon Infinity Pro-coating en inductiebodem.",
        "brand": "GreenPan",
        "diameter": 26,
        "material": "Keramisch",
        "features": ["Inductie", "Ovenbestendig"],
        "rating": 5,
        "rating_count": 260,
        "price": 88.00,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/greenpan-barcelona-pro-koekenpan-met-keramische-antikleeflaag-26-cm/9300000112544367/?cid=1766134118440-6260833350819&bltgh=9e5707c4-b491-40a2-8b58-a18398cb99f9.ProductList_Middle.0.ProductImage",
        "award": "🏆 Beste keuze",
        "price_range": "€€€",
        "image": "koekenpan01_greenpan_barcelona_pro_26cm.jpg",
        "image_path": "images/koekenpannen",
        "pros": [
            "PFAS-vrij Thermolon-coating",
            "Uitstekende warmteverdeling",
            "Ovenbestendig tot 220 °C",
        ],
        "cons": [
            "Vrij zwaar",
            "Hogere prijs",
        ],
        "verdict": "De ultieme keuze voor wie dagelijks gezond en PFAS-vrij wil koken.",
    },

    "greenchef_vintage_26": {
        "slug": "greenchef_vintage_26",
        "name": "GreenChef Vintage",
        "description": "Stijlvolle en betaalbare keramische koekenpan met een PFAS-vrije antiaanbaklaag.",
        "brand": "GreenChef",
        "diameter": 26,
        "material": "Keramisch",
        "features": [
            "Inductie",
            "PFAS-vrij",
            "Vintage afwerking",
        ],
        "rating": 4.5,
        "rating_count": 220,
        "price_range": "€€",
        "price": 34.90,
        "currency": "EUR",
        "availability": "InStock",
        "image": "greenchef-vintage-26cm.jpg",
        "image_path": "images/koekenpannen",
        "affiliate_url": "https://www.bol.com/nl/nl/p/greenchef-vintage-koekenpan-26cm-zwart-inductie-pfas-vrij/9200000130094513/",
        "award": "💰 Budget keuze",
        "pros": [
            "Keramische coating, expliciet PFAS-vrij",
            "Goede warmteverdeling en prettig bakresultaat",
            "Geschikt voor inductie en andere warmtebronnen",
        ],
        "cons": [
            "Minder duurzaam dan premium keramische pannen",
            "Afwerking eenvoudiger dan bij hogere prijsklassen",
        ],
        "verdict": "De beste betaalbare keuze voor wie een PFAS-vrije keramische koekenpan van 26 cm zoekt met een goede balans tussen prijs, prestaties en uitstraling.",
    },

    "demeyere_alu_pro_5_ceraforce_26": {
        "slug": "demeyere_alu_pro_5_ceraforce_26",
        "name": "Demeyere Alu Pro 5 Ceraforce",
        "description": "Hoogwaardige premium koekenpan met PFAS-vrije Ceraforce® keramische coating.",
        "brand": "Demeyere",
        "diameter": 26,
        "material": "Keramisch (Ceraforce®)",
        "features": ["Inductie", "PFAS-vrij", "Professionele kwaliteit"],
        "rating": 4.5,
        "rating_count": 210,
        "price": 84.95,
        "price_range": "€€€€",
        "currency": "EUR",
        "availability": "InStock",
        "image": "demeyere-alu-pro-5-ceraforce-26cm.jpg",
        "image_path": "images/koekenpannen",
        "affiliate_url": "https://www.bol.com/nl/nl/p/demeyere-alu-pro-ceraforce-koekenpan-26-cm/9300000045881510/?s2a=&bltgh=h103zKHjxqIbi4zamSNCeA.4_74_75.76.FeatureListItem#productTitle",
        "award": "💎 Premium keuze",
        "pros": [
            "PFAS-vrije Ceraforce® keramische coating",
            "Zeer stabiele en gelijkmatige warmteverdeling",
            "Uitstekend geschikt voor inductie",
        ],
        "cons": [
            "Zwaarder dan gemiddelde keramische pannen",
            "Hoger prijsniveau",
        ],
        "verdict": "De beste premium keuze voor wie een duurzame, PFAS-vrije keramische koekenpan van 26 cm zoekt met professionele prestaties.",
    },

    "bk_easy_induction_26": {
        "slug": "bk_easy_induction_26",
        "name": "BK Easy Induction Ceramic",
        "description": "PFAS-vrije keramische pan met koele greep en stevige bodem.",
        "brand": "BK",
        "diameter": 26,
        "material": "Keramisch",
        "features": ["Koele greep", "Inductie"],
        "rating": 4.5,
        "rating_count": 200,
        "price": 38.49,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/bk-easy-induction-ceramic-koekenpan-o26-cm-inductie-pfas-vrij/9300000032891766/?cid=1766176900717-8018805583756&bltgh=69454728-c866-471a-9628-a58300558e6c.ProductList_Middle.0.ProductImage",
        "price_range": "€€",
        "award": "🥇 Meest gekozen",
        "image": "bk_easy_induction_26cm.jpg",
        "image_path": "images/koekenpannen",
        "pros": [
            "Goede prijs-kwaliteit",
            "Snelle opwarming",
            "Koele handgreep",
        ],
        "cons": [
            "Niet ovenbestendig",
        ],
        "verdict": "Praktische pan voor dagelijks gebruik met betrouwbare antiaanbaklaag.",
    },

    "fissler_cenit_ceramic_26": {
        "slug": "fissler_cenit_ceramic_26",
        "name": "Fissler Cenit Ceramic",
        "description": "Hoogwaardige keramische koekenpan van Duitse makelij met een PFAS-vrije coating en robuuste bouwkwaliteit.",
        "brand": "Fissler",
        "diameter": 26,
        "material": "Keramisch",
        "features": [
            "Keramische PFAS-vrije coating",
            "Zeer gelijkmatige warmteverdeling",
            "Duitse kwaliteit",
        ],
        "rating": 4.5,
        "rating_count": 180,
        "price": 39.00,
        "currency": "EUR",
        "availability": "InStock",
        "price_range": "€€€",
        "image": "fissler-cenit-ceramic-26cm.jpg",
        "image_path": "images/koekenpannen",
        "affiliate_url": "https://www.bol.com/nl/nl/p/fissler-cenit-inductie-koekenpan-o-26cm/9300000120586614/?cid=1766177639078-1777086256577&bltgh=f4bd7be4-384c-4cfe-96e1-ff083d88b68b.ProductList_Middle.7.ProductTitle",
        "pros": [
            "Keramische, PFAS-vrije coating",
            "Zeer gelijkmatige warmteverdeling",
            "Duurzame constructie",
        ],
        "cons": [
            "Hoger prijsniveau dan instapmodellen",
            "Iets zwaarder",
        ],
        "verdict": "Een sterke middenklasse keuze voor wie duurzaamheid belangrijk vindt.",
    },
    "greenpan_venice_pro_26": {
        "slug": "greenpan_venice_pro_26",
        "name": "GreenPan Venice Pro Ceramic",
        "description": "Robuuste keramische koekenpan met PFAS-vrije Thermolon™ coating en roestvrijstalen handgreep, geschikt voor intensief gebruik.",
        "brand": "GreenPan",
        "diameter": 26,
        "material": "Keramisch (Thermolon™)",
        "features": [
            "Expliciet PFAS-vrij",
            "RVS handgreep, ovenbestendig",
            "Zeer stabiele inductiebodem",
        ],
        "rating": 4.5,
        "rating_count": 240,
        "price": 67.00,
        "currency": "EUR",
        "availability": "InStock",
        "price_range": "€€€",
        "image": "greenpan-venice-pro-26cm.jpg",
        "image_path": "images/koekenpannen",
        "affiliate_url": "https://www.bol.com/nl/nl/p/pan-cc001200-001-o-26-cm-aluminium/9300000021025034/?Referrer=ADVNLYAH002032-HRXEOXFOOEMTE-9300000021025034&msclkid=09cd0a55ac3a1c10919e63f482380890",
        "pros": [
            "Keramische, PFAS-vrije coating",
            "Zeer gelijkmatige warmteverdeling",
            "Duurzame constructie",
        ],
        "cons": [
            "Relatief zwaar",
            "IHoger geprijsd dan instapmodellen",
        ],
        "verdict": "Een duurzaam alternatief binnen het GreenPan-assortiment zonder concessies aan veiligheid.",
    },
    "scanpan_ceramic_26": {
        "name": "Scanpan HaptIQ",
        "slug": "scanpan_ceramic_26",
        "description": " Hoogwaardige Scandinavische koekenpan met keramische, PFAS-vrije coating en een focus op duurzaamheid.",
        "brand": "Scanpan",
        "diameter": 26,
        "material": "Keramisch",
        "features": [
            "Keramisch en PFAS-vrij",
            "Scandinavische kwaliteit",
            "Gelijkmatige warmteverdeling",
        ],
        "rating": 4,
        "rating_count": 130,
        "price": 117.00,
        "currency": "EUR",
        "availability": "InStock",
        "price_range": "€€€€",
        "image": "scanpan-ceramic-26cm.jpg",
        "image_path": "images/koekenpannen",
        "affiliate_url": "https://www.bol.com/nl/nl/p/scanpan-haptiq-koekenpan-26cm/9300000091888696/?cid=1766177547258-6261554048316&bltgh=055c1703-f402-43d9-a07c-b37e1251d795.ProductList_Middle.2.ProductImage",
        "pros": [
            "Keramisch en PFAS-vrij",
            "Zeer gelijkmatige warmteverdeling",
            "Solide bouwkwaliteit",
        ],
        "cons": [
            "Prijs hoger dan gemiddelde middenklasse",
        ],
        "verdict": "Een interessante keuze voor wie Scandinavische kwaliteit waardeert.",
    },

    # 20CM KOEKENPANNEN

    "greenpan_barcelona_pro_20": {
        "slug": "greenpan-barcelona-pro-20",
        "name": "GreenPan Barcelona Pro",
        "description": "Hoogwaardige keramische PFAS-vrije pan met Thermolon Infinity Pro-coating en inductiebodem.",
        "brand": "GreenPan",
        "diameter": 20,
        "material": "Keramisch",
        "features": ["Inductie", "Ovenbestendig", ],
        "rating": 5,
        "rating_count": 230,
        "price": 73.19,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/greenpan-barcelona-pro-bakpan-20cm/9300000118067708/?cid=1766379753550-4526062311539&bltgh=44069767-9921-4f7f-9122-4609e5ee2e20.ProductList_Middle.0.ProductTitle",
        "award": "🏆 Beste keuze",
        "price_range": "€€€",
        "image": "koekenpan01_greenpan_barcelona_pro_20cm.jpg",
        "image_path": "images/koekenpannen",
        "pros": [
            "PFAS-vrij Thermolon-coating",
            "Uitstekende warmteverdeling",
            "Ovenbestendig tot 220 °C",
        ],
        "cons": [
            "Vrij zwaar",
            "Hogere prijs",
        ],
        "verdict": "De ultieme keuze voor wie dagelijks gezond en PFAS-vrij wil koken.",
    },

    "kochstar_essenz_20": {
        "slug": "kochstar-essenz-20",
        "name": "Kochstar Essenz",
        "description": "Betaalbare PFAS-vrije keramische pan voor dagelijks gebruik.",
        "brand": "Kochstar",
        "diameter": 20,
        "material": "Keramisch",
        "features": ["PFAS-vrij", "Lichtgewicht", ],
        "rating": 4,
        "rating_count": 95,
        "price": 8.99,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/kochstar-essenz-koekenpan-20cm-pfas-vrij-inductie-pan-keramische-anti-aanbaklaag-koelgreep-zwart/9300000231848104/?cid=1766379984042-5119684659337&bltgh=9b39677e-d58b-40f0-a878-a7ecdf087af8.ProductList_Middle.0.ProductImage",
        "award": "💰 Budget keuze",
        "price_range": "€",
        "image": "koekenpan02_kochstar_essenz_20cm.jpg",
        "image_path": "images/koekenpannen",
        "pros": [
            "Goede prijs-kwaliteit",
            "PFAS-vrij",
            "Snel warm",
        ],
        "cons": [
            "Niet ovenbestendig",
            "Kortere levensduur",
        ],
        "verdict": "Een uitstekende keuze voor wie betaalbaar PFAS-vrij wil koken.",
    },

    "demeyere_alu_pro_5_ceraforce_20": {
        "slug": "demeyere_alu_pro_5_ceraforce_20",
        "name": "Demeyere Alu Pro 5 Ceraforce",
        "description": "Hoogwaardige premium koekenpan met PFAS-vrije Ceraforce® keramische coating.",
        "brand": "Demeyere",
        "diameter": 20,
        "material": "Keramisch (Ceraforce®)",
        "features": ["Inductie", "PFAS-vrij", "Professionele kwaliteit"],
        "rating": 4.5,
        "rating_count": 180,
        "price": 74.81,
        "price_range": "€€€€",
        "currency": "EUR",
        "availability": "InStock",
        "image": "demeyere-alu-pro-5-ceraforce-20cm.jpg",
        "image_path": "images/koekenpannen",
        "affiliate_url": "https://www.bol.com/nl/nl/p/demeyere-12620-alu-pro-5-ceraforce-bakpan-antikleef-20-cm/9300000035395887/?s2a=&bltgh=vBPmUIfEwQiHh3ga2R1Fww.4_74_75.76.FeatureListItem#productTitle",
        "award": "💎 Premium keuze",
        "pros": [
            "PFAS-vrije Ceraforce® keramische coating",
            "Zeer stabiele en gelijkmatige warmteverdeling",
            "Uitstekend geschikt voor inductie",
        ],
        "cons": [
            "Zwaarder dan gemiddelde keramische pannen",
            "Hoger prijsniveau",
        ],
        "verdict": "De beste premium keuze voor wie een duurzame, PFAS-vrije keramische koekenpan van 24 cm zoekt met professionele prestaties.",
    },

    "greenchef_diamond_20": {
        "slug": "greenchef_diamond_20",
        "name": "GreenChef Diamond Induction",
        "description": "PFAS-vrije keramische pan met diamantdeeltjes en hoge slijtvastheid.",
        "brand": "GreenChef",
        "diameter": 20,
        "material": "Keramisch",
        "features": ["Diamantcoating", "Duurzaam"],
        "rating": 4.5,
        "rating_count": 150,
        "price": 29.90,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/greenchef-diamond-koekenpan-20cm-zwart-inductie-pfas-vrij/9200000130094501/?cid=1766380314980-2767784476758&bltgh=5ffdbb59-a081-4721-acd2-2cae85acec26.ProductList_Middle.0.ProductImage",
        "price_range": "€€",
        "image": "koekenpan04_greenchef_diamond_20cm.jpg",
        "image_path": "images/koekenpannen",
        "pros": [
            "Extra duurzame diamantcoating",
            "Goede hitteverdeling",
            "Gemakkelijk schoon te maken",
        ],
        "cons": [
            "Niet ovenbestendig",
        ],
        "verdict": "Solide keuze voor wie een betrouwbare en duurzame keramische pan zoekt.",
    },

    "bk_easy_induction_20": {
        "slug": "bk_easy_induction_20",
        "name": "BK Easy Induction Ceramic",
        "description": "PFAS-vrije keramische pan met koele greep en stevige bodem.",
        "brand": "BK",
        "diameter": 20,
        "material": "Keramisch",
        "features": ["Koele greep", "Inductie"],
        "rating": 4.5,
        "rating_count": 200,
        "price": 32.49,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/bk-easy-induction-ceramic-koekenpan-o20-cm-pfas-vrij/9300000032891763/?cid=1766380483899-7763794392492&bltgh=721b099c-fcb4-4086-b787-280ca02ac2e5.ProductList_Middle.0.ProductImage",
        "price_range": "€€",
        "award": "🥇 Meest gekozen",
        "image": "koekenpan05_bk_easy_induction_20cm.jpg",
        "image_path": "images/koekenpannen",
        "pros": [
            "Goede prijs-kwaliteit",
            "Snelle opwarming",
            "Koele handgreep",
        ],
        "cons": [
            "Niet ovenbestendig",
        ],
        "verdict": "Praktische pan voor dagelijks gebruik met betrouwbare antiaanbaklaag.",
    },

    "greenpan_mayflower_20": {
        "slug": "greenpan_mayflower_20",
        "name": "GreenPan Mayflower",
        "description": "Stijlvolle keramische koekenpan met PFAS-vrije Thermolon™ coating.",
        "brand": "GreenPan",
        "diameter": 20,
        "material": "Keramisch (Thermolon™)",
        "features": [
            "Goede warmteverdeling",
            "Geschikt voor inductie",
        ],
        "rating": 4.5,
        "rating_count": 210,
        "price": 32.05,
        "currency": "EUR",
        "availability": "InStock",
        "price_range": "€€",
        "image": "greenpan-mayflower-20cm.jpg",
        "image_path": "images/koekenpannen",
        "affiliate_url": "https://www.bol.com/nl/nl/p/greenpan-mayflower-pro-koekenpan-20cm-grijs-inductie-pfas-vrij/9300000091450193/?cid=1766382322505-6956927587708&bltgh=9fc57af3-7cb6-445b-b40b-8d49fe92c203.ProductList_Middle.0.ProductImage",
        "pros": [
            "Thermolon™ keramische coating",
            "Goede warmteverdeling",
            "Aantrekkelijk design",
        ],
        "cons": [
            "Minder robuust dan premium GreenPan-lijnen",
            "Geen ovenbestendige greep",
        ],
        "verdict": "Betrouwbare keuze voor milieubewuste gebruiker met modern comfort.",
    },

    "tefal_renew_20": {
        "slug": "tefal_renew_20",
        "name": "Tefal Renew+",
        "description": "Gemaakt van gerecycled aluminium met PFAS-vrije laag.",
        "brand": "Tefal",
        "diameter": 20,
        "material": "Keramisch",
        "features": ["Gerecycled aluminium", "Thermo-Spot"],
        "rating": 4,
        "rating_count": 310,
        "price": 32.99,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/tefal-renew-keramische-koekenpan-o-20-cm/9300000120126719/?cid=1766380777710-2580610106203&bltgh=a24bc707-9434-45de-a969-58034170aee3.ProductList_Middle.0.ProductImage",
        "price_range": "€€",
        "award": "",
        "image": "koekenpan07_tefal_renew_20cm.jpg",
        "image_path": "images/koekenpannen",
        "pros": [
            "Duurzaam gerecycled materiaal",
            "Goede warmtegeleiding",
            "Thermo-Spot-hitte-indicator",
        ],
        "cons": [
            "Niet ovenbestendig",
        ],
        "verdict": "Betrouwbare keuze voor milieubewuste gebruiker met modern comfort.",
    },

    "bk_enjoy_20": {
        "slug": "bk_enjoy_20",
        "name": "BK Enjoy",
        "description": "Betaalbare keramische pan met natuurlijke PFAS-vrije coating.",
        "brand": "BK",
        "diameter": 20,
        "material": "Keramisch",
        "features": ["Lichtgewicht", "Eenvoudig schoon te maken"],
        "rating": 4,
        "rating_count": 120,
        "price": 32.49,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/bk-easy-induction-ceramic-koekenpan-o20-cm-pfas-vrij/9300000032891763/?cid=1772171055630-1240041169147&bltgh=3f92d763-a322-42e8-b4fd-58ed4d739e96.ProductList_Middle.0.ProductImage",
        "price_range": "€€",
        "image": "koekenpan08_bk_enjoy_20cm.jpg",
        "image_path": "images/koekenpannen",
        "pros": [
            "Licht van gewicht",
            "Goede warmtegeleiding",
            "Gemakkelijk schoon te maken",
        ],
        "cons": [
            "Niet geschikt voor oven",
        ],
        "verdict": "Een lichte en praktische pan voor dagelijks gezond koken.",
    },

    "hema_milano_20": {
        "slug": "hema_milano_20",
        "name": "HEMA Milano",
        "description": "Compacte en betaalbare keramische koekenpan voor dagelijks gebruik.",
        "brand": "HEMA",
        "diameter": 20,
        "material": "Keramisch",
        "features": [
            "Lichtgewicht",
            "Geschikt voor inductie",
        ],
        "rating": 4,
        "rating_count": 320,
        "price": 26.99,
        "currency": "EUR",
        "availability": "InStock",
        "price_range": "€",
        "image": "hema-milano-20cm.jpg",
        "image_path": "images/koekenpannen",
        "affiliate_url": "https://www.hema.nl/koken-tafelen/koken/pannen/koekenpannen/koekenpan-20cm-milano-pfas-vrij-80120001.html",
        "pros": [
            "Keramische coating",
            "Zeer scherp geprijsd",
            "Compact en lichtgewicht",
        ],
        "cons": [
            "Minder duurzaam bij intensief gebruik",
            "Eenvoudige afwerking",
        ],
        "verdict": "Een toegankelijke en betaalbare instappan voor wie veilig en PFAS-vrij wil koken in een compact formaat.",
    },

    "berndes_b_green_20": {
        "slug": "berndes-b-green-20",
        "name": "Berndes B.Green",
        "description": "PFAS-vrije keramische koekenpan van 100% gerecycled aluminium met b.nature kwarts-antiaanbaklaag.",
        "brand": "Berndes",
        "diameter": 20,
        "material": "Keramisch (b.nature kwarts)",
        "features": ["b.nature kwarts-coating", "Inductie", "100% gerecycled aluminium", "Ovenbestendig", "Vaatwasserbestendig"],
        "rating": 4.3,
        "rating_count": 65,
        "price": 40.00,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/berndes-b-green-koekenpan-20-cm-gerecycled-aluminium-zilver/9300000006419842/?Referrer=ADVNLGOO002032-S--9300000006419842-PMAX-C-22285073478&gad_source=1&gad_campaignid=22291735154&gclid=Cj0KCQjwy_fOBhC6ARIsAHKFB7_MvQ5YAN6K8e-7WijgD5kAcsagV-88-NXgepFBixxwH8uPoPvPBi8aAqYmEALw_wcB",
        "award": None,
        "price_range": "€€",
        "image": "berndes-b-green-20cm.jpg",
        "image_path": "images/koekenpannen",
        "pros": [
            "100% PFAS-vrije b.nature kwarts-coating",
            "Gemaakt van 100% gerecycled aluminium",
            "Hittebestendig tot 400 °C",
            "Duurzaam Duits merk met meer dan 100 jaar ervaring",
        ],
        "cons": [
            "Minder glanzend bakoppervlak dan sommige keramische alternatieven",
            "Zachte greep minder geschikt voor hoge oventemperaturen",
        ],
        "verdict": "Milieuvriendelijke keuze voor wie echt PFAS-vrij wil koken met een coating van volledig natuurlijke grondstoffen.",
    },

    # 30CM KOEKENPANNEN

    "greenpan_barcelona_pro_30": {
        "slug": "greenpan-barcelona-pro-30",
        "name": "GreenPan Barcelona Pro",
        "description": "Hoogwaardige keramische PFAS-vrije pan met Thermolon Infinity Pro-coating en inductiebodem.",
        "brand": "GreenPan",
        "diameter": 30,
        "material": "Keramisch",
        "features": ["Inductie", "Ovenbestendig", ],
        "rating": 5,
        "rating_count": 340,
        "price": 79.99,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/greenpan-barcelona-evershine-koekenpan-30cm-zilver-inductie-pfas-vrij/9200000091127464/?bltgh=fc18ffe3-a975-418b-905e-ec6d7aa9c44d.ProductList_Middle.0.ProductImage&cid=1766554993577-2580961884565",
        "award": "🏆 Beste keuze",
        "price_range": "€€€",
        "image": "greenpan_barcelona_pro_30cm.jpg",
        "image_path": "images/koekenpannen",
        "pros": [
            "PFAS-vrij Thermolon-coating",
            "Uitstekende warmteverdeling",
            "Ovenbestendig tot 220 °C",
        ],
        "cons": [
            "Vrij zwaar",
            "Hogere prijs",
        ],
        "verdict": "De ultieme keuze voor wie dagelijks gezond en PFAS-vrij wil koken.",
    },

    "kochstar_stein_30": {
        "slug": "kochstar_stein_30",
        "name": "Kochstar Stein",
        "description": "Ruime keramische koekenpan met een PFAS-vrije coating, ontworpen voor grotere bereidingen.",
        "brand": "Kochstar",
        "diameter": 30,
        "material": "Keramisch",
        "features": [
            "Inductie",
            "Prijs-kwaliteitverhouding",
        ],
        "rating": 4,
        "rating_count": 140,
        "price": 18.99,
        "currency": "EUR",
        "availability": "InStock",
        "price_range": "€€",
        "image": "kochstar-stein-30cm.jpg",
        "image_path": "images/koekenpannen",
        "award": "💰 Budget keuze",
        "affiliate_url": "https://www.bol.com/nl/nl/p/kochstar-stein-koekenpan-30cm-pfas-vrij-inductie-pan-keramische-anti-aanbaklaag-koelgreep-graniet/9300000231848100/?cid=1766607286820-3364580713069&bltgh=bf2852e3-d6f4-49f0-8592-8238c901b20a.ProductList_Middle.0.ProductImage",
        "pros": [
            "Keramische coating, expliciet PFAS-vrij",
            "Geschikt voor grote inductiezones",
            "Goede prijs-kwaliteitverhouding",
        ],
        "cons": [
            "Minder verfijnde afwerking",
            "Niet bedoeld voor professioneel gebruik",
        ],
        "verdict": "Een toegankelijke en betrouwbare keuze voor wie een grote, PFAS-vrije koekenpan zoekt zonder direct naar het premiumsegment te gaan.",
    },

    "demeyere_alu_pro_5_ceraforce_30": {
        "slug": "demeyere_alu_pro_5_ceraforce_30",
        "name": "Demeyere Alu Pro 5 Ceraforce",
        "description": "Hoogwaardige premium koekenpan met PFAS-vrije Ceraforce® keramische coating.",
        "brand": "Demeyere",
        "diameter": 30,
        "material": "Keramisch (Ceraforce®)",
        "features": ["Inductie", "PFAS-vrij", "Professionele kwaliteit"],
        "rating": 4.5,
        "rating_count": 260,
        "price": 95.88,
        "price_range": "€€€€",
        "currency": "EUR",
        "availability": "InStock",
        "image": "demeyere-alu-pro-5-ceraforce-30cm.jpg",
        "image_path": "images/koekenpannen",
        "affiliate_url": "https://www.bol.com/nl/nl/p/demeyere-alu-pro-ceraforce-koekenpan-30-cm/9300000045881607/?s2a=&bltgh=kdZ0yO3pHolnAODNrotE3A.4_82_83.84.FeatureListItem#productTitle",
        "award": "💎 Premium keuze",
        "pros": [
            "PFAS-vrije Ceraforce® keramische coating",
            "Zeer stabiele en gelijkmatige warmteverdeling",
            "Uitstekend geschikt voor inductie",
        ],
        "cons": [
            "Zwaarder dan gemiddelde keramische pannen",
            "Hoger prijsniveau",
        ],
        "verdict": "De beste premium keuze voor wie een duurzame, PFAS-vrije keramische koekenpan van 30 cm zoekt met professionele prestaties.",
    },

    "greenchef_diamond_30": {
        "slug": "greenchef-diamond-30",
        "name": "GreenChef Diamond Induction",
        "description": "PFAS-vrije keramische pan met diamantdeeltjes en hoge slijtvastheid.",
        "brand": "GreenChef",
        "diameter": 30,
        "material": "Keramisch",
        "features": ["Diamantcoating", "Duurzaam"],
        "rating": 4.5,
        "rating_count": 290,
        "price": 39.90,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/greenchef-diamond-koekenpan-30cm-zwart-inductie-pfas-vrij/9200000131576064/?cid=1766555531803-2721358459335&bltgh=0b70f7a4-83a9-4b03-a123-b52b2f75f548.ProductList_Middle.0.ProductTitle",
        "price_range": "€€",
        "image": "greenchef_diamond_30cm.jpg",
        "image_path": "images/koekenpannen",
        "pros": [
            "Extra duurzame diamantcoating",
            "Goede hitteverdeling",
            "Gemakkelijk schoon te maken",
        ],
        "cons": [
            "Niet ovenbestendig",
        ],
        "verdict": "Solide keuze voor wie een betrouwbare en duurzame keramische pan zoekt.",
    },

    "bk_easy_induction_30": {
        "slug": "bk-easy-induction-30",
        "name": "BK Easy Induction Ceramic",
        "description": "PFAS-vrije keramische pan met koele greep en stevige bodem.",
        "brand": "BK",
        "diameter": 30,
        "material": "Keramisch",
        "features": ["Koele greep", "Inductie"],
        "rating": 4.5,
        "rating_count": 410,
        "price": 41.50,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/bk-easy-induction-ceramic-koekenpan-o30-cm-pfas-vrij/9300000032891768/?cid=1766555806050-3582054560194&bltgh=93cf7e04-5bca-4d0a-b78e-c9a9cee22cbc.ProductList_Middle.0.ProductImage",
        "price_range": "€€",
        "award": "🥇 Meest gekozen",
        "image": "bk_easy_induction_30cm.jpg",
        "image_path": "images/koekenpannen",
        "pros": [
            "Goede prijs-kwaliteit",
            "Snelle opwarming",
            "Koele handgreep",
        ],
        "cons": [
            "Niet ovenbestendig",
        ],
        "verdict": "Praktische pan voor dagelijks gebruik met betrouwbare antiaanbaklaag.",
    },

    "greenpan_torino_30": {
        "slug": "greenpan_torino_30",
        "name": "GreenPan Torino",
        "description": "Betrouwbare PFAS-vrije keramische koekenpan voor dagelijks gebruik.",
        "brand": "GreenPan",
        "diameter": 30,
        "material": "Keramisch",
        "features": ["Inductie", "PFAS-vrij"],
        "rating": 4,
        "rating_count": 370,
        "price": 55.95,
        "currency": "EUR",
        "availability": "InStock",
        "price_range": "€€",
        "image": "greenpan-torino-30cm.jpg",
        "image_path": "images/koekenpannen",
        "affiliate_url": "https://www.bol.com/nl/nl/p/greenpan-torino-keramische-koekenpan-30-cm/9300000121455786/?s2a=&bltgh=p1NKv29PjTBJZ5yrSsVPUg.4_70_71.72.FeatureOptionButton#productTitle",
        "pros": [
            "PFAS-vrije Thermolon™ keramische coating",
            "Lichtgewicht en prettig in gebruik",
            "Geschikt voor inductie en andere warmtebronnen",
        ],
        "cons": [
            "Minder robuust dan premium GreenPan-series",
            "Niet geschikt voor zeer hoge temperaturen",
        ],
        "verdict": "Een uitstekende, betaalbare keuze voor wie een gezonde PFAS-vrije koekenpan van 30 cm zoekt voor dagelijks koken.",
    },

    "tefal_renew_30": {
        "slug": "tefal-renew-30",
        "name": "Tefal Renew+",
        "description": "Gemaakt van gerecycled aluminium met PFAS-vrije laag.",
        "brand": "Tefal",
        "diameter": 30,
        "material": "Keramisch",
        "features": ["Gerecycled aluminium", "Thermo-Spot"],
        "rating": 4,
        "rating_count": 520,
        "price": 39.99,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.coolblue.nl/product/913828/tefal-renew-keramische-koekenpan-30-cm.html?srsltid=AfmBOoqmDHo_7PbZ3Zoxhyk8WZXLgLI2HBWj0ZQg73mtxBChSc-HGxfM",
        "price_range": "€€",
        "award": "",
        "image": "tefal_renew_30cm.jpg",
        "image_path": "images/koekenpannen",
        "pros": [
            "Duurzaam gerecycled materiaal",
            "Goede warmtegeleiding",
            "Thermo-Spot-hitte-indicator",
        ],
        "cons": [
            "Niet ovenbestendig",
        ],
        "verdict": "Betrouwbare keuze voor milieubewuste gebruiker met modern comfort.",
    },

    "brabantia_indu_plus_r_30": {
        "slug": "brabantia_indu_plus_r_30",
        "name": "Brabantia Indu+ R Keramische Koekenpan (30 cm)",
        "description": "Ruime en stabiele keramische koekenpan, speciaal ontwikkeld voor inductie.",
        "brand": "Brabantia",
        "diameter": 30,
        "material": "Keramisch",
        "features": [
            "Inductie",
            "Grote kookzones",
        ],
        "rating": 4.5,
        "rating_count": 190,
        "price": 30.99,
        "currency": "EUR",
        "availability": "InStock",
        "price_range": "€€€",
        "image": "brabantia-indu-plus-r-30cm.jpg",
        "image_path": "images/koekenpannen",
        "affiliate_url": "https://www.bol.com/nl/nl/p/brabantia-indu-r-koekenpan-o-30-cm-100-gerecycled-aluminium-keramische-antiaanbaklaag-ergonomisch-en-licht-ook-geschikt-voor-inductie-100-pfas-vrij-kleur-grijs/9300000183634541/?cid=1766656019958-5924530706126&bltgh=4af6ca51-8341-4130-8090-cc0620a89161.ProductList_Middle.2.ProductTitle",
        "pros": [
            "Keramische coating, expliciet PFAS-vrij",
            "Geoptimaliseerd voor inductiekoken",
            "Grote bakoppervlak voor gezinnen",
        ],
        "cons": [
            "Geen premium afwerking",
        ],
        "verdict": "Een betrouwbare middenklasse keuze voor wie een grote, PFAS-vrije koekenpan zoekt met focus op inductie en gebruiksgemak.",
    },

    "scanpan_techniq_30": {
        "slug": "ikea_hemlagad_keramisch_32",
        "name": "Scanpan TechnIQ",
        "description": "Professionele keramische koekenpan uit de TechnIQ-lijn, ontwikkeld in samenwerking met chefs.",
        "brand": "Scanpan",
        "diameter": 30,
        "material": "Keramisch",
        "features": [
            "Warmteverdeling",
            "Inductie",
        ],
        "rating": 4.5,
        "rating_count": 180,
        "price": 185.00,
        "currency": "EUR",
        "availability": "InStock",
        "price_range": "€€€€",
        "image": "scanpan-techniq-30cm.jpg",
        "image_path": "images/koekenpannen",
        "affiliate_url": "https://www.bol.com/nl/nl/p/scanpan-techniq-koekenpan-30-cm/9200000126639847/?cid=1766606728869-3499678274754&bltgh=1d7c6f3c-4444-4250-b000-ebe5c02b1456.ProductList_Middle.7.ProductImage",
        "pros": [
            "Keramische coating, expliciet PFAS-vrij",
            "Zeer gelijkmatige warmteverdeling",
            "Ontworpen voor professioneel gebruik",
        ],
        "cons": [
            "Hoger prijsniveau",
            "Relatief zwaar",
        ],
        "verdict": "Een uitstekende keuze voor wie in het 30 cm-formaat maximale prestaties en duurzaamheid zoekt.",
    },

    # 32CM KOEKENPANNEN
    "greenpan_barcelona_pro_32": {
        "slug": "greenpan-barcelona-pro-32",
        "name": "GreenPan Barcelona Pro",
        "description": "Hoogwaardige keramische PFAS-vrije pan met Thermolon Infinity Pro-coating en inductiebodem.",
        "brand": "GreenPan",
        "diameter": 32,
        "material": "Keramisch",
        "features": ["Inductie", "Ovenbestendig", ],
        "rating": 5,
        "rating_count": 360,
        "price": 62.95,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/greenpan-barcelona-infinity-pro-koekenpan-32cm-zwart-inductie-pfas-vrij/9200000091127466/?cid=1766654508682-4311957350539&bltgh=83e353ee-2c06-480b-910c-f1f61936a35d.ProductList_Middle.0.ProductImage",
        "award": "🏆 Beste keuze",
        "price_range": "€€€",
        "image": "greenpan_barcelona_pro_32cm.jpg",
        "image_path": "images/koekenpannen",
        "pros": [
            "PFAS-vrij Thermolon-coating",
            "Uitstekende warmteverdeling",
            "Ovenbestendig tot 220 °C",
        ],
        "cons": [
            "Vrij zwaar",
            "Hogere prijs",
        ],
        "verdict": "De ultieme keuze voor wie dagelijks gezond en PFAS-vrij wil koken.",
    },

    "demeyere_alu_pro_5_ceraforce_32": {
        "slug": "demeyere_alu_pro_5_ceraforce_32",
        "name": "Demeyere Alu Pro 5 Ceraforce",
        "description": "Hoogwaardige premium koekenpan met PFAS-vrije Ceraforce® keramische coating.",
        "brand": "Demeyere",
        "diameter": 32,
        "material": "Keramisch (Ceraforce®)",
        "features": ["Inductie", "PFAS-vrij", "Professionele kwaliteit"],
        "rating": 4.5,
        "rating_count": 280,
        "price": 101.80,
        "price_range": "€€€€",
        "currency": "EUR",
        "availability": "InStock",
        "image": "demeyere-alu-pro-5-ceraforce-32cm.jpg",
        "image_path": "images/koekenpannen",
        "affiliate_url": "https://www.bol.com/nl/nl/p/demeyere-alu-pro-5-ceraforce-bakpan-32cm/9300000023769225/?s2a=&bltgh=hg-NXeuD4MXWFUeGSg9L7Q.4_82_83.84.FeatureListItem#productTitle",
        "award": "💎 Premium keuze",
        "pros": [
            "PFAS-vrije Ceraforce® keramische coating",
            "Zeer stabiele en gelijkmatige warmteverdeling",
            "Uitstekend geschikt voor inductie",
        ],
        "cons": [
            "Zwaarder dan gemiddelde keramische pannen",
            "Hoger prijsniveau",
        ],
        "verdict": "De beste premium keuze voor wie een duurzame, PFAS-vrije keramische koekenpan van 32 cm zoekt met professionele prestaties.",
    },

    "combekk_ceramic_pro_32": {
        "slug": "bk-easy-induction-32",
        "name": "Combekk Ceramic Pro",
        "description": "Duurzame keramische koekenpan van Nederlands ontwerp, ontwikkeld met focus op gezond koken en een lange levensduur.",
        "brand": "Combekk",
        "diameter": 32,
        "material": "Keramisch",
        "features": [
            "Zeer stabiele bodem voor grote inductiezones",
            "Duurzaam Nederlands merk",
        ],
        "rating": 4.5,
        "rating_count": 160,
        "price": 58.99,
        "currency": "EUR",
        "availability": "InStock",
        "price_range": "€€€",
        "image": "combekk-ceramic-pro-32cm.jpg",
        "image_path": "images/koekenpannen",
        "affiliate_url": "https://www.bol.com/nl/nl/p/combekk-koekenpan-ceramic-pro-koekenpan-anti-aanbak-keramisch-roestvrijstaal-32cm/9300000072548969/?cid=1766655185920-4711281622513&bltgh=23319959-4c5c-4ef9-a0b4-b0cc519f26d9.ProductList_Middle.13.ProductTitle",
        "pros": [
            "Keramische coating, expliciet PFAS-vrij",
            "Zeer stabiel en geschikt voor grote inductiezones",
            "Duurzaam merk met focus op kwaliteit",
        ],
        "cons": [
            "Hoger gewicht door robuuste bouw",
            "Hoger prijsniveau dan instapmodellen",
        ],
        "verdict": "Een sterke middenklasse keuze voor wie in het 32 cm-formaat duurzaam, PFAS-vrij en met vertrouwen wil koken.",
    },

    "bk_easy_induction_32": {
        "slug": "bk-easy-induction-32",
        "name": "BK Easy Induction Ceramic",
        "description": "PFAS-vrije keramische pan met koele greep en stevige bodem.",
        "brand": "BK",
        "diameter": 32,
        "material": "Keramisch",
        "features": ["Koele greep", "Inductie"],
        "rating": 4.5,
        "rating_count": 430,
        "price": 50.99,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/bk-easy-induction-vispan-o-32-cm-inductie-pfas-vrij/9300000089414301/?cid=1766655064205-1733964093749&bltgh=b2689f89-faf1-468c-87cb-b989c8c4f351.ProductList_Middle.9.ProductTitle",
        "price_range": "€€",
        "award": "🥇 Meest gekozen",
        "image": "bk_easy_induction_32cm.jpg",
        "image_path": "images/koekenpannen",
        "pros": [
            "Goede prijs-kwaliteit",
            "Snelle opwarming",
            "Koele handgreep",
        ],
        "cons": [
            "Niet ovenbestendig",
        ],
        "verdict": "Praktische pan voor dagelijks gebruik met betrouwbare antiaanbaklaag.",
    },

    "greenpan_torino_32": {
        "slug": "greenpan_torino_32",
        "name": "GreenPan Torino",
        "description": "Betrouwbare PFAS-vrije keramische koekenpan voor dagelijks gebruik.",
        "brand": "GreenPan",
        "diameter": 32,
        "material": "Keramisch",
        "features": ["Inductie", "PFAS-vrij"],
        "rating": 4,
        "rating_count": 390,
        "price": 49.99,
        "currency": "EUR",
        "availability": "InStock",
        "price_range": "€€",
        "image": "greenpan-torino-32cm.jpg",
        "image_path": "images/koekenpannen",
        "affiliate_url": "https://www.bol.com/nl/nl/p/greenpan-torino-vispan/9300000121455776/?s2a=&bltgh=va9fygct4-z4dcpWAPpBdg.4_67_68.69.FeatureOptionButton#productTitle",
        "pros": [
            "PFAS-vrije Thermolon™ keramische coating",
            "Lichtgewicht en prettig in gebruik",
            "Geschikt voor inductie en andere warmtebronnen",
        ],
        "cons": [
            "Minder robuust dan premium GreenPan-series",
            "Niet geschikt voor zeer hoge temperaturen",
        ],
        "verdict": "Een uitstekende, betaalbare keuze voor wie een gezonde PFAS-vrije koekenpan van 30 cm zoekt voor dagelijks koken.",
    },

    "tefal_renew_32": {
        "slug": "tefal-renew-32",
        "name": "Tefal Renew+",
        "description": "Gemaakt van gerecycled aluminium met PFAS-vrije laag.",
        "brand": "Tefal",
        "diameter": 32,
        "material": "Keramisch",
        "features": ["Gerecycled aluminium", "Thermo-Spot"],
        "rating": 4,
        "rating_count": 540,
        "price": 36.74,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/tefal-renew-on-keramische-koekenpan-o-32-cm/9300000117431080/?cid=1766655540107-9223038508418&bltgh=c1879416-2445-440e-bc08-1f53f5887c81.ProductList_Middle.0.ProductImage",
        "price_range": "€€",
        "award": "",
        "image": "tefal_renew_32cm.jpg",
        "image_path": "images/koekenpannen",
        "pros": [
            "Duurzaam gerecycled materiaal",
            "Goede warmtegeleiding",
            "Thermo-Spot-hitte-indicator",
        ],
        "cons": [
            "Niet ovenbestendig",
        ],
        "verdict": "Betrouwbare keuze voor milieubewuste gebruiker met modern comfort.",
    },

    "blue_diamond_32": {
        "slug": "blue_diamond_32",
        "description": "Grote keramische koekenpan met diamantversterkte coating, gericht op betaalbaar gebruik in een ruim formaat.",
        "name": "Blue Diamond",
        "brand": "Blue Diamond",
        "diameter": 32,
        "material": "Keramisch",
        "features": [
            "Groot bakoppervlak",
            "Scherp geprijsd instapmodel",
        ],
        "rating": 4,
        "rating_count": 240,
        "price": 52.90,
        "currency": "EUR",
        "availability": "OutOfStock",
        "price_range": "€€",
        "image": "blue-diamond-32cm.jpg",
        "image_path": "images/koekenpannen",
        "affiliate_url": "https://www.bol.com/nl/nl/p/blue-diamond-koekenpan-o32cm-blauw-inductie-anti-aanbak-pfas-vrij/9300000143528849/?cid=1766654994564-9177026698185&bltgh=773d2b83-efa3-4a43-8424-fb0f96f6cc4e.ProductList_Middle.3.ProductImage",
        "pros": [
            "Keramische coating zonder PFAS",
            "Groot bakoppervlak voor meerdere ingrediënten",
            "Relatief scherp geprijsd voor 32 cm",
        ],
        "cons": [
            "Minder duurzame coating bij intensief gebruik",
            "Marketingclaim (“diamond”) belangrijker dan techniek",
        ],
        "verdict": "Een toegankelijke instapoptie voor wie een grote, PFAS-vrije koekenpan zoekt zonder hoge investering.",
    },

    "ikea_hemlagad_keramisch_32": {
        "slug": "ikea_hemlagad_keramisch_32",
        "name": "IKEA HEMLAGAD",
        "description": " Betaalbare en toegankelijke keramische koekenpan van IKEA met een PTFE- en PFAS-vrije antiaanbaklaag.",
        "brand": "IKEA",
        "diameter": 32,
        "material": "Keramisch",
        "features": [
            "Inductie",
            "PFAS-vrij",
        ],
        "rating": 4,
        "rating_count": 500,
        "price_range": "€",
        "price": 17.99,
        "currency": "EUR",
        "availability": "InStock",
        "image": "ikea-hemlagad-keramisch-32cm.jpg",
        "image_path": "images/koekenpannen",
        "affiliate_url": "https://www.ikea.com/nl/nl/p/hemlagad-koekenpan-antiaanbaklaag-zwart-30580899/#content",
        "pros": [
            "Keramische coating, expliciet PFAS-vrij",
            "Zeer scherpe prijs",
            "Geschikt voor inductie en andere warmtebronnen",
        ],
        "cons": [
            "Minder duurzaam dan midden- en premium pannen",
            "Warmteverdeling is eenvoudiger",
        ],
        "verdict": "Een goede keuze voor wie een goedkope, PFAS-vrije koekenpan van 30 cm zoekt voor licht en dagelijks gebruik, zonder concessies te doen aan basisveiligheid.",
    },

    "scanpan_ceramic_32": {
        "name": "Scanpan HaptIQ",
        "slug": "scanpan_ceramic_32",
        "description": " Hoogwaardige Scandinavische koekenpan met keramische, PFAS-vrije coating en een focus op duurzaamheid.",
        "brand": "Scanpan",
        "diameter": 32,
        "material": "Keramisch",
        "features": [
            "Keramisch en PFAS-vrij",
            "Scandinavische kwaliteit",
            "Gelijkmatige warmteverdeling",
        ],
        "rating": 4.5,
        "rating_count": 210,
        "price": 180.00,
        "currency": "EUR",
        "availability": "InStock",
        "price_range": "€€€",
        "image": "scanpan-ceramic-32cm.jpg",
        "image_path": "images/koekenpannen",
        "affiliate_url": "https://www.bol.com/nl/nl/p/scanpan-haptiq-koekenpan-32-cm/9200000116693186/?cid=1766655687794-9869876503169&bltgh=cd3a2be1-6fbc-4d58-ac60-c5045d68fd26.ProductList_Middle.4.ProductTitle",
        "pros": [
            "Keramisch en PFAS-vrij",
            "Zeer gelijkmatige warmteverdeling",
            "Solide bouwkwaliteit",
        ],
        "cons": [
            "Prijs hoger dan gemiddelde middenklasse",
        ],
        "verdict": "Een interessante keuze voor wie Scandinavische kwaliteit waardeert.",
    },
}
