PRODUCTS = {
    # 28CM KOEKENPANNEN
    "greenpan_barcelona_pro_28": {
        "slug": "greenpan-barcelona-pro-28",
        "name": "GreenPan Barcelona Pro",
        "description": "Stevige aluminium koekenpan met Thermolon Infinity Pro-coating, "
        "brede inductiebodem en ovenbestendige RVS greep.",
        "brand": "GreenPan",
        "diameter": 28,
        "material": "Aluminium met keramische antiaanbaklaag",
        "features": ["Geschikt voor inductie", "Ovenbestendig tot 220 °C", ],
        "rating": 4.7,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 91.03,
        "currency": "EUR",
        "price_last_checked": "2026-07-27",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/greenpan-barcelona-pro-koekenpan-met-keramische-antikleeflaag-28-cm/9300000111189161/",
        "award": "🏆 Beste keuze",
        "price_range": "€€€",
        "image": "greenpan-barcelona-pro-28cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Gelijkmatige warmteverdeling",
            "Stevige constructie",
            "Geschikt voor ovengebruik",
        ],
        "cons": [
            "Relatief zwaar",
            "Hogere aanschafprijs",
        ],
        "verdict": "Onze beste allround keuze voor wie een stevige keramische pan "
        "voor dagelijks gebruik zoekt.",
    },

    "kochstar_essenz_28": {
        "slug": "kochstar-essenz-28",
        "name": "Kochstar Essenz",
        "description": "Voordelige aluminium koekenpan met keramische antiaanbaklaag, "
        "koel blijvende greep en geschiktheid voor inductie.",
        "brand": "Kochstar",
        "diameter": 28,
        "material": "Aluminium met keramische antiaanbaklaag",
        "features": ["PFAS-vrij", "Lichtgewicht", ],
        "rating": 4,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 13.99,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/kochstar-essenz-zwart-keramische-koekenpan-28cm-pfas-vrij-inductie-koekenpan-inductie-pan-keramische-anti-aanbaklaag-koelgreep-ovenbestendig-tot-130-c-zwart/9300000231848099/",
        "award": "💰 Budget keuze",
        "price_range": "€",
        "image": "kochstar-essenz-28cm-zwart.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "variants": [
            {
                "name": "Zwart",
                "image": "kochstar-essenz-28cm-zwart.webp",
                "hex": "#000000",
                "affiliate_url": "",
                "retailer_url": "https://www.bol.com/nl/nl/p/kochstar-essenz-zwart-keramische-koekenpan-28cm-pfas-vrij-inductie-koekenpan-inductie-pan-keramische-anti-aanbaklaag-koelgreep-ovenbestendig-tot-130-c-zwart/9300000231848099/",
                "price": 13.99,
                "price_last_checked": "2026-07-27",
            },
            {
                "name": "Taupe",
                "image": "kochstar-essenz-28cm-taupe.webp",
                "hex": "#B8A99A",
                "affiliate_url":"",
                "retailer_url":"https://www.bol.com/nl/nl/p/kochstar-essenz-koekenpan-28cm-pfas-vrij-inductie-pan-keramische-anti-aanbaklaag-koelgreep-taupe/9300000231848102/",
                "price": 14.99,
                "price_last_checked": "2026-07-27",
            },
        ],
        "pros": [
            "Zeer lage aanschafprijs",
            "Licht en gemakkelijk hanteerbaar",
            "Verkrijgbaar in twee kleuren",
        ],
        "cons": [
            "Slechts beperkt ovenbestendig tot 130 °C",
            "Eenvoudigere afwerking dan duurdere modellen",
        ],
        "verdict": "Een toegankelijke budgetkeuze voor licht en regelmatig gebruik.",
    },

    "greenchef_diamond_28": {
        "slug": "greenchef-diamond-28",
        "name": "GreenChef Diamond Induction",
        "description": "Aluminium koekenpan met keramische antiaanbaklaag "
    "waaraan volgens de fabrikant diamantdeeltjes zijn toegevoegd.",
        "brand": "GreenChef",
        "diameter": 28,
        "material": "Aluminium met keramische antiaanbaklaag",
        "features": ["Keramische coating met diamantdeeltjes", "Duurzaam"],
        "rating": 4.3,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 26.99,
        "price_last_checked": "2026-07-27",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/greenchef-diamond-koekenpan-28cm-zwart-inductie-pfas-vrij/9200000130094499/",
        "price_range": "€€",
        "image": "greenchef-diamond-28cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Diamantversterkte keramische coating",
            "Licht en gemakkelijk hanteerbaar",
            "Eenvoudig schoon te maken",
        ],
        "cons": [
            "Niet ovenbestendig",
        ],
        "verdict": "Een betaalbare middenklassepan voor dagelijks bakken op lage tot middelhoge temperatuur.",
    },

    "bk_easy_induction_28": {
        "slug": "bk-easy-induction-28",
        "name": "BK Easy Induction Ceramic",
        "description": "PFAS-vrije keramische pan met koele greep en stevige bodem.",
        "brand": "BK",
        "diameter": 28,
        "material": "Aluminium met keramische antiaanbaklaag",
        "features": ["Koele greep", "Inductie"],
        "rating": 4.3,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 39.99,
        "price_last_checked": "2026-07-27",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/bk-easy-induction-ceramic-koekenpan-28-cm-pfas-vrij-inductie/9300000032109237/",
        "award": None,
        "price_range": "€€",
        "image": "bk-easy-induction-28cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Goede prijs-kwaliteit",
            "Snelle opwarming",
            "Koele handgreep",
        ],
        "cons": [
            "Niet ovenbestendig",
        ],
        "verdict":  "Een praktische middenklassepan met comfortabele greep "
        "en een toegankelijke prijs.",
    },

    "brabantia_dusk_28": {
        "slug": "brabantia-dusk-28",
        "name": "Brabantia Dusk",
        "description": "Moderne keramische PFAS-vrije pan met stijlvolle afwerking.",
        "brand": "Brabantia",
        "diameter": 28,
        "material": "Aluminium met keramische antiaanbaklaag",
        "features": ["PFAS-vrij", "Stevige bodem"],
        "rating": 4.2,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 30.00,
        "price_last_checked": "2026-07-27",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/brabantia-dusk-r-ns-koekenpan-o-28cm-100-pfas-vrij/9300000225842102/",
        "price_range": "€€",
        "image": "brabantia-dusk-28cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Stevige inductiebodem",
            "Comfortabele greep",
            "Verzorgde, moderne afwerking",
        ],
        "cons": [
            "Niet vaatwasserbestendig",
        ],
        "verdict": "Een aantrekkelijke keuze voor wie functionaliteit en een moderne vormgeving wil combineren.",
    },

    "tefal_renew_28": {
        "slug": "tefal-renew-28",
        "name": "Tefal Renew+",
        "description": "Gemaakt van 100% gerecycled aluminium met PFAS-vrije laag.",
        "brand": "Tefal",
        "diameter": 28,
        "material": "Gerecycled aluminium met keramische antiaanbaklaag",
        "features": ["Gerecycled aluminium", "Thermo-Signal"],
        "rating": 4.2,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 38.99,
        "price_last_checked": "2026-07-27",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/tefal-renew-koekenpan-o28-cm-keramisch-pfas-vrij-geschikt-voor-inductie/9300000118641472/",
        "award": "",
        "price_range": "€€",
        "image": "tefal-renew-28cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Duurzaam gerecycled materiaal",
            "Goede warmtegeleiding",
            "Thermo-Signal-hitte-indicator",
        ],
        "cons": [
            "Niet ovenbestendig",
        ],
        "verdict": "Een gebruiksvriendelijke keuze voor wie een keramische Tefal-pan "
    "met hitte-indicator zoekt.",
    },

    "bk_enjoy_28": {
        "slug": "bk-enjoy-28",
        "name": "BK Enjoy",
        "description": "Lichtgewicht aluminium koekenpan met keramische antiaanbaklaag "
        "voor dagelijks gebruik.",
        "brand": "BK",
        "diameter": 28,
        "material": "Aluminium met keramische antiaanbaklaag",
        "features": ["Lichtgewicht", "Eenvoudig schoon te maken"],
        "rating": 4.1,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 34.90,
        "price_last_checked": "2026-07-27",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://bk.nl/products/enjoy-koekenpan-zwart-28-cm?srsltid=AfmBOoqIJ-LNGVZmMJZThGeFbB_cW7XcZXFB0rnlbkDqbVjERLMNIpFY",
        "price_range": "€€",
        "image": "bk-enjoy-28cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Licht van gewicht",
            "Goede warmtegeleiding",
            "Gemakkelijk schoon te maken",
        ],
        "cons": [
            "Niet geschikt voor oven",
        ],
        "verdict": "Een lichte en praktische pan voor dagelijks gezond koken.",
    },

    "demeyere_alu_pro_5_28": {
        "slug": "demeyere-alu-pro-5-28",
        "name": "Demeyere Alu Pro 5 Ceraforce",
        "description": "Stevige aluminium koekenpan met Ceraforce keramische coating "
        "en een dikke bodem voor stabiele warmteverdeling.",
        "brand": "Demeyere",
        "diameter": 28,
        "material": "Aluminium met Ceraforce keramische antiaanbaklaag",
        "features": [
            "Ceraforce keramische coating",
            "Geschikt voor inductie",
            "Dikke aluminium bodem",
        ],
        "rating": 4.6,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 85.00,
        "price_last_checked": "2026-07-27",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/demeyere-12628-alu-pro-5-ceraforce-antikleef-bakpan-28-cm/9300000032747130/",
        "award": "💎 Premium keuze",
        "price_range": "€€€€",
        "image": "demeyere-alu-pro-5-ceraforce-28cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Hoge aanschafprijs",
            "Relatief zwaar",
        ],
        "cons": [
            "Hogere prijsklasse",
            "Relatief zwaar",
        ],
        "verdict": "Onze premium keuze voor wie bouwkwaliteit en stabiele "
        "warmteverdeling belangrijker vindt dan een lage prijs.",
    },

    "debuyer_ceranoa_28": {
        "slug": "debuyer-ceranoa-28",
        "name": "De Buyer Ceranoa",
        "description": "Hoogwaardige keramische pan zonder PFAS met ergonomische greep.",
        "brand": "De Buyer",
        "diameter": 28,
        "material": "Aluminium met keramische antiaanbaklaag",
        "features": ["PFAS-vrij", "Premium afwerking"],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 105.00,
        "price_last_checked": "2026-07-27",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/debuyer-ceranoa-koekenpan-28cm/9300000232243696/",
        "price_range": "€€€€",
        "image": "debuyer-ceranoa-28cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Gelijkmatige warmteverdeling",
            "Hoogwaardig afgewerkte keramische antiaanbaklaag"
            "Ergonomisch handvat",
        ],
        "cons": [
            "Hoge aanschafprijs",
            "Niet vaatwasserbestendig",
        ],
        "verdict": "Een hoogwaardig afgewerkte pan voor wie ergonomie en een stevige constructie vooropstelt.",
    },

    "greenpan_mayflower_28": {
        "slug": "greenpan-mayflower-28",
        "name": "GreenPan Mayflower",
        "description": "Stijlvolle keramische koekenpan met PFAS-vrije Thermolon™ coating en inductiebodem.",
        "brand": "GreenPan",
        "diameter": 28,
        "material": "Aluminium met Thermolon keramische antiaanbaklaag",
        "features": [
            "Thermolon™ PFAS-vrije coating",
            "Geschikt voor inductie",
            "Goede warmteverdeling",
        ],
        "rating": 4.4,
        "rating_count": None,
        "rating_source": "editorial",
        "currency": "EUR",
        "availability": "InStock",
        "award": "",
        "price_range": "€€-€€€",
        "image": "greenpan-mayflower-28cm.jpg",
        "image_path": "images/products/keramische-koekenpannen",
        "variants": [
            {
                "name": "Grijs",
                "image": "greenpan-mayflower-grijs-28cm.webp",
                "hex": "#3F4448",
                "affiliate_url": "",
                "retailer_url": "https://www.bol.com/nl/nl/p/greenpan-mayflower-pro-koekenpan-28cm-grijs-inductie-pfas-vrij/9300000091450190/",
                "price": 59.90,
                "price_last_checked": "2026-07-27",
                "price_range": "€€€",
            },
            {
                "name": "Blauw",
                "image": "greenpan-mayflower-blauw-28cm.webp",
                "hex": "#8CA9B5",
                "affiliate_url":"",
                "retailer_url": "https://www.bol.com/nl/nl/p/greenpan-mayflower-koekenpan-o28-cm-inductie-anti-aanbak-pfas-vrij/9300000001596267/",
                "price": 42.99,
                "price_last_checked": "2026-07-27",
                "price_range": "€€",
            },
        ],
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/greenpan-mayflower-pro-koekenpan-28cm-grijs-inductie-pfas-vrij/9300000091450190/",
        "pros": [
            "PFAS-vrije Thermolon™ coating",
            "Goede warmteverdeling",
            "Aantrekkelijk design",
        ],
        "cons": [
            "Niet geschikt voor ovengebruik",
            "Prijs verschilt duidelijk per kleurvariant",
        ],
        "verdict": "Betrouwbare keuze voor milieubewuste gebruiker die stijl en gezond koken combineert.",
    },

    # 24CM KOEKENPANNEN
    "greenpan_barcelona_pro_24": {
        "slug": "greenpan-barcelona-pro-24",
        "name": "GreenPan Barcelona Pro",
        "description": "Stevige aluminium koekenpan met Thermolon Infinity Pro-coating, "
        "inductiebodem en ovenbestendige RVS greep.",
        "brand": "GreenPan",
        "diameter": 24,
        "material": "Aluminium met Thermolon keramische antiaanbaklaag",
        "features": ["Geschikt voor inductie",
                    "Ovenbestendig tot 220 °C",],
        "rating": 4.7,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 79.29,
        "price_last_checked": "2026-07-27",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/greenpan-barcelona-pro-bakpan-24cm/9300000117606007/",
        "award": "🏆 Beste keuze",
        "price_range": "€€€",
        "image": "greenpan-barcelona-pro-24cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Gelijkmatige warmteverdeling",
            "Stevige constructie",
            "Geschikt voor ovengebruik",
        ],
        "cons": [
            "Relatief zwaar",
            "Hogere aanschafprijs",
        ],
        "verdict":  "Onze beste allround keuze voor wie een stevige keramische pan "
        "voor dagelijks gebruik zoekt.",
    },

    "kochstar_essenz_24": {
        "slug": "kochstar-essenz-24",
        "name": "Kochstar Essenz",
        "description": "Voordelige aluminium koekenpan met keramische antiaanbaklaag, "
        "koel blijvende greep en geschiktheid voor inductie.",
        "brand": "Kochstar",
        "diameter": 24,
        "material": "Aluminium met keramische antiaanbaklaag",
        "features": ["PFAS-vrij", "Lichtgewicht", ],
        "rating": 4,
        "rating_count": None,
        "rating_source": "editorial",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/kochstar-essenz-koekenpan-24cm-pfas-vrij-inductie-pan-keramische-anti-aanbaklaag-koelgreep-zwart/9300000231848093/",
        "award": "💰 Budget keuze",
        "price_range": "€",
        "image": "koekenpan02_kochstar_essenz_24cm.jpg",
        "image_path": "images/products/keramische-koekenpannen",
        "variants": [
            {
                "name": "Zwart",
                "image": "kochstar-essenz-zwart-24cm.webp",
                "hex": "#000000",
                "affiliate_url": "",
                "retailer_url": "https://www.bol.com/nl/nl/p/kochstar-essenz-koekenpan-24cm-pfas-vrij-inductie-pan-keramische-anti-aanbaklaag-koelgreep-zwart/9300000231848093/",
                "price": 11.99,
                "price_last_checked": "2026-07-27",
            },
            {
                "name": "Taupe",
                "image": "kochstar-essenz-taupe-24cm.webp",
                "hex": "#B8A99A",
                "affiliate_url":"",
                "retailer_url": "https://www.bol.com/nl/nl/p/kochstar-essenz-koekenpan-24cm-pfas-vrij-inductie-pan-keramische-anti-aanbaklaag-koelgreep-taupe/9300000231848096/",
                "price": 11.99,
                "price_last_checked": "2026-07-27",
            },
        ],
        "pros": [
            "Zeer lage aanschafprijs",
            "Licht en gemakkelijk hanteerbaar",
            "Verkrijgbaar in twee kleuren",
        ],
        "cons": [
            "Eenvoudigere afwerking",
            "Beperkte ovenbestendigheid",
        ],
        "verdict":  "Een toegankelijke budgetkeuze voor licht en regelmatig gebruik.",
    },

    "demeyere_alu_pro_5_ceraforce_24": {
        "slug": "demeyere-alu-pro-5-ceraforce-24",
        "name": "Demeyere Alu Pro 5 Ceraforce",
        "description": "Stevige aluminium koekenpan met Ceraforce keramische coating "
        "en een dikke bodem voor stabiele warmteverdeling.",
        "brand": "Demeyere",
        "diameter": 24,
        "material": "Aluminium met Ceraforce keramische antiaanbaklaag",
        "features": ["Ceraforce keramische coating",
                    "Geschikt voor inductie",
                    "Stevige aluminium constructie",],
        "rating": 4.6,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 77.00,
        "price_last_checked": "2026-07-27",
        "price_range": "€€€",
        "currency": "EUR",
        "availability": "InStock",
        "image": "demeyere-alu-pro-5-ceraforce-24cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/demeyere-12624-alu-pro-5-ceraforce-bakpan-antikleef-24-cm/9300000032747131/",
        "award": "💎 Premium keuze",
        "pros": [
            "Gelijkmatige warmteverdeling",
            "Stevige afwerking",
            "Geschikt voor intensief dagelijks gebruik",
        ],
        "cons": [
            "Relatief zwaar",
            "Hoge aanschafprijs",
        ],
        "verdict": "Onze premium keuze voor wie stevige bouwkwaliteit en stabiele "
        "warmteverdeling belangrijk vindt.",
    },

    "greenchef_diamond_24": {
        "slug": "greenchef-diamond-24",
        "name": "GreenChef Diamond Induction",
        "description": "Aluminium koekenpan met keramische "
        "antiaanbaklaag voor dagelijks gebruik.",
        "brand": "GreenChef",
        "diameter": 24,
        "material": "Aluminium met keramische antiaanbaklaag",
        "features": ["Keramische coating met diamantdeeltjes",
                    "Geschikt voor inductie",],
        "rating": 4.2,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 23.99,
        "price_last_checked": "2026-07-27",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/greenchef-diamond-inductie-koekenpan-o24-cm-keramisch-pfas-vrij-best-getest/9200000130094485/",
        "price_range": "€",
        "image": "greenchef-diamond-24cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Licht en gemakkelijk hanteerbaar",
            "Eenvoudig schoon te maken",
            "Scherpe prijs",
        ],
        "cons": [
            "Niet ovenbestendig",
        ],
        "verdict": "Een betaalbare keramische pan voor dagelijks bakken op lage tot "
        "middelhoge temperaturen.",
    },

    "bk_easy_induction_24": {
        "slug": "bk-easy-induction-24",
        "name": "BK Easy Induction Ceramic",
        "description": "PFAS-vrije keramische pan met koele greep en stevige bodem.",
        "brand": "BK",
        "diameter": 24,
        "material": "Aluminium met keramische antiaanbaklaag",
        "features": ["Koele greep", "Inductie"],
        "rating": 4.3,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 33.95,
        "price_last_checked": "2026-07-27",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/bk-easy-induction-ceramic-koekenpan-o24-cm-pfas-vrij/9300000032891762/",
        "price_range": "€€",
        "award": None,
        "image": "bk-easy-induction-24cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Goede prijs-kwaliteit",
            "Snelle opwarming",
            "Koele handgreep",
        ],
        "cons": [
            "Niet ovenbestendig",
        ],
        "verdict": "Een praktische middenklassepan met comfortabele greep "
        "en een toegankelijke prijs.",
    },

    "greenpan_torino_24": {
        "slug": "greenpan-torino-24",
        "name": "GreenPan Torino",
        "description": "Lichte aluminium koekenpan met Thermolon keramische antiaanbaklaag "
        "voor dagelijks gebruik.",
        "brand": "GreenPan",
        "diameter": 24,
        "material": "Aluminium met Thermolon keramische antiaanbaklaag",
        "features": ["Inductie", "PFAS-vrij"],
        "rating": 4.3,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 39.60,
        "price_last_checked": "2026-07-27",
        "currency": "EUR",
        "availability": "InStock",
        "price_range": "€€",
        "image": "greenpan-torino-24cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/greenpan-torino-keramische-koekenpan-24-cm/9300000036288442/",
        "pros": [
            "Licht en gemakkelijk hanteerbaar",
            "Geschikt voor inductie",
            "Eenvoudig schoon te maken",
        ],
        "cons": [
            "Beperkte ovenbestendigheid",
            "Eenvoudigere constructie dan de Barcelona Pro-serie",
        ],
        "verdict": "Een toegankelijke middenklassepan voor dagelijks gebruik en "
        "kleinere maaltijden.",
    },

    "tefal_renew_24": {
        "slug": "tefal-renew-24",
        "name": "Tefal Renew+",
        "description": "Koekenpan van 100% gerecycled aluminium met keramische antiaanbaklaag "
        "en geïntegreerde hitte-indicator.",
        "brand": "Tefal",
        "diameter": 24,
        "material": "Gerecycled aluminium met keramische antiaanbaklaag",
        "features": ["Gerecycled aluminium",
                    "Hitte-indicator",],
        "rating": 4.2,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 35.99,
        "price_last_checked": "2026-07-27",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/tefal-renew-keramische-koekenpan-o-24-cm/9300000118641479/",
        "price_range": "€€",
        "award": "",
        "image": "tefal-renew-24cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Pan van gerecycled materiaal",
            "Goede warmtegeleiding",
            "Handige hitte-indicator",
        ],
        "cons": [
            "Niet ovenbestendig",
        ],
        "verdict": "Een gebruiksvriendelijke keuze voor wie een keramische Tefal-pan "
        "met hitte-indicator zoekt.",
    },

    "bk_enjoy_24": {
        "slug": "bk-enjoy-24",
        "name": "BK Enjoy",
        "description": "Lichtgewicht aluminium koekenpan met keramische antiaanbaklaag "
        "voor dagelijks gebruik.",
        "brand": "BK",
        "diameter": 24,
        "material": "Aluminium met keramische antiaanbaklaag",
        "features": ["Lichtgewicht", "Eenvoudig schoon te maken"],
        "rating": 4.1,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 29.90,
        "price_last_checked": "2026-07-27",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.kookexpert.nl/koekenpan-bk-enjoy-met-keramische-antikleeflaag-24-cm.html",
        "price_range": "€€",
        "image": "bk-enjoy-24cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Licht en gemakkelijk hanteerbaar",
            "Goede warmtegeleiding",
            "Eenvoudig schoon te maken",
        ],
        "cons": [
            "Niet geschikt voor oven",
        ],
        "verdict": "Een lichte en praktische koekenpan voor eenvoudig dagelijks gebruik.",
    },

    "ikea_hemlagad_keramisch_24": {
        "slug": "ikea-hemlagad-keramisch-24",
        "name": "IKEA HEMLAGAD",
        "description": "Voordelige aluminium koekenpan met keramische antiaanbaklaag "
        "voor kleinere dagelijkse bereidingen.",
        "brand": "IKEA",
        "diameter": 24,
        "material": "Aluminium met keramische antiaanbaklaag",
        "features": [
            "Geschikt voor inductie",
            "Keramische antiaanbaklaag",
        ],
        "rating": 3.9,
        "rating_count": None,
        "rating_source": "editorial",
        "price_range": "€",
        "price": 9.99,
        "price_last_checked": "2026-07-27",
        "currency": "EUR",
        "availability": "InStock",
        "image": "ikea-hemlagad-keramisch-24cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "affiliate_url": "",
        "retailer_url": "https://www.ikea.com/nl/nl/p/hemlagad-koekenpan-antiaanbaklaag-zwart-60580893/",
        "pros": [
            "Zeer lage aanschafprijs",
            "Geschikt voor inductie",
            "Licht en eenvoudig in gebruik",
        ],
        "cons": [
            "Eenvoudigere constructie dan duurdere modellen",
        ],
        "verdict": "Een zeer voordelige keuze voor licht dagelijks gebruik en kleinere porties.",
    },

    "berndes_b_green_24": {
        "slug": "berndes-b-green-24",
        "name": "Berndes B.Green",
        "description":  "Een veelzijdige midden-premiumpan voor wie gerecycled aluminium "
        "en brede gebruiksmogelijkheden belangrijk vindt.",
        "brand": "Berndes",
        "diameter": 24,
        "material": "Gerecycled aluminium met b.nature kwarts-antiaanbaklaag",
        "features": ["b.nature kwarts-coating", "Inductie", "100% gerecycled aluminium", "Ovenbestendig", "Vaatwasserbestendig"],
        "rating": 4.4,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 64.99,
        "price_last_checked": "2026-07-27",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/b-green-koekenpan-24-cm-berndes/9300000006419832/",
        "award": None,
        "price_range": "€€€",
        "image": "berndes-b-green-24cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Pan gemaakt van gerecycled aluminium",
            "Specifieke b.nature kwartscoating",
            "Geschikt voor inductie",       
        ],
        "cons": [
            "Hogere aanschafprijs",
            "Beperkte ovenbestendigheid",
        ],
        "verdict": "Milieuvriendelijke keuze voor wie echt PFAS-vrij wil koken met een coating van volledig natuurlijke grondstoffen.",
    },

    # 26CM KOEKENPANNEN
    "greenpan_barcelona_pro_26": {
        "slug": "greenpan-barcelona-pro-26",
        "name": "GreenPan Barcelona Pro",
        "description": "Stevige aluminium koekenpan met Thermolon keramische "
        "antiaanbaklaag, inductiebodem en ovenbestendige RVS greep.",
        "brand": "GreenPan",
        "diameter": 26,
        "material": "Aluminium met Thermolon keramische antiaanbaklaag",
        "features": ["Geschikt voor inductie",
                    "Ovenbestendig tot 220 °C",],
        "rating": 4.7,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 79.90,
        "price_last_checked": "2026-07-27",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/greenpan-barcelona-pro-koekenpan-met-keramische-antikleeflaag-26-cm/9300000112544367/",
        "award": "🏆 Beste keuze",
        "price_range": "€€€",
        "image": "greenpan-barcelona-pro-26cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Gelijkmatige warmteverdeling",
            "Stevige constructie",
            "Geschikt voor ovengebruik",
        ],
        "cons": [
            "Relatief zwaar",
            "Hogere aanschafprijs",
        ],
        "verdict": "Onze beste allround keuze voor wie een stevige en veelzijdige "
    "keramische koekenpan zoekt.",
    },

    "greenchef_vintage_26": {
        "slug": "greenchef-vintage-26",
        "name": "GreenChef Vintage",
        "description": "Aluminium koekenpan met keramische antiaanbaklaag en "
        "een herkenbare vintage afwerking.",
        "brand": "GreenChef",
        "diameter": 26,
        "material": "Aluminium met keramische antiaanbaklaag",
        "features": [
            "Geschikt voor inductie",
            "Vintage afwerking",
        ],
        "rating": 4.3,
        "rating_count": None,
        "rating_source": "editorial",
        "price_range": "€€",
        "price": 42.90,
        "price_last_checked": "2026-07-27",
        "currency": "EUR",
        "availability": "InStock",
        "image": "greenchef-vintage-26cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/greenchef-vintage-koekenpan-26cm-zwart-inductie-pfas-vrij/9200000130094513/",
        "award": None,
        "pros": [
            "Aantrekkelijke vormgeving",
            "Geschikt voor inductie",
            "Toegankelijke middenklasseprijs",
        ],
        "cons": [
            "Eenvoudigere afwerking dan premium modellen",
        ],
        "verdict": "Een toegankelijke middenklassepan die een aantrekkelijke vormgeving "
    "combineert met dagelijks gebruiksgemak.",
    },

    "demeyere_alu_pro_5_ceraforce_26": {
        "slug": "demeyere-alu-pro-5-ceraforce-26",
        "name": "Demeyere Alu Pro 5 Ceraforce",
        "description": "Stevige aluminium koekenpan met Ceraforce keramische "
        "antiaanbaklaag en een bodem voor stabiele warmteverdeling.",
        "brand": "Demeyere",
        "diameter": 26,
        "material": "Aluminium met Ceraforce keramische antiaanbaklaag",
        "features": ["Geschikt voor inductie",
                    "Ceraforce keramische coating",],
        "rating": 4.6,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 83.00,
        "price_last_checked": "2026-07-27",
        "price_range": "€€€",
        "currency": "EUR",
        "availability": "InStock",
        "image": "demeyere-alu-pro-5-ceraforce-26cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/demeyere-alu-pro-ceraforce-koekenpan-26-cm/9300000045881510/",
        "award": "💎 Premium keuze",
        "pros": [
            "Gelijkmatige warmteverdeling",
            "Stevige afwerking",
            "Geschikt voor intensief dagelijks gebruik",
        ],
        "cons": [
            "Relatief zwaar",
            "Hoge aanschafprijs",
        ],
        "verdict": "Onze premium keuze voor wie stevige bouwkwaliteit en stabiele "
    "warmteverdeling belangrijk vindt.",
    },

    "bk_easy_induction_26": {
        "slug": "bk-easy-induction-26",
        "name": "BK Easy Induction Ceramic",
        "description": "Aluminium koekenpan met keramische antiaanbaklaag, "
        "koel blijvende greep en stevige inductiebodem.",
        "brand": "BK",
        "diameter": 26,
        "material": "Aluminium met keramische antiaanbaklaag",
        "features": ["Geschikt voor inductie",
                    "Ovenbestendig tot 160 °C"],
        "rating": 4.3,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 37.95,
        "price_last_checked": "2026-07-27",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/bk-easy-induction-ceramic-koekenpan-o26-cm-inductie-pfas-vrij/9300000032891766/",
        "price_range": "€€",
        "award": "💰 Budget keuze",
        "image": "bk-easy-induction-26cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Snelle en gelijkmatige opwarming",
            "Koel blijvende handgreep",
            "Geschikt voor oven en vaatwasser",
        ],
        "cons": [
             "Beperkt tot maximaal 160 °C in de oven",
        ],
        "verdict": "Een betaalbare allrounder met comfortabele greep en bruikbare "
        "ovenbestendigheid.",
    },

    "fissler_essential_26": {
        "slug": "fissler-essential-26",
        "name": "Fissler Essential",
        "description": (
            "Aluminium koekenpan met keramische antiaanbaklaag, "
            "Essential-inductiebodem en een gladde binnenzijde die eenvoudig "
            "schoon te maken is."
        ),
        "brand": "Fissler",
        "diameter": 26,
        "material": (
            "100% gerecycled aluminium met keramische antiaanbaklaag"
        ),
        "features": [
            "Geschikt voor inductie",
            "Essential-inductiebodem",
            "Ergonomische kunststof handgreep",
        ],
        "rating": 4.3,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 53.99,
        "price_last_checked": "2026-07-30",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/fissler-essential-koekenpan-26cm/9300000233111085/",
        "award": "",
        "price_range": "€€€",
        "image": "fissler-essential-26cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Gelijkmatige warmteverdeling",
            "Eenvoudig schoon te maken",
            "Comfortabele handgreep",
        ],
        "cons": [
            "Minder geschikt voor kookplaten met een zeer hoog vermogen",
            "Kunststof handgreep beperkt de inzetbaarheid in de oven",
        ],
        "verdict": (
            "Een gebruiksvriendelijke middenklassepan met eenvoudige reiniging "
            "en een keramische antiaanbaklaag."
        ),
    },
    "greenpan_venice_pro_26": {
        "slug": "greenpan-venice-pro-26",
        "name": "GreenPan Venice Pro Ceramic",
        "description": "Hard-geanodiseerde aluminium koekenpan met "
        "keramische antiaanbaklaag en ovenbestendige RVS greep.",
        "brand": "GreenPan",
        "diameter": 26,
        "material": "Hard-geanodiseerd aluminium met "
    "keramische antiaanbaklaag",
        "features": [
            "Geschikt voor inductie",
            "Ovenbestendige RVS greep",
            "Vaatwasserbestendig; handwas aanbevolen",
        ],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 99.90,
        "price_last_checked": "2026-07-27",
        "currency": "EUR",
        "availability": "InStock",
        "price_range": "€€€€",
        "image": "greenpan-venice-pro-26cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "affiliate_url": "",
        "retailer_url": "https://greenpan.nl/products/venice-pro-koekenpan-26cm",
        "pros": [
            "Stevig hard-geanodiseerd panlichaam",
            "Geschikt voor ovengebruik",
            "Gelijkmatige warmteverdeling",
        ],
        "cons": [
            "Relatief zwaar",
            "Hoge aanschafprijs",
        ],
        "verdict": "Een stevige premiumoptie voor wie ovengebruik, een RVS greep "
    "en een hard-geanodiseerde pan waardeert.",
    },
    "scanpan_nura_26": {
        "slug": "scanpan-nura-26",
        "name": "Scanpan Nura",
        "description": (
            "Meerlaagse stalen koekenpan met Stratanium Leap keramische "
            "antiaanbaklaag en een ovenbestendige RVS handgreep."
        ),
        "brand": "Scanpan",
        "diameter": 26,
        "material": (
            "Meerlaags staal met Stratanium Leap keramische antiaanbaklaag"
        ),
        "features": [
            "Geschikt voor alle warmtebronnen",
            "Ovenbestendig tot 250 °C",
            "Vaatwasserbestendig",
        ],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": None,
        "price_last_checked": None,
        "currency": "EUR",
        "availability": None,
        "availability_label": "Nog niet algemeen verkrijgbaar",
        "affiliate_url": "",
        "official_url": "https://www.scanpan.eu/shop/28-cm-fry-pan-nura/26cm",
        "award": "",
        "price_range": None,
        "image": "scanpan-nura-26cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Stevige meerlaagse staalconstructie",
            "Geschikt voor ovengebruik tot 250 °C",
            "Geschikt voor alle gangbare warmtebronnen",
        ],
        "cons": [
            "Relatief zwaar met een gewicht van circa 1,33 kg",
            "Nog niet algemeen verkrijgbaar in Nederland",
        ],
        "verdict": (
            "Een veelzijdige premiumoptie met brede inzetbaarheid, "
            "maar voorlopig nog beperkt verkrijgbaar."
        ),
    },

    # 20CM KOEKENPANNEN

    "greenpan_barcelona_pro_20": {
        "slug": "greenpan-barcelona-pro-20",
        "name": "GreenPan Barcelona Pro",
        "description": "Stevige aluminium koekenpan met Thermolon Infinity Pro "
        "keramische antiaanbaklaag, inductiebodem en ovenbestendige greep.",
        "brand": "GreenPan",
        "diameter": 20,
        "material": "Aluminium met Thermolon Infinity Pro keramische antiaanbaklaag",
        "features": ["Geschikt voor inductie",
                    "Ovenbestendig tot 220 °C",
                    "RVS handgreep",],
        "rating": 4.7,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 69.06,
        "price_last_checked": "2026-07-27",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/greenpan-barcelona-pro-bakpan-20cm/9300000118067708/",
        "award": "🏆 Beste keuze",
        "price_range": "€€€",
        "image": "greenpan-barcelona-pro-20cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Gelijkmatige warmteverdeling",
            "Stevige constructie",
            "Geschikt voor ovengebruik",
        ],
        "cons": [
            "Relatief zwaar voor een pan van 20 cm",
            "Hogere aanschafprijs",
        ],
        "verdict": "Onze beste allround keuze voor wie een stevige en veelzijdige "
    "koekenpan voor kleinere bereidingen zoekt.",
    },

    "kochstar_essenz_20": {
        "slug": "kochstar-essenz-20",
        "name": "Kochstar Essenz",
        "description": "Voordelige aluminium koekenpan met keramische antiaanbaklaag, "
        "inductiebodem en koel blijvende handgreep.",
        "brand": "Kochstar",
        "diameter": 20,
        "material": "Aluminium met keramische antiaanbaklaag",
        "features": ["Geschikt voor inductie",
                    "Lichtgewicht",
                    "Koel blijvende handgreep",],
        "rating": 4,
        "rating_count": None,
        "rating_source": "editorial",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/kochstar-essenz-koekenpan-20cm-pfas-vrij-inductie-pan-keramische-anti-aanbaklaag-koelgreep-zwart/9300000231848104/",
        "award": "💰 Budget keuze",
        "price_range": "€",
        "image": "koekenpan02_kochstar_essenz_20cm.jpg",
        "image_path": "images/products/keramische-koekenpannen",
        "variants": [
            {
                "name": "Zwart",
                "image": "kochstar-essenz-zwart-20cm.webp",
                "hex": "#000000",
                "affiliate_url": "",
                "retailer_url": "https://www.bol.com/nl/nl/p/kochstar-essenz-koekenpan-20cm-pfas-vrij-inductie-pan-keramische-anti-aanbaklaag-koelgreep-zwart/9300000231848104/",
                "price": 8.99,
                "price_last_checked": "2026-07-27",
            },
            {
                "name": "Taupe",
                "image": "kochstar-essenz-taupe-20cm.webp",
                "hex": "#B8A99A",
                "affiliate_url":"",
                "retailer_url": "https://www.bol.com/nl/nl/p/kochstar-essenz-koekenpan-20cm-pfas-vrij-inductie-pan-keramische-anti-aanbaklaag-koelgreep-taupe/9300000231848112/",
                "price": 8.99,
                "price_last_checked": "2026-07-27",
            },
        ],
        "pros": [
            "Zeer lage aanschafprijs",
            "Licht en gemakkelijk hanteerbaar",
            "Verkrijgbaar in twee kleuren",
        ],
        "cons": [
            "Beperkte ovenbestendigheid",
            "Eenvoudigere afwerking dan duurdere modellen",
        ],
        "verdict": "Een zeer voordelige keuze voor kleinere porties en licht dagelijks gebruik.",
    },

    "demeyere_alu_pro_5_ceraforce_20": {
        "slug": "demeyere-alu-pro-5-ceraforce-20",
        "name": "Demeyere Alu Pro 5 Ceraforce",
        "description": "Stevige aluminium koekenpan met Ceraforce keramische "
        "antiaanbaklaag en een bodem voor stabiele warmteverdeling.",
        "brand": "Demeyere",
        "diameter": 20,
        "material": "Aluminium met Ceraforce keramische antiaanbaklaag",
        "features": ["Geschikt voor inductie",
                    "Ceraforce keramische coating",
                    "Stevige aluminium constructie",],
        "rating": 4.6,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 72.25,
        "price_last_checked": "2026-07-27",
        "price_range": "€€€",
        "currency": "EUR",
        "availability": "InStock",
        "image": "demeyere-alu-pro-5-ceraforce-20cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/demeyere-12620-alu-pro-5-ceraforce-bakpan-antikleef-20-cm/9300000035395887/",
        "award": "💎 Premium keuze",
        "pros": [
            "Gelijkmatige warmteverdeling",
            "Stevige afwerking",
            "Geschikt voor intensief dagelijks gebruik",
        ],
        "cons": [
            "Relatief zwaar voor het compacte formaat",
            "Hoge aanschafprijs",
        ],
        "verdict": "Onze premium keuze voor wie stevige bouwkwaliteit en stabiele "
    "warmteverdeling in een compact formaat belangrijk vindt.",
    },

    "greenchef_diamond_20": {
        "slug": "greenchef-diamond-20",
        "name": "GreenChef Diamond Induction",
        "description": "Aluminium koekenpan met keramische "
        "antiaanbaklaag voor kleinere dagelijkse bereidingen.",
        "brand": "GreenChef",
        "diameter": 20,
        "material": "Aluminium met keramische antiaanbaklaag",
        "features": ["Keramische coating met diamantdeeltjes",
                    "Geschikt voor inductie",
                    "Lichtgewicht",],
        "rating": 4.2,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 23.39,
        "price_last_checked": "2026-07-28",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/greenchef-diamond-koekenpan-20cm-zwart-inductie-pfas-vrij/9200000130094501/",
        "price_range": "€",
        "image": "greenchef-diamond-20cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Scherpe aanschafprijs",
            "Goede warmteverdeling",
            "Eenvoudig schoon te maken",
        ],
        "cons": [
            "Niet ovenbestendig",
        ],
        "verdict": "Een scherp geprijsde keramische koekenpan voor kleine dagelijkse bereidingen.",
    },

    "bk_easy_induction_20": {
        "slug": "bk-easy-induction-20",
        "name": "BK Easy Induction Ceramic",
        "description": "Aluminium koekenpan met keramische antiaanbaklaag, "
        "koel blijvende greep en stevige inductiebodem.",
        "brand": "BK",
        "diameter": 20,
        "material": "Aluminium met keramische antiaanbaklaag",
        "features": ["Geschikt voor inductie",
                    "Ovenbestendig tot 160 °C",
                    "Vaatwasserbestendig",],
        "rating": 4.3,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 28.95,
        "price_last_checked": "2026-07-28",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/bk-easy-induction-ceramic-koekenpan-o20-cm-pfas-vrij/9300000032891763/",
        "price_range": "€€",
        "award": None,
        "image": "bk-easy-induction-20cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Snelle en gelijkmatige opwarming",
            "Koel blijvende handgreep",
            "Geschikt voor oven en vaatwasser",
        ],
        "cons": [
            "Beperkt tot maximaal 160 °C in de oven",
        ],
        "verdict": "Een betaalbare allrounder met comfortabele greep en bruikbare "
        "ovenbestendigheid.",
    },

    "greenpan_mayflower_20": {
        "slug": "greenpan-mayflower-20",
        "name": "GreenPan Mayflower",
        "description": "Aluminium koekenpan met Thermolon "
        "keramische antiaanbaklaag en houten handgreep.",
        "brand": "GreenPan",
        "diameter": 20,
        "material": "Aluminium met Thermolon keramische antiaanbaklaag",
        "features": [
            "Geschikt voor inductie",
            "Houten handgreep",
            "Alleen handwas",
        ],
        "rating": 4.4,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 41.99,
        "price_last_checked": "2026-07-28",
        "currency": "EUR",
        "availability": "InStock",
        "price_range": "€€",
        "image": "greenpan-mayflower-grijs-20cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/greenpan-mayflower-pro-koekenpan-20cm-grijs-inductie-pfas-vrij/9300000091450193/",
        "pros": [
            "Goede warmteverdeling",
            "Comfortabele houten handgreep",
            "Aantrekkelijke vormgeving",
        ],
        "cons": [
            "Niet geschikt voor ovengebruik",
            "Niet vaatwasserbestendig",
        ],
        "verdict": "Een compacte designkeuze met houten greep voor dagelijks gebruik.",
    },

    "tefal_renew_20": {
        "slug": "tefal-renew-20",
        "name": "Tefal Renew+",
        "description": "Koekenpan van gerecycled aluminium met keramische "
        "antiaanbaklaag en geïntegreerde hitte-indicator.",
        "brand": "Tefal",
        "diameter": 20,
        "material": "Gerecycled aluminium met keramische antiaanbaklaag",
        "features": [ "Gerecycled aluminium",
                    "Thermo-Signal hitte-indicator",
                    "Geschikt voor inductie",],
        "rating": 4.2,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 30.99,
        "price_last_checked": "2026-07-28",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/tefal-renew-keramische-koekenpan-o-20-cm/9300000120126719/",
        "price_range": "€€",
        "award": "",
        "image": "tefal-renew-20cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Pan gemaakt van gerecycled materiaal",
            "Goede warmtegeleiding",
            "Thermo-Spot-hitte-indicator",
        ],
        "cons": [
            "Niet ovenbestendig",
        ],
        "verdict": "Een gebruiksvriendelijke compacte pan met geïntegreerde hitte-indicator.",
    },

    "bk_enjoy_20": {
        "slug": "bk-enjoy-20",
        "name": "BK Enjoy",
        "description": "Lichte aluminium koekenpan met keramische antiaanbaklaag "
        "voor kleine dagelijkse bereidingen.",
        "brand": "BK",
        "diameter": 20,
        "material": "Aluminium met keramische antiaanbaklaag",
        "features": ["Geschikt voor inductie",
                    "Ovenbestendig tot 160 °C",
                    "Vaatwasserbestendig",],
        "rating": 4.1,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 24.90,
        "price_last_checked": "2026-07-28",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/bk-enjoy-koekenpan-20cm-pfas-vrije-antikleeflaag-koekenpan-inductie-keramische-pan-ovenbestendig-tot-160-c-vaatwasserbestendig-koudgrepen-oxford-blue/9300000311002492/",
        "price_range": "€",
        "image": "bk-enjoy-20cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Licht en gemakkelijk hanteerbaar",
            "Goede warmtegeleiding",
            "Geschikt voor oven en vaatwasser",
        ],
        "cons": [
            "Beperkte maximale oventemperatuur van 160 °C",
        ],
        "verdict": "Een lichte en praktische koekenpan voor kleine dagelijkse bereidingen.",
    },

    "hema_milano_20": {
        "slug": "hema-milano-20",
        "name": "HEMA Milano",
        "description": "Compacte en betaalbare keramische koekenpan voor dagelijks gebruik.",
        "brand": "HEMA",
        "diameter": 20,
        "material": "Pan met RVS bodem, aluminium warmteverdeelplaat "
    "en keramische antiaanbaklaag",
        "features": [
            "Lichtgewicht",
            "Geschikt voor inductie",
        ],
        "rating": 4,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 26.99,
        "price_last_checked": "2026-07-28",
        "currency": "EUR",
        "availability": "InStock",
        "price_range": "€€",
        "image": "hema-milano-20cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "affiliate_url": "",
        "retailer_url": "https://www.hema.nl/koken-tafelen/koken/pannen/koekenpannen/koekenpan-20cm-milano-pfas-vrij-80120001.html",
        "pros": [
            "Compact en licht in gebruik",
            "Geschikt voor inductie",
            "Toegankelijke aanschafprijs",
        ],
        "cons": [
             "Eenvoudigere afwerking dan premium modellen",
        ],
        "verdict": "Een toegankelijke instappan voor kleine porties en dagelijks gebruik.",
    },

    "berndes_b_green_20": {
        "slug": "berndes-b-green-20",
        "name": "Berndes B.Green",
        "description": "Koekenpan van gerecycled aluminium met b.nature "
        "kwarts-antiaanbaklaag en inductiebodem.",
        "brand": "Berndes",
        "diameter": 20,
        "material": "100% gerecycled aluminium met b.nature kwarts-antiaanbaklaag",
        "features": ["Geschikt voor inductie",
                    "Panlichaam van gerecycled aluminium",
                    "Vaatwasserbestendig",],
        "rating": 4.3,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 40.00,
        "price_last_checked": "2026-07-28",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/berndes-b-green-koekenpan-20-cm-gerecycled-aluminium-zilver/9300000006419842/",
        "award": None,
        "price_range": "€€",
        "image": "berndes-b-green-20cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Pan gemaakt van 100% gerecycled aluminium",
            "Specifieke b.nature kwartscoating",
            "Geschikt voor inductie",
        ],
        "cons": [
            "Hogere prijs dan de meeste compacte instapmodellen",
            "Beperkte ovenbestendigheid tot 160 °C",
        ],
        "verdict": "Een onderscheidende middenklassekeuze met gerecycled "
        "aluminium en een specifieke kwartscoating.",
    },

    # 30CM KOEKENPANNEN

    "greenpan_barcelona_pro_30": {
        "slug": "greenpan-barcelona-pro-30",
        "name": "GreenPan Barcelona Pro",
        "description": "Stevige aluminium koekenpan met Thermolon keramische "
        "antiaanbaklaag, inductiebodem en ovenbestendige RVS handgreep.",
        "brand": "GreenPan",
        "diameter": 30,
        "material": "Aluminium met Thermolon keramische antiaanbaklaag",
        "features": ["Geschikt voor inductie",
                    "Ovenbestendig tot 220 °C",
                    "RVS handgreep",],
        "rating": 4.7,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 76.00,
        "price_last_checked": "2026-07-28",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/greenpan-barcelona-pro-bakpan-30cm/9300000118068291/",
        "award": "🏆 Beste keuze",
        "price_range": "€€€",
        "image": "greenpan-barcelona-pro-30cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Gelijkmatige warmteverdeling",
            "Stevige constructie",
            "Ovenbestendig tot 220 °C",
        ],
        "cons": [
            "Relatief zwaar",
            "Hoge aanschafprijs",
        ],
        "verdict": "Onze beste allround keuze voor grotere porties en veelzijdig dagelijks gebruik.",
    },

    "kochstar_stein_30": {
        "slug": "kochstar-stein-30",
        "name": "Kochstar Stein",
        "description": "Voordelige aluminium koekenpan met keramische antiaanbaklaag, "
        "koel blijvende handgreep en ruim bakoppervlak.",
        "brand": "Kochstar",
        "diameter": 30,
        "material": "Aluminium met keramische antiaanbaklaag",
        "features": ["Geschikt voor inductie",
            "Ovenbestendig tot 130 °C",
            "Koel blijvende handgreep",
        ],
        "rating": 4,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 15.33,
        "price_last_checked": "2026-07-28",
        "currency": "EUR",
        "availability": "InStock",
        "price_range": "€",
        "image": "kochstar-stein-30cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "award": "💰 Budget keuze",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/kochstar-stein-koekenpan-30cm-pfas-vrij-inductie-pan-keramische-anti-aanbaklaag-koelgreep-graniet/9300000231848100/",
        "pros": [
            "Zeer lage aanschafprijs",
            "Ruim bakoppervlak",
            "Koel blijvende handgreep",
        ],
        "cons": [
            "Beperkte maximale oventemperatuur van 130 °C",
            "Eenvoudigere afwerking dan duurdere modellen",
        ],
        "verdict": "Een zeer voordelige keuze voor grotere porties en dagelijks gebruik.",
    },

    "demeyere_alu_pro_5_ceraforce_30": {
        "slug": "demeyere-alu-pro-5-ceraforce-30",
        "name": "Demeyere Alu Pro 5 Ceraforce",
        "description": "Stevige aluminium koekenpan met Ceraforce keramische "
        "antiaanbaklaag en inductiebodem voor grotere bereidingen.",
        "brand": "Demeyere",
        "diameter": 30,
        "material": "Aluminium met Ceraforce keramische antiaanbaklaag",
        "features": ["Geschikt voor inductie",
                    "Ceraforce keramische coating",
                    "Ovenbestendig tot 230 °C",],
        "rating": 4.6,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 95.98,
        "price_last_checked": "2026-07-28",
        "price_range": "€€€€",
        "currency": "EUR",
        "availability": "InStock",
        "image": "demeyere-alu-pro-5-ceraforce-30cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/demeyere-alu-pro-ceraforce-koekenpan-30-cm/9300000045881607/",
        "award": "💎 Premium keuze",
        "pros": [
            "Gelijkmatige warmteverdeling",
            "Stevige afwerking",
            "Ruim bakoppervlak",
        ],
        "cons": [
            "Relatief zwaar",
            "Hoge aanschafprijs",
        ],
        "verdict": "Onze premium keuze voor wie stabiele warmteverdeling en een "
        "ruim bakoppervlak belangrijk vindt.",
    },

    "greenchef_diamond_30": {
        "slug": "greenchef-diamond-30",
        "name": "GreenChef Diamond Induction",
        "description": "Aluminium koekenpan met keramische antiaanbaklaag "
        "waaraan volgens de fabrikant diamantdeeltjes zijn toegevoegd.",
        "brand": "GreenChef",
        "diameter": 30,
        "material": "Aluminium met keramische antiaanbaklaag",
        "features": [ "Keramische coating met diamantdeeltjes",
                    "Geschikt voor inductie",],
        "rating": 4.2,
        "rating_count": None,
        "rating_source": "editorial",
        "price_last_checked": "2026-07-28",
        "price": 39.90,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/greenchef-diamond-koekenpan-30cm-zwart-inductie-pfas-vrij/9200000131576064/",
        "price_range": "€€",
        "image": "greenchef-diamond-30cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Toegankelijke aanschafprijs",
            "Goede warmteverdeling",
            "Eenvoudig schoon te maken",
        ],
        "cons": [
            "Niet ovenbestendig",
        ],
        "verdict": "Een betaalbare grote koekenpan voor dagelijkse gezinsmaaltijden.",
    },

    "bk_easy_induction_30": {
        "slug": "bk-easy-induction-30",
        "name": "BK Easy Induction Ceramic",
        "description": "Aluminium koekenpan met keramische antiaanbaklaag, "
        "koel blijvende handgreep en stevige inductiebodem.",
        "brand": "BK",
        "diameter": 30,
        "material": "Aluminium met keramische antiaanbaklaag",
        "features": ["Geschikt voor inductie",
                    "Ovenbestendig tot 160 °C",
                    "Vaatwasserbestendig",],
        "rating": 4.3,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 44.95,
        "price_last_checked": "2026-07-28",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/bk-easy-induction-ceramic-koekenpan-o30-cm-pfas-vrij/9300000032891768/",
        "price_range": "€€",
        "award": None,
        "image": "bk-easy-induction-30cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Snelle en gelijkmatige opwarming",
            "Koel blijvende handgreep",
            "Geschikt voor oven en vaatwasser",
        ],
        "cons": [
            "Beperkte maximale oventemperatuur van 160 °C",
        ],
         "verdict": "Een betaalbare allrounder met ruim bakoppervlak en bruikbare "
        "ovenbestendigheid.",
    },

    "greenpan_torino_30": {
        "slug": "greenpan-torino-30",
        "name": "GreenPan Torino",
        "description": "Lichte aluminium koekenpan met Thermolon keramische "
        "antiaanbaklaag voor dagelijks gebruik.",
        "brand": "GreenPan",
        "diameter": 30,
        "material": "Aluminium met Thermolon keramische antiaanbaklaag",
        "features": [  "Geschikt voor inductie",
                    "Ovenbestendig tot 160 °C",
                    "Vaatwasserbestendig",],
        "rating": 4.2,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 39.00,
        "price_last_checked": "2026-07-28",
        "currency": "EUR",
        "availability": "InStock",
        "price_range": "€€",
        "image": "greenpan-torino-30cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/greenpan-torino-keramische-koekenpan-30-cm/9300000121455786/",
        "pros": [
            "Licht en gemakkelijk hanteerbaar",
            "Geschikt voor inductie",
            "Ruim bakoppervlak",
        ],
        "cons": [
            "Beperkte maximale oventemperatuur van 160 °C",
        ],
        "verdict": "Een toegankelijke grote koekenpan voor dagelijks gebruik en grotere porties.",
    },

    "tefal_renew_30": {
        "slug": "tefal-renew-30",
        "name": "Tefal Renew+",
        "description": "Koekenpan van gerecycled aluminium met keramische "
        "antiaanbaklaag en geïntegreerde hitte-indicator.",
        "brand": "Tefal",
        "diameter": 30,
        "material": "Gerecycled aluminium met keramische antiaanbaklaag",
        "features": ["Gerecycled aluminium", "Thermo-Signal hitte-indicator", "Geschikt voor inductie",],
        "rating": 4.2,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 43.99,
        "price_last_checked": "2026-07-28",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/tefal-renew-keramische-koekenpan-o-30-cm/9300000120126720/",
        "price_range": "€€",
        "award": "",
        "image": "tefal-renew-30cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Pan gemaakt met gerecycled materiaal",
            "Goede warmtegeleiding",
            "Thermo-Spot-hitte-indicator",
        ],
        "cons": [
            "Niet ovenbestendig",
        ],
        "verdict": "Een gebruiksvriendelijke grote pan met geïntegreerde hitte-indicator.",
    },

    "brabantia_indu_plus_r_30": {
        "slug": "brabantia-indu-plus-r-30",
        "name": "Brabantia Indu+ R Keramische Koekenpan (30 cm)",
        "description": "Ruime koekenpan van gerecycled aluminium met keramische "
        "antiaanbaklaag en geschiktheid voor inductie.",
        "brand": "Brabantia",
        "diameter": 30,
        "material": "Gerecycled aluminium met keramische antiaanbaklaag",
        "features": [ "Geschikt voor inductie",
            "Ruim bakoppervlak",
            "Ergonomische handgreep",
        ],
        "rating": 4.1,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 15.09,
        "price_last_checked": "2026-07-28",
        "currency": "EUR",
        "availability": "InStock",
        "price_range": "€",
        "image": "brabantia-indu-plus-r-30cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/brabantia-indu-r-koekenpan-o-30-cm-100-gerecycled-aluminium-keramische-antiaanbaklaag-ergonomisch-en-licht-ook-geschikt-voor-inductie-100-pfas-vrij-kleur-grijs/9300000183634541/",
        "pros": [
            "Zeer lage aanschafprijs",
            "Ruim bakoppervlak",
            "Geschikt voor inductie",
        ],
        "cons": [
            "Geen premium afwerking",
            "Ovenbestendigheid niet bevestigd",
        ],
        "verdict": "Een zeer scherp geprijsde grote koekenpan voor inductie en "
    "dagelijkse gezinsmaaltijden.",
    },

    # 32CM KOEKENPANNEN
    "greenpan_barcelona_pro_32": {
        "slug": "greenpan-barcelona-pro-32",
        "name": "GreenPan Barcelona Pro",
        "description": "Grote aluminium koekenpan met Thermolon keramische "
        "antiaanbaklaag, inductiebodem en ovenbestendige RVS handgreep.",
        "brand": "GreenPan",
        "diameter": 32,
        "material": "Aluminium met Thermolon keramische antiaanbaklaag",
        "features": [ "Geschikt voor inductie",
                    "Ovenbestendig",
                    "Vaatwasserbestendig; handwas aanbevolen",],
        "rating": 4.7,
      "rating_count": None,
        "rating_source": "editorial",
        "price": 80.00,
        "price_last_checked": "2026-07-28",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": (
            "https://www.bol.com/nl/nl/p/"
            "greenpan-barcelona-pro-bakpan-32cm/"
            "9300000118071130/"
        ),
        "official_url": "",
        "availability_label": "",
        "award": "🏆 Beste keuze",
        "price_range": "€€€",
        "image": "greenpan-barcelona-pro-32cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Gelijkmatige warmteverdeling",
            "Ruim bakoppervlak",
            "Geschikt voor ovengebruik",
        ],
        "cons": [
            "Relatief zwaar",
            "Hoge aanschafprijs",
        ],
        "verdict": (
            "Onze beste allround keuze voor grote porties en "
            "veelzijdig dagelijks gebruik."
        ),
    },

    "demeyere_alu_pro_5_ceraforce_32": {
        "slug": "demeyere-alu-pro-5-ceraforce-32",
        "name": "Demeyere Alu Pro 5 Ceraforce",
        "description": (
            "Grote aluminium koekenpan met Ceraforce keramische "
            "antiaanbaklaag en inductiebodem."
        ),
        "brand": "Demeyere",
        "diameter": 32,
        "material": "Aluminium met Ceraforce keramische antiaanbaklaag",
        "features": [
            "Geschikt voor inductie",
            "Ceraforce keramische coating",
            "Ruim bakoppervlak",
        ],
        "rating": 4.6,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 99.50,
        "price_last_checked": "2026-07-28",
        "price_range": "€€€€",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": (
            "https://www.bol.com/nl/nl/p/"
            "demeyere-alu-pro-5-ceraforce-bakpan-32cm/"
            "9300000023769225/"
        ),
        "official_url": "",
        "availability_label": "",
        "award": "💎 Premium keuze",
        "image": "demeyere-alu-pro-5-ceraforce-32cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Gelijkmatige warmteverdeling",
            "Stevige afwerking",
            "Geschikt voor grote porties",
        ],
        "cons": [
            "Relatief zwaar",
            "Hoge aanschafprijs",
        ],
        "verdict": (
            "Onze premium keuze voor wie stabiele warmteverdeling "
            "en een groot bakoppervlak belangrijk vindt."
        ),
    },

    "combekk_forest_easy_32": {
        "slug": "combekk-forest-easy-32",
        "name": "Combekk Forest Easy",
        "description": "Grote koekenpan van gerecycled aluminium met keramische "
        "antiaanbaklaag, inductiebodem en koel blijvende handgreep.",
        "brand": "Combekk",
        "diameter": 32,
        "material": "Gerecycled aluminium met keramische antiaanbaklaag",
        "features": [
            "Geschikt voor alle warmtebronnen",
            "Volledig magnetische inductiebodem",
            "Koel blijvende bakelieten handgreep",
        ],
        "rating": 4.4,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 59.00,
     "price_last_checked": "2026-07-30",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": (
            "https://combekk.com/product/"
            "forest-easy-fry-pan-o-32-cm/"
        ),
        "official_url": "",
        "availability_label": "",
        "award": "",
        "price_range": "€€€",
        "image": "combekk-forest-easy-32cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Gelijkmatige warmteverdeling via de inductiebodem",
            "Comfortabele koel blijvende handgreep",
            "Relatief gunstig geprijsd binnen het grote formaat",
        ],
        "cons": [
            "Relatief zwaar",
            "Langzaam opwarmen wordt aanbevolen",
        ],
        "verdict": (
            "Een complete middenklassekeuze met een stabiele inductiebodem "
            "en een toegankelijke prijs."
        ),
    },

    "tefal_renew_32": {
        "slug": "tefal-renew-32",
        "name": "Tefal Renew ON",
        "description": (
            "Grote koekenpan van gerecycled aluminium met keramische "
            "antiaanbaklaag en geïntegreerde hitte-indicator."
        ),
        "brand": "Tefal",
        "diameter": 32,
        "material": (
            "Gerecycled aluminium met keramische antiaanbaklaag"
        ),
        "features": [
            "Geschikt voor alle warmtebronnen",
            "Thermo-Signal hitte-indicator",
            "Pan gemaakt van gerecycled aluminium",
        ],
        "rating": 4.2,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 36.79,
        "price_last_checked": "2026-07-30",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": (
            "https://www.bol.com/nl/nl/p/"
            "tefal-renew-on-keramische-koekenpan-o-32-cm/"
            "9300000117431080/"
        ),
        "official_url": "",
        "availability_label": "",
        "award": "",
        "price_range": "€€",
        "image": "tefal-renew-32cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Pan gemaakt van gerecycled aluminium",
            "Goede warmtegeleiding",
            "Handige hitte-indicator",
        ],
        "cons": [
            "Niet geschikt voor ovengebruik",
        ],
        "verdict": (
            "Een gebruiksvriendelijke grote pan met geïntegreerde "
            "hitte-indicator en een aantrekkelijke prijs."
        ),
    },

    "primecook_32": {
        "slug": "primecook-32",
        "name": "Primecook Koekenpan",
        "description": (
            "Grote aluminium koekenpan met Excilon-antiaanbaklaag "
    "op keramische basis, inductiebodem en twee handgrepen."
        ),
        "brand": "Primecook",
        "diameter": 32,
        "material": "Aluminium met Excilon-antiaanbaklaag op keramische basis",
        "features": [
            "Excilon-coating op keramische basis",
            "Geschikt voor alle warmtebronnen",
            "Geschikt voor ovengebruik",
        ],
        "rating": 4.1,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 81.90,
        "price_last_checked": "2026-07-28",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": (
            "https://www.primecook.nl/"
            "1903-primecook-koekenpan-32-cm-pfas-vrij"
        ),
        "official_url": "",
        "availability_label": "",
        "award": "",
        "price_range": "€€€",
        "image": "primecook-32cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Groot bakoppervlak",
            "Geschikt voor inductie en ovengebruik",
            "Twee handgrepen vergemakkelijken het verplaatsen",
        ],
        "cons": [
            "Hoge aanschafprijs",
            "Handwas wordt aanbevolen",
        ],
        "verdict": (
            "Een ruime koekenpan voor wie ovengebruik en een tweede "
            "handgreep belangrijk vindt."
        ),
    },

    "ikea_hemlagad_keramisch_32": {
        "slug": "ikea-hemlagad-keramisch-32",
        "name": "IKEA HEMLAGAD",
        "description": (
            "Grote aluminium koekenpan met keramische antiaanbaklaag "
            "voor dagelijks gebruik op alle gangbare kookplaten."
        ),
        "brand": "IKEA",
        "diameter": 32,
        "material": "Aluminium met keramische antiaanbaklaag",
        "features": [
            "Geschikt voor inductie",
            "Groot bakoppervlak",
            "Alleen handwas",
        ],
        "rating": 4.0,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 17.99,
        "price_last_checked": "2026-07-30",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": (
            "https://www.ikea.com/nl/nl/p/"
            "hemlagad-koekenpan-antiaanbaklaag-zwart-30580899/"
        ),
        "official_url": "",
        "availability_label": "",
        "award": "💰 Budget keuze",
        "price_range": "€",
        "image": "ikea-hemlagad-keramisch-32cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Zeer lage aanschafprijs",
            "Ruim bakoppervlak",
            "Geschikt voor alle gangbare kookplaten",
        ],
        "cons": [
            "Niet vaatwasserbestendig",
            "Voorzichtig opwarmen op krachtige kookzones",
        ],
        "verdict": (
            "Een zeer voordelige grote koekenpan voor licht en "
            "regelmatig dagelijks gebruik."
        ),
    },

    "scanpan_nura_32": {
        "slug": "scanpan-nura-32",
        "name": "Scanpan Nura",
        "description": (
            "Meerlaagse stalen koekenpan met Stratanium Leap "
            "antiaanbaklaag en ovenbestendige RVS handgreep."
        ),
        "brand": "Scanpan",
        "diameter": 32,
        "material": (
            "Meerlaags staal met Stratanium Leap antiaanbaklaag"
        ),
        "features": [
            "Geschikt voor alle warmtebronnen",
            "Ovenbestendig tot 250 °C",
            "Vaatwasserbestendig",
        ],
        "rating": 4.4,
        "rating_count": None,
        "rating_source": "editorial",
        "price": None,
        "price_last_checked": None,
        "currency": "EUR",
        "availability": None,
        "affiliate_url": "",
        "retailer_url": "",
        "official_url": (
            "https://www.scanpan.eu/shop/"
            "28-cm-fry-pan-nura/32cm"
        ),
        "availability_label": "Nog niet algemeen verkrijgbaar",
        "award": "",
        "price_range": None,
        "image": "scanpan-nura-32cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Stevige meerlaagse staalconstructie",
            "Geschikt voor ovengebruik tot 250 °C",
            "Breed inzetbaar op verschillende warmtebronnen",
        ],
        "cons": [
            "Relatief zwaar",
            "Prijs-kwaliteit nog niet goed te beoordelen",
        ],
        "verdict": (
            "Een veelzijdige nieuwe premiumoptie, maar door de beperkte "
            "verkrijgbaarheid nog lastig op prijs-kwaliteit te beoordelen."
        ),
    },
}
