PRODUCTS = {
    # LOSSE VERSHOUDBAKJES
    "pyrex_cook_store_3delig": {
        "slug": "pyrex-cook-store-enkel",
        "name": "Pyrex Cook & Store \u2013 enkele schaal",
        "brand": "Pyrex",
        "material": "Borosilicaatglas",
        "capacities": [800],
        "features": [
            "Klikdeksel",
            "Magnetronventiel"
        ],
        "image": "pyrex-cookstore-enkel.webp",
        "image_path": "images/products/vershoudbakjes",
        "description": "Hoogwaardig glazen vershoudbakje van borosilicaatglas met stevig klikdeksel en stoomventiel. Ideaal voor bewaren, invriezen, opwarmen en bereiden in de oven.",
        "pros": [
            "Borosilicaatglas is bestand tegen grote temperatuurverschillen",
            "Geschikt voor oven, magnetron, koelkast en vriezer (zonder deksel)",
            "Stevig klikdeksel met siliconen afdichting",
            "Praktisch stoomventiel voor opwarmen in de magnetron",
        ],
        "cons": [
            "Deksel is niet ovenbestendig",
            "Zwaarder dan kunststof bewaarbakjes",
        ],
        "rating": 5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 23.21,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/pyrex-cook-store-vershoudbakje-borosilicaatglas-800-ml-transparant/9200000117155201/?Referrer=ADVNLGOO002032-S--9200000117155201-PMAX-C-23805101224&gad_source=1&gad_campaignid=23800679711&gclid=CjwKCAjwx7LSBhB3EiwAjcodxPDQqSSW-0jo4vqy2cbNCFI_X5_kmcEN5BJGefXiKIWKRN4xpy8vbRoCPu4QAvD_BwE",
        "price_range": "\u20ac\u20ac",
        "verdict": "Een van de beste losse glazen vershoudbakjes dankzij de uitstekende bouwkwaliteit, veelzijdigheid en lange levensduur.",
        "award": "🏆 Beste keuze",
    },
    "ikea_365+_enkel": {
        "slug": "ikea-365-plus-enkel",
        "name": "Ikea 365+ \u2013 enkele schaal",
        "brand": "Ikea",
        "material": "Borosilicaatglas",
        "capacities": [600],
        "features": [
            "Ovenbestendig",
            "Losse deksels verkrijgbaar"
        ],
        "image": "ikea-365-enkel.webp",
        "image_path": "images/products/vershoudbakjes",
        "description": "Betaalbaar glazen vershoudbakje van borosilicaatglas met los verkrijgbaar deksel. Geschikt voor dagelijks bewaren, invriezen en opwarmen.",
        "pros": [
            "Uitstekende prijs-kwaliteitverhouding",
            "Borosilicaatglas is oven-, magnetron- en vriezerbestendig",
            "Deksels zijn los verkrijgbaar",
            "Verkrijgbaar in veel verschillende maten",
        ],
        "cons": [
            "Deksel wordt apart verkocht",
            "Minder lekdicht dan premium systemen",
        ],
        "rating":4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 3.49,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.ikea.com/nl/nl/p/ikea-365-voorraadpot-met-deksel-vierkant-glas-kunststof-s39269120/#content",
        "price_range": "\u20ac",
        "verdict": "De beste budgetkeuze voor wie een degelijk glazen vershoudbakje zoekt zonder veel uit te geven.",
        "award": "💰 Budget keuze",
        "variant_label": "Inhoud",
        "variants": [
            {
                "id": "600-ml",
                "label": "600 ml",
                "shape": "600 ml",
                "capacities": [600],
                "image": "ikea-365-enkel.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 3.49,
                "price_last_checked": "2026-07-24",
                "currency": "EUR",
                "availability": "InStock",
                "affiliate_url": "https://www.ikea.com/nl/nl/p/ikea-365-voorraadpot-740-ml",
                "is_default": True,
            },
            {                
                "id": "1000-ml",
                "label": "1 L",
                "shape": "1 L",
                "capacities": [1000],
                "image": "ikea-365-1l-enkel.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 4.49,
                "price_last_checked": "2026-07-24",
                "currency": "EUR",
                "availability": "InStock",
                "affiliate_url": "https://www.ikea.com/nl/nl/p/ikea-365-voorraadpot-met-deksel-rechthoekig-glas-kunststof-s89269071/#content",
                "is_default": False,
            },
            {
                "id": "1200-ml",
                "label": "1.2 L",
                "shape": "1.2 L",
                "capacities": [1200],
                "image": "ikea-365-12l-enkel.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 4.99,
                "price_last_checked": "2026-07-24",
                "currency": "EUR",
                "availability": "InStock",
                "affiliate_url": "https://www.ikea.com/nl/nl/p/ikea-365-voorraadpot-met-deksel-vierkant-glas-kunststof-s59269119/#content",
                "is_default": False,
            },
        ],
    },

    "mepal_easyclip_glass_enkel": {
        "slug": "mepal-easyclip-glass-enkel",
        "name": "Mepal EasyClip Glass \u2013 vershoudbakje",
        "brand": "Mepal",
        "material": "Borosilicaatglas",
        "capacities": [450],
        "features": [
            "EasyClip sluiting",
            "Lekvrij"
        ],
        "image": "mepal-easyclip-glass-enkel.webp",
        "image_path": "images/products/vershoudbakjes",
        "description": "Premium glazen vershoudbakje van borosilicaatglas met het innovatieve EasyClip-sluitsysteem. Volledig lekdicht en geschikt voor oven, magnetron, koelkast en vriezer.",
        "pros": [
            "Volledig lekdicht dankzij EasyClip-sluiting",
            "Borosilicaatglas neemt geen geuren of kleuren op",
            "Geschikt voor oven, magnetron, koelkast en vriezer",
            "Hoogwaardige afwerking en eenvoudig te openen",
        ],
        "cons": [
            "Hoger geprijsd dan veel alternatieven",
            "Deksel is niet geschikt voor ovengebruik",
        ],
        "rating": 5,
        "rating_count": None,
        "rating_source": "editorial",
        "currency": "EUR",
        "availability": "InStock",
        "price_range": "\u20ac\u20ac",
        "verdict": "Een premium vershoudbakje dat uitblinkt in gebruiksgemak, lekdichtheid en afwerking.",
        "award": None,
        "variant_label": "Inhoud",
        "variants": [
            {
                "id": "450-ml",
                "label": "450 ml",
                "shape": "450 ml",
                "capacities": [450],
                "image": "mepal-easyclip-glass-450ml-enkel.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 9.99,
                "price_last_checked": "2026-07-24",
                "currency": "EUR",
                "availability": "InStock",
                "affiliate_url": "https://www.bol.com/nl/nl/p/mepal-glazen-vershouddoos-easyclip-450-ml-glazen-vershoudbakjes-met-schuifsluiting-geschikt-voor-magnetron-oven-koelkast-en-vriezer-nordic-sage/9300000251601243/?cid=1783484630487-9015465582122",
                "is_default": True,
            },
            {                
                "id": "700-ml",
                "label": "700 ml",
                "shape": "700 ml",
                "capacities": [700],
                "image": "mepal-easyclip-glass-700ml-enkel.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 9.94,
                "price_last_checked": "2026-07-24",
                "currency": "EUR",
                "availability": "InStock",
                "affiliate_url": "https://www.bol.com/nl/nl/p/mepal-glazen-vershouddoos-easyclip-700-ml-glazen-vershoudbakjes-met-schuifsluiting-geschikt-voor-magnetron-oven-koelkast-en-vriezer-nordic-sage/9300000251601247/?cid=1784894100162-7241311797016",
                "is_default": False,
            },
            {
                "id": "1500-ml",
                "label": "1.5 L",
                "shape": "1.5 L",
                "capacities": [1500],
                "image": "mepal-easyclip-glass-1500ml-enkel.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 15.69,
                "price_last_checked": "2026-07-24",
                "currency": "EUR",
                "availability": "InStock",
                "affiliate_url": "https://www.bol.com/nl/nl/p/mepal-glazen-vershouddoos-easyclip-1-5-l-glazen-vershoudbakjes-met-schuifsluiting-geschikt-voor-magnetron-oven-koelkast-en-vriezer-nordic-sage/9300000251601246/?cid=1784894617532-8761170651405",
                "is_default": False,
            },
            {
                "id": "2250-ml",
                "label": "2.25 L",
                "shape": "2.25 L",
                "capacities": [2250],
                "image": "mepal-easyclip-glass-2250ml-enkel.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 24.19,
                "price_last_checked": "2026-07-24",
                "currency": "EUR",
                "availability": "InStock",
                "affiliate_url": "https://www.bol.com/nl/nl/p/mepal-glazen-vershouddoos-easyclip-2-25-l-glazen-vershoudbakjes-met-schuifsluiting-geschikt-voor-magnetron-oven-koelkast-en-vriezer-nordic-sage/9300000251601250/?cid=1784894769878-6037310564606",
                "is_default": False,
            },
        ],
    },
    "locknlock_enkel": {
        "slug": "locknlock-enkel",
        "name": "Lock&Lock \u2013 glazen vershoudbakje",
        "brand": "Lock&Lock",
        "material": "Borosilicaatglas",
        "capacities": [740],
        "features": [
            "4-zijdige sluiting",
            "Lekvrij"
        ],
        "image": "locknlock-enkel.jpg",
        "image_path": "images/vershoudbakjes",
        "description": "Stevig glazen vershoudbakje met de bekende vierzijdige Lock&Lock-sluiting. Ideaal voor lekvrij bewaren, meenemen en opwarmen.",
        "pros": [
            "Zeer betrouwbare vierzijdige kliksluiting",
            "Lekvrij dankzij siliconen afdichting",
            "Geschikt voor koelkast, vriezer en magnetron",
            "Stevig glas voor dagelijks gebruik",
        ],
        "cons": [
            "Deksel is niet ovenbestendig",
            "Iets zwaarder dan vergelijkbare kunststof bakjes",
        ],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 12.95,
        "price_last_checked": "2026-07-08",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://locklock.nl/product/keuken/ovenschalen-met-deksel/glazen-ovenschaaltje-met-deksel-740-ml/",
        "price_range": "\u20ac\u20ac",
        "verdict": "Een uitstekende keuze voor wie maximale lekdichtheid en betrouwbaarheid belangrijk vindt.",
        "award": "",
        "variant_selectors": [
            {"key": "capacity", "label": "Inhoud"},
        ],
        "variants": [
            {
                "id": "630-ml",
                "options": {"capacity": 630},
                "option_labels": {"capacity": "630 ml"},
                "capacities": [630],
                "image": "locknlock-630ml-enkel.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 9.95,
                "price_last_checked": "2026-07-24",
                "currency": "EUR",
                "availability": "InStock",
                "affiliate_url": "https://locklock.nl/product/keuken/ovenschalen-met-deksel/ovenschaaltje-met-deksel-630-ml/",
                "is_default": True,
            },
            {
                "id": "740-ml",
                "options": {"capacity": 740},
                "option_labels": {"capacity": "740 ml"},
                "capacities": [740],
                "image": "locknlock-740ml-enkel.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 12.95,
                "price_last_checked": "2026-07-24",
                "currency": "EUR",
                "availability": "InStock",
                "affiliate_url": "https://locklock.nl/product/keuken/ovenschalen-met-deksel/glazen-ovenschaaltje-met-deksel-740-ml/",
                "is_default": False,
            },
            {
                "id": "1000-ml",
                "options": {"capacity": 1000},
                "option_labels": {"capacity": "1 L"},
                "capacities": [1000],
                "image": "locknlock-1l-enkel.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 15.95,
                "price_last_checked": "2026-07-24",
                "currency": "EUR",
                "availability": "InStock",
                "affiliate_url": "https://locklock.nl/product/keuken/ovenschalen-met-deksel/ovenschaal-met-deksel-1-0-liter/",
                "is_default": False,
            },
        ],
    },
    "luminarc_purebox_enkel": {
        "slug": "luminarc-purebox-enkel",
        "name": "Luminarc Pure Box Active \u2013 glazen vershoudbakje",
        "brand": "Luminarc",
        "material": "Gehard glas",
        "capacities": [820],
        "features": [
            "Ventieldeksel",
            "Lekvrij"
        ],
        "image": "luminarc-purebox-enkel.jpg",
        "image_path": "images/vershoudbakjes",
        "description": "Praktisch glazen vershoudbakje van gehard glas met lekvrij deksel en geïntegreerd stoomventiel. Ideaal voor dagelijks bewaren en opwarmen.",
        "pros": [
            "Gehard glas is zeer sterk en krasbestendig",
            "Lekvrij deksel met siliconen afdichting",
            "Handig stoomventiel voor magnetrongebruik",
            "Goede prijs-kwaliteitverhouding",
        ],
        "cons": [
            "Deksel is niet geschikt voor ovengebruik",
            "Minder premium afgewerkt dan de topmodellen",
        ],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 10.15,
        "price_last_checked": "2026-07-08",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/luminarc-pure-box-active-vershouddoos-rechthoekig-glas-0-82l/9200000035762057/?cid=1783485254896-7774995525740",
        "price_range": "\u20ac\u20ac",
        "verdict": "Een degelijk glazen vershoudbakje dat veel functionaliteit biedt voor een aantrekkelijke prijs.",
        "award": "",
        "variant_selectors": [
            {"key": "shape", "label": "Vorm"},
            {"key": "capacity", "label": "Inhoud"}
        ],
        "variants": [
            {
                "id": "630-ml-rectangle",
                "options": {"shape": "rectangle", "capacity": 820},
                "option_labels": {"shape": "Rechthoek", "capacity": "820 ml"},
                "capacities": [820],
                "image": "luminarc-purebox-820ml-enkel.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 9.14,
                "price_last_checked": "2026-07-24",
                "currency": "EUR",
                "availability": "InStock",
                "affiliate_url": "https://www.bol.com/nl/nl/p/luminarc-pure-box-active-vershouddoos-rechthoekig-glas-0-82l/9200000035762057/?cid=1783485254896-7774995525740",
                "is_default": False,
            },
            {
                "id": "380-ml-rectangle",
                "options": {"shape": "rectangle", "capacity": 380},
                "option_labels": {"shape": "Rechthoek", "capacity": "380 ml"},
                "image": "luminarc-purebox-380ml-enkel.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 10.06,
                "price_last_checked": "2026-07-24",
                "currency": "EUR",
                "availability": "InStock",
                "affiliate_url": "https://www.bol.com/nl/nl/p/luminarc-pure-box-active-vershouddoos-rechthoekig-glas-0-38l/9200000035762025/?cid=1784894937238-5373799041297",
                "is_default": True,
            },
            {
                "id": "1220-ml-rectangle",
                "options": {"shape": "rectangle", "capacity": 1220},
                "option_labels": {"shape": "Rechthoek", "capacity": "1.22 L"},
                "image": "luminarc-purebox-1220ml-enkel.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 10.58,
                "price_last_checked": "2026-07-24",
                "currency": "EUR",
                "availability": "InStock",
                "affiliate_url": "https://www.bol.com/nl/nl/p/luminarc-pure-box-active-vershouddoos-rechthoekig-glas-1-22l/9200000035762061/?cid=1784900984244-1791694709757",
                "is_default": False,
            },
            {
                "id": "1970-ml-rectangle",
                "options": {"shape": "rectangle", "capacity": 1970},
                "option_labels": {"shape": "Rechthoek", "capacity": "1.97 L"},
                "image": "luminarc-purebox-1970ml-enkel.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 28.90,
                "price_last_checked": "2026-07-24",
                "currency": "EUR",
                "availability": "InStock",
                "affiliate_url": "https://www.bol.com/nl/nl/p/luminarc-pure-box-active-vershoudbak-glas-rechthoekig-1-97-l/9200000035762035/?cid=1784901152715-4393093396771",
                "is_default": False,
            },
            {
                "id": "1220-ml-square",
                "options": {"shape": "square", "capacity": 1220},
                "option_labels": {"shape": "Vierkant", "capacity": "1.22 L"},
                "image": "luminarc-purebox-1220ml-vierkant-enkel.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 12.68,
                "price_last_checked": "2026-07-24",
                "currency": "EUR",
                "availability": "InStock",
                "affiliate_url": "https://www.bol.com/nl/nl/p/luminarc-pure-box-active-vershoudbak-glas-vierkant-1-22-l/9200000035762051/?cid=1784901339136-4495919986708",
                "is_default": False,
            },
            {
                "id": "760-ml-square",
                "options": {"shape": "square", "capacity": 760},
                "option_labels": {"shape": "Vierkant", "capacity": "760 ml"},
                "image": "luminarc-purebox-760ml-vierkant-enkel.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 11.72,
                "price_last_checked": "2026-07-24",
                "currency": "EUR",
                "availability": "InStock",
                "affiliate_url": "https://www.bol.com/nl/nl/p/luminarc-pure-box-active-vershouddoos-vierkant-glas-0-76l/9200000035762031/?cid=1784901948668-8312460538790",
                "is_default": False,
            },
            {
                "id": "420-ml-round",
                "options": {"shape": "round", "capacity": 420},
                "option_labels": {"shape": "Rond", "capacity": "420 ml"},
                "image": "luminarc-purebox-420ml-rond-enkel.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 7.95,
                "price_last_checked": "2026-07-24",
                "currency": "EUR",
                "availability": "InStock",
                "affiliate_url": "https://www.bol.com/nl/nl/p/luminarc-pure-box-active-vershouddoos-rond-glas-0-42l/9200000035762053/",
                "is_default": False,
            },
            {
                "id": "920-ml-round",
                "options": {"shape": "round", "capacity": 920},
                "option_labels": {"shape": "Rond", "capacity": "920 ml"},
                "image": "luminarc-purebox-920ml-rond-enkel.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 11.45,
                "price_last_checked": "2026-07-24",
                "currency": "EUR",
                "availability": "InStock",
                "affiliate_url": "https://www.bol.com/nl/nl/p/luminarc-pure-box-active-vershouddoos-rond-glas-0-92l/9200000035762029/",
                "is_default": False,
            },
        ],
    },
    "berghoff_perfect_seal": {
        "slug": "berghoff-perfect-seal",
        "name": "Berghoff Perfect Seal \u2013 glazen vershoudbakje",
        "brand": "Berghoff",
        "material": "Borosilicaatglas",
        "capacities": [500],
        "features": [
            "4-zijdige sluiting",
            "Lekvrij"
        ],
        "image": "berghoff_perfect_seal.jpg",
        "image_path": "images/vershoudbakjes",
        "description": "Stevig glazen vershoudbakje met de bekende vierzijdige Lock&Lock-sluiting. Ideaal voor lekvrij bewaren, meenemen en opwarmen.",
        "pros": [
            "Zeer betrouwbare vierzijdige kliksluiting",
            "Lekvrij dankzij siliconen afdichting",
            "Geschikt voor koelkast, vriezer en magnetron",
            "Stevig glas voor dagelijks gebruik",
        ],
        "cons": [
            "Deksel is niet ovenbestendig",
            "Iets zwaarder dan vergelijkbare kunststof bakjes",
        ],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 16.95,
        "price_last_checked": "2026-07-17",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://locklock.nl/product/keuken/ovenschalen-met-deksel/glazen-ovenschaaltje-met-deksel-740-ml/",
        "price_range": "\u20ac\u20ac",
        "verdict": "Een uitstekende keuze voor wie maximale lekdichtheid en betrouwbaarheid belangrijk vindt.",
        "award": "",
    },
    
    # 3-DELIGE SETS
    "mepal_easyclip_glass_3delig": {
        "slug": "mepal-easyclip-glass-3delig",
        "name": "Mepal EasyClip Glass \u2013 3-delige glazen vershoudbakjes",
        "brand": "Mepal",
        "material": "Borosilicaat glas",
        "capacities": [700, 700, 1500],
        "features": ["Lekvrij",
                    "EasyClip-sluiting",
                    "Ovenbestendig glas"],
        "image": "mepal-easyclip-glass-3.jpg",
        "image_path": "images/vershoudbakjes",
        "description": "Een premium borosilicaat glazen set met lekvrije EasyClip-deksels. Geschikt voor oven, magnetron, koelkast en vriezer. Uitstekende duurzaamheid en gebruiksgemak.",
        "pros": [
            "Borosilicaat glas: veilig en geurvrij",
            "Ovenbestendig (zonder deksel)",
            "Zeer stevige silicone afdichting",
            "Nederlands kwaliteitsmerk",
        ],
        "cons": [
            "Iets zwaarder dan kunststof alternatieven",
            "Hogere prijsklasse",
        ],
        "rating": 5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 49.97,
        "price_last_checked": "2026-07-15",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.wehkamp.nl/mepal-easyclip-bewaardoos-3-delig-2x-700-1500-ml-glas-17577617/?ref=%7B%22id%22%3A%22shop%22%2C%22filter%22%3A%22mepal%22%2C%22params%22%3A%22merk%3Dmepal%22%7D",
        "price_range": "\u20ac\u20ac\u20ac",
        "verdict": "Totaalpakket van kwaliteit, veiligheid en gebruiksgemak \u2014 de beste glazen 3-delige set.",
        "award": "🏆 Beste keuze",
    },
    "igluu_meal_prep_3delig": {
        "slug": "igluu-meal-prep-3delig",
        "name": "Igluu Meal Prep \u2013 3-delige glazen vershoudset",
        "brand": "Igluu",
        "material": "Borosilicaat glas",
        "features": ["Lekvrij", "Klikdeksel + silicone"],
        # "image_path": "images/vershoudbakjes",
        "description": "Betaalbare en praktische 3-delige set van borosilicaat glas met lekvrije klikdeksels. Ideaal als instapset voor gezond bewaren en opwarmen.",
        "pros": [
            "Borosilicaat glas: oven- en magnetronbestendig (zonder deksel in de oven)",
            "Drie verschillende formaten voor dagelijkse porties",
            "Lekvrije klikdeksels met silicone afdichting",
            "Betaalbare instapset zonder concessies aan materiaalveiligheid",
        ],
        "cons": [
            "Geen extra grote schaal voor familieporties",
            "Deksels zijn niet geschikt voor gebruik in de oven",
        ],
        "rating": 4,
        "rating_count": None,
        "rating_source": "editorial",
        "price_range": "\u20ac",
        "verdict": "Een voordelige en complete glazen basisset voor iedereen die PFAS-vrij wil bewaren en opwarmen.",
        "award": "💰 Budget keuze",
        "variant_label": "Vorm",
        "variants": [
            {
                "id": "round",
                "label": "Rond",
                "shape": "Rond",
                "capacities": [400, 650, 950],
                "image": "igluu-meal-prep-3delig.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 24.95,
                "price_last_checked": "2026-07-23",
                "currency": "EUR",
                "availability": "InStock",
                "affiliate_url": "https://www.amazon.nl/dp/B08DYF9GXP/?th=1",
                "is_default": True,
            },
            {
                "id": "square",
                "label": "Vierkant",
                "shape": "Vierkant",
                "capacities": [320, 520, 800],
                "image": "igluu-meal-prep-3delig-vierkant.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 24.95,
                "price_last_checked": "2026-07-23",
                "currency": "EUR",
                "availability": "InStock",  
                "affiliate_url": "https://www.amazon.nl/dp/B08WJHTSQ1/?th=1",
                "is_default": False,
            },
        ],
    },
    "pyrex_cook_heat_3delig": {
        "slug": "pyrex-cook-heat-3delig",
        "name": "Pyrex Cook & Heat \u2013 3-delige glazen vershoudset",
        "brand": "Pyrex",
        "material": "Borosilicaat glas",
        "features": ["klikdeksel", "Magnetronventiel"],
        "image": "pyrex-cookheat-3delig.jpg",
        "image_path": "images/vershoudbakjes",
        "description": "Een hoogwaardige 3-delige set van borosilicaat glas met stevige klikdeksels en silicone afdichting. Ontworpen voor veilig bewaren \u00e9n opwarmen in zowel oven als magnetron.",
        "pros": [
            "Borosilicaat glas: ovenbestendig tot hoge temperaturen",
            "Stevige klikdeksels met silicone ring",
            "Subtiel magnetronventiel voor veilig opwarmen",
            "Hoge kwaliteit en uitstekende duurzaamheid",
        ],
        "cons": [
            "Deksels niet geschikt voor ovengebruik",
            "Grotere formaten nemen meer ruimte in",
        ],
        "rating": 5,
        "rating_count": None,
        "rating_source": "editorial",
        "price_range": "\u20ac\u20ac\u20ac",
        "verdict": "De ideale glazen set voor wie regelmatig bewaart, opwarmt én gerechten rechtstreeks vanuit de oven serveert.",
        "award": "💎 Premium keuze",
        "variant_label": "Vorm",
        "variants": [
            {
                "id": "round",
                "label": "Rond",
                "shape": "Rond",
                "capacities": [1100, 1100, 1100],
                "image": "pyrex-cook-heat-3delig-rond.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 61.84,
                "price_last_checked": "2026-07-23",
                "currency": "EUR",
                "availability": "InStock",
                "affiliate_url": "https://www.amazon.nl/Pyrex-Cook-Heat-Borosilicaatglas-Luchtdicht/dp/B07TWH7QHT/ref=pd_bxgy_thbs_d_sccl_1/260-4820568-4617558?pd_rd_w=rr9En&content-id=amzn1.sym.75142c34-87ae-4c36-8448-6beafeb35427&pf_rd_p=75142c34-87ae-4c36-8448-6beafeb35427&pf_rd_r=H2M5KX2QH6CGEM84DB24&pd_rd_wg=7zKcX&pd_rd_r=70717590-5f81-4642-86f9-b8378e083655&pd_rd_i=B07TWH7QHT&th=1",
                "is_default": True,
            },
            {
                "id": "square",
                "label": "Vierkant",
                "shape": "Vierkant",
                "capacities": [1100, 1100, 1100],
                "image": "pyrex-cook-heat-3delig.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 39.87,
                "price_last_checked": "2026-07-23",
                "currency": "EUR",
                "availability": "InStock",  
                "affiliate_url": "https://www.amazon.nl/dp/B07TTCV55F?ref=emc_p_m_5_i_atc&th=1",
                "is_default": False,
            },
        ],
    },
    "bormioli_frigoverre_3delig": {
        "slug": "bormioli-frigoverre-3delig",
        "name": "Bormioli Rocco Frigoverre \u2013 3-delige glazen vershoudset",
        "brand": "Bormioli Rocco",
        "material": "Borosilicaat glas",
        "capacities": [240, 750, 1600],
        "features": ["Ovenbestendig", "Vriezerbestendig"],
        "image": "vershoudbakjes_bormioli_frigoverre_set_3.jpg",
        "image_path": "images/vershoudbakjes",
        "description": "Duurzame set van glazen vershoudbakjes voor dagelijks bewaren en meenemen. Het glas is voedselveilig en geschikt voor oven, magnetron en vriezer (gebruik zonder deksel bij verhitting).",
        "pros": [
            "Voedselveilig glas, vrij van schadelijke stoffen",
            "Geschikt voor oven en magnetron (zonder deksel)",
            "Geschikt voor vriezer",
            "Handige 3-delige set voor meal-prep en restjes",
        ],
        "cons": [
            "Deksel sluit minder stevig dan sommige premium kliksystemen",
            "Controleer per set of deksels volledig lekvrij zijn",
        ],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 27.99,
        "price_last_checked": "2026-07-08",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.wehkamp.nl/bormioli-rocco-frigoverre-vershoudbakjes-frigoverre-glas-blauw-3-stuks-16432465/",
        "price_range": "\u20ac\u20ac",
        "verdict": "Een betrouwbare glazen set voor dagelijks gebruik: duurzaam, veelzijdig en ideaal als je een praktische 3-delige glasoplossing zoekt voor bewaren en opwarmen.",
        "award": None,
    },
    "luminarc_purebox_3delig": {
        "slug": "luminarc-purebox-3delig",
        "name": "Luminarc Pure Box Active \u2013 3-delige glazen vershoudset",
        "brand": "Luminarc",
        "material": "Gehard glas",
        "capacities": [420, 670, 920],
        "features": ["Ventieldeksel", "Lekvrij"],
        "image": "luminarc-purebox-3delig.jpg",
        "image_path": "images/vershoudbakjes",
        "description": "Een praktische en sterke 3-delige set van gehard glas met ventieldeksels. Ideaal voor dagelijks bewaren, opwarmen en meenemen dankzij de stevige 4-kliks sluiting.",
        "pros": [
            "Extra stootbestendig gehard glas",
            "4-kliks sluiting met silicone ring voor lekvrije opslag",
            "Handig ventiel voor veilig magnetrongebruik",
            "Compacte ronde formaten, makkelijk stapelbaar",
        ],
        "cons": [
            "Ronde vorm minder effici\u00ebnt voor mealprep-stapeling",
            "Deksels zijn niet ovenbestendig",
        ],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 26.61,
        "price_last_checked": "2026-07-08",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/luminarc-pure-box-active-vershouddoos-rond-glas-set-3/9200000036318348/",
        "price_range": "\u20ac\u20ac",
        "verdict": "Een stevige en gebruiksvriendelijke set met uitstekend ventielsysteem voor dagelijks gebruik.",
        "award": "",
    },
    "glasslock_3delig": {
        "slug": "glasslock-3delig",
        "name": "Glasslock \u2013 3-delige glazen vershoudset",
        "brand": "Glasslock",
        "material": "Gehard glas",
        "capacities": [480, 970, 1730],
        "features": ["Ventieldeksel", "Lekvrij"],
        "image": "glasslock-ovensafe-3delig.jpg",
        "image_path": "images/vershoudbakjes",
        "description": "Een praktische en sterke 3-delige set van gehard glas met ventieldeksels. Ideaal voor dagelijks bewaren, opwarmen en meenemen dankzij de stevige 4-kliks sluiting.",
        "pros": [
            "Extra stootbestendig gehard glas",
            "4-kliks sluiting met silicone ring voor lekvrije opslag",
            "Handig ventiel voor veilig magnetrongebruik",
            "Compacte ronde formaten, makkelijk stapelbaar",
        ],
        "cons": [
            "Ronde vorm minder effici\u00ebnt voor mealprep-stapeling",
            "Deksels zijn niet ovenbestendig",
        ],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 41.29,
        "price_last_checked": "2026-07-08",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.amazon.nl/-/en/Glasslock-GL-529-1750ml-Rectangular-Container/dp/B00MX16YKE/ref=sr_1_5?adgrpid=1345804604584798&dib=eyJ2IjoiMSJ9.ta58l7hdwLQglioY2JkbABkIwNp__ai_XeE9jHyw5Nh7i2gsskIeu5f1Ire_sgEx8mQmIC6O0U4oxckqRWndxMhmfNWgjOcVvnqoSXx6e49s4S-cO5hfPJ8k5iskNpdR7zg-eOKZcvdDhFXnequiETZ8g4aSAux5Q2DKtzBTRRbcyeSwFMqWorMY-jIsSychk8UvjVRiEyRZR5K2nhplADD6sa6tTGLWgC3Dj5khAuCmUSqnWo593NWyRdsPu7F3w_CqpyEPbAGFOrrSiEsN5x5E_1qSZRjSd_DwKWXqvPg.Ge4XaEwsJBmqIY1uvH4N8JNl2uqO5oOxeasXthlWGxY&dib_tag=se&hvadid=84113043168595&hvbmt=bp&hvdev=c&hvlocphy=152250&hvnetw=o&hvqmt=p&hvtargid=kwd-84113816710888%3Aloc-129&hydadcr=6813_2256395&keywords=glasslock+set&mcid=80ac74f8738c33b5bb69e05482fecdab&msclkid=c7e6a6c2ff4b108f5869cc9b551b7bdb&qid=1784261236&sr=8-5&language=nl_NL",
        "price_range": "\u20ac\u20ac\u20ac",
        "verdict": "Een stevige en gebruiksvriendelijke set met uitstekend ventielsysteem voor dagelijks gebruik.",
        "award": "",
    },

    # 5-DELIGE SETS
    "pyrex_cook_heat_5delig": {
        "slug": "pyrex-cook-heat-5delig",
        "name": "Pyrex Cook & Heat \u2013 5-delige glazen vershoudset",
        "brand": "Pyrex",
        "material": "Borosilicaat glas",
        "capacities": [400, 600, 1000, 1200, 2500],
        "features": ["Clipdeksel", "Magnetronventiel"],
        "image": "pyrex-cookheat-5delig.jpg",
        "image_path": "images/vershoudbakjes",
        "description": "Een hoogwaardige 5-delige set van borosilicaat glas met stevige klikdeksels en silicone afdichting. Ontworpen voor veilig bewaren \u00e9n opwarmen in zowel oven als magnetron.",
        "pros": [
            "Borosilicaat glas: ovenbestendig tot hoge temperaturen",
            "Stevige klikdeksels met silicone ring",
            "Subtiel magnetronventiel voor veilig opwarmen",
            "Hoge kwaliteit en uitstekende duurzaamheid",
        ],
        "cons": [
            "Deksels niet geschikt voor ovengebruik",
            "Grotere formaten nemen meer ruimte in",
        ],
        "rating": 5,
        "rating_count": 295,
        "price": "65.00",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.amazon.nl/-/en/Pyrex-glass-dishes-airtight-microwave/dp/B08297GR65/ref=pd_bxgy_thbs_d_sccl_1/262-4000866-4191437?pd_rd_w=jiJYP&content-id=amzn1.sym.75142c34-87ae-4c36-8448-6beafeb35427&pf_rd_p=75142c34-87ae-4c36-8448-6beafeb35427&pf_rd_r=C2V0YSA2BKFHRGZNBH2C&pd_rd_wg=z7GlD&pd_rd_r=bc0a416f-878f-4caa-a30d-5fbfb410b2f0&pd_rd_i=B08297GR65&psc=1",
        "price_range": "\u20ac\u20ac\u20ac",
        "verdict": "De meest betrouwbare en complete premium glas-set voor veilig bewaren en opwarmen.",
        "award": "💎 Premium keuze",
    },
    "bormioli_frigoverre_5delig": {
        "slug": "bormioli-frigoverre-5delig",
        "name": "Bormioli Rocco Frigoverre \u2013 5-delige glazen vershoudset",
        "brand": "Bormioli Rocco",
        "material": "Borosilicaat glas",
        "capacities": [150, 240, 300, 400, 1100],
        "features": ["Ovenbestendig"],
        "image": "vershoudbakjes_bormioli_frigoverre_set_5.jpg",
        "image_path": "images/vershoudbakjes",
        "description": "Duurzame set van glazen vershoudbakjes voor dagelijks bewaren en meenemen. Het glas is voedselveilig en geschikt voor oven, magnetron en vriezer (gebruik zonder deksel bij verhitting).",
        "pros": [
            "Voedselveilig glas, vrij van schadelijke stoffen",
            "Geschikt voor oven en magnetron (zonder deksel)",
            "Geschikt voor vriezer",
            "Handige 3-delige set voor meal-prep en restjes",
        ],
        "cons": [
            "Sluitmechanisme vaak eenvoudiger dan klikdeksels",
            "Controleer per set of deksels volledig lekvrij zijn",
        ],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 44.99,
        "price_last_checked": "2026-07-08",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.wehkamp.nl/bormioli-rocco-frigoverre-vershoudbakjes-frigoverre-glas-blauw-5-delig-16432384/",
        "price_range": "\u20ac\u20ac",
        "verdict": "Een betrouwbare glazen set voor dagelijks gebruik: duurzaam, veelzijdig en ideaal als je een praktische 3-delige glasoplossing zoekt voor bewaren en opwarmen.",
        "award": None,
    },
    "igluu_meal_prep_5delig": {
        "slug": "igluu-meal-prep-5delig",
        "name": "Igluu Meal Prep \u2013 5-delige glazen vershoudset",
        "brand": "Igluu",
        "material": "Borosilicaat glas",
        "capacities": [950, 950, 950, 950, 950],
        "features": ["Lekvrij", "Klikdeksel + silicone"],
        "image": "igluu-5delig.jpg",
        "image_path": "images/vershoudbakjes",
        "description": "Betaalbare en praktische 5-delige set van borosilicaat glas met lekvrije klikdeksels. Ideaal als instapset voor gezond bewaren en opwarmen.",
        "pros": [
            "Borosilicaat glas: oven- en magnetronbestendig (zonder deksel in de oven)",
            "Drie verschillende formaten voor dagelijkse porties",
            "Lekvrije klikdeksels met silicone afdichting",
            "Betaalbare instapset zonder concessies aan materiaalveiligheid",
        ],
        "cons": [
            "Geen extra grote schaal voor familieporties",
            "Deksels zijn niet geschikt voor gebruik in de oven",
        ],
        "rating": 4,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 33.95,
        "price_last_checked": "2026-07-15",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.amazon.nl/Igluu-Meal-Prep-Storage-Containers/dp/B0CJC5BHJZ?ref_=ast_sto_dp&th=1",
        "price_range": "\u20ac",
        "verdict": "Een voordelige en complete glazen basisset voor iedereen die PFAS-vrij wil bewaren en opwarmen.",
        "award": "💰 Budget keuze",
    },
    "kitchenbrothers_5delig": {
        "slug": "kitchenbrothers-5delig",
        "name": "KitchenBrothers \u2013 5-delige glazen vershoudset",
        "brand": "KitchenBrothers",
        "material": "Borosilicaat glas",
        "capacities": [1000, 1000, 1000, 1000, 1000],
        "features": ["Lekvrij"],
        "image": "kitchenbrothers_5delig.jpg",
        "image_path": "images/vershoudbakjes",
        "description": "Een praktische en sterke 5-delige set van gehard glas met ventieldeksels. Ideaal voor dagelijks bewaren, opwarmen en meenemen dankzij de stevige 4-kliks sluiting.",
        "pros": [
            "Extra stootbestendig gehard glas",
            "4-kliks sluiting met silicone ring voor lekvrije opslag",
            "Handig ventiel voor veilig magnetrongebruik",
            "Compacte ronde formaten, makkelijk stapelbaar",
        ],
        "cons": [
            "Ronde vorm minder effici\u00ebnt voor mealprep-stapeling",
            "Deksels zijn niet ovenbestendig",
        ],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 25.00,
        "price_last_checked": "2026-07-17",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/kitchenbrothers-meal-prep-bakjes-vershoudbakjes-set-luchtdicht-bpa-vrij-1l-glas-5-stuks/9300000003218666/?Referrer=ADVNLYAH002032-S-2330346176471134-9300000003218666-PMAX-C-698295020&msclkid=e7e8b08fdc3b1fc25db8dad674cf256b",
        "price_range": "\u20ac\u20ac",
        "verdict": "Een stevige en gebruiksvriendelijke set met uitstekend ventielsysteem voor dagelijks gebruik.",
        "award": "",
    },
    "luminarc_purebox_5delig": {
        "slug": "luminarc-purebox-5delig",
        "name": "Luminarc Pure Box Active \u2013 5-delige glazen vershoudset",
        "brand": "Luminarc",
        "material": "Gehard glas",
        "capacities": [760, 820, 920, 1220, 1220],
        "features": ["Ventieldeksel", "Lekvrij"],
        "image": "luminarc-purebox-5delig.jpg",
        "image_path": "images/vershoudbakjes",
        "description": "Een praktische en sterke 5-delige set van gehard glas met ventieldeksels. Ideaal voor dagelijks bewaren, opwarmen en meenemen dankzij de stevige 4-kliks sluiting.",
        "pros": [
            "Extra stootbestendig gehard glas",
            "4-kliks sluiting met silicone ring voor lekvrije opslag",
            "Handig ventiel voor veilig magnetrongebruik",
            "Compacte ronde formaten, makkelijk stapelbaar",
        ],
        "cons": [
            "Ronde vorm minder effici\u00ebnt voor mealprep-stapeling",
            "Deksels zijn niet ovenbestendig",
        ],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 49.63,
        "price_last_checked": "2026-07-17",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.amazon.nl/-/en/Luminarc-Pure-Box-Active-Containers/dp/B07X9TBHZY/ref=sr_1_13?adgrpid=1344703190322925&dib=eyJ2IjoiMSJ9.xfpWNZov6m19C74qLrOefVHLNsM98_pL9kZp3qRtm_NsyTTlrx6LPK0F6-m1HZuRLA_K1sFDh97SOVrqsm6Z-pr16e7z1H2JOwsbLOsYI9IQe3t7SpmU1oBUuVURAdqbAicQBrFMucTyRgCIqnGbcTjzyGBPpYH3xMIksgpwC9Zm_bNdD-R9pk22kTW2KOwrVm4uRj6TGm4kGAFLMMd7h_EWRxTE8Vsp5agE81v0_umoKijgLhIRQnLFdDJzxjBi0xoscLQi07is2Ho7NdsoH6OM91vPvTMLZ4YWnwV1NtU.Dzfyl9zJqPt1S_JI8wpy0nb_0GWN6dc55tjOGMVZt20&dib_tag=se&hvadid=84044332754086&hvbmt=be&hvdev=c&hvlocphy=152250&hvnetw=o&hvqmt=e&hvtargid=kwd-84044354453747%3Aloc-129&hydadcr=6809_2353046&keywords=luminarc+pure+box&mcid=083e308abf35375fbf678195375b60d3&msclkid=6478e831dc2e121ef7fb82687aa5e633&qid=1784260240&sr=8-13",
        "price_range": "\u20ac\u20ac",
        "verdict": "Een stevige en gebruiksvriendelijke set met uitstekend ventielsysteem voor dagelijks gebruik.",
        "award": "",
    },
    "oxo_good_grips_smart_seal_6delig": {
        "slug": "oxo-good-grips-smart-seal-6delig",
        "name": "OXO Good Grips Smart Seal \u2013 6-delige glazen vershoudset",
        "brand": "Oxo",
        "material": "Borosilicaat glas",
        "capacities": [480, 970, 1730],
        "features": ["Ventieldeksel", "Lekvrij"],
        "image": "glasslock-3delig.jpg",
        "image_path": "images/vershoudbakjes",
        "description": "Een praktische en sterke 3-delige set van gehard glas met ventieldeksels. Ideaal voor dagelijks bewaren, opwarmen en meenemen dankzij de stevige 4-kliks sluiting.",
        "pros": [
            "Extra stootbestendig gehard glas",
            "4-kliks sluiting met silicone ring voor lekvrije opslag",
            "Handig ventiel voor veilig magnetrongebruik",
            "Compacte ronde formaten, makkelijk stapelbaar",
        ],
        "cons": [
            "Ronde vorm minder effici\u00ebnt voor mealprep-stapeling",
            "Deksels zijn niet ovenbestendig",
        ],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 41.29,
        "price_last_checked": "2026-07-08",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.amazon.nl/-/en/Glasslock-GL-529-1750ml-Rectangular-Container/dp/B00MX16YKE/ref=sr_1_5?adgrpid=1345804604584798&dib=eyJ2IjoiMSJ9.ta58l7hdwLQglioY2JkbABkIwNp__ai_XeE9jHyw5Nh7i2gsskIeu5f1Ire_sgEx8mQmIC6O0U4oxckqRWndxMhmfNWgjOcVvnqoSXx6e49s4S-cO5hfPJ8k5iskNpdR7zg-eOKZcvdDhFXnequiETZ8g4aSAux5Q2DKtzBTRRbcyeSwFMqWorMY-jIsSychk8UvjVRiEyRZR5K2nhplADD6sa6tTGLWgC3Dj5khAuCmUSqnWo593NWyRdsPu7F3w_CqpyEPbAGFOrrSiEsN5x5E_1qSZRjSd_DwKWXqvPg.Ge4XaEwsJBmqIY1uvH4N8JNl2uqO5oOxeasXthlWGxY&dib_tag=se&hvadid=84113043168595&hvbmt=bp&hvdev=c&hvlocphy=152250&hvnetw=o&hvqmt=p&hvtargid=kwd-84113816710888%3Aloc-129&hydadcr=6813_2256395&keywords=glasslock+set&mcid=80ac74f8738c33b5bb69e05482fecdab&msclkid=c7e6a6c2ff4b108f5869cc9b551b7bdb&qid=1784261236&sr=8-5&language=nl_NL",
        "price_range": "\u20ac\u20ac\u20ac",
        "verdict": "Een stevige en gebruiksvriendelijke set met uitstekend ventielsysteem voor dagelijks gebruik.",
        "award": "",
    },
}
