PRODUCTS = {
    # LOSSE VERSHOUDBAKJES
    "pyrex_cook_store_enkel": {
        "slug": "pyrex-cook-store-enkel",
        "name": "Pyrex Cook & Store \u2013 enkele schaal",
        "brand": "Pyrex",
        "material": "Borosilicaatglas",
        "capacities": [800],
        "features": [
            "Klikdeksel",
            "Magnetronventiel"
        ],
        "image": "pyrex-cookstore-enkel.webp",
        "image_path": "images/products/vershoudbakjes",
        "description": "Hoogwaardig glazen vershoudbakje van borosilicaatglas met stevig klikdeksel en stoomventiel. Ideaal voor bewaren, invriezen, opwarmen en bereiden in de oven.",
        "usage": {
            "oven": {"container": True, "lid": False, "note": "Alleen het glazen bakje"},
            "microwave": {"container": True, "lid": False, "note": "Alleen het glazen bakje"},
            "freezer": {"container": True, "lid": True, "note": None},
            "dishwasher": {"container": True, "lid": None, "note": None},
        },
        "pros": [
            "Borosilicaatglas is bestand tegen grote temperatuurverschillen",
            "Stevig klikdeksel met siliconen afdichting",
            "Praktisch stoomventiel voor opwarmen in de magnetron",
        ],
        "cons": [
            "Zwaarder dan kunststof bewaarbakjes",
        ],
        "rating": 4.4,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 23.21,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/pyrex-cook-store-vershoudbakje-borosilicaatglas-800-ml-transparant/9200000117155201/",
        "price_last_checked": "2026-07-24",
        "price_range": "\u20ac\u20ac",
        "verdict": "Een van de beste losse glazen vershoudbakjes dankzij de uitstekende bouwkwaliteit, veelzijdigheid en lange levensduur.",
        "award": "🏆 Beste keuze",
    },
    "ikea_365+_enkel": {
        "slug": "ikea-365-plus-enkel",
        "name": "Ikea 365+ \u2013 enkele schaal",
        "brand": "Ikea",
        "material": "Borosilicaatglas",
        "capacities": [600],
        "features": [
            "Ovenbestendig",
            "Losse deksels verkrijgbaar"
        ],
        "image": "ikea-365-enkel.webp",
        "image_path": "images/products/vershoudbakjes",
        "description": "Betaalbaar glazen vershoudbakje van borosilicaatglas met los verkrijgbaar deksel. Geschikt voor dagelijks bewaren, invriezen en opwarmen.",
        "usage": {
            "oven": {"container": True, "lid": None, "note": "Alleen het glazen bakje"},
            "microwave": {"container": True, "lid": True, "note": None},
            "freezer": {"container": True, "lid": True, "note": None},
            "dishwasher": {"container": True, "lid": True, "note": None},
        },
        "pros": [
            "Uitstekende prijs-kwaliteitverhouding",
            "Verkrijgbaar in veel verschillende maten",
            "Deksels zijn los verkrijgbaar",
        ],
        "cons": [
            "Deksel wordt apart verkocht",
            "Minder lekdicht dan premium systemen",
        ],
        "rating":4.3,
        "rating_count": None,
        "rating_source": "editorial",
        "price_range": "\u20ac",
        "verdict": "De beste budgetkeuze voor wie een degelijk glazen vershoudbakje zoekt zonder veel uit te geven.",
        "award": "💰 Budget keuze",
        "variant_selectors": [
            {"key": "capacity", "label": "Inhoud"},
        ],
        "variants": [
            {
                "id": "600-ml",
                "options": {"capacity": 600},
                "option_labels": {"capacity": "600 ml"},
                "capacities": [600],
                "image": "ikea-365-enkel.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 3.49,
                "price_last_checked": "2026-07-24",
                "currency": "EUR",
                "availability": "InStock",
                "affiliate_url": "",
                "retailer_url": "https://www.ikea.com/nl/nl/p/ikea-365-voorraadpot-met-deksel-vierkant-glas-kunststof-s39269120/#content",
                "is_default": True,
            },
            {
                "id": "1000-ml",
                "options": {"capacity": 1000},
                "option_labels": {"capacity": "1 L"},
                "capacities": [1000],
                "image": "ikea-365-1l-enkel.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 4.49,
                "price_last_checked": "2026-07-24",
                "currency": "EUR",
                "availability": "InStock",
                "affiliate_url": "",
                "retailer_url": "https://www.ikea.com/nl/nl/p/ikea-365-voorraadpot-met-deksel-rechthoekig-glas-kunststof-s89269071/#content",
                "is_default": False,
            },
            {
                "id": "1200-ml",
                "options": {"capacity": 1200},
                "option_labels": {"capacity": "1,2 L"},
                "capacities": [1200],
                "image": "ikea-365-12l-enkel.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 4.99,
                "price_last_checked": "2026-07-24",
                "currency": "EUR",
                "availability": "InStock",
                "affiliate_url": "",
                "retailer_url": "https://www.ikea.com/nl/nl/p/ikea-365-voorraadpot-met-deksel-vierkant-glas-kunststof-s59269119/#content",
                "is_default": False,
            },
        ],
    },

    "mepal_easyclip_glass_enkel": {
        "slug": "mepal-easyclip-glass-enkel",
        "name": "Mepal EasyClip Glass \u2013 vershoudbakje",
        "brand": "Mepal",
        "material": "Borosilicaatglas",
        "capacities": [450],
        "features": [
            "EasyClip sluiting",
            "Lekvrij"
        ],
        "image": "mepal-easyclip-glass-enkel.webp",
        "image_path": "images/products/vershoudbakjes",
        "description": "Premium glazen vershoudbakje van borosilicaatglas met het innovatieve EasyClip-sluitsysteem. Volledig lekdicht en geschikt voor oven, magnetron, koelkast en vriezer.",
        "usage": {
            "oven": {"container": True, "lid": False, "note": "Alleen het glazen bakje"},
            "microwave": {"container": True, "lid": True, "note": "Met deksel het stoomventiel openen"},
            "freezer": {"container": True, "lid": True, "note": None},
            "dishwasher": {"container": True, "lid": True, "note": None},
        },
        "pros": [
            "Volledig lekdicht dankzij EasyClip-sluiting",
            "Borosilicaatglas neemt geen geuren of kleuren op",
            "Hoogwaardige afwerking en eenvoudig te openen",
        ],
        "cons": [
            "Hoger geprijsd dan veel alternatieven",
        ],
        "rating": 4.7,
        "rating_count": None,
        "rating_source": "editorial",
        "currency": "EUR",
        "availability": "InStock",
        "price_range": "\u20ac\u20ac",
        "verdict": "Een premium vershoudbakje dat uitblinkt in gebruiksgemak, lekdichtheid en afwerking.",
        "award": None,
        "variant_selectors": [
            {"key": "capacity", "label": "Inhoud"},
        ],
        "variants": [
            {
                "id": "450-ml",
                "options": {"capacity": 450},
                "option_labels": {"capacity": "450 ml"},
                "capacities": [450],
                "image": "mepal-easyclip-glass-450ml-enkel.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 9.99,
                "price_last_checked": "2026-07-24",
                "currency": "EUR",
                "availability": "InStock",
                "affiliate_url": "",
                "retailer_url": "https://www.bol.com/nl/nl/p/mepal-glazen-vershouddoos-easyclip-450-ml-glazen-vershoudbakjes-met-schuifsluiting-geschikt-voor-magnetron-oven-koelkast-en-vriezer-nordic-sage/9300000251601243/",
                "is_default": True,
            },
            {
                "id": "700-ml",
                "options": {"capacity": 700},
                "option_labels": {"capacity": "700 ml"},
                "capacities": [700],
                "image": "mepal-easyclip-glass-700ml-enkel.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 9.94,
                "price_last_checked": "2026-07-24",
                "currency": "EUR",
                "availability": "InStock",
                "affiliate_url": "",
                "retailer_url": "https://www.bol.com/nl/nl/p/mepal-glazen-vershouddoos-easyclip-700-ml-glazen-vershoudbakjes-met-schuifsluiting-geschikt-voor-magnetron-oven-koelkast-en-vriezer-nordic-sage/9300000251601247/",
                "is_default": False,
            },
            {
                "id": "1500-ml",
                "options": {"capacity": 1500},
                "option_labels": {"capacity": "1,5 L"},
                "capacities": [1500],
                "image": "mepal-easyclip-glass-1500ml-enkel.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 15.69,
                "price_last_checked": "2026-07-24",
                "currency": "EUR",
                "availability": "InStock",
                "affiliate_url": "",
                "retailer_url": "https://www.bol.com/nl/nl/p/mepal-glazen-vershouddoos-easyclip-1-5-l-glazen-vershoudbakjes-met-schuifsluiting-geschikt-voor-magnetron-oven-koelkast-en-vriezer-nordic-sage/9300000251601246/",
                "is_default": False,
            },
            {
                "id": "2250-ml",
                "options": {"capacity": 2250},
                "option_labels": {"capacity": "2,25 L"},
                "capacities": [2250],
                "image": "mepal-easyclip-glass-2250ml-enkel.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 24.19,
                "price_last_checked": "2026-07-24",
                "currency": "EUR",
                "availability": "InStock",
                "affiliate_url": "",
                "retailer_url": "https://www.bol.com/nl/nl/p/mepal-glazen-vershouddoos-easyclip-2-25-l-glazen-vershoudbakjes-met-schuifsluiting-geschikt-voor-magnetron-oven-koelkast-en-vriezer-nordic-sage/9300000251601250/",
                "is_default": False,
            },
        ],
    },
    "locknlock_enkel": {
        "slug": "locknlock-enkel",
        "name": "Lock&Lock \u2013 glazen vershoudbakje",
        "brand": "Lock&Lock",
        "material": "Borosilicaatglas",
        "capacities": [740],
        "features": [
            "4-zijdige sluiting",
            "Lekvrij"
        ],
        "image": "locknlock-enkel.jpg",
        "image_path": "images/vershoudbakjes",
        "description": "Stevig glazen vershoudbakje met de bekende vierzijdige Lock&Lock-sluiting. Ideaal voor lekvrij bewaren, meenemen en opwarmen.",
        "usage": {
            "oven": {"container": True, "lid": False, "note": "Alleen het glazen bakje tot 400 °C"},
            "microwave": {"container": True, "lid": False, "note": "Alleen het glazen bakje"},
            "freezer": {"container": True, "lid": True, "note": "Tot -20 °C"},
            "dishwasher": {"container": True, "lid": True, "note": "Bovenste rek"},
        },
        "pros": [
            "Zeer betrouwbare vierzijdige kliksluiting",
            "Lekvrij dankzij siliconen afdichting",
            "Stevig glas voor dagelijks gebruik",
        ],
        "cons": [
            "Iets zwaarder dan vergelijkbare kunststof bakjes",
        ],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price_range": "\u20ac\u20ac",
        "verdict": "Een uitstekende keuze voor wie maximale lekdichtheid en betrouwbaarheid belangrijk vindt.",
        "award": None,
        "variant_selectors": [
            {"key": "capacity", "label": "Inhoud"},
        ],
        "variants": [
            {
                "id": "630-ml",
                "options": {"capacity": 630},
                "option_labels": {"capacity": "630 ml"},
                "image": "locknlock-630ml-enkel.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 9.95,
                "price_last_checked": "2026-07-24",
                "currency": "EUR",
                "availability": "InStock",
                "affiliate_url": "",
                "retailer_url": "https://locklock.nl/product/keuken/ovenschalen-met-deksel/ovenschaaltje-met-deksel-630-ml/",
                "is_default": True,
            },
            {
                "id": "740-ml",
                "options": {"capacity": 740},
                "option_labels": {"capacity": "740 ml"},
                "image": "locknlock-740ml-enkel.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 12.95,
                "price_last_checked": "2026-07-24",
                "currency": "EUR",
                "availability": "InStock",
                "affiliate_url": "",
                "retailer_url": "https://locklock.nl/product/keuken/ovenschalen-met-deksel/glazen-ovenschaaltje-met-deksel-740-ml/",
                "is_default": False,
            },
            {
                "id": "1000-ml",
                "options": {"capacity": 1000},
                "option_labels": {"capacity": "1 L"},
                "image": "locknlock-1l-enkel.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 15.95,
                "price_last_checked": "2026-07-24",
                "currency": "EUR",
                "availability": "InStock",
                "affiliate_url": "",
                "retailer_url": "https://locklock.nl/product/keuken/ovenschalen-met-deksel/ovenschaal-met-deksel-1-0-liter/",
                "is_default": False,
            },
        ],
    },
    "luminarc_purebox_enkel": {
        "slug": "luminarc-purebox-enkel",
        "name": "Luminarc Pure Box Active \u2013 glazen vershoudbakje",
        "brand": "Luminarc",
        "material": "Gehard glas",
        "capacities": [820],
        "features": [
            "Ventieldeksel",
            "Lekvrij"
        ],
        "image": "luminarc-purebox-enkel.jpg",
        "image_path": "images/vershoudbakjes",
        "description": "Praktisch glazen vershoudbakje van gehard glas met lekvrij deksel en geïntegreerd stoomventiel. Ideaal voor dagelijks bewaren en opwarmen.",
        "usage": {
            "oven": {"container": None, "lid": False, "note": None},
            "microwave": {"container": True, "lid": True, "note": "Ventiel openen"},
            "freezer": {"container": True, "lid": True, "note": None},
            "dishwasher": {"container": None, "lid": None, "note": None},
        },
        "pros": [
            "Gehard glas is zeer sterk en krasbestendig",
            "Handig stoomventiel voor magnetrongebruik",
            "Goede prijs-kwaliteitverhouding",
        ],
        "cons": [
            "Minder premium afgewerkt dan de topmodellen",
            "Niet geschikt voor de opwarming in de oven",
        ],
        "rating": 4.4,
        "rating_count": None,
        "rating_source": "editorial",
        "price_range": "\u20ac\u20ac",
        "verdict": "Een degelijk glazen vershoudbakje dat veel functionaliteit biedt voor een aantrekkelijke prijs.",
        "award": None,
        # NB: de volgorde bepaalt de prioriteit: de eerste selector toont
        # altijd al zijn opties; latere selectors tonen alleen opties die
        # bestaan binnen de eerdere keuze. Vorm dus altijd vóór Inhoud.
        "variant_selectors": [
            {"key": "shape", "label": "Vorm"},
            {"key": "capacity", "label": "Inhoud"}
        ],
        "variants": [
            {
                "id": "820-ml-rectangle",
                "options": {"shape": "rectangle", "capacity": 820},
                "option_labels": {"shape": "Rechthoek", "capacity": "820 ml"},
                "image": "luminarc-purebox-820ml-enkel.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 9.14,
                "price_last_checked": "2026-07-24",
                "currency": "EUR",
                "availability": "InStock",
                "affiliate_url": "",
                "retailer_url": "https://www.bol.com/nl/nl/p/luminarc-pure-box-active-vershouddoos-rechthoekig-glas-0-82l/9200000035762057/",
                "is_default": False,
            },
            {
                "id": "380-ml-rectangle",
                "options": {"shape": "rectangle", "capacity": 380},
                "option_labels": {"shape": "Rechthoek", "capacity": "380 ml"},
                "image": "luminarc-purebox-380ml-enkel.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 10.06,
                "price_last_checked": "2026-07-24",
                "currency": "EUR",
                "availability": "InStock",
                "affiliate_url": "",
                "retailer_url": "https://www.bol.com/nl/nl/p/luminarc-pure-box-active-vershouddoos-rechthoekig-glas-0-38l/9200000035762025/",
                "is_default": True,
            },
            {
                "id": "1220-ml-rectangle",
                "options": {"shape": "rectangle", "capacity": 1220},
                "option_labels": {"shape": "Rechthoek", "capacity": "1,22 L"},
                "image": "luminarc-purebox-1220ml-enkel.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 10.58,
                "price_last_checked": "2026-07-24",
                "currency": "EUR",
                "availability": "InStock",
                "affiliate_url": "",
                "retailer_url": "https://www.bol.com/nl/nl/p/luminarc-pure-box-active-vershouddoos-rechthoekig-glas-1-22l/9200000035762061/?cid=1784900984244-1791694709757",
                "is_default": False,
            },
            {
                "id": "1970-ml-rectangle",
                "options": {"shape": "rectangle", "capacity": 1970},
                "option_labels": {"shape": "Rechthoek", "capacity": "1,97 L"},
                "image": "luminarc-purebox-1970ml-enkel.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 28.90,
                "price_last_checked": "2026-07-24",
                "currency": "EUR",
                "availability": "InStock",
                "affiliate_url": "",
                "retailer_url": "https://www.bol.com/nl/nl/p/luminarc-pure-box-active-vershoudbak-glas-rechthoekig-1-97-l/9200000035762035/",
                "is_default": False,
            },
            {
                "id": "1220-ml-square",
                "options": {"shape": "square", "capacity": 1220},
                "option_labels": {"shape": "Vierkant", "capacity": "1,22 L"},
                "image": "luminarc-purebox-1220ml-vierkant-enkel.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 12.68,
                "price_last_checked": "2026-07-24",
                "currency": "EUR",
                "availability": "InStock",
                "affiliate_url": "",
                "retailer_url": "https://www.bol.com/nl/nl/p/luminarc-pure-box-active-vershoudbak-glas-vierkant-1-22-l/9200000035762051/",
                "is_default": False,
            },
            {
                "id": "760-ml-square",
                "options": {"shape": "square", "capacity": 760},
                "option_labels": {"shape": "Vierkant", "capacity": "760 ml"},
                "image": "luminarc-purebox-760ml-vierkant-enkel.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 11.72,
                "price_last_checked": "2026-07-24",
                "currency": "EUR",
                "availability": "InStock",
                "affiliate_url": "",
                "retailer_url": "https://www.bol.com/nl/nl/p/luminarc-pure-box-active-vershouddoos-vierkant-glas-0-76l/9200000035762031/",
                "is_default": False,
            },
            {
                "id": "420-ml-round",
                "options": {"shape": "round", "capacity": 420},
                "option_labels": {"shape": "Rond", "capacity": "420 ml"},
                "image": "luminarc-purebox-420ml-rond-enkel.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 7.95,
                "price_last_checked": "2026-07-24",
                "currency": "EUR",
                "availability": "InStock",
                "affiliate_url": "",
                "retailer_url": "https://www.bol.com/nl/nl/p/luminarc-pure-box-active-vershouddoos-rond-glas-0-42l/9200000035762053/",
                "is_default": False,
            },
            {
                "id": "920-ml-round",
                "options": {"shape": "round", "capacity": 920},
                "option_labels": {"shape": "Rond", "capacity": "920 ml"},
                "image": "luminarc-purebox-920ml-rond-enkel.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 11.45,
                "price_last_checked": "2026-07-24",
                "currency": "EUR",
                "availability": "InStock",
                "affiliate_url": "",
                "retailer_url": "https://www.bol.com/nl/nl/p/luminarc-pure-box-active-vershouddoos-rond-glas-0-92l/9200000035762029/",
                "is_default": False,
            },
        ],
    },
    "berghoff_perfect_seal": {
        "slug": "berghoff-perfect-seal",
        "name": "Berghoff Perfect Seal \u2013 glazen vershoudbakje",
        "brand": "Berghoff",
        "material": "Borosilicaatglas",
        "features": [
            "Eenhandige sluiting",
            "Lekvrij",
            "Magnetronventiel",
        ],
        "description": "Gebruiksvriendelijk vershoudbakje van borosilicaatglas met een "
        "luchtdichte, lekvrije deksel die met één hand opent en sluit. "
        "Het stapelbare bakje is geschikt voor bewaren, invriezen, "
        "opwarmen en gebruik in de oven.",
        "pros": [
            "Eenvoudig met één hand te openen en te sluiten",
            "Luchtdichte, lekvrije afsluiting voor bewaren en meenemen",
            "Stapelbaar ontwerp benut de kastruimte efficiënt",
        ],
        "cons": [
            "Hoger geprijsd dan veel eenvoudige glazen vershoudbakjes",
        ],
        "rating": 4.4,
        "rating_count": None,
        "rating_source": "editorial",
        "price_range": "\u20ac\u20ac",
        "verdict": "Gebruiksvriendelijk premium bakje met sterke lekdichting "
        "en praktische eenhandige sluiting.",
        "usage": {
            "oven": {
                "container": True,
                "lid": False,
                "note": "Glazen bakje maximaal 280 °C",
            },
            "microwave": {
                "container": True,
                "lid": True,
                "note": "Ventiel openen; maximaal 600 W gedurende 3 minuten",
            },
            "freezer": {
                "container": True,
                "lid": True,
                "note": None,
            },
            "dishwasher": {
                "container": True,
                "lid": False,
                "note": "Zonder deksel",
            },
        },
        "award": "💎 Premium keuze",
        "variant_selectors": [
            {"key": "capacity", "label": "Inhoud"},
        ],
        "variants": [
            {
                "id": "500-ml-square",
                "options": {"capacity": 500},
                "option_labels": {"capacity": "500 ml"},
                "image": "leo-perfect-seal-500ml-enkel.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 21.95,
                "price_last_checked": "2026-07-24",
                "currency": "EUR",
                "availability": "InStock",
                "affiliate_url": "",
                "retailer_url": "https://www.bol.com/nl/nl/p/leo-perfect-seal-voorraaddoos-0-50l-transparant/9300000257748350/",
                "is_default": True,
            },
            {
                "id": "1100-ml-square",
                "options": {"capacity": 1100},
                "option_labels": {"capacity": "1,1 L"},
                "image": "leo-perfect-seal-1100ml-enkel.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 29.95,
                "price_last_checked": "2026-07-24",
                "currency": "EUR",
                "availability": "InStock",
                "affiliate_url": "",
                "retailer_url": "https://www.bol.com/nl/nl/p/leo-perfect-seal-voorraaddoos-1-10l-transparant/9300000257748352/",
                "is_default": False,
            },
        ]
    },
    
    # 3-DELIGE SETS
    "mepal_easyclip_glass_3delig": {
        "slug": "mepal-easyclip-glass-3delig",
        "name": "Mepal EasyClip Glass \u2013 3-delige glazen vershoudbakjes",
        "brand": "Mepal",
        "material": "Borosilicaatglas",
        "capacities": [700, 700, 1500],
        "features": ["Lekvrij",
                    "EasyClip-sluiting",
                    "Ovenbestendig glas"],
        "image": "mepal-easyclip-glass-3.webp",
        "image_path": "images/products/vershoudbakjes",
        "description": "Een premium borosilicaat glazen set met lekvrije EasyClip-deksels. Geschikt voor oven, magnetron, koelkast en vriezer. Uitstekende duurzaamheid en gebruiksgemak.",
        "usage": {
            "oven": {"container": True, "lid": False, "note": "Alleen het glazen bakje"},
            "microwave": {"container": True, "lid": True, "note": "Met deksel het stoomventiel openen"},
            "freezer": {"container": True, "lid": True, "note": None},
            "dishwasher": {"container": True, "lid": True, "note": None},
        },
        "pros": [
            "Borosilicaatglas: veilig en geurvrij",
            "Volledig lekdichte EasyClip-deksels",
            "Zeer stevige siliconen afdichting",
        ],
        "cons": [
            "Iets zwaarder dan kunststof alternatieven",
            "Hogere prijsklasse",
        ],
        "rating": 4.7,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 49.97,
        "price_last_checked": "2026-07-15",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.wehkamp.nl/mepal-easyclip-bewaardoos-3-delig-2x-700-1500-ml-glas-17577617/",
        "price_range": "\u20ac\u20ac\u20ac",
        "verdict": "Totaalpakket van kwaliteit, veiligheid en gebruiksgemak \u2014 de beste glazen 3-delige set.",
        "award": "🏆 Beste keuze",
    },
    "igluu_meal_prep_3delig": {
        "slug": "igluu-meal-prep-3delig",
        "name": "Igluu Meal Prep \u2013 3-delige glazen vershoudset",
        "brand": "Igluu",
        "material": "Borosilicaatglas",
        "features": ["Lekvrij", "Klikdeksel met siliconen afdichting"],
        "description": "Betaalbare en praktische 3-delige set van borosilicaat glas met lekvrije klikdeksels. Ideaal als instapset voor gezond bewaren en opwarmen.",
        "usage": {
            "oven": {"container": True, "lid": False, "note": "Alleen het glazen bakje tot 300 °C"},
            "microwave": {"container": True, "lid": False, "note": "Alleen het glazen bakje"},
            "freezer": {"container": True, "lid": True, "note": "Tot -20 °C"},
            "dishwasher": {"container": True, "lid": False, "note": None},
        },
        "pros": [
            "Drie verschillende formaten voor dagelijkse porties",
            "Lekvrije klikdeksels met siliconen afdichting",
            "Betaalbare instapset zonder concessies aan materiaalveiligheid",
        ],
        "cons": [
            "Geen extra grote schaal voor familieporties",
        ],
        "rating": 4.3,
        "rating_count": None,
        "rating_source": "editorial",
        "price_range": "\u20ac",
        "verdict": "Een voordelige en complete glazen basisset voor iedereen die PFAS-vrij wil bewaren en opwarmen.",
        "award": "💰 Budget keuze",
        "variant_label": "Vorm",
        "variants": [
            {
                "id": "round",
                "label": "Rond",
                "shape": "Rond",
                "capacities": [400, 650, 950],
                "image": "igluu-meal-prep-3delig.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 24.95,
                "price_last_checked": "2026-07-23",
                "currency": "EUR",
                "availability": "InStock",
                "affiliate_url": "",
                "retailer_url": "https://www.amazon.nl/dp/B08DYF9GXP/",
                "is_default": True,
            },
            {
                "id": "square",
                "label": "Vierkant",
                "shape": "Vierkant",
                "capacities": [320, 520, 800],
                "image": "igluu-meal-prep-3delig-vierkant.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 24.95,
                "price_last_checked": "2026-07-23",
                "currency": "EUR",
                "availability": "InStock",  
                "affiliate_url": "",
                "retailer_url": "https://www.amazon.nl/dp/B08WJHTSQ1/",
                "is_default": False,
            },
        ],
    },
    "pyrex_cook_heat_3delig": {
        "slug": "pyrex-cook-heat-3delig",
        "name": "Pyrex Cook & Heat \u2013 3-delige glazen vershoudset",
        "brand": "Pyrex",
        "material": "Borosilicaatglas",
        "features": ["Klikdeksel", "Magnetronventiel"],
        "description": "Een hoogwaardige 3-delige set van borosilicaat glas met stevige klikdeksels en siliconen afdichting. Ontworpen voor veilig bewaren \u00e9n opwarmen in zowel oven als magnetron.",
        "usage": {
            "oven": {"container": True, "lid": False, "note": "Alleen het glazen bakje tot 350 °C"},
            "microwave": {"container": True, "lid": True, "note": "Ventiel openen"},
            "freezer": {"container": True, "lid": True, "note": "Tot -40 °C"},
            "dishwasher": {"container": True, "lid": True, "note": None},
        },
        "pros": [
            "Borosilicaatglas: ovenbestendig tot hoge temperaturen",
            "Stevige klikdeksels met siliconen ring",
            "Subtiel magnetronventiel voor veilig opwarmen",
        ],
        "cons": [
            "Grotere formaten nemen meer ruimte in",
        ],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price_range": "\u20ac\u20ac\u20ac",
        "verdict": "De ideale glazen set voor wie regelmatig bewaart, opwarmt én gerechten rechtstreeks vanuit de oven serveert.",
        "award": "💎 Premium keuze",
        "variant_label": "Vorm",
        "variants": [
            {
                "id": "round",
                "label": "Rond",
                "shape": "Rond",
                "capacities": [1100, 1100, 1100],
                "image": "pyrex-cook-heat-3delig-rond.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 61.84,
                "price_last_checked": "2026-07-23",
                "currency": "EUR",
                "availability": "InStock",
                "affiliate_url": "",
                "retailer_url": "https://www.amazon.nl/Pyrex-Cook-Heat-Borosilicaatglas-Luchtdicht/dp/B07TWH7QHT/",
                "is_default": True,
            },
            {
                "id": "square",
                "label": "Vierkant",
                "shape": "Vierkant",
                "capacities": [1100, 1100, 1100],
                "image": "pyrex-cook-heat-3delig.webp",
                "image_path": "images/products/vershoudbakjes",
                "price": 39.87,
                "price_last_checked": "2026-07-23",
                "currency": "EUR",
                "availability": "InStock",  
                "affiliate_url": "",
                "retailer_url": "https://www.amazon.nl/dp/B07TTCV55F/",
                "is_default": False,
            },
        ],
    },
    "bormioli_frigoverre_3delig": {
        "slug": "bormioli-frigoverre-3delig",
        "name": "Bormioli Rocco Frigoverre \u2013 3-delige glazen vershoudset",
        "brand": "Bormioli Rocco",
        "material": "Borosilicaatglas",
        "capacities": [240, 750, 1600],
        "features": ["Magnetronbestendig", "Vriezerbestendig"],
        "image": "bormioli-frigoverre-set-3.webp",
        "image_path": "images/products/vershoudbakjes",
        "description": "Duurzame set van glazen vershoudbakjes voor dagelijks bewaren en meenemen. Het glas is voedselveilig en geschikt voor oven, magnetron en vriezer (gebruik zonder deksel bij verhitting).",
        "usage": {
            "oven": {"container": False, "lid": False, "note": None},
            "microwave": {"container": True, "lid": False, "note": "Zonder deksel verwarmen"},
            "freezer": {"container": True, "lid": True, "note": None},
            "dishwasher": {"container": True, "lid": True, "note": None},
        },
        "pros": [
            "Voedselveilig glas, vrij van schadelijke stoffen",
            "Handige 3-delige set voor meal-prep en restjes",
        ],
        "cons": [
            "Deksel sluit minder stevig dan sommige premium kliksystemen",
            "Niet geschikt voor opwarming in de oven",
        ],
        "rating": 4.0,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 27.99,
        "price_last_checked": "2026-07-08",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.wehkamp.nl/bormioli-rocco-frigoverre-vershoudbakjes-frigoverre-glas-blauw-3-stuks-16432465/",
        "price_range": "\u20ac\u20ac",
        "verdict": "Een betrouwbare glazen set voor dagelijks gebruik: duurzaam, veelzijdig en ideaal als je een praktische 3-delige glasoplossing zoekt voor bewaren en opwarmen.",
        "award": None,
    },
    "luminarc_purebox_3delig": {
        "slug": "luminarc-purebox-3delig",
        "name": "Luminarc Pure Box Active \u2013 3-delige glazen vershoudset",
        "brand": "Luminarc",
        "material": "Gehard glas",
        "capacities": [420, 670, 920],
        "features": ["Ventieldeksel", "Lekvrij"],
        "image": "luminarc-purebox-3delig.webp",
        "image_path": "images/products/vershoudbakjes",
        "description": "Een praktische en sterke 3-delige set van gehard glas met ventieldeksels. Ideaal voor dagelijks bewaren, opwarmen en meenemen dankzij de stevige 4-kliks sluiting.",
        "usage": {
            "oven": {"container": None, "lid": False, "note": None},
            "microwave": {"container": True, "lid": True, "note": "Ventiel openen"},
            "freezer": {"container": True, "lid": True, "note": None},
            "dishwasher": {"container": None, "lid": None, "note": None},
        },
        "pros": [
            "Extra stootbestendig gehard glas",
            "4-kliks sluiting met siliconen ring voor lekvrije opslag",
            "Compacte ronde formaten, makkelijk stapelbaar",
        ],
        "cons": [
            "Ronde vorm minder effici\u00ebnt voor mealprep-stapeling",
            "Niet geschikt voor opwarming in de oven",
        ],
        "rating": 4.3,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 26.61,
        "price_last_checked": "2026-07-08",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/luminarc-pure-box-active-vershouddoos-rond-glas-set-3/9200000036318348/",
        "price_range": "\u20ac\u20ac",
        "verdict": "Een stevige en gebruiksvriendelijke set met uitstekend ventielsysteem voor dagelijks gebruik.",
        "award": None,
    },
    "glasslock_3delig": {
        "slug": "glasslock-3delig",
        "name": "Glasslock \u2013 3-delige glazen vershoudset",
        "brand": "Glasslock",
        "material": "Gehard glas",
        "capacities": [480, 970, 1730],
        "features": ["Ventieldeksel", "Lekvrij"],
        "image": "glasslock-ovensafe-3delig.webp",
        "image_path": "images/products/vershoudbakjes",
        "description": "Een praktische en sterke 3-delige set van gehard glas met ventieldeksels. Ideaal voor dagelijks bewaren, opwarmen en meenemen dankzij de stevige 4-kliks sluiting.",
        "usage": {
            "oven": {"container": True, "lid": False, "note": "Alleen het glazen bakje tot 230 °C"},
            "microwave": {"container": True, "lid": False, "note": "Alleen het glazen bakje"},
            "freezer": {"container": True, "lid": True, "note": "Tot -20 °C"},
            "dishwasher": {"container": True, "lid": True, "note": None},
        },
        "pros": [
            "Extra stootbestendig gehard glas",
            "4-kliks sluiting met siliconen ring voor lekvrije opslag",
            "Compacte ronde formaten, makkelijk stapelbaar",
        ],
        "cons": [
            "Ronde vorm minder effici\u00ebnt voor mealprep-stapeling",
        ],
        "rating": 4.3,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 41.29,
        "price_last_checked": "2026-07-08",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.amazon.nl/-/en/Glasslock-GL-529-1750ml-Rectangular-Container/dp/B00MX16YKE/",
        "price_range": "\u20ac\u20ac\u20ac",
        "verdict": "Een stevige en gebruiksvriendelijke set met uitstekend ventielsysteem voor dagelijks gebruik.",
        "award": None,
    },

    # 5-DELIGE SETS
    "pyrex_cook_heat_5delig": {
        "slug": "pyrex-cook-heat-5delig",
        "name": "Pyrex Cook & Heat \u2013 5-delige glazen vershoudset",
        "brand": "Pyrex",
        "material": "Borosilicaatglas",
        "capacities": [400, 600, 1000, 1200, 2500],
        "features": ["Clipdeksel", "Magnetronventiel"],
        "image": "pyrex-cookheat-5delig.webp",
        "image_path": "images/products/vershoudbakjes",
        "description": "Een hoogwaardige 5-delige set van borosilicaat glas met stevige klikdeksels en siliconen afdichting. Ontworpen voor veilig bewaren \u00e9n opwarmen in zowel oven als magnetron.",
        "usage": {
            "oven": {"container": True, "lid": False, "note": "Alleen het glazen bakje tot 350 °C"},
            "microwave": {"container": True, "lid": True, "note": "Ventiel openen"},
            "freezer": {"container": True, "lid": True, "note": "Tot -40 °C"},
            "dishwasher": {"container": True, "lid": True, "note": None},
        },
        "pros": [
            "Borosilicaatglas: ovenbestendig tot hoge temperaturen",
            "Stevige klikdeksels met siliconen ring",
            "Subtiel magnetronventiel voor veilig opwarmen",
        ],
        "cons": [
            "Grotere formaten nemen meer ruimte in",
        ],
        "rating": 4.5,
        "rating_count": 295,
        "price": 65.00,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.amazon.nl/-/en/Pyrex-glass-dishes-airtight-microwave/dp/B08297GR65/",
        "price_range": "\u20ac\u20ac\u20ac",
        "verdict": "De meest betrouwbare en complete premium glas-set voor veilig bewaren en opwarmen.",
        "award": "🏆 Beste keuze",
    },
    "bormioli_frigoverre_5delig": {
        "slug": "bormioli-frigoverre-5delig",
        "name": "Bormioli Rocco Frigoverre \u2013 5-delige glazen vershoudset",
        "brand": "Bormioli Rocco",
        "material": "Borosilicaatglas",
        "capacities": [150, 240, 300, 400, 1100],
        "features": ["Ovenbestendig"],
        "image": "vershoudbakjes_bormioli_frigoverre_set_5.jpg",
        "image_path": "images/vershoudbakjes",
        "description": "Duurzame set van glazen vershoudbakjes voor dagelijks bewaren en meenemen. Het glas is voedselveilig en geschikt voor oven, magnetron en vriezer (gebruik zonder deksel bij verhitting).",
        "usage": {
            "oven": {"container": False, "lid": False, "note": None},
            "microwave": {"container": True, "lid": False, "note": "Zonder deksel verwarmen"},
            "freezer": {"container": True, "lid": True, "note": None},
            "dishwasher": {"container": True, "lid": True, "note": None},
        },
        "pros": [
            "Voedselveilig glas, vrij van schadelijke stoffen",
            "Handige 5-delige set voor meal-prep en restjes",
        ],
        "cons": [
            "Sluitmechanisme vaak eenvoudiger dan klikdeksels",
            "Niet geschikt voor opwarming in de oven",
        ],
        "rating": 3.9,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 44.99,
        "price_last_checked": "2026-07-08",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.wehkamp.nl/bormioli-rocco-frigoverre-vershoudbakjes-frigoverre-glas-blauw-5-delig-16432384/",
        "price_range": "\u20ac\u20ac",
        "verdict": "Een betrouwbare glazen set voor dagelijks gebruik: duurzaam, veelzijdig en ideaal als je een praktische 5-delige glasoplossing zoekt voor bewaren en opwarmen.",
        "award": None,
    },
    "igluu_meal_prep_5delig": {
        "slug": "igluu-meal-prep-5delig",
        "name": "Igluu Meal Prep \u2013 5-delige glazen vershoudset",
        "brand": "Igluu",
        "material": "Borosilicaatglas",
        "capacities": [950, 950, 950, 950, 950],
        "features": ["Lekvrij", "Klikdeksel met siliconen afdichting"],
        "image": "igluu-5delig-rond.webp",
        "image_path": "images/products/vershoudbakjes",
        "description": "Betaalbare en praktische 5-delige set van borosilicaat glas met lekvrije klikdeksels. Ideaal als instapset voor gezond bewaren en opwarmen.",
        "usage": {
            "oven": {"container": True, "lid": False, "note": "Alleen het glazen bakje tot 300 °C"},
            "microwave": {"container": True, "lid": True, "note": "Met deksel het stoomventiel openen"},
            "freezer": {"container": True, "lid": True, "note": "Tot -20 °C"},
            "dishwasher": {"container": True, "lid": False, "note": None},
        },
        "pros": [
            "Vijf gelijke bakjes van 950 ml, handig voor meal-prep",
            "Lekvrije klikdeksels met siliconen afdichting",
            "Betaalbare instapset zonder concessies aan materiaalveiligheid",
        ],
        "cons": [
            "Geen extra grote schaal voor familieporties",
        ],
        "rating": 4.3,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 33.95,
        "price_last_checked": "2026-07-15",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.amazon.nl/Igluu-Meal-Prep-Storage-Containers/dp/B0CJC5BHJZ/",
        "price_range": "\u20ac",
        "verdict": "Een voordelige en complete glazen basisset voor iedereen die PFAS-vrij wil bewaren en opwarmen.",
        "award": None,
        "variant_selectors": [
            {"key": "shape", "label": "Vorm"},
        ],
        "variants": [
            {
                "id": "set-5x950-round",
                "options": {"shape": "round"},
                "option_labels": {"shape": "Rond"},
                "image": "igluu-5delig-rond.webp",
                "image_path": "images/products/vershoudbakjes",
                "capacities": [950, 950, 950, 950, 950],
                "price": 33.95,
                "price_last_checked": "2026-07-24",
                "currency": "EUR",
                "availability": "InStock",
                "affiliate_url": "",
                "retailer_url": "https://www.amazon.nl/Igluu-Meal-Prep-Storage-Containers/dp/B0CJC5BHJZ/",
                "is_default": True,
            },
            {
                "id": "set-5x950-rectangle",
                "options": {"shape": "rectangle"},
                "option_labels": {"shape": "Rechthoek"},
                "image": "igluu-5delig-rechthoek.webp",
                "image_path": "images/products/vershoudbakjes",
                "capacities": [840, 840, 840, 840, 840],
                "price": 38.95,
                "price_last_checked": "2026-07-24",
                "currency": "EUR",
                "availability": "InStock",
                "affiliate_url": "",
                "retailer_url": "https://www.amazon.nl/Igluu-Meal-Prep-Storage-Containers/dp/B07XJ68DCP/",
                "is_default": False,
            },
        ]
    },
    "kitchenbrothers_5delig": {
        "slug": "kitchenbrothers-5delig",
        "name": "KitchenBrothers \u2013 5-delige glazen vershoudset",
        "brand": "KitchenBrothers",
        "material": "Borosilicaatglas",
        "capacities": [1000, 1000, 1000, 1000, 1000],
        "features": ["Luchtdichte klikdeksels"],
        "image": "kitchenbrothers-5delig.webp",
        "image_path": "images/products/vershoudbakjes",
        "description": "Praktische meal-prepset met vijf rechthoekige bakjes van "
        "borosilicaatglas, elk met een inhoud van 1 liter. De luchtdichte "
        "klikdeksels met siliconen afdichting maken de set geschikt voor "
        "voorbereiden, bewaren, invriezen en meenemen van maaltijden.",
        "usage": {
            "oven": {
                "container": True,
                "lid": False,
                "note": "Alleen het glazen bakje; deksel volledig verwijderen",
            },
            "microwave": {
                "container": True,
                "lid": False,
                "note": "Deksel volledig verwijderen voor het opwarmen",
            },
            "freezer": {
                "container": True,
                "lid": True,
                "note": "Geschikt voor temperaturen vanaf -40 °C",
            },
            "dishwasher": {
                "container": True,
                "lid": None,
                "note": "Niet duidelijk voor de deksel",
            },
        },
        "pros": [
            "Vijf gelijke bakjes van 1 liter zijn praktisch voor meal-prepping",
            "Luchtdichte en lekvrije klikdeksels met siliconen afdichting",
            "Borosilicaatglas is goed bestand tegen grote temperatuurverschillen",
        ],
        "cons": [
            "Alle bakjes hebben hetzelfde formaat, waardoor de set minder veelzijdig is",
            "Vijf glazen bakjes nemen relatief veel ruimte en gewicht in",
        ],
        "rating": 4.3,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 25.00,
        "price_last_checked": "2026-07-17",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/kitchenbrothers-meal-prep-bakjes-vershoudbakjes-set-luchtdicht-bpa-vrij-1l-glas-5-stuks/9300000003218666/",
        "price_range": "\u20ac\u20ac",
        "verdict": "Sterke en betaalbare meal-prepset voor vijf volledige maaltijden "
        "in gelijke porties.",
        "award": "💰 Budget keuze",
    },
    "luminarc_purebox_5delig": {
        "slug": "luminarc-purebox-5delig",
        "name": "Luminarc Pure Box Active \u2013 5-delige glazen vershoudset",
        "brand": "Luminarc",
        "material": "Gehard glas",
        "capacities": [760, 820, 920, 1220, 1220],
        "features": ["Ventieldeksel", "Lekvrij"],
        "image": "luminarc-purebox-5delig.webp",
        "image_path": "images/products/vershoudbakjes",
        "description": "Een praktische en sterke 5-delige set van gehard glas met ventieldeksels. Ideaal voor dagelijks bewaren, opwarmen en meenemen dankzij de stevige 4-kliks sluiting.",
        "usage": {
            "oven": {"container": None, "lid": False, "note": None},
            "microwave": {"container": True, "lid": True, "note": "Ventiel openen"},
            "freezer": {"container": None, "lid": None, "note": None},
            "dishwasher": {"container": None, "lid": None, "note": None},
        },
        "pros": [
            "Extra stootbestendig gehard glas",
            "4-kliks sluiting met siliconen ring voor lekvrije opslag",
            "Compacte ronde formaten, makkelijk stapelbaar",
        ],
        "cons": [
            "Ronde vorm minder effici\u00ebnt voor mealprep-stapeling",
            "Niet geschikt voor opwarming in de oven",
        ],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 49.63,
        "price_last_checked": "2026-07-17",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.amazon.nl/-/en/Luminarc-Pure-Box-Active-Containers/dp/B07X9TBHZY/",
        "price_range": "\u20ac\u20ac",
        "verdict": "Een stevige en gebruiksvriendelijke set met uitstekend ventielsysteem voor dagelijks gebruik.",
        "award": None,
    },
    "oxo_good_grips_smart_seal_6delig": {
        "slug": "oxo-good-grips-smart-seal-6delig",
        "name": "OXO Good Grips Smart Seal \u2013 6-delige glazen vershoudset",
        "brand": "Oxo",
        "material": "Borosilicaatglas",
        "capacities": [480, 970, 1730],
        "features": ["Ventieldeksel", "Lekvrij"],
        "image": "glasslock-3delig.jpg",
        "image_path": "images/vershoudbakjes",
        "description": "Een praktische en sterke 3-delige set van gehard glas met ventieldeksels. Ideaal voor dagelijks bewaren, opwarmen en meenemen dankzij de stevige 4-kliks sluiting.",
        "pros": [
            "Extra stootbestendig gehard glas",
            "4-kliks sluiting met siliconen ring voor lekvrije opslag",
            "Compacte ronde formaten, makkelijk stapelbaar",
        ],
        "cons": [
            "Ronde vorm minder effici\u00ebnt voor mealprep-stapeling",
        ],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 41.29,
        "price_last_checked": "2026-07-08",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.amazon.nl/-/en/Glasslock-GL-529-1750ml-Rectangular-Container/dp/B00MX16YKE/",
        "price_range": "\u20ac\u20ac\u20ac",
        "verdict": "Een stevige en gebruiksvriendelijke set met uitstekend ventielsysteem voor dagelijks gebruik.",
        "award": None,
    },
}
