PRODUCTS = {
    # 28CM KOEKENPANNEN
    "greenpan_barcelona_pro_28": {
        "slug": "greenpan-barcelona-pro-28",
        "name": "GreenPan Barcelona Pro",
        "description": "Stevige aluminium koekenpan met Thermolon Infinity Pro-coating, "
        "brede inductiebodem en ovenbestendige RVS greep.",
        "brand": "GreenPan",
        "diameter": 28,
        "material": "Aluminium met keramische antiaanbaklaag",
        "features": ["Geschikt voor inductie", "Ovenbestendig tot 220 °C", ],
        "rating": 4.7,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 91.03,
        "currency": "EUR",
        "price_last_checked": "2026-07-27",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/greenpan-barcelona-pro-koekenpan-met-keramische-antikleeflaag-28-cm/9300000111189161/",
        "award": "🏆 Beste keuze",
        "price_range": "€€€",
        "image": "greenpan-barcelona-pro-28cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Gelijkmatige warmteverdeling",
            "Stevige constructie",
            "Geschikt voor ovengebruik",
        ],
        "cons": [
            "Relatief zwaar",
            "Hogere aanschafprijs",
        ],
        "verdict": "Onze beste allround keuze voor wie een stevige keramische pan "
        "voor dagelijks gebruik zoekt.",
    },

    "kochstar_essenz_28": {
        "slug": "kochstar-essenz-28",
        "name": "Kochstar Essenz",
        "description": "Voordelige aluminium koekenpan met keramische antiaanbaklaag, "
        "koel blijvende greep en geschiktheid voor inductie.",
        "brand": "Kochstar",
        "diameter": 28,
        "material": "Aluminium met keramische antiaanbaklaag",
        "features": ["PFAS-vrij", "Lichtgewicht", ],
        "rating": 4,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 13.99,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/kochstar-essenz-zwart-keramische-koekenpan-28cm-pfas-vrij-inductie-koekenpan-inductie-pan-keramische-anti-aanbaklaag-koelgreep-ovenbestendig-tot-130-c-zwart/9300000231848099/",
        "award": "💰 Budget keuze",
        "price_range": "€",
        "image": "kochstar-essenz-28cm-zwart.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "variants": [
            {
                "name": "Zwart",
                "image": "kochstar-essenz-28cm-zwart.webp",
                "hex": "#000000",
                "affiliate_url": "",
                "retailer_url": "https://www.bol.com/nl/nl/p/kochstar-essenz-zwart-keramische-koekenpan-28cm-pfas-vrij-inductie-koekenpan-inductie-pan-keramische-anti-aanbaklaag-koelgreep-ovenbestendig-tot-130-c-zwart/9300000231848099/",
                "price": 13.99,
                "price_last_checked": "2026-07-27",
            },
            {
                "name": "Taupe",
                "image": "kochstar-essenz-28cm-taupe.webp",
                "hex": "#B8A99A",
                "affiliate_url":"",
                "retailer_url":"https://www.bol.com/nl/nl/p/kochstar-essenz-koekenpan-28cm-pfas-vrij-inductie-pan-keramische-anti-aanbaklaag-koelgreep-taupe/9300000231848102/",
                "price": 14.99,
                "price_last_checked": "2026-07-27",
            },
        ],
        "pros": [
            "Zeer lage aanschafprijs",
            "Licht en gemakkelijk hanteerbaar",
            "Verkrijgbaar in twee kleuren",
        ],
        "cons": [
            "Slechts beperkt ovenbestendig tot 130 °C",
            "Eenvoudigere afwerking dan duurdere modellen",
        ],
        "verdict": "Een toegankelijke budgetkeuze voor licht en regelmatig gebruik.",
    },

    "greenchef_diamond_28": {
        "slug": "greenchef-diamond-28",
        "name": "GreenChef Diamond Induction",
        "description": "PFAS-vrije keramische pan met diamantdeeltjes en hoge slijtvastheid.",
        "brand": "GreenChef",
        "diameter": 28,
        "material": "Aluminium met diamantversterkte keramische antiaanbaklaag",
        "features": ["Diamantcoating", "Duurzaam"],
        "rating": 4.3,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 26.99,
        "price_last_checked": "2026-07-27",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/greenchef-diamond-koekenpan-28cm-zwart-inductie-pfas-vrij/9200000130094499/",
        "price_range": "€€",
        "image": "greenchef-diamond-28cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Diamantversterkte keramische coating",
            "Licht en gemakkelijk hanteerbaar",
            "Eenvoudig schoon te maken",
        ],
        "cons": [
            "Niet ovenbestendig",
        ],
        "verdict": "Een betaalbare middenklassepan voor dagelijks bakken op lage tot middelhoge temperatuur.",
    },

    "bk_easy_induction_28": {
        "slug": "bk-easy-induction-28",
        "name": "BK Easy Induction Ceramic",
        "description": "PFAS-vrije keramische pan met koele greep en stevige bodem.",
        "brand": "BK",
        "diameter": 28,
        "material": "Aluminium met keramische antiaanbaklaag",
        "features": ["Koele greep", "Inductie"],
        "rating": 4.3,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 39.99,
        "price_last_checked": "2026-07-27",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/bk-easy-induction-ceramic-koekenpan-28-cm-pfas-vrij-inductie/9300000032109237/",
        "award": None,
        "price_range": "€€",
        "image": "bk-easy-induction-28cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Goede prijs-kwaliteit",
            "Snelle opwarming",
            "Koele handgreep",
        ],
        "cons": [
            "Niet ovenbestendig",
        ],
        "verdict":  "Een praktische middenklassepan met comfortabele greep "
        "en een toegankelijke prijs.",
    },

    "brabantia_dusk_28": {
        "slug": "brabantia-dusk-28",
        "name": "Brabantia Dusk",
        "description": "Moderne keramische PFAS-vrije pan met stijlvolle afwerking.",
        "brand": "Brabantia",
        "diameter": 28,
        "material": "Aluminium met keramische antiaanbaklaag",
        "features": ["PFAS-vrij", "Stevige bodem"],
        "rating": 4.2,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 30.00,
        "price_last_checked": "2026-07-27",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/brabantia-dusk-r-ns-koekenpan-o-28cm-100-pfas-vrij/9300000225842102/",
        "price_range": "€€",
        "image": "brabantia-dusk-28cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Stevige inductiebodem",
            "Comfortabele greep",
            "Verzorgde, moderne afwerking",
        ],
        "cons": [
            "Niet vaatwasserbestendig",
        ],
        "verdict": "Een aantrekkelijke keuze voor wie functionaliteit en een moderne vormgeving wil combineren.",
    },

    "tefal_renew_28": {
        "slug": "tefal-renew-28",
        "name": "Tefal Renew+",
        "description": "Gemaakt van 100% gerecycled aluminium met PFAS-vrije laag.",
        "brand": "Tefal",
        "diameter": 28,
        "material": "Gerecycled aluminium met keramische antiaanbaklaag",
        "features": ["Gerecycled aluminium", "Thermo-Signal"],
        "rating": 4.2,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 38.99,
        "price_last_checked": "2026-07-27",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/tefal-renew-koekenpan-o28-cm-keramisch-pfas-vrij-geschikt-voor-inductie/9300000118641472/",
        "award": "",
        "price_range": "€€",
        "image": "tefal-renew-28cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Duurzaam gerecycled materiaal",
            "Goede warmtegeleiding",
            "Thermo-Signal-hitte-indicator",
        ],
        "cons": [
            "Niet ovenbestendig",
        ],
        "verdict": "Een gebruiksvriendelijke keuze voor wie een keramische Tefal-pan "
    "met hitte-indicator zoekt.",
    },

    "bk_enjoy_28": {
        "slug": "bk-enjoy-28",
        "name": "BK Enjoy",
        "description": "Lichtgewicht aluminium koekenpan met keramische antiaanbaklaag "
        "voor dagelijks gebruik.",
        "brand": "BK",
        "diameter": 28,
        "material": "Aluminium met keramische antiaanbaklaag",
        "features": ["Lichtgewicht", "Eenvoudig schoon te maken"],
        "rating": 4.1,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 34.90,
        "price_last_checked": "2026-07-27",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://bk.nl/products/enjoy-koekenpan-zwart-28-cm?srsltid=AfmBOoqIJ-LNGVZmMJZThGeFbB_cW7XcZXFB0rnlbkDqbVjERLMNIpFY",
        "price_range": "€€",
        "image": "bk-enjoy-28cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Licht van gewicht",
            "Goede warmtegeleiding",
            "Gemakkelijk schoon te maken",
        ],
        "cons": [
            "Niet geschikt voor oven",
        ],
        "verdict": "Een lichte en praktische pan voor dagelijks gezond koken.",
    },

    "demeyere_alu_pro_5_28": {
        "slug": "demeyere-alu-pro-5-28",
        "name": "Demeyere Alu Pro 5 Ceraforce",
        "description": "Stevige aluminium koekenpan met Ceraforce keramische coating "
        "en een dikke bodem voor stabiele warmteverdeling.",
        "brand": "Demeyere",
        "diameter": 28,
        "material": "Aluminium met Ceraforce keramische antiaanbaklaag",
        "features": [
            "Ceraforce keramische coating",
            "Geschikt voor inductie",
            "Dikke aluminium bodem",
        ],
        "rating": 4.6,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 85.00,
        "price_last_checked": "2026-07-27",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/demeyere-12628-alu-pro-5-ceraforce-antikleef-bakpan-28-cm/9300000032747130/",
        "award": "💎 Premium keuze",
        "price_range": "€€€€",
        "image": "demeyere-alu-pro-5-ceraforce-28cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Hoge aanschafprijs",
            "Relatief zwaar",
        ],
        "cons": [
            "Hogere prijsklasse",
            "Relatief zwaar",
        ],
        "verdict": "Onze premium keuze voor wie bouwkwaliteit en stabiele "
        "warmteverdeling belangrijker vindt dan een lage prijs.",
    },

    "debuyer_ceranoa_28": {
        "slug": "debuyer-ceranoa-28",
        "name": "De Buyer Ceranoa",
        "description": "Hoogwaardige keramische pan zonder PFAS met ergonomische greep.",
        "brand": "De Buyer",
        "diameter": 28,
        "material": "Aluminium met keramische antiaanbaklaag",
        "features": ["PFAS-vrij", "Premium afwerking"],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 105.00,
        "price_last_checked": "2026-07-27",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/debuyer-ceranoa-koekenpan-28cm/9300000232243696/",
        "price_range": "€€€€",
        "image": "debuyer-ceranoa-28cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Gelijkmatige warmteverdeling",
            "Hoogwaardig afgewerkte keramische antiaanbaklaag"
            "Ergonomisch handvat",
        ],
        "cons": [
            "Hoge aanschafprijs",
            "Niet vaatwasserbestendig",
        ],
        "verdict": "Een hoogwaardig afgewerkte pan voor wie ergonomie en een stevige constructie vooropstelt.",
    },

    "greenpan_mayflower_28": {
        "slug": "greenpan-mayflower-28",
        "name": "GreenPan Mayflower",
        "description": "Stijlvolle keramische koekenpan met PFAS-vrije Thermolon™ coating en inductiebodem.",
        "brand": "GreenPan",
        "diameter": 28,
        "material": "Aluminium met Thermolon keramische antiaanbaklaag",
        "features": [
            "Thermolon™ PFAS-vrije coating",
            "Geschikt voor inductie",
            "Goede warmteverdeling",
        ],
        "rating": 4.4,
        "rating_count": None,
        "rating_source": "editorial",
        "currency": "EUR",
        "availability": "InStock",
        "award": "",
        "price_range": "€€-€€€",
        "image": "greenpan-mayflower-28cm.jpg",
        "image_path": "images/products/keramische-koekenpannen",
        "variants": [
            {
                "name": "Grijs",
                "image": "greenpan-mayflower-grijs-28cm.webp",
                "hex": "#3F4448",
                "affiliate_url": "",
                "retailer_url": "https://www.bol.com/nl/nl/p/greenpan-mayflower-pro-koekenpan-28cm-grijs-inductie-pfas-vrij/9300000091450190/",
                "price": 59.90,
                "price_last_checked": "2026-07-27",
                "price_range": "€€€",
            },
            {
                "name": "Blauw",
                "image": "greenpan-mayflower-blauw-28cm.webp",
                "hex": "#8CA9B5",
                "affiliate_url":"",
                "retailer_url": "https://www.bol.com/nl/nl/p/greenpan-mayflower-koekenpan-o28-cm-inductie-anti-aanbak-pfas-vrij/9300000001596267/",
                "price": 42.99,
                "price_last_checked": "2026-07-27",
                "price_range": "€€",
            },
        ],
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/greenpan-mayflower-pro-koekenpan-28cm-grijs-inductie-pfas-vrij/9300000091450190/",
        "pros": [
            "PFAS-vrije Thermolon™ coating",
            "Goede warmteverdeling",
            "Aantrekkelijk design",
        ],
        "cons": [
            "Niet geschikt voor ovengebruik",
            "Prijs verschilt duidelijk per kleurvariant",
        ],
        "verdict": "Betrouwbare keuze voor milieubewuste gebruiker die stijl en gezond koken combineert.",
    },

    # 24CM KOEKENPANNEN
    "greenpan_barcelona_pro_24": {
        "slug": "greenpan-barcelona-pro-24",
        "name": "GreenPan Barcelona Pro",
        "description": "Stevige aluminium koekenpan met Thermolon Infinity Pro-coating, "
        "inductiebodem en ovenbestendige RVS greep.",
        "brand": "GreenPan",
        "diameter": 24,
        "material": "Aluminium met Thermolon keramische antiaanbaklaag",
        "features": ["Geschikt voor inductie",
                    "Ovenbestendig tot 220 °C",],
        "rating": 4.7,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 79.29,
        "price_last_checked": "2026-07-27",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/greenpan-barcelona-pro-bakpan-24cm/9300000117606007/",
        "award": "🏆 Beste keuze",
        "price_range": "€€€",
        "image": "greenpan-barcelona-pro-24cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Gelijkmatige warmteverdeling",
            "Stevige constructie",
            "Geschikt voor ovengebruik",
        ],
        "cons": [
            "Relatief zwaar",
            "Hogere aanschafprijs",
        ],
        "verdict":  "Onze beste allround keuze voor wie een stevige keramische pan "
        "voor dagelijks gebruik zoekt.",
    },

    "kochstar_essenz_24": {
        "slug": "kochstar-essenz-24",
        "name": "Kochstar Essenz",
        "description": "Voordelige aluminium koekenpan met keramische antiaanbaklaag, "
        "koel blijvende greep en geschiktheid voor inductie.",
        "brand": "Kochstar",
        "diameter": 24,
        "material": "Aluminium met keramische antiaanbaklaag",
        "features": ["PFAS-vrij", "Lichtgewicht", ],
        "rating": 4,
        "rating_count": None,
        "rating_source": "editorial",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/kochstar-essenz-koekenpan-24cm-pfas-vrij-inductie-pan-keramische-anti-aanbaklaag-koelgreep-zwart/9300000231848093/",
        "award": "💰 Budget keuze",
        "price_range": "€",
        "image": "koekenpan02_kochstar_essenz_24cm.jpg",
        "image_path": "images/products/keramische-koekenpannen",
        "variants": [
            {
                "name": "Zwart",
                "image": "kochstar-essenz-zwart-24cm.webp",
                "hex": "#000000",
                "affiliate_url": "",
                "retailer_url": "https://www.bol.com/nl/nl/p/kochstar-essenz-koekenpan-24cm-pfas-vrij-inductie-pan-keramische-anti-aanbaklaag-koelgreep-zwart/9300000231848093/",
                "price": 11.99,
                "price_last_checked": "2026-07-27",
            },
            {
                "name": "Taupe",
                "image": "kochstar-essenz-taupe-24cm.webp",
                "hex": "#B8A99A",
                "affiliate_url":"",
                "retailer_url": "https://www.bol.com/nl/nl/p/kochstar-essenz-koekenpan-24cm-pfas-vrij-inductie-pan-keramische-anti-aanbaklaag-koelgreep-taupe/9300000231848096/",
                "price": 11.99,
                "price_last_checked": "2026-07-27",
            },
        ],
        "pros": [
            "Zeer lage aanschafprijs",
            "Licht en gemakkelijk hanteerbaar",
            "Verkrijgbaar in twee kleuren",
        ],
        "cons": [
            "Eenvoudigere afwerking",
            "Beperkte ovenbestendigheid",
        ],
        "verdict":  "Een toegankelijke budgetkeuze voor licht en regelmatig gebruik.",
    },

    "demeyere_alu_pro_5_ceraforce_24": {
        "slug": "demeyere-alu-pro-5-ceraforce-24",
        "name": "Demeyere Alu Pro 5 Ceraforce",
        "description": "Stevige aluminium koekenpan met Ceraforce keramische coating "
        "en een dikke bodem voor stabiele warmteverdeling.",
        "brand": "Demeyere",
        "diameter": 24,
        "material": "Aluminium met Ceraforce keramische antiaanbaklaag",
        "features": ["Ceraforce keramische coating",
                    "Geschikt voor inductie",
                    "Stevige aluminium constructie",],
        "rating": 4.6,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 77.00,
        "price_last_checked": "2026-07-27",
        "price_range": "€€€",
        "currency": "EUR",
        "availability": "InStock",
        "image": "demeyere-alu-pro-5-ceraforce-24cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/demeyere-12624-alu-pro-5-ceraforce-bakpan-antikleef-24-cm/9300000032747131/",
        "award": "💎 Premium keuze",
        "pros": [
            "Gelijkmatige warmteverdeling",
            "Stevige afwerking",
            "Geschikt voor intensief dagelijks gebruik",
        ],
        "cons": [
            "Relatief zwaar",
            "Hoge aanschafprijs",
        ],
        "verdict": "Onze premium keuze voor wie stevige bouwkwaliteit en stabiele "
        "warmteverdeling belangrijk vindt.",
    },

    "greenchef_diamond_24": {
        "slug": "greenchef-diamond-24",
        "name": "GreenChef Diamond Induction",
        "description": "Aluminium koekenpan met diamantversterkte keramische "
        "antiaanbaklaag voor dagelijks gebruik.",
        "brand": "GreenChef",
        "diameter": 24,
        "material": "Aluminium met diamantversterkte keramische antiaanbaklaag",
        "features": ["Diamantversterkte keramische coating",
                    "Geschikt voor inductie",],
        "rating": 4.2,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 23.99,
        "price_last_checked": "2026-07-27",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/greenchef-diamond-inductie-koekenpan-o24-cm-keramisch-pfas-vrij-best-getest/9200000130094485/",
        "price_range": "€",
        "image": "greenchef-diamond-24cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Licht en gemakkelijk hanteerbaar",
            "Eenvoudig schoon te maken",
            "Scherpe prijs",
        ],
        "cons": [
            "Niet ovenbestendig",
        ],
        "verdict": "Een betaalbare keramische pan voor dagelijks bakken op lage tot "
        "middelhoge temperaturen.",
    },

    "bk_easy_induction_24": {
        "slug": "bk-easy-induction-24",
        "name": "BK Easy Induction Ceramic",
        "description": "PFAS-vrije keramische pan met koele greep en stevige bodem.",
        "brand": "BK",
        "diameter": 24,
        "material": "Aluminium met keramische antiaanbaklaag",
        "features": ["Koele greep", "Inductie"],
        "rating": 4.3,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 33.95,
        "price_last_checked": "2026-07-27",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/bk-easy-induction-ceramic-koekenpan-o24-cm-pfas-vrij/9300000032891762/",
        "price_range": "€€",
        "award": "🥇 Meest gekozen",
        "image": "bk-easy-induction-24cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Goede prijs-kwaliteit",
            "Snelle opwarming",
            "Koele handgreep",
        ],
        "cons": [
            "Niet ovenbestendig",
        ],
        "verdict": "Een praktische middenklassepan met comfortabele greep "
        "en een toegankelijke prijs.",
    },

    "greenpan_torino_24": {
        "slug": "greenpan-torino-24",
        "name": "GreenPan Torino",
        "description": "Lichte aluminium koekenpan met Thermolon keramische antiaanbaklaag "
        "voor dagelijks gebruik.",
        "brand": "GreenPan",
        "diameter": 24,
        "material": "Aluminium met Thermolon keramische antiaanbaklaag",
        "features": ["Inductie", "PFAS-vrij"],
        "rating": 4.3,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 39.60,
        "price_last_checked": "2026-07-27",
        "currency": "EUR",
        "availability": "InStock",
        "price_range": "€€",
        "image": "greenpan-torino-24cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/greenpan-torino-keramische-koekenpan-24-cm/9300000036288442/",
        "pros": [
            "Licht en gemakkelijk hanteerbaar",
            "Geschikt voor inductie",
            "Eenvoudig schoon te maken",
        ],
        "cons": [
            "Beperkte ovenbestendigheid",
            "Eenvoudigere constructie dan de Barcelona Pro-serie",
        ],
        "verdict": "Een toegankelijke middenklassepan voor dagelijks gebruik en "
        "kleinere maaltijden.",
    },

    "tefal_renew_24": {
        "slug": "tefal-renew-24",
        "name": "Tefal Renew+",
        "description": "Koekenpan van 100% gerecycled aluminium met keramische antiaanbaklaag "
        "en geïntegreerde hitte-indicator.",
        "brand": "Tefal",
        "diameter": 24,
        "material": "Gerecycled aluminium met keramische antiaanbaklaag",
        "features": ["Gerecycled aluminium",
                    "Hitte-indicator",],
        "rating": 4.2,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 35.99,
        "price_last_checked": "2026-07-27",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/tefal-renew-keramische-koekenpan-o-24-cm/9300000118641479/",
        "price_range": "€€",
        "award": "",
        "image": "tefal-renew-24cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Pan van gerecycled materiaal",
            "Goede warmtegeleiding",
            "Handige hitte-indicator",
        ],
        "cons": [
            "Niet ovenbestendig",
        ],
        "verdict": "Een gebruiksvriendelijke keuze voor wie een keramische Tefal-pan "
        "met hitte-indicator zoekt.",
    },

    "bk_enjoy_24": {
        "slug": "bk-enjoy-24",
        "name": "BK Enjoy",
        "description": "Lichtgewicht aluminium koekenpan met keramische antiaanbaklaag "
        "voor dagelijks gebruik.",
        "brand": "BK",
        "diameter": 24,
        "material": "Aluminium met keramische antiaanbaklaag",
        "features": ["Lichtgewicht", "Eenvoudig schoon te maken"],
        "rating": 4.1,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 29.90,
        "price_last_checked": "2026-07-27",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.kookexpert.nl/koekenpan-bk-enjoy-met-keramische-antikleeflaag-24-cm.html",
        "price_range": "€€",
        "image": "bk-enjoy-24cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Licht en gemakkelijk hanteerbaar",
            "Goede warmtegeleiding",
            "Eenvoudig schoon te maken",
        ],
        "cons": [
            "Niet geschikt voor oven",
        ],
        "verdict": "Een lichte en praktische koekenpan voor eenvoudig dagelijks gebruik.",
    },

    "ikea_hemlagad_keramisch_24": {
        "slug": "ikea-hemlagad-keramisch-24",
        "name": "IKEA HEMLAGAD",
        "description": "Voordelige aluminium koekenpan met keramische antiaanbaklaag "
        "voor kleinere dagelijkse bereidingen.",
        "brand": "IKEA",
        "diameter": 24,
        "material": "Aluminium met keramische antiaanbaklaag",
        "features": [
            "Geschikt voor inductie",
            "Keramische antiaanbaklaag",
        ],
        "rating": 3.9,
        "rating_count": None,
        "rating_source": "editorial",
        "price_range": "€",
        "price": 9.99,
        "price_last_checked": "2026-07-27",
        "currency": "EUR",
        "availability": "InStock",
        "image": "ikea-hemlagad-keramisch-24cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "affiliate_url": "",
        "retailer_url": "https://www.ikea.com/nl/nl/p/hemlagad-koekenpan-antiaanbaklaag-zwart-60580893/",
        "pros": [
            "Zeer lage aanschafprijs",
            "Geschikt voor inductie",
            "Licht en eenvoudig in gebruik",
        ],
        "cons": [
            "Eenvoudigere constructie dan duurdere modellen",
        ],
        "verdict": "Een zeer voordelige keuze voor licht dagelijks gebruik en kleinere porties.",
    },

    "berndes_b_green_24": {
        "slug": "berndes-b-green-24",
        "name": "Berndes B.Green",
        "description":  "Een veelzijdige midden-premiumpan voor wie gerecycled aluminium "
        "en brede gebruiksmogelijkheden belangrijk vindt.",
        "brand": "Berndes",
        "diameter": 24,
        "material": "Gerecycled aluminium met b.nature kwarts-antiaanbaklaag",
        "features": ["b.nature kwarts-coating", "Inductie", "100% gerecycled aluminium", "Ovenbestendig", "Vaatwasserbestendig"],
        "rating": 4.4,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 64.99,
        "price_last_checked": "2026-07-27",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/b-green-koekenpan-24-cm-berndes/9300000006419832/",
        "award": None,
        "price_range": "€€€",
        "image": "berndes-b-green-24cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Pan gemaakt van gerecycled aluminium",
            "Specifieke b.nature kwartscoating",
            "Geschikt voor inductie",       
        ],
        "cons": [
            "Hogere aanschafprijs",
            "Beperkte ovenbestendigheid",
        ],
        "verdict": "Milieuvriendelijke keuze voor wie echt PFAS-vrij wil koken met een coating van volledig natuurlijke grondstoffen.",
    },

    # 26CM KOEKENPANNEN
    "greenpan_barcelona_pro_26": {
        "slug": "greenpan-barcelona-pro-26",
        "name": "GreenPan Barcelona Pro",
        "description": "Stevige aluminium koekenpan met Thermolon keramische "
        "antiaanbaklaag, inductiebodem en ovenbestendige RVS greep.",
        "brand": "GreenPan",
        "diameter": 26,
        "material": "Aluminium met Thermolon keramische antiaanbaklaag",
        "features": ["Geschikt voor inductie",
                    "Ovenbestendig tot 220 °C",],
        "rating": 4.7,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 79.90,
        "price_last_checked": "2026-07-27",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/greenpan-barcelona-pro-koekenpan-met-keramische-antikleeflaag-26-cm/9300000112544367/",
        "award": "🏆 Beste keuze",
        "price_range": "€€€",
        "image": "greenpan-barcelona-pro-26cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Gelijkmatige warmteverdeling",
            "Stevige constructie",
            "Geschikt voor ovengebruik",
        ],
        "cons": [
            "Relatief zwaar",
            "Hogere aanschafprijs",
        ],
        "verdict": "Onze beste allround keuze voor wie een stevige en veelzijdige "
    "keramische koekenpan zoekt.",
    },

    "greenchef_vintage_26": {
        "slug": "greenchef-vintage-26",
        "name": "GreenChef Vintage",
        "description": "Aluminium koekenpan met keramische antiaanbaklaag en "
        "een herkenbare vintage afwerking.",
        "brand": "GreenChef",
        "diameter": 26,
        "material": "Aluminium met keramische antiaanbaklaag",
        "features": [
            "Geschikt voor inductie",
            "Vintage afwerking",
        ],
        "rating": 4.3,
        "rating_count": None,
        "rating_source": "editorial",
        "price_range": "€€",
        "price": 42.90,
        "price_last_checked": "2026-07-27",
        "currency": "EUR",
        "availability": "InStock",
        "image": "greenchef-vintage-26cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/greenchef-vintage-koekenpan-26cm-zwart-inductie-pfas-vrij/9200000130094513/",
        "award": None,
        "pros": [
            "Aantrekkelijke vormgeving",
            "Geschikt voor inductie",
            "Toegankelijke middenklasseprijs",
        ],
        "cons": [
            "Eenvoudigere afwerking dan premium modellen",
        ],
        "verdict": "Een toegankelijke middenklassepan die een aantrekkelijke vormgeving "
    "combineert met dagelijks gebruiksgemak.",
    },

    "demeyere_alu_pro_5_ceraforce_26": {
        "slug": "demeyere-alu-pro-5-ceraforce-26",
        "name": "Demeyere Alu Pro 5 Ceraforce",
        "description": "Stevige aluminium koekenpan met Ceraforce keramische "
        "antiaanbaklaag en een bodem voor stabiele warmteverdeling.",
        "brand": "Demeyere",
        "diameter": 26,
        "material": "Aluminium met Ceraforce keramische antiaanbaklaag",
        "features": ["Geschikt voor inductie",
                    "Ceraforce keramische coating",],
        "rating": 4.6,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 83.00,
        "price_last_checked": "2026-07-27",
        "price_range": "€€€",
        "currency": "EUR",
        "availability": "InStock",
        "image": "demeyere-alu-pro-5-ceraforce-26cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/demeyere-alu-pro-ceraforce-koekenpan-26-cm/9300000045881510/",
        "award": "💎 Premium keuze",
        "pros": [
            "Gelijkmatige warmteverdeling",
            "Stevige afwerking",
            "Geschikt voor intensief dagelijks gebruik",
        ],
        "cons": [
            "Relatief zwaar",
            "Hoge aanschafprijs",
        ],
        "verdict": "Onze premium keuze voor wie stevige bouwkwaliteit en stabiele "
    "warmteverdeling belangrijk vindt.",
    },

    "bk_easy_induction_26": {
        "slug": "bk-easy-induction-26",
        "name": "BK Easy Induction Ceramic",
        "description": "Aluminium koekenpan met keramische antiaanbaklaag, "
        "koel blijvende greep en stevige inductiebodem.",
        "brand": "BK",
        "diameter": 26,
        "material": "Aluminium met keramische antiaanbaklaag",
        "features": ["Geschikt voor inductie",
                    "Ovenbestendig tot 160 °C"],
        "rating": 4.3,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 37.95,
        "price_last_checked": "2026-07-27",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/bk-easy-induction-ceramic-koekenpan-o26-cm-inductie-pfas-vrij/9300000032891766/",
        "price_range": "€€",
        "award": "💰 Budget keuze",
        "image": "bk-easy-induction-26cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Snelle en gelijkmatige opwarming",
            "Koel blijvende handgreep",
            "Geschikt voor oven en vaatwasser",
        ],
        "cons": [
             "Beperkt tot maximaal 160 °C in de oven",
        ],
        "verdict": "Een betaalbare allrounder met comfortabele greep en bruikbare "
        "ovenbestendigheid.",
    },

    "fissler_essential_26": {
        "slug": "fissler-essential-26",
        "name": "Fissler Essential",
        "description": (
            "Aluminium koekenpan met keramische antiaanbaklaag, "
            "Essential-inductiebodem en een gladde binnenzijde die eenvoudig "
            "schoon te maken is."
        ),
        "brand": "Fissler",
        "diameter": 26,
        "material": (
            "100% gerecycled aluminium met keramische antiaanbaklaag"
        ),
        "features": [
            "Geschikt voor inductie",
            "Essential-inductiebodem",
            "Ergonomische kunststof handgreep",
        ],
        "rating": 4.3,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 53.99,
        "price_last_checked": "2026-07-30",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/fissler-essential-koekenpan-26cm/9300000233111085/",
        "award": "",
        "price_range": "€€€",
        "image": "fissler-essential-26cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Gelijkmatige warmteverdeling",
            "Eenvoudig schoon te maken",
            "Comfortabele handgreep",
        ],
        "cons": [
            "Minder geschikt voor kookplaten met een zeer hoog vermogen",
            "Kunststof handgreep beperkt de inzetbaarheid in de oven",
        ],
        "verdict": (
            "Een gebruiksvriendelijke middenklassepan met eenvoudige reiniging "
            "en een keramische antiaanbaklaag."
        ),
    },
    "greenpan_venice_pro_26": {
        "slug": "greenpan-venice-pro-26",
        "name": "GreenPan Venice Pro Ceramic",
        "description": "Hard-geanodiseerde aluminium koekenpan met diamantversterkte "
        "keramische antiaanbaklaag en ovenbestendige RVS greep.",
        "brand": "GreenPan",
        "diameter": 26,
        "material": "Hard-geanodiseerd aluminium met diamantversterkte "
    "keramische antiaanbaklaag",
        "features": [
            "Geschikt voor inductie",
            "Ovenbestendige RVS greep",
            "Vaatwasserbestendig; handwas aanbevolen",
        ],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 99.90,
        "price_last_checked": "2026-07-27",
        "currency": "EUR",
        "availability": "InStock",
        "price_range": "€€€€",
        "image": "greenpan-venice-pro-26cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "affiliate_url": "",
        "retailer_url": "https://greenpan.nl/products/venice-pro-koekenpan-26cm",
        "pros": [
            "Stevig hard-geanodiseerd panlichaam",
            "Geschikt voor ovengebruik",
            "Gelijkmatige warmteverdeling",
        ],
        "cons": [
            "Relatief zwaar",
            "Hoge aanschafprijs",
        ],
        "verdict": "Een stevige premiumoptie voor wie ovengebruik, een RVS greep "
    "en een hard-geanodiseerde pan waardeert.",
    },
    "scanpan_nura_26": {
        "slug": "scanpan-nura-26",
        "name": "Scanpan Nura",
        "description": (
            "Meerlaagse stalen koekenpan met Stratanium Leap keramische "
            "antiaanbaklaag en een ovenbestendige RVS handgreep."
        ),
        "brand": "Scanpan",
        "diameter": 26,
        "material": (
            "Meerlaags staal met Stratanium Leap keramische antiaanbaklaag"
        ),
        "features": [
            "Geschikt voor alle warmtebronnen",
            "Ovenbestendig tot 250 °C",
            "Vaatwasserbestendig",
        ],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": None,
        "price_last_checked": None,
        "currency": "EUR",
        "availability": None,
        "availability_label": "Nog niet algemeen verkrijgbaar",
        "affiliate_url": "",
        "official_url": "https://www.scanpan.eu/shop/28-cm-fry-pan-nura/26cm",
        "award": "",
        "price_range": None,
        "image": "scanpan-nura-26cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Stevige meerlaagse staalconstructie",
            "Geschikt voor ovengebruik tot 250 °C",
            "Geschikt voor alle gangbare warmtebronnen",
        ],
        "cons": [
            "Relatief zwaar met een gewicht van circa 1,33 kg",
            "Nog niet algemeen verkrijgbaar in Nederland",
        ],
        "verdict": (
            "Een veelzijdige premiumoptie met brede inzetbaarheid, "
            "maar voorlopig nog beperkt verkrijgbaar."
        ),
    },

    # 20CM KOEKENPANNEN

    "greenpan_barcelona_pro_20": {
        "slug": "greenpan-barcelona-pro-20",
        "name": "GreenPan Barcelona Pro",
        "description": "Hoogwaardige keramische PFAS-vrije pan met Thermolon Infinity Pro-coating en inductiebodem.",
        "brand": "GreenPan",
        "diameter": 20,
        "material": "Keramisch",
        "features": ["Inductie", "Ovenbestendig", ],
        "rating": 5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 69.06,
        "price_last_checked": "2026-07-27",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "?cid=1766379753550-4526062311539&bltgh=44069767-9921-4f7f-9122-4609e5ee2e20.ProductList_Middle.0.ProductTitle",
        "retailer_url": "https://www.bol.com/nl/nl/p/greenpan-barcelona-pro-bakpan-20cm/9300000118067708/"
        "award": "🏆 Beste keuze",
        "price_range": "€€€",
        "image": "greenpan-barcelona-pro-20cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "PFAS-vrij Thermolon-coating",
            "Uitstekende warmteverdeling",
            "Ovenbestendig tot 220 °C",
        ],
        "cons": [
            "Vrij zwaar",
            "Hogere prijs",
        ],
        "verdict": "De ultieme keuze voor wie dagelijks gezond en PFAS-vrij wil koken.",
    },

    "kochstar_essenz_20": {
        "slug": "kochstar-essenz-20",
        "name": "Kochstar Essenz",
        "description": "Betaalbare PFAS-vrije keramische pan voor dagelijks gebruik.",
        "brand": "Kochstar",
        "diameter": 20,
        "material": "Keramisch",
        "features": ["PFAS-vrij", "Lichtgewicht", ],
        "rating": 4,
        "rating_count": None,
        "rating_source": "editorial",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/kochstar-essenz-koekenpan-20cm-pfas-vrij-inductie-pan-keramische-anti-aanbaklaag-koelgreep-zwart/9300000231848104/?cid=1766379984042-5119684659337&bltgh=9b39677e-d58b-40f0-a878-a7ecdf087af8.ProductList_Middle.0.ProductImage",
        "award": "💰 Budget keuze",
        "price_range": "€",
        "image": "koekenpan02_kochstar_essenz_20cm.jpg",
        "image_path": "images/products/keramische-koekenpannen",
        "variants": [
            {
                "name": "Zwart",
                "image": "kochstar-essenz-zwart-20cm.webp",
                "hex": "#000000",
                "affiliate_url": "https://www.bol.com/nl/nl/p/kochstar-essenz-koekenpan-20cm-pfas-vrij-inductie-pan-keramische-anti-aanbaklaag-koelgreep-zwart/9300000231848104/",
                "price": 8.99,
                "price_last_checked": "2026-07-27",
            },
            {
                "name": "Taupe",
                "image": "kochstar-essenz-taupe-20cm.webp",
                "hex": "#B8A99A",
                "affiliate_url":"https://www.bol.com/nl/nl/p/kochstar-essenz-koekenpan-20cm-pfas-vrij-inductie-pan-keramische-anti-aanbaklaag-koelgreep-taupe/9300000231848112/",
                "price": 8.99,
                "price_last_checked": "2026-07-27",
            },
        ],
        "pros": [
            "Goede prijs-kwaliteit",
            "PFAS-vrij",
            "Snel warm",
        ],
        "cons": [
            "Niet ovenbestendig",
            "Kortere levensduur",
        ],
        "verdict": "Een uitstekende keuze voor wie betaalbaar PFAS-vrij wil koken.",
    },

    "demeyere_alu_pro_5_ceraforce_20": {
        "slug": "demeyere-alu-pro-5-ceraforce-20",
        "name": "Demeyere Alu Pro 5 Ceraforce",
        "description": "Hoogwaardige premium koekenpan met PFAS-vrije Ceraforce® keramische coating.",
        "brand": "Demeyere",
        "diameter": 20,
        "material": "Keramisch (Ceraforce®)",
        "features": ["Inductie", "PFAS-vrij", "Professionele kwaliteit"],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 72.25,
        "price_last_checked": "2026-07-27",
        "price_range": "€€€€",
        "currency": "EUR",
        "availability": "InStock",
        "image": "demeyere-alu-pro-5-ceraforce-20cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "affiliate_url": "https://www.bol.com/nl/nl/p/demeyere-12620-alu-pro-5-ceraforce-bakpan-antikleef-20-cm/9300000035395887/?s2a=&bltgh=vBPmUIfEwQiHh3ga2R1Fww.4_74_75.76.FeatureListItem#productTitle",
        "award": "💎 Premium keuze",
        "pros": [
            "PFAS-vrije Ceraforce® keramische coating",
            "Zeer stabiele en gelijkmatige warmteverdeling",
            "Uitstekend geschikt voor inductie",
        ],
        "cons": [
            "Zwaarder dan gemiddelde keramische pannen",
            "Hoger prijsniveau",
        ],
        "verdict": "De beste premium keuze voor wie een duurzame, PFAS-vrije keramische koekenpan van 24 cm zoekt met professionele prestaties.",
    },

    "greenchef_diamond_20": {
        "slug": "greenchef-diamond-20",
        "name": "GreenChef Diamond Induction",
        "description": "PFAS-vrije keramische pan met diamantdeeltjes en hoge slijtvastheid.",
        "brand": "GreenChef",
        "diameter": 20,
        "material": "Keramisch",
        "features": ["Diamantcoating", "Duurzaam"],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 23.39,
        "price_last_checked": "2026-07-28",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/greenchef-diamond-koekenpan-20cm-zwart-inductie-pfas-vrij/9200000130094501/?cid=1766380314980-2767784476758&bltgh=5ffdbb59-a081-4721-acd2-2cae85acec26.ProductList_Middle.0.ProductImage",
        "price_range": "€€",
        "image": "greenchef-diamond-20cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Extra duurzame diamantcoating",
            "Goede hitteverdeling",
            "Gemakkelijk schoon te maken",
        ],
        "cons": [
            "Niet ovenbestendig",
        ],
        "verdict": "Solide keuze voor wie een betrouwbare en duurzame keramische pan zoekt.",
    },

    "bk_easy_induction_20": {
        "slug": "bk-easy-induction-20",
        "name": "BK Easy Induction Ceramic",
        "description": "PFAS-vrije keramische pan met koele greep en stevige bodem.",
        "brand": "BK",
        "diameter": 20,
        "material": "Keramisch",
        "features": ["Koele greep", "Inductie"],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 28.95,
        "price_last_checked": "2026-07-28",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/bk-easy-induction-ceramic-koekenpan-o20-cm-pfas-vrij/9300000032891763/?cid=1766380483899-7763794392492&bltgh=721b099c-fcb4-4086-b787-280ca02ac2e5.ProductList_Middle.0.ProductImage",
        "price_range": "€€",
        "award": "🥇 Meest gekozen",
        "image": "bk-easy-induction-20cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Goede prijs-kwaliteit",
            "Snelle opwarming",
            "Koele handgreep",
        ],
        "cons": [
            "Niet ovenbestendig",
        ],
        "verdict": "Praktische pan voor dagelijks gebruik met betrouwbare antiaanbaklaag.",
    },

    "greenpan_mayflower_20": {
        "slug": "greenpan-mayflower-20",
        "name": "GreenPan Mayflower",
        "description": "Stijlvolle keramische koekenpan met PFAS-vrije Thermolon™ coating.",
        "brand": "GreenPan",
        "diameter": 20,
        "material": "Keramisch (Thermolon™)",
        "features": [
            "Goede warmteverdeling",
            "Geschikt voor inductie",
        ],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 41.99,
        "price_last_checked": "2026-07-28",
        "currency": "EUR",
        "availability": "InStock",
        "price_range": "€€",
        "image": "greenpan-mayflower-grijs-20cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "affiliate_url": "https://www.bol.com/nl/nl/p/greenpan-mayflower-pro-koekenpan-20cm-grijs-inductie-pfas-vrij/9300000091450193/?cid=1766382322505-6956927587708&bltgh=9fc57af3-7cb6-445b-b40b-8d49fe92c203.ProductList_Middle.0.ProductImage",
        "pros": [
            "Thermolon™ keramische coating",
            "Goede warmteverdeling",
            "Aantrekkelijk design",
        ],
        "cons": [
            "Minder robuust dan premium GreenPan-lijnen",
            "Geen ovenbestendige greep",
        ],
        "verdict": "Betrouwbare keuze voor milieubewuste gebruiker met modern comfort.",
    },

    "tefal_renew_20": {
        "slug": "tefal-renew-20",
        "name": "Tefal Renew+",
        "description": "Gemaakt van gerecycled aluminium met PFAS-vrije laag.",
        "brand": "Tefal",
        "diameter": 20,
        "material": "Keramisch",
        "features": ["Gerecycled aluminium", "Thermo-Spot"],
        "rating": 4,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 30.99,
        "price_last_checked": "2026-07-28",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/tefal-renew-keramische-koekenpan-o-20-cm/9300000120126719/?cid=1766380777710-2580610106203&bltgh=a24bc707-9434-45de-a969-58034170aee3.ProductList_Middle.0.ProductImage",
        "price_range": "€€",
        "award": "",
        "image": "tefal-renew-20cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Duurzaam gerecycled materiaal",
            "Goede warmtegeleiding",
            "Thermo-Spot-hitte-indicator",
        ],
        "cons": [
            "Niet ovenbestendig",
        ],
        "verdict": "Betrouwbare keuze voor milieubewuste gebruiker met modern comfort.",
    },

    "bk_enjoy_20": {
        "slug": "bk-enjoy-20",
        "name": "BK Enjoy",
        "description": "Betaalbare keramische pan met natuurlijke PFAS-vrije coating.",
        "brand": "BK",
        "diameter": 20,
        "material": "Keramisch",
        "features": ["Lichtgewicht", "Eenvoudig schoon te maken"],
        "rating": 4,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 24.90,
        "price_last_checked": "2026-07-28",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/bk-enjoy-koekenpan-20cm-pfas-vrije-antikleeflaag-koekenpan-inductie-keramische-pan-ovenbestendig-tot-160-c-vaatwasserbestendig-koudgrepen-oxford-blue/9300000311002492/",
        "price_range": "€€",
        "image": "bk-enjoy-20cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Licht van gewicht",
            "Goede warmtegeleiding",
            "Gemakkelijk schoon te maken",
        ],
        "cons": [
            "",
        ],
        "verdict": "Een lichte en praktische pan voor dagelijks gezond koken.",
    },

    "hema_milano_20": {
        "slug": "hema-milano-20",
        "name": "HEMA Milano",
        "description": "Compacte en betaalbare keramische koekenpan voor dagelijks gebruik.",
        "brand": "HEMA",
        "diameter": 20,
        "material": "Keramisch",
        "features": [
            "Lichtgewicht",
            "Geschikt voor inductie",
        ],
        "rating": 4,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 26.99,
        "price_last_checked": "2026-07-28",
        "currency": "EUR",
        "availability": "InStock",
        "price_range": "€",
        "image": "hema-milano-20cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "affiliate_url": "https://www.hema.nl/koken-tafelen/koken/pannen/koekenpannen/koekenpan-20cm-milano-pfas-vrij-80120001.html",
        "pros": [
            "Keramische coating",
            "Zeer scherp geprijsd",
            "Compact en lichtgewicht",
        ],
        "cons": [
            "Minder duurzaam bij intensief gebruik",
            "Eenvoudige afwerking",
        ],
        "verdict": "Een toegankelijke en betaalbare instappan voor wie veilig en PFAS-vrij wil koken in een compact formaat.",
    },

    "berndes_b_green_20": {
        "slug": "berndes-b-green-20",
        "name": "Berndes B.Green",
        "description": "PFAS-vrije keramische koekenpan van 100% gerecycled aluminium met b.nature kwarts-antiaanbaklaag.",
        "brand": "Berndes",
        "diameter": 20,
        "material": "Keramisch (b.nature kwarts)",
        "features": ["b.nature kwarts-coating", "Inductie", "100% gerecycled aluminium", "Ovenbestendig", "Vaatwasserbestendig"],
        "rating": 4.3,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 40.00,
        "price_last_checked": "2026-07-28",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/berndes-b-green-koekenpan-20-cm-gerecycled-aluminium-zilver/9300000006419842/?Referrer=ADVNLGOO002032-S--9300000006419842-PMAX-C-22285073478&gad_source=1&gad_campaignid=22291735154&gclid=Cj0KCQjwy_fOBhC6ARIsAHKFB7_MvQ5YAN6K8e-7WijgD5kAcsagV-88-NXgepFBixxwH8uPoPvPBi8aAqYmEALw_wcB",
        "award": None,
        "price_range": "€€",
        "image": "berndes-b-green-20cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "100% PFAS-vrije b.nature kwarts-coating",
            "Gemaakt van 100% gerecycled aluminium",
            "Hittebestendig tot 400 °C",
            "Duurzaam Duits merk met meer dan 100 jaar ervaring",
        ],
        "cons": [
            "Minder glanzend bakoppervlak dan sommige keramische alternatieven",
            "Zachte greep minder geschikt voor hoge oventemperaturen",
        ],
        "verdict": "Milieuvriendelijke keuze voor wie echt PFAS-vrij wil koken met een coating van volledig natuurlijke grondstoffen.",
    },

    # 30CM KOEKENPANNEN

    "greenpan_barcelona_pro_30": {
        "slug": "greenpan-barcelona-pro-30",
        "name": "GreenPan Barcelona Pro",
        "description": "Hoogwaardige keramische PFAS-vrije pan met Thermolon Infinity Pro-coating en inductiebodem.",
        "brand": "GreenPan",
        "diameter": 30,
        "material": "Keramisch",
        "features": ["Inductie", "Ovenbestendig", ],
        "rating": 5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 98.31,
        "price_last_checked": "2026-07-28",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/greenpan-barcelona-evershine-koekenpan-30cm-zilver-inductie-pfas-vrij/9200000091127464/?bltgh=fc18ffe3-a975-418b-905e-ec6d7aa9c44d.ProductList_Middle.0.ProductImage&cid=1766554993577-2580961884565",
        "award": "🏆 Beste keuze",
        "price_range": "€€€",
        "image": "greenpan-barcelona-pro-30cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "PFAS-vrij Thermolon-coating",
            "Uitstekende warmteverdeling",
            "Ovenbestendig tot 220 °C",
        ],
        "cons": [
            "Vrij zwaar",
            "Hogere prijs",
        ],
        "verdict": "De ultieme keuze voor wie dagelijks gezond en PFAS-vrij wil koken.",
    },

    "kochstar_stein_30": {
        "slug": "kochstar-stein-30",
        "name": "Kochstar Stein",
        "description": "Ruime keramische koekenpan met een PFAS-vrije coating, ontworpen voor grotere bereidingen.",
        "brand": "Kochstar",
        "diameter": 30,
        "material": "Keramisch",
        "features": [
            "Inductie",
            "Prijs-kwaliteitverhouding",
        ],
        "rating": 4,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 15.33,
        "price_last_checked": "2026-07-28",
        "currency": "EUR",
        "availability": "InStock",
        "price_range": "€€",
        "image": "kochstar-stein-30cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "award": "💰 Budget keuze",
        "affiliate_url": "https://www.bol.com/nl/nl/p/kochstar-stein-koekenpan-30cm-pfas-vrij-inductie-pan-keramische-anti-aanbaklaag-koelgreep-graniet/9300000231848100/?cid=1766607286820-3364580713069&bltgh=bf2852e3-d6f4-49f0-8592-8238c901b20a.ProductList_Middle.0.ProductImage",
        "pros": [
            "Keramische coating, expliciet PFAS-vrij",
            "Geschikt voor grote inductiezones",
            "Goede prijs-kwaliteitverhouding",
        ],
        "cons": [
            "Minder verfijnde afwerking",
            "Niet bedoeld voor professioneel gebruik",
        ],
        "verdict": "Een toegankelijke en betrouwbare keuze voor wie een grote, PFAS-vrije koekenpan zoekt zonder direct naar het premiumsegment te gaan.",
    },

    "demeyere_alu_pro_5_ceraforce_30": {
        "slug": "demeyere-alu-pro-5-ceraforce-30",
        "name": "Demeyere Alu Pro 5 Ceraforce",
        "description": "Hoogwaardige premium koekenpan met PFAS-vrije Ceraforce® keramische coating.",
        "brand": "Demeyere",
        "diameter": 30,
        "material": "Keramisch (Ceraforce®)",
        "features": ["Inductie", "PFAS-vrij", "Professionele kwaliteit"],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 95.98,
        "price_last_checked": "2026-07-28",
        "price_range": "€€€€",
        "currency": "EUR",
        "availability": "InStock",
        "image": "demeyere-alu-pro-5-ceraforce-30cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "affiliate_url": "https://www.bol.com/nl/nl/p/demeyere-alu-pro-ceraforce-koekenpan-30-cm/9300000045881607/?s2a=&bltgh=kdZ0yO3pHolnAODNrotE3A.4_82_83.84.FeatureListItem#productTitle",
        "award": "💎 Premium keuze",
        "pros": [
            "PFAS-vrije Ceraforce® keramische coating",
            "Zeer stabiele en gelijkmatige warmteverdeling",
            "Uitstekend geschikt voor inductie",
        ],
        "cons": [
            "Zwaarder dan gemiddelde keramische pannen",
            "Hoger prijsniveau",
        ],
        "verdict": "De beste premium keuze voor wie een duurzame, PFAS-vrije keramische koekenpan van 30 cm zoekt met professionele prestaties.",
    },

    "greenchef_diamond_30": {
        "slug": "greenchef-diamond-30",
        "name": "GreenChef Diamond Induction",
        "description": "PFAS-vrije keramische pan met diamantdeeltjes en hoge slijtvastheid.",
        "brand": "GreenChef",
        "diameter": 30,
        "material": "Keramisch",
        "features": ["Diamantcoating", "Duurzaam"],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price_last_checked": "2026-07-28",
        "price": 39.90,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/greenchef-diamond-koekenpan-30cm-zwart-inductie-pfas-vrij/9200000131576064/?cid=1766555531803-2721358459335&bltgh=0b70f7a4-83a9-4b03-a123-b52b2f75f548.ProductList_Middle.0.ProductTitle",
        "price_range": "€€",
        "image": "greenchef-diamond-30cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Extra duurzame diamantcoating",
            "Goede hitteverdeling",
            "Gemakkelijk schoon te maken",
        ],
        "cons": [
            "Niet ovenbestendig",
        ],
        "verdict": "Solide keuze voor wie een betrouwbare en duurzame keramische pan zoekt.",
    },

    "bk_easy_induction_30": {
        "slug": "bk-easy-induction-30",
        "name": "BK Easy Induction Ceramic",
        "description": "PFAS-vrije keramische pan met koele greep en stevige bodem.",
        "brand": "BK",
        "diameter": 30,
        "material": "Keramisch",
        "features": ["Koele greep", "Inductie"],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 44.95,
        "price_last_checked": "2026-07-28",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/bk-easy-induction-ceramic-koekenpan-o30-cm-pfas-vrij/9300000032891768/?cid=1766555806050-3582054560194&bltgh=93cf7e04-5bca-4d0a-b78e-c9a9cee22cbc.ProductList_Middle.0.ProductImage",
        "price_range": "€€",
        "award": "🥇 Meest gekozen",
        "image": "bk-easy-induction-30cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Goede prijs-kwaliteit",
            "Snelle opwarming",
            "Koele handgreep",
        ],
        "cons": [
            "Niet ovenbestendig",
        ],
         "verdict": "Praktische pan voor dagelijks gebruik met betrouwbare antiaanbaklaag.",
    },

    "greenpan_torino_30": {
        "slug": "greenpan-torino-30",
        "name": "GreenPan Torino",
        "description": "Betrouwbare PFAS-vrije keramische koekenpan voor dagelijks gebruik.",
        "brand": "GreenPan",
        "diameter": 30,
        "material": "Keramisch",
        "features": ["Inductie", "PFAS-vrij"],
        "rating": 4,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 39.00,
        "price_last_checked": "2026-07-28",
        "currency": "EUR",
        "availability": "InStock",
        "price_range": "€€",
        "image": "greenpan-torino-30cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "affiliate_url": "https://www.bol.com/nl/nl/p/greenpan-torino-keramische-koekenpan-30-cm/9300000121455786/?s2a=&bltgh=p1NKv29PjTBJZ5yrSsVPUg.4_70_71.72.FeatureOptionButton#productTitle",
        "pros": [
            "PFAS-vrije Thermolon™ keramische coating",
            "Lichtgewicht en prettig in gebruik",
            "Geschikt voor inductie en andere warmtebronnen",
        ],
        "cons": [
            "Minder robuust dan premium GreenPan-series",
            "Niet geschikt voor zeer hoge temperaturen",
        ],
        "verdict": "Een uitstekende, betaalbare keuze voor wie een gezonde PFAS-vrije koekenpan van 30 cm zoekt voor dagelijks koken.",
    },

    "tefal_renew_30": {
        "slug": "tefal-renew-30",
        "name": "Tefal Renew+",
        "description": "Gemaakt van gerecycled aluminium met PFAS-vrije laag.",
        "brand": "Tefal",
        "diameter": 30,
        "material": "Keramisch",
        "features": ["Gerecycled aluminium", "Thermo-Spot"],
        "rating": 4,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 43.99,
        "price_last_checked": "2026-07-28",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/tefal-renew-keramische-koekenpan-o-30-cm/9300000120126720/?Referrer=ADVNLYAH002032-S-2330277456935787-9300000120126720-PMAX-C-698295020&msclkid=a424529cacf31a360f6e38f465b179ec",
        "price_range": "€€",
        "award": "",
        "image": "tefal-renew-30cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Duurzaam gerecycled materiaal",
            "Goede warmtegeleiding",
            "Thermo-Spot-hitte-indicator",
        ],
        "cons": [
            "Niet ovenbestendig",
        ],
        "verdict": "Betrouwbare keuze voor milieubewuste gebruiker met modern comfort.",
    },

    "brabantia_indu_plus_r_30": {
        "slug": "brabantia-indu-plus-r-30",
        "name": "Brabantia Indu+ R Keramische Koekenpan (30 cm)",
        "description": "Ruime en stabiele keramische koekenpan, speciaal ontwikkeld voor inductie.",
        "brand": "Brabantia",
        "diameter": 30,
        "material": "Keramisch",
        "features": [
            "Inductie",
            "Grote kookzones",
        ],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 15.09,
        "price_last_checked": "2026-07-28",
        "currency": "EUR",
        "availability": "InStock",
        "price_range": "€€€",
        "image": "brabantia-indu-plus-r-30cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "affiliate_url": "https://www.bol.com/nl/nl/p/brabantia-indu-r-koekenpan-o-30-cm-100-gerecycled-aluminium-keramische-antiaanbaklaag-ergonomisch-en-licht-ook-geschikt-voor-inductie-100-pfas-vrij-kleur-grijs/9300000183634541/?cid=1766656019958-5924530706126&bltgh=4af6ca51-8341-4130-8090-cc0620a89161.ProductList_Middle.2.ProductTitle",
        "pros": [
            "Keramische coating, expliciet PFAS-vrij",
            "Geoptimaliseerd voor inductiekoken",
            "Grote bakoppervlak voor gezinnen",
        ],
        "cons": [
            "Geen premium afwerking",
        ],
        "verdict": "Een betrouwbare middenklasse keuze voor wie een grote, PFAS-vrije koekenpan zoekt met focus op inductie en gebruiksgemak.",
    },

    "scanpan_techniq_30": {
        "slug": "scanpan-techniq-30",
        "name": "Scanpan TechnIQ",
        "description": "Professionele keramische koekenpan uit de TechnIQ-lijn, ontwikkeld in samenwerking met chefs.",
        "brand": "Scanpan",
        "diameter": 30,
        "material": "Keramisch",
        "features": [
            "Warmteverdeling",
            "Inductie",
        ],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 152.00,
        "price_last_checked": "2026-07-28",
        "currency": "EUR",
        "availability": "InStock",
        "price_range": "€€€€",
        "image": "scanpan-techniq-30cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "affiliate_url": "https://www.bol.com/nl/nl/p/scanpan-techniq-koekenpan-30-cm/9200000126639847/?cid=1766606728869-3499678274754&bltgh=1d7c6f3c-4444-4250-b000-ebe5c02b1456.ProductList_Middle.7.ProductImage",
        "pros": [
            "Keramische coating, expliciet PFAS-vrij",
            "Zeer gelijkmatige warmteverdeling",
            "Ontworpen voor professioneel gebruik",
        ],
        "cons": [
            "Hoger prijsniveau",
            "Relatief zwaar",
        ],
        "verdict": "Een uitstekende keuze voor wie in het 30 cm-formaat maximale prestaties en duurzaamheid zoekt.",
    },

    # 32CM KOEKENPANNEN
    "greenpan_barcelona_pro_32": {
        "slug": "greenpan-barcelona-pro-32",
        "name": "GreenPan Barcelona Pro",
        "description": "Hoogwaardige keramische PFAS-vrije pan met Thermolon Infinity Pro-coating en inductiebodem.",
        "brand": "GreenPan",
        "diameter": 32,
        "material": "Keramisch",
        "features": ["Inductie", "Ovenbestendig", ],
        "rating": 5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 80.00,
        "price_last_checked": "2026-07-28",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/greenpan-barcelona-pro-bakpan-32cm/9300000118071130/?cid=1778183584664-3095916976973&bltgh=51c022df-298c-40ee-a5fb-042d0e7d66d5.ProductList_Middle.0.ProductImage",
        "award": "🏆 Beste keuze",
        "price_range": "€€€",
        "image": "greenpan-barcelona-pro-32cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "PFAS-vrij Thermolon-coating",
            "Uitstekende warmteverdeling",
            "Ovenbestendig tot 220 °C",
        ],
        "cons": [
            "Vrij zwaar",
            "Hogere prijs",
        ],
        "verdict": "De ultieme keuze voor wie dagelijks gezond en PFAS-vrij wil koken.",
    },

    "demeyere_alu_pro_5_ceraforce_32": {
        "slug": "demeyere-alu-pro-5-ceraforce-32",
        "name": "Demeyere Alu Pro 5 Ceraforce",
        "description": "Hoogwaardige premium koekenpan met PFAS-vrije Ceraforce® keramische coating.",
        "brand": "Demeyere",
        "diameter": 32,
        "material": "Keramisch (Ceraforce®)",
        "features": ["Inductie", "PFAS-vrij", "Professionele kwaliteit"],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 99.50,
        "price_last_checked": "2026-07-28",
        "price_range": "€€€€",
        "currency": "EUR",
        "availability": "InStock",
        "image": "demeyere-alu-pro-5-ceraforce-32cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "affiliate_url": "https://www.bol.com/nl/nl/p/demeyere-alu-pro-5-ceraforce-bakpan-32cm/9300000023769225/?s2a=&bltgh=hg-NXeuD4MXWFUeGSg9L7Q.4_82_83.84.FeatureListItem#productTitle",
        "award": "💎 Premium keuze",
        "pros": [
            "PFAS-vrije Ceraforce® keramische coating",
            "Zeer stabiele en gelijkmatige warmteverdeling",
            "Uitstekend geschikt voor inductie",
        ],
        "cons": [
            "Zwaarder dan gemiddelde keramische pannen",
            "Hoger prijsniveau",
        ],
        "verdict": "De beste premium keuze voor wie een duurzame, PFAS-vrije keramische koekenpan van 32 cm zoekt met professionele prestaties.",
    },

    "combekk_ceramic_pro_32": {
        "slug": "combekk-ceramic-pro-32",
        "name": "Combekk Ceramic Pro",
        "description": "Duurzame keramische koekenpan van Nederlands ontwerp, ontwikkeld met focus op gezond koken en een lange levensduur.",
        "brand": "Combekk",
        "diameter": 32,
        "material": "Keramisch",
        "features": [
            "Zeer stabiele bodem voor grote inductiezones",
            "Duurzaam Nederlands merk",
        ],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 57.99,
        "price_last_checked": "2026-07-28",
        "currency": "EUR",
        "availability": "InStock",
        "price_range": "€€€",
        "image": "combekk-ceramic-pro-32cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "affiliate_url": "https://www.bol.com/nl/nl/p/combekk-koekenpan-ceramic-pro-koekenpan-anti-aanbak-keramisch-roestvrijstaal-32cm/9300000072548969/?cid=1766655185920-4711281622513&bltgh=23319959-4c5c-4ef9-a0b4-b0cc519f26d9.ProductList_Middle.13.ProductTitle",
        "pros": [
            "Keramische coating, expliciet PFAS-vrij",
            "Zeer stabiel en geschikt voor grote inductiezones",
            "Duurzaam merk met focus op kwaliteit",
        ],
        "cons": [
            "Hoger gewicht door robuuste bouw",
            "Hoger prijsniveau dan instapmodellen",
        ],
        "verdict": "Een sterke middenklasse keuze voor wie in het 32 cm-formaat duurzaam, PFAS-vrij en met vertrouwen wil koken.",
    },

    "bk_easy_induction_32": {
        "slug": "bk-easy-induction-32",
        "name": "BK Easy Induction Ceramic",
        "description": "PFAS-vrije keramische pan met koele greep en stevige bodem.",
        "brand": "BK",
        "diameter": 32,
        "material": "Keramisch",
        "features": ["Koele greep", "Inductie"],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 49.91,
        "price_last_checked": "2026-07-28",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/bk-easy-induction-vispan-o-32-cm-inductie-pfas-vrij/9300000089414301/?cid=1766655064205-1733964093749&bltgh=b2689f89-faf1-468c-87cb-b989c8c4f351.ProductList_Middle.9.ProductTitle",
        "price_range": "€€",
        "award": "🥇 Meest gekozen",
        "image": "bk-easy-induction-32cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Goede prijs-kwaliteit",
            "Snelle opwarming",
            "Koele handgreep",
        ],
        "cons": [
            "Niet ovenbestendig",
        ],
        "verdict": "Praktische pan voor dagelijks gebruik met betrouwbare antiaanbaklaag.",
    },

    "greenpan_torino_32": {
        "slug": "greenpan-torino-32",
        "name": "GreenPan Torino",
        "description": "Betrouwbare PFAS-vrije keramische koekenpan voor dagelijks gebruik.",
        "brand": "GreenPan",
        "diameter": 32,
        "material": "Keramisch",
        "features": ["Inductie", "PFAS-vrij"],
        "rating": 4,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 44.89,
        "price_last_checked": "2026-07-28",
        "currency": "EUR",
        "availability": "InStock",
        "price_range": "€€",
        "image": "greenpan-torino-32cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "affiliate_url": "https://www.bol.com/nl/nl/p/greenpan-torino-vispan/9300000121455776/?s2a=&bltgh=va9fygct4-z4dcpWAPpBdg.4_67_68.69.FeatureOptionButton#productTitle",
        "pros": [
            "PFAS-vrije Thermolon™ keramische coating",
            "Lichtgewicht en prettig in gebruik",
            "Geschikt voor inductie en andere warmtebronnen",
        ],
        "cons": [
            "Minder robuust dan premium GreenPan-series",
            "Niet geschikt voor zeer hoge temperaturen",
        ],
        "verdict": "Een uitstekende, betaalbare keuze voor wie een gezonde PFAS-vrije koekenpan van 30 cm zoekt voor dagelijks koken.",
    },

    "tefal_renew_32": {
        "slug": "tefal-renew-32",
        "name": "Tefal Renew+",
        "description": "Gemaakt van gerecycled aluminium met PFAS-vrije laag.",
        "brand": "Tefal",
        "diameter": 32,
        "material": "Keramisch",
        "features": ["Gerecycled aluminium", "Thermo-Spot"],
        "rating": 4,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 36.79,
        "price_last_checked": "2026-07-28",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/tefal-renew-on-keramische-koekenpan-o-32-cm/9300000117431080/?cid=1766655540107-9223038508418&bltgh=c1879416-2445-440e-bc08-1f53f5887c81.ProductList_Middle.0.ProductImage",
        "price_range": "€€",
        "award": "",
        "image": "tefal-renew-32cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "pros": [
            "Duurzaam gerecycled materiaal",
            "Goede warmtegeleiding",
            "Thermo-Spot-hitte-indicator",
        ],
        "cons": [
            "Niet ovenbestendig",
        ],
        "verdict": "Betrouwbare keuze voor milieubewuste gebruiker met modern comfort.",
    },

    "primecook_32": {
        "slug": "primecook-32",
        "name": "Primecook Keramische Koekenpan",
        "brand": "Primecook",
        "diameter": 32,
        "material": "Keramisch",
        "description": "Italiaanse PFAS-vrije keramische koekenpan van 32 cm met een stevige aluminium body en inductiebodem. Primecook richt zich op duurzame, gezonde antiaanbakpannen met een onderscheidend Italiaans design.",
        "features": [
            "PFAS-vrije keramische antiaanbaklaag",
            "Geschikt voor inductie",
            "Groot bakoppervlak van 32 cm",
            "Italiaans design en productie",
        ],
        "rating": 4,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 81.90,
        "price_last_checked": "2026-07-28",
        "currency": "EUR",
        "availability": "InStock",
        "price_range": "€€€",
        "image": "primecook-32cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "affiliate_url": "https://www.primecook.nl/1903-primecook-koekenpan-32-cm-pfas-vrij",
        "pros": [
            "Volledig PFAS-vrije keramische coating",
            "Stevige inductiebodem, weinig kans op vervorming",
            "Onderscheidend Italiaans merk met sterk duurzaamheidsverhaal",
            "Optioneel verkrijgbaar met deksel of personalisatie",
        ],
        "cons": [
            "Minder bekend bij gemiddelde NL-consument dan GreenPan of Tefal",
            "Alleen rechtstreeks bij Primecook verkrijgbaar (geen bol.com)",
        ],
        "verdict": "Een onderscheidende, eerlijk gepositioneerde Italiaanse PFAS-vrije koekenpan van 32 cm — ideaal voor wie kwaliteit en design boven merkbekendheid stelt.",
    },

    "blue_diamond_32": {
        "slug": "blue-diamond-32",
        "description": "Grote keramische koekenpan met diamantversterkte coating, gericht op betaalbaar gebruik in een ruim formaat.",
        "name": "Blue Diamond",
        "brand": "Blue Diamond",
        "diameter": 32,
        "material": "Keramisch",
        "features": [
            "Groot bakoppervlak",
            "Scherp geprijsd instapmodel",
        ],
        "rating": 4,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 82.41,
        "price_last_checked": "2026-07-29",
        "currency": "EUR",
        "availability": "InStock",
        "price_range": "€€€",
        "image": "blue-diamond-32cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "affiliate_url": "https://www.amazon.nl/Blue-Diamond-Geanodiseerd-Keramische-Vaatwasmachinebestendig/dp/B09PVMTPYN?th=1",
        "pros": [
            "Keramische coating zonder PFAS",
            "Groot bakoppervlak voor meerdere ingrediënten",
            "Relatief scherp geprijsd voor 32 cm",
        ],
        "cons": [
            "Minder duurzame coating bij intensief gebruik",
            "Marketingclaim (“diamond”) belangrijker dan techniek",
        ],
        "verdict": "Een toegankelijke instapoptie voor wie een grote, PFAS-vrije koekenpan zoekt zonder hoge investering.",
    },

    "ikea_hemlagad_keramisch_32": {
        "slug": "ikea-hemlagad-keramisch-32",
        "name": "IKEA HEMLAGAD",
        "description": " Betaalbare en toegankelijke keramische koekenpan van IKEA met een PTFE- en PFAS-vrije antiaanbaklaag.",
        "brand": "IKEA",
        "diameter": 32,
        "material": "Keramisch",
        "features": [
            "Inductie",
            "PFAS-vrij",
        ],
        "rating": 4,
        "rating_count": None,
        "rating_source": "editorial",
        "price_range": "€",
        "price": 17.99,
        "price_last_checked": "2026-07-29",
        "currency": "EUR",
        "availability": "InStock",
        "image": "ikea-hemlagad-keramisch-32cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "affiliate_url": "https://www.ikea.com/nl/nl/p/hemlagad-koekenpan-antiaanbaklaag-zwart-30580899/#content",
        "pros": [
            "Keramische coating, expliciet PFAS-vrij",
            "Zeer scherpe prijs",
            "Geschikt voor inductie en andere warmtebronnen",
        ],
        "cons": [
            "Minder duurzaam dan midden- en premium pannen",
            "Warmteverdeling is eenvoudiger",
        ],
        "verdict": "Een goede keuze voor wie een goedkope, PFAS-vrije koekenpan van 30 cm zoekt voor licht en dagelijks gebruik, zonder concessies te doen aan basisveiligheid.",
    },

    "scanpan_ceramic_32": {
        "name": "Scanpan HaptIQ",
        "slug": "scanpan-ceramic-32",
        "description": " Hoogwaardige Scandinavische koekenpan met keramische, PFAS-vrije coating en een focus op duurzaamheid.",
        "brand": "Scanpan",
        "diameter": 32,
        "material": "Keramisch",
        "features": [
            "Keramisch en PFAS-vrij",
            "Scandinavische kwaliteit",
            "Gelijkmatige warmteverdeling",
        ],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 198.49,
        "price_last_checked": "2026-07-29",
        "currency": "EUR",
        "availability": "InStock",
        "price_range": "€€€€",
        "image": "scanpan-ceramic-32cm.webp",
        "image_path": "images/products/keramische-koekenpannen",
        "affiliate_url": "https://www.bol.com/nl/nl/p/scanpan-haptiq-koekenpan-32-cm/9200000116693186/?cid=1766655687794-9869876503169&bltgh=cd3a2be1-6fbc-4d58-ac60-c5045d68fd26.ProductList_Middle.4.ProductTitle",
        "pros": [
            "Keramisch en PFAS-vrij",
            "Zeer gelijkmatige warmteverdeling",
            "Solide bouwkwaliteit",
        ],
        "cons": [
            "Prijs hoger dan gemiddelde middenklasse",
        ],
               "verdict": "Een interessante keuze voor wie Scandinavische kwaliteit waardeert.",
    },
}
