PRODUCTS = {
    "greenpan_barcelona_pro_28": {
        "slug": "greenpan-barcelona-pro-hapjespan-28",
        "name": "GreenPan Barcelona Pro",
        "description": "Premium hapjespan van 28 cm met keramische coating, diepe vorm en glazen deksel, geschikt voor bakken, sudderen en complete éénpansgerechten.",
        "brand": "GreenPan",
        "diameter": 28,
        "material": "Aluminium met keramische coating",
        "features": [
            "PFAS-vrij",
            "Thermolon Infinity Pro coating",
            "Inductie- en ovenbestendig",
            "Inclusief glazen deksel",
        ],
        "rating": 4.8,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 159.90,
        "price_last_checked": "2026-05-29",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url":"https://www.greenpan.nl/products/barcelona-pro-hapjespan-met-deksel-28cm",
        "price_range": "€€€€",
        "image": "hapjespan01.jpg",
        "image_path": "images/hapjespannen",
        "pros": [
            "Diepe vorm geschikt voor grotere porties en sauzen",
            "Stevige inductiebodem met gelijkmatige warmteverdeling",
            "Glazen deksel maakt langzaam garen eenvoudig",
        ],
        "cons": [
            "Hogere prijsklasse",
            "Iets zwaarder door RVS buitenwand",
        ],
        "verdict": "De meest complete allround hapjespan voor dagelijks bakken, sudderen en grotere maaltijden.",
        "award": "🏆 Beste keuze",
    },
    "bk_enjoy_28": {
        "slug": "bk-enjoy-hapjespan-28",
        "name": "BK Enjoy Keramische Hapjespan",
        "description": "Toegankelijke keramische hapjespan van 28 cm voor dagelijks koken, pasta's en eenvoudige éénpansgerechten.",
        "brand": "BK",
        "diameter": 28,
        "material": "Aluminium met keramische coating",
        "features": [
            "Keramische antiaanbaklaag",
            "Geschikt voor inductie",
        ],
        "rating": 4.2,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 41.93,
        "price_last_checked": "2026-05-29",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/bk-enjoy-hapjespan-o-28cm-deksel-pfas-vrij-zwart-koelgreep-ovenbestendig-tot-160/9300000196237263/",
        "price_range": "€",
        "image": "hapjespan_bk_enjoy_28cm.jpg",
        "image_path": "images/hapjespannen",
        "pros": [
            "Toegankelijke prijs",
            "Diepe vorm voor dagelijkse maaltijden",
            "Gebruiksvriendelijke antiaanbakprestaties",
        ],
        "cons": [
            "Minder duurzaam dan midden- en premiumklasse",
            "Niet bedoeld voor intensief of professioneel gebruik",
        ],
        "verdict": "Een praktische instapper voor dagelijkse maaltijden zoals pasta's, rijstgerechten en groenteschotels.",
        "award": "💰 Budget keuze",
    },
    "woll_ecolite_qxr_28": {
        "slug": "woll-ecolite-qxr-28",
        "name": "WOLL Eco Lite QXR",
        "description": "Premium PFAS-vrije hapjespan met QXR-keramische antiaanbaklaag, lichtgewicht body en stevige inductiebodem.",
        "brand": "WOLL",
        "diameter": 28,
        "material": "Gerecycled aluminium met keramische coating",
        "features": [
            "PFAS-vrij",
            "QXR-keramische coating",
            "Lichtgewicht premium constructie",
        ],
        "rating": 4.7,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 104.90,
        "price_last_checked": "2026-05-29",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/hapjespan-o-28-cm-3-3-l-gerecycled-aluminium-qxr-non-stick-inductie-woll-ecolite-qxr/9300000180122490/",
        "price_range": "€€€",
        "image": "hapjespan03.jpg",
        "image_path": "images/hapjespannen",
        "pros": [
            "Sterke warmteverdeling voor gelijkmatig garen",
            "Licht voor een premium hapjespan",
            "Diepe vorm geschikt voor grotere hoeveelheden",
        ],
        "cons": [
            "Hogere prijsklasse",
            "Handwas aanbevolen",
        ],
        "verdict": "Premium keuze voor wie veel kookt en een lichte maar hoogwaardige hapjespan zoekt.",
        "award": "💎 Premium keuze",
    },
    "greenchef_diamond_28": {
        "slug": "greenchef-diamond-hapjespan-28",
        "name": "GreenChef Diamond Induction",
        "description": "PFAS-vrije keramische hapjespan met diamantversterkte coating en deksel.",
        "brand": "GreenChef",
        "diameter": 28,
        "material": "Aluminium met keramische coating",
        "features": [
            "PFAS-vrij",
            "Diamantversterkte keramische coating",
            "Inclusief deksel",
        ],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 52.50,
        "price_last_checked": "2026-05-29",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/greenchef-diamond-inductie-hapjespan-o28-cm-keramisch-pfas-vrij/9200000131435585/",
        "price_range": "€€",
        "award": None,
        "image": "hapjespan04.jpg",
        "image_path": "images/hapjespannen",
        "pros": [
            "Zeer goede prijs-kwaliteitverhouding",
            "Diamantversterkte coating",
            "Inclusief deksel",
        ],
        "cons": [
            "Niet ovenbestendig",
            "Niet geschikt voor metalen spatels",
        ],
        "verdict": "Een sterke middenklasse hapjespan met goede balans tussen gebruiksgemak en prijs.",
    },
    "bk_easy_induction_28": {
        "slug": "bk-easy-induction-hapjespan-28",
        "name": "BK Easy Induction Ceramic",
        "description": "Betaalbare PFAS-vrije hapjespan met keramische antiaanbaklaag en stevige koudgreep.",
        "brand": "BK",
        "diameter": 28,
        "material": "Aluminium met keramische coating",
        "features": [
            "PFAS-vrij",
            "Keramische antiaanbaklaag",
            "Inclusief glazen deksel",
        ],
        "rating": 4.3,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 71.35,
        "price_last_checked": "2026-05-29",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/bk-easy-induction-ceramic-hapjespan-met-deksel-o28cm-4-6l-inductie-pfas-vrij/9300000032891765/",
        "price_range": "€",
        "image": "hapjespan02.jpg",
        "image_path": "images/hapjespannen",
        "pros": [
            "Ruime inhoud voor éénpansgerechten",
            "Glazen deksel voor langzaam garen",
            "Goede prijs voor complete set",
        ],
        "cons": [
            "Niet ovenbestendig",
            "Antiaanbakeigenschappen kunnen bij intensief gebruik sneller afnemen",
        ],
        "verdict": "Een uitstekende keuze voor dagelijks gebruik tegen een vriendelijke prijs.",
    },
    "be_living_28": {
        "slug": "be-living-28",
        "name": "BE Living",
        "description": "Toegankelijke PFAS-vrije hapjespan met glazen deksel en keramische coating.",
        "brand": "BE Living",
        "diameter": 28,
        "material": "Aluminium met keramische coating",
        "features": [
            "PFAS-vrij",
            "Inclusief glazen deksel",
            "Betaalbaar",
        ],
        "rating": 4.1,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 46.95,
        "price_last_checked": "2026-05-29",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/be-living-hapjespan-met-deksel-o-28-cm-sauteerpan-keramisch-inductie-pfas-vrij-anti-aanbak-delight-series/9300000236794346/",
        "price_range": "€€",
        "image": "hapjespan06.jpg",
        "image_path": "images/hapjespannen",
        "pros": [
            "Met glazen deksel",
            "PFAS-vrije coating",
            "Vriendelijk geprijsd",
        ],
        "cons": [
            "Coating minder duurzaam",
            "Niet geschikt voor metalen spatels",
        ],
        "verdict": "Een voordelige keuze voor wie een complete PFAS-vrije hapjespan zoekt.",
    },
    "greenpan_torino_28": {
        "slug": "greenpan-torino-28",
        "name": "GreenPan Torino",
        "description": "Solide PFAS-vrije hapjespan met Thermolon-keramische coating.",
        "brand": "GreenPan",
        "diameter": 28,
        "material": "Aluminium met keramische coating",
        "features": [
            "PFAS-vrij",
            "Thermolon coating",
            "Lichtgewicht",
        ],
        "rating": 4.4,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 54.00,
        "price_last_checked": "2026-05-29",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.coolblue.nl/product/819625/greenpan-torino-keramische-hapjespan-met-deksel-28-cm.html",
        "price_range": "€€",
        "image": "hapjespan07.jpg",
        "image_path": "images/hapjespannen",
        "pros": [
            "Goede prijs-kwaliteitverhouding",
            "Fijne antiaanbakeigenschappen",
            "Relatief licht",
        ],
        "cons": [
            "Langdurig gebruik op zeer hoge temperaturen kan de antiaanbakeigenschappen sneller verminderen",
            "Coating vraagt voorzichtig gebruik",
        ],
        "verdict": "Een toegankelijke hapjespan voor dagelijkse maaltijden en regelmatig gebruik.",
    },
    "beka_cicla_28": {
        "slug": "beka-cicla-28",
        "name": "Beka Cicla",
        "description": "PFAS-vrije hapjespan van gerecycled aluminium met keramische coating en glazen deksel.",
        "brand": "Beka",
        "diameter": 28,
        "material": "Gerecycled aluminium met keramische coating",
        "features": [
            "PFAS-vrij",
            "Gerecycled aluminium",
            "Inclusief glazen deksel",
        ],
        "rating": 4.4,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 85.00,
        "price_last_checked": "2026-05-29",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/beka-cicla-sauteerpan-hapjespan-o-28cm-met-deksel-uit-glas-gerecycleerd-rvs-pfas-vrij-2-stevige-handvaten-geschikt-voor-inductie-vaatwasser/9300000226669764/",
        "price_range": "€€",
        "image": "hapjespan10.jpg",
        "image_path": "images/hapjespannen",
        "pros": [
            "PFAS-vrije keramische laag",
            "Duurzaam materiaal",
            "Inclusief glazen deksel",
        ],
        "cons": [
            "Niet geschikt voor metalen spatels",
            "Gevoelig voor schuurmiddelen",
        ],
        "verdict": "Een duurzame hapjespan voor wie dagelijks kookt en waarde hecht aan gerecyclede materialen.",
    },

# 24 CM HAPJESPANNEN
    "greenpan_barcelona_pro_24": {
        "slug": "greenpan-barcelona-pro-hapjespan-24",
        "name": "GreenPan Barcelona Pro",
        "description": "Premium 24 cm hapjespan met Thermolon™ Infinity Pro-coating en glazen deksel, geschikt voor bakken, sudderen en complete maaltijden voor 1–3 personen.",
        "brand": "GreenPan",
        "diameter": 24,
        "material": "Aluminium met keramische coating",
        "features": [
            "PFAS-vrij",
            "Thermolon Infinity Pro coating",
            "Inductie- en ovenbestendig",
            "Inclusief glazen deksel",
        ],
        "rating": 4.8,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 149.90,
        "price_last_checked": "2026-05-29",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.greenpan.nl/products/barcelona-pro-hapjespan-met-deksel-24cm",
        "price_range": "€€€€",
        "image": "greenpan-barcelona-pro-24cm.jpg",
        "image_path": "images/hapjespannen",
        "pros": [
            "Diepe vorm geschikt voor pasta's, sauzen en éénpansgerechten",
            "Stevige inductiebodem met gelijkmatige warmteverdeling",
            "Glazen deksel maakt langzaam garen eenvoudig",
        ],
        "cons": [
            "Hogere prijsklasse",
            "Iets zwaarder door RVS buitenwand",
        ],
        "verdict": "De meest complete 24 cm hapjespan voor dagelijks koken en kleinere huishoudens.",
        "award": "🏆 Beste keuze",
    },

"bk_brilliant_24": {
   "slug": "bk-brilliant-24",
   "name": "BK Brilliant Keramische Hapjespan",
   "description": "PFAS-vrije keramische hapjespan met moderne afwerking en solide bouwkwaliteit, geschikt voor dagelijks gebruik in het 24 cm formaat.",
   "brand": "BK",
   "diameter": 24,
   "material": "Aluminium met keramische coating",
   "features": [
       "Keramische antiaanbaklaag",
       "Geschikt voor inductie",
   ],
   "rating": 4.4,
   "rating_count": None,
   "rating_source": "editorial",
   "price": 44.64,
    "price_last_checked": "2026-05-29",
   "currency": "EUR",
   "availability": "InStock",
   "affiliate_url": "",
    "retailer_url": "https://www.bol.com/nl/nl/p/bk-brilliant-hapjespan-met-deksel-o24-cm-inductie-anti-aanbak-pfas-vrij/9300000121455778/",
   "price_range": "€€",
   "image": "hapjespan_bk_brilliant_24cm.jpg",
   "image_path": "images/hapjespannen",
   "pros": [
       "Goede balans tussen prijs en prestaties",
       "Praktisch formaat voor dagelijkse maaltijden",
       "Geschikt voor alle warmtebronnen",
   ],
   "cons": [
       "Warmteverdeling minder verfijnd dan premium modellen",
       "Niet bedoeld voor zeer hoge temperaturen",
   ],
    "verdict": "Een sterke middenklasse keuze voor dagelijks gebruik zonder premium prijs.",
   "award": None,
},

"woll_ecolite_qxr_24": {
        "slug": "woll-ecolite-qxr-24",
        "name": "WOLL Eco Lite QXR",
        "description": "Premium lichte hapjespan van gerecycled aluminium met QXR-keramische coating en sterke warmtecontrole.",
        "brand": "WOLL",
        "diameter": 24,
        "material": "Gerecycled aluminium met keramische coating",
        "features": [
            "PFAS-vrij",
            "QXR-keramische coating",
            "Lichtgewicht premium constructie",
        ],
        "rating": 4.7,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 81.00,
        "price_last_checked": "2026-05-29",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/hapjespan-o-24-cm-2-4-l-gerecycled-aluminium-qxr-non-stick-inductie-woll-ecolite-qxr/9300000180122500/",
        "price_range": "€€€",
        "image": "woll_ecolite_qxr_24cm.jpg",
        "image_path": "images/hapjespannen",
        "pros": [
            "Sterke warmteverdeling voor gelijkmatig garen",
            "Opvallend licht voor een premium hapjespan",
            "Diepe vorm geschikt voor grotere maaltijden",
        ],
        "cons": [
            "Hogere prijsklasse",
            "Handwas aanbevolen",
        ],
        "verdict": "Premium keuze voor intensieve thuiskoks die een lichte maar hoogwaardige hapjespan zoeken.",
        "award": "💎 Premium keuze",
    },

    "greenchef_prime_24": {
        "slug": "greenchef-prime-24",
        "name": "GreenChef Prime Keramische Hapjespan",
        "description": "Hoogwaardige PFAS-vrije keramische hapjespan met duurzame Thermolon™-coating, ontworpen voor dagelijks gebruik met betere slijtvastheid dan instapmodellen.",
        "brand": "GreenChef",
        "diameter": 24,
        "material": "Aluminium met keramische coating",
        "features": [
            "Thermolon™ keramische coating",
            "Geschikt voor inductie",
        ],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 49.90,
        "price_last_checked": "2026-05-29",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/greenchef-prime-stoofpan-24cm-pfas-vrij-hapjespan-met-deksel-geschikt-voor-inductie/9300000223447989/",
        "price_range": "€€",
        "image": "greenchef_prime_24cm.jpg",
        "image_path": "images/hapjespannen",
        "pros": [
            "Gelijkmatige warmteverdeling",
            "Geschikt voor dagelijkse éénpansgerechten",
            "Betere slijtvastheid dan veel instapmodellen",
        ],
        "cons": [
            "Hoger geprijsd dan budgetalternatieven",
            "Niet bedoeld voor extreem hoge temperaturen",
        ],
        "verdict": "Een sterke keuze voor wie iets meer kwaliteit wil dan een instapmodel zonder premium prijzen.",
    },

    "bk_balans_plus_24": {
       "slug": "bk-balans-plus-24",
       "name": "BK Balans+ Keramische Hapjespan",
       "description": "PFAS-vrije keramische hapjespan van 24 cm met stevige inductiebodem, glazen deksel en een goede balans tussen gebruiksgemak, duurzaamheid en prijs.",
       "brand": "BK",
       "diameter": 24,
       "material": "Keramisch",
       "features": [
           "PFAS-vrije keramische coating",
           "Geschikt voor inductie",
           "Inclusief glazen deksel",
           "Gerecycled aluminium"
       ],
       "rating": 4.5,
       "rating_count": None,
       "rating_source": "editorial",
       "price": 49.90,
       "price_last_checked": "2026-05-29",
       "currency": "EUR",
       "availability": "InStock",
       "affiliate_url": "",
        "retailer_url": "https://bk.nl/products/balans-hapjespan",
       "price_range": "€€",
       "image": "bk_balans_plus_24cm.jpg",
       "image_path": "images/hapjespannen",
       "pros": [
           "PFAS-vrije keramische coating",
           "Stevige inductiebodem met gelijkmatige warmteverdeling",
           "Inclusief glazen deksel",
           "Goede prijs-kwaliteitverhouding"
       ],
       "cons": [
           "Niet geschikt voor metalen spatels",
           "Keramische eigenschappen nemen op termijn af bij intensief gebruik"
       ],
       "verdict": "Een van de meest uitgebalanceerde PFAS-vrije hapjespannen in het middensegment. Ideaal voor dagelijks gebruik, sauzen, pasta's en kleinere eenpansgerechten.",
    },


"kochstar_essenz_24": {
   "slug": "kochstar-essenz-hapjespan-24",
   "name": "Kochstar Essenz Keramische Hapjespan",
   "description": "Betaalbare PFAS-vrije keramische hapjespan in 24 cm, geschikt voor dagelijks gebruik en kleinere huishoudens.",
   "brand": "Kochstar",
   "diameter": 24,
   "material": "Aluminium met keramische coating",
   "features": [
       "Keramische antiaanbaklaag",
       "Geschikt voor inductie",
   ],
   "rating": 4.0,
   "rating_count": None,
   "rating_source": "editorial",
   "price": 19.99,
   "price_last_checked": "2026-05-29",
   "currency": "EUR",
   "availability": "OutOfStock",
   "affiliate_url": "",
    "retailer_url": "https://www.bol.com/nl/nl/p/kochstar-essenz-keramische-inductie-kookpan-met-deksel-24cm-3-5l-pfas-vrij-inductie-kookpan-keramische-anti-aanbaklaag-koelgreep-zwart/9300000231848098/",
   "price_range": "€",
   "image": "hapjespan_kochstar_essenz_24cm.jpg",
   "image_path": "images/hapjespannen",
   "pros": [
       "Zeer toegankelijke prijs",
       "Compact formaat voor kleinere huishoudens",
       "Eenvoudig in gebruik",
   ],
   "cons": [
       "Eenvoudigere constructie dan duurdere modellen",
       "Niet bedoeld voor intensief of professioneel gebruik",
   ],
    "verdict": "Een eenvoudige instapper voor kleinere huishoudens of incidenteel gebruik.",
    "award":"💰 Budget keuze",
},


"beka_cicla_24": {
        "slug": "beka-cicla-24",
        "name": "Beka Cicla",
        "description": "PFAS-vrije hapjespan van gerecycled aluminium met keramische coating en glazen deksel.",
        "brand": "Beka",
        "diameter": 24,
        "material": "Gerecycled aluminium met keramische coating",
        "features": [
            "PFAS-vrij",
            "Gerecycled aluminium",
            "Inclusief glazen deksel",
        ],
        "rating": 4.4,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 74.95,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/beka-cicla-sauteerpan-hapjespan-o-24cm-met-deksel-uit-glas-gerecycleerd-rvs-pfas-vrij-geschikt-voor-inductie-vaatwasser/9300000226669762/",
        "price_range": "€€",
        "image": "beka_cicla_24cm.jpg",
        "image_path": "images/hapjespannen",
        "pros": [
            "Gemaakt van gerecycled aluminium",
            "Glazen deksel voor langzaam garen",
            "Stevige constructie voor dagelijks gebruik",
        ],
        "cons": [
            "Niet geschikt voor metalen spatels",
            "Gevoelig voor schuurmiddelen",
        ],
        "verdict": "Een duurzame hapjespan voor wie dagelijks kookt en waarde hecht aan gerecyclede materialen.",
    },


# 30 CM HAPJESPANNEN
    "greenpan_barcelona_pro_30": {
        "slug": "greenpan-barcelona-pro-hapjespan-30",
        "name": "GreenPan Barcelona Pro",
        "description": "Premium keramische hapjespan zonder PFAS met Thermolon™ Infinity Pro-coating en stevig glazen deksel.",
        "brand": "GreenPan",
        "diameter": 30,
        "material": "Keramisch",
        "features": [
            "PFAS-vrij",
            "Thermolon Infinity Pro coating",
            "Inductie- en ovenbestendig",
            "Inclusief glazen deksel",
        ],
        "rating": 5,
        "rating_count": 230,
        "price": 59.90,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/greenpan-barcelona-infinity-pro-hapjespan-met-deksel-30cm-zwart-inductie-pfas-vrij/9200000091127472/",
        "price_range": "€€",
        "image": "greenpan-barcelona-pro-30cm.jpg",
        "image_path": "images/hapjespannen",
        "pros": [
            "Zeer duurzame keramische coating",
            "Met glazen deksel",
            "Inductie- en ovenbestendig",
        ],
        "cons": [
            "Hogere prijsklasse",
            "Iets zwaarder door RVS buitenwand",
        ],
        "suitable_for": ["wie graag in één keer voor iedereen kookt", "een upgrade van budget naar premium", "risotto, paella en stoofschotels"],
        "verdict": "De beste allround PFAS-vrije hapjespan dankzij de combinatie van duurzaamheid, bakresultaten en bouwkwaliteit.",
        "award": "🏆 Beste keuze",
    },
}
