PRODUCTS = {
    "demeyere_industry_5_28": {
        "slug": "demeyere-industry-5-28",
        "name": "Demeyere Industry 5 Koekenpan 28 cm",
        "description": "Hoogwaardige 5-lagen RVS koekenpan met uitstekende warmteverdeling en duurzame constructie zonder coating.",
        "brand": "Demeyere",
        "diameter": 28,
        "material": "RVS",
        "features": [
            "5-lagenmateriaal",
            "Warmteverdeling tot aan de rand",
            "Inductie",
            "Ovenbestendig",
            "Vaatwasserbestendig",
        ],
        "rating": 4.8,
        "rating_count": 120,
        "price": 185.00,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/demeyere-industry-5-koekenpan-28-cm-nanotouch/9300000243733912/?cid=1776400258644-9855550444144&bltgh=17989b40-ca98-4009-b953-deda580ab379.ProductList_Middle.0.ProductTitle",
        "award": "🏆 Beste keuze",
        "price_range": "€€€",
        "image": "demeyere-industry-5-28.jpg",
        "image_path": "images/products/rvs-koekenpannen",
        "pros": [
            "Zeer gelijkmatige warmteverdeling",
            "Sterke reputatie voor serieus dagelijks gebruik",
            "Volledig RVS zonder antiaanbaklaag",
        ],
        "cons": [
            "Hogere instapprijs",
            "Heeft wat leercurve vergeleken met keramisch",
        ],
        "verdict": "Sterke allround RVS-koekenpan voor wie duurzaam en controlegericht wil bakken.",
    },
    "demeyere_silverline_7_nanotouch_28": {
        "slug": "demeyere-silverline-7-nanotouch-28",
        "name": "Demeyere Silverline 7 Koekenpan NanoTouch 28 cm",
        "description": "Premium 7-lagen RVS koekenpan met maximale warmtecontrole en professionele prestaties zonder antiaanbaklaag.",
        "brand": "Demeyere",
        "diameter": 28,
        "material": "RVS",
        "features": [
            "7-lagenmateriaal",
            "NanoTouch-oppervlak",
            "PFAS-vrij",
            "Inductie",
            "Ovenbestendig",
            "Vaatwasserbestendig",
        ],
        "rating": 4.9,
        "rating_count": 80,
        "price": 229.00,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.pannenhuis.nl/products/demeyere-silverline-7-nano-touch-koekenpan?gad_source=1&gad_campaignid=21432908150&gclid=CjwKCAjwspPOBhB9EiwATFbi5A149zJ9c_Phs3IG8xeBNJyBZPYjZpzkri4Xk1KJh0Hcd3arhLzlfBoCoEEQAvD_BwE",
        "award": "💎 Premium keuze",
        "price_range": "€€€€",
        "image": "demeyere-silverline-7-28.jpg",
        "image_path": "images/products/rvs-koekenpannen",
        "pros": [
            "Uitstekende warmtespreiding",
            "RVS-oppervlak met extra gebruiksgemak",
            "Sterke premium-positionering",
        ],
        "cons": [
            "Hoog geprijsd",
            "Voor veel thuiskoks meer dan nodig",
        ],
        "verdict": "Premium RVS-pan voor wie maximale prestaties en langdurige kwaliteit zoekt.",
    },
    "demeyere_multiline_7_28": {
        "slug": "demeyere-multiline-7-28",
        "name": "Demeyere Multiline 7 Koekenpan 28 cm",
        "description": "Topklasse 7-lagen RVS koekenpan met volledige warmteverdeling tot aan de rand, ideaal voor intensief gebruik.",
        "brand": "Demeyere",
        "diameter": 28,
        "material": "RVS",
        "features": [
            "7-lagenmateriaal",
            "Sterk op inductie",
            "Geschikt voor hoge baktemperaturen",
            "Ovenbestendig",
            "Vaatwasserbestendig",
        ],
        "rating": 4.9,
        "rating_count": 150,
        "price": 169.00,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/demeyere-multiline-7-koekenpan-28-cm/9300000192368989/?cid=1774512903816-6709989288509&bltgh=3100e097-0d5a-4cd0-a57b-a1a975111d65.ProductList_Middle.0.ProductTitle",
        "award": "⚡ Beste voor inductie",
        "price_range": "€€€",
        "image": "demeyere-multiline-7-28.jpg",
        "image_path": "images/products/rvs-koekenpannen",
        "pros": [
            "Zeer sterke reputatie op inductie",
            "Geschikt voor aanbakken en bruinen",
            "Duurzame RVS-constructie",
        ],
        "cons": [
            "Duidelijk premium geprijsd",
            "Minder vergevingsgezind dan keramisch",
        ],
        "verdict": "Sterke keuze voor wie vooral op inductie kookt en maximale bakprestaties zoekt.",
    },
    "debuyer_affinity_28": {
        "slug": "debuyer-affinity-28",
        "name": "De Buyer Affinity Koekenpan 28 cm",
        "description": "Professionele 5-lagen RVS koekenpan met snelle warmtegeleiding en precieze controle voor veeleisende koks.",
        "brand": "De Buyer",
        "diameter": 28,
        "material": "RVS 18/10",
        "features": [
            "18/10 RVS",
            "5-laags constructie",
            "Snelle temperatuurrespons",
            "Inductie",
            "Ovenbestendig",
        ],
        "rating": 4.7,
        "rating_count": 90,
        "price": 165.95,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/debuyer-affinity-koekenpan-o-28-cm/9200000015324060/?Referrer=ADVNLGOO002032-S--9200000015324060-PMAX-C-22285073469&gad_source=1&gad_campaignid=22295458996&gclid=CjwKCAjwhe3OBhABEiwA6392zKCzcUihW8X9OC1FqLrn1fWuyrjHmltZHAIzxaaczsQRdP6yxy0QRRoCWIoQAvD_BwE",
        "award": None,
        "price_range": "€€€",
        "image": "debuyer-affinity-28.jpg",
        "image_path": "images/products/rvs-koekenpannen",
        "pros": [
            "Zeer responsieve pan",
            "Hoogwaardige 5-laags constructie",
            "Mooie optie voor serieus kookwerk",
        ],
        "cons": [
            "Duur",
            "Minder logisch voor de gemiddelde koper",
        ],
        "verdict": "Premium RVS-keuze voor wie bewust voor techniek, controle en bouwkwaliteit gaat.",
    },
    "wmf_profi_28": {
        "slug": "wmf-profi-28",
        "name": "WMF Profi Koekenpan 28 cm",
        "description": "Degelijke RVS koekenpan met TransTherm-bodem voor gelijkmatige warmteverdeling en dagelijks gebruik.",
        "brand": "WMF",
        "diameter": 28,
        "material": "Cromargan RVS 18/10",
        "features": [
            "Cromargan 18/10",
            "TransTherm-bodem",
            "Alle warmtebronnen",
            "Inductie",
            "Ovenbestendig",
            "Vaatwasserbestendig",
        ],
        "rating": 4.6,
        "rating_count": 200,
        "price": 61.99,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/wmf-profi-koekenpan-o-28-cm/9200000055361082/?Referrer=ADVNLGOO002032-S--9200000055361082-PMAX-C-22285073469&gad_source=1&gad_campaignid=22295458996&gclid=CjwKCAjwhe3OBhABEiwA6392zC5p2lPz8Rjt14ZCaPm5caMM71Jns_9Fke0sQM60fTzjsfXQVleqJhoCGrsQAvD_BwE",
        "award": None,
        "price_range": "€€",
        "image": "wmf-profi-28.jpg",
        "image_path": "images/products/rvs-koekenpannen",
        "pros": [
            "Degelijk merk met sterke RVS-basis",
            "Praktische keuze voor dagelijks gebruik",
            "Goede balans tussen kwaliteit en prijs",
        ],
        "cons": [
            "Minder exclusief dan de topmodellen van Demeyere",
            "Niet de meest verfijnde warmtespreiding in dit overzicht",
        ],
        "verdict": "Goede middenklasse RVS-koekenpan voor wie een degelijk merk zoekt zonder direct topsegmentprijzen.",
    },
    "bk_superior_tri_ply_28": {
        "slug": "bk-superior-tri-ply-28",
        "name": "BK Superior Tri-Ply Koekenpan 28 cm",
        "description": "Betaalbare 3-laagse RVS koekenpan met goede warmteverdeling en solide prestaties voor dagelijks koken.",
        "brand": "BK",
        "diameter": 28,
        "material": "RVS",
        "features": [
            "3-ply constructie",
            "Snelle warmteverdeling",
            "PFAS-vrij",
            "Inductie",
            "Ovenbestendig",
            "Vaatwasserbestendig",
        ],
        "rating": 4.5,
        "rating_count": 140,
        "price": 70.00,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/bk-superior-triply-koekenpan-o-28-cm-rvs-inductie/9300000022010168/",
        "award": None,
        "price_range": "€€",
        "image": "bk-superior-tri-ply-28.jpg",
        "image_path": "images/products/rvs-koekenpannen",
        "pros": [
            "Mooie balans tussen prijs en prestaties",
            "Volledige RVS-positionering",
            "Geschikt voor dagelijks gebruik",
        ],
        "cons": [
            "Minder premium afgewerkt dan Demeyere",
            "Kortere staat van dienst dan klassieke toplijnen",
        ],
        "verdict": "Waarschijnlijk de interessantste keuze voor de gemiddelde koper die bewust naar RVS wil overstappen.",
    },
    "bk_bright_28": {
        "slug": "bk-bright-28",
        "name": "BK Bright Koekenpan 28 cm",
        "description": "Eenvoudige RVS koekenpan zonder coating, geschikt als instapmodel voor basisgebruik.",
        "brand": "BK",
        "diameter": 28,
        "material": "RVS",
        "features": [
            "Toegankelijke prijspositie",
            "RVS greep",
            "Inductie",
            "Vaatwasserbestendig",
        ],
        "rating": 4.3,
        "rating_count": 220,
        "price": 33.90,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/bk-bright-koekenpan-28-cm-rvs/9300000111596418/",
        "award": "💰 Budget keuze",
        "price_range": "€",
        "image": "bk-bright-28.jpg",
        "image_path": "images/products/rvs-koekenpannen",
        "pros": [
            "Toegankelijke instap in RVS",
            "Eenvoudig en praktisch",
            "Logische keuze voor wie wil testen of RVS bevalt",
        ],
        "cons": [
            "Minder verfijnde constructie dan tri-ply/topmodellen",
            "Niet de beste keuze voor maximale warmterespons",
        ],
        "verdict": "Goede budgetvriendelijke instapper voor wie een eenvoudige RVS-koekenpan zonder coating zoekt.",
    },
}
