PRODUCTS = {
    "inventum_gf500hld_5l": {
        "slug": "inventum_gf500hld_5l",
        "name": "Inventum GF500HLD Airfryer \u2013 5 L",
        "brand": "Inventum",
        "material": "Keramisch",
        "features": ["5 L", "PFAS-vrij keramisch", "Stil", "8 programma\u2019s"],
        "image": "airfryer-inventum-gf500hld-5l-pfasvrij-keramisch.jpg",
        "image_path": "images",
        "description": "Robuuste en gebruiksvriendelijke PFAS-vrije airfryer met een ruime 5-liter keramische binnenmand en gelijkmatige bakprestaties voor dagelijks gebruik.",
        "pros": [
            "PFAS-vrije keramische binnenmand",
            "Gelijkmatige en krachtige luchtcirculatie",
            "Overzichtelijk en eenvoudig digitaal bedieningspaneel",
        ],
        "cons": [
            "Behuizing kan warm worden tijdens gebruik",
            "Digitaal menu heeft relatief eenvoudige instellingen",
        ],
        "rating": 5,
        "rating_count": 210,
        "price": "109.99",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/inventum-gf500hld-airfryer-heteluchtfriteuse-beste-koop-november-2022-inhoud-5-liter-zwart-rvs/9200000114032192/?s2a=#productTitle",
        "price_range": "\u20ac\u20ac",
        "verdict": "Een uitstekende allround PFAS-vrije airfryer die dankzij zijn ruime capaciteit en keramische binnenmand ideaal is voor gezinnen en dagelijks gebruik.",
        "award": "🏆 Beste keuze",
    },
    "bourgini_slimfit_xl_5l": {
        "slug": "bourgini_slimfit_xl_5l",
        "name": "Bourgini Slimfit Airfryer XL \u2013 5 L",
        "brand": "Bourgini",
        "material": "Keramisch",
        "features": ["5 L", "PFAS-vrij keramisch", "Compact"],
        "image": "airfryer-bourgini-slimfit-5l-pfasvrij-keramisch.jpg",
        "image_path": "images",
        "description": "Een betaalbare PFAS-vrije airfryer met een ruime keramische binnenmand, ideaal voor gezinnen die veilig en gezond willen bakken zonder hoge kosten.",
        "pros": [
            "Keramische binnenmand zonder PFAS",
            "Ruim 5-liter formaat ideaal voor dagelijks gebruik",
            "Eenvoudige bediening met digitaal display",
        ],
        "cons": [
            "Behuizing voelt minder premium aan",
            "Minder functies dan duurdere modellen",
        ],
        "rating": 3.5,
        "rating_count": 130,
        "price": "79.70",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/bourgini-slimfit-airfryer-xl-hetelucht-friteuse-5-liter-1500w/9300000163583334/",
        "price_range": "\u20ac",
        "verdict": "De beste budgetvriendelijke PFAS-vrije keuze dankzij de ruime inhoud, de keramische coating en de solide prestaties.",
        "award": "💰 Beste budgetoptie",
    },
    "greenpan_silhouette_xl_5l": {
        "slug": "greenpan_silhouette_xl_5l",
        "name": "GreenPan Silhouette Airfryer XL \u2013 5 L",
        "brand": "GreenPan",
        "material": "Keramisch",
        "features": ["5 L", "Thermolon PFAS-vrij", "12 programma\u2019s"],
        "image": "airfryer-greenpan-silhouette-xl-5l-pfasvrij.jpg",
        "image_path": "images",
        "description": "Een hoogwaardige PFAS-vrije airfryer met GreenPan\u2019s Thermolon\u2122 keramische coating. Ontworpen voor gelijkmatige bakresultaten, hoge temperaturen en een stijlvol design voor elke keuken.",
        "pros": [
            "Thermolon\u2122 PFAS-vrije keramische binnenmand",
            "12 automatische kookprogramma\u2019s",
            "Stijlvol ontwerp in hoogwaardige afwerking",
        ],
        "cons": [
            "Iets hoger prijspunt",
            "Breder ontwerp neemt meer aanrechtruimte in",
        ],
        "rating": 4,
        "rating_count": 95,
        "price": "109.00",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/greenpan-silhouette-air-fryer-xl-5l-enkele-mand-tot-4-personen-pfas-vrij-12-programma-s-automatisch-uitschakelen-met-timerfunctie-moroccan-green/9300000241640428/",
        "price_range": "\u20ac\u20ac\u20ac",
        "verdict": "Een stijlvolle en volledig PFAS-vrije airfryer met uitstekende keramische prestaties en ruime capaciteit.",
        "award": "💎 Premium keuze",
    },
    "masterpro_rocket_cyclone_5l": {
        "slug": "masterpro_rocket_cyclone_5l",
        "name": "MasterPRO Rocket Cyclone 500 Airfryer \u2013 5 L",
        "brand": "MasterPRO",
        "material": "Keramisch",
        "features": ["5 L", "PFAS-vrij", "Cyclone-luchtcirculatie"],
        "image": "airfryer-masterpro-rocket-cyclone-500-5l-pfasvrij.jpg",
        "image_path": "images",
        "description": "Krachtige PFAS-vrije airfryer met een keramische binnenmand, effici\u00ebnte luchtcyclus en een solide, duurzame bouwkwaliteit die geschikt is voor dagelijks gebruik.",
        "pros": [
            "Volledig PFAS-vrije keramische coating",
            "Gelijkmatige luchtcirculatie door Cyclone-technologie",
            "Robuuste metalen behuizing",
        ],
        "cons": [
            "Display is minder intu\u00eftief",
            "Wordt iets zwaarder warm aan de buitenzijde",
        ],
        "rating": 4,
        "rating_count": 110,
        "price": "125.99",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.amazon.nl/-/en/MasterPRO-Cyclone-Capacity-Digital-Circulation/dp/B0F3P6FW2Y",
        "price_range": "\u20ac\u20ac",
        "verdict": "Een betrouwbare en krachtige PFAS-vrije airfryer met uitstekende luchtcirculatie en een duurzame keramische mand.",
        "award": "🥇 Meest gekozen",
    },
    "wartmann_wm2312af_5l": {
        "slug": "wartmann_wm2312af_5l",
        "name": "Wartmann WM-2312 AF \u2013 5 L",
        "brand": "Wartmann",
        "material": "Keramisch",
        "features": ["5 L", "PFAS-vrije keramische mand", "Stil"],
        "image": "airfryer-wartmann-wm2312af-5l-pfasvrij.jpg",
        "image_path": "images",
        "description": "Krachtige PFAS-vrije airfryer met een duurzame keramische binnenmand en stille werking. Ideaal voor dagelijks gebruik in middelgrote keukens.",
        "pros": [
            "Keramische PFAS-vrije binnenmand",
            "Zeer stille werking",
            "Robuuste bouwkwaliteit",
        ],
        "cons": [
            "Menu-instellingen zijn beperkt",
            "Behuizing is zwaarder dan gemiddeld",
        ],
        "rating": 4,
        "rating_count": 80,
        "price": "115.00",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/wartmann-airfryer-pfas-vrije-heteluchtfriteuse-met-kijkvenster-nieuw-model-5-7-liter-10-programma-s-1700-watt-zwart/9300000180236809/",
        "price_range": "\u20ac\u20ac",
        "verdict": "Een solide en stille PFAS-vrije airfryer die overtuigt door zijn duurzame keramische binnenmand en consistente resultaten.",
        "award": "🤫 Stilste model",
    },
    "maison_kitchen_5l": {
        "slug": "maison_kitchen_5l",
        "name": "Maison & Kitchen Airfryer \u2013 5 L",
        "brand": "Maison & Kitchen",
        "material": "Keramisch",
        "features": ["5 L", "PFAS-vrij keramisch", "Compact"],
        "image": "airfryer-maison-kitchen-5l-pfasvrij.jpg",
        "image_path": "images",
        "description": "Een toegankelijk geprijsde PFAS-vrije airfryer met een volledig keramische binnenmand en een compact ontwerp voor dagelijks gebruik.",
        "pros": [
            "Volledig PFAS-vrije keramische binnenmand",
            "Compact en licht ontwerp",
            "Gebruiksvriendelijk digitaal display",
        ],
        "cons": [
            "Minder duurzame kunststof behuizing",
            "Ventilatorgeluid iets hoger dan gemiddeld",
        ],
        "rating": 3.5,
        "rating_count": 60,
        "price": "59.00",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/maison-kitchen-airfryer-heteluchtfriteuse-pfas-vrij-1500w-5l-inhoud-80-c-tot-200-c-zwart/9300000197704759/",
        "price_range": "\u20ac",
        "verdict": "Een betaalbare PFAS-vrije airfryer met een ruime binnenmand en een eenvoudige bediening.",
        "award": "",
    },
}
