PRODUCTS = {
    "demeyere_industry_5_24": {
        "slug": "demeyere-industry-5-24",
        "name": "Demeyere Industry 5 Koekenpan 24 cm",
        "description": "Hoogwaardige 5-lagen RVS koekenpan met uitstekende warmteverdeling en duurzame constructie.",
        "brand": "Demeyere",
        "diameter": 24,
        "material": "RVS",
        "features": [
            "5-lagenmateriaal",
            "Warmteverdeling tot aan de rand",
            "Inductie",
            "Ovenbestendig",
            "Vaatwasserbestendig",
        ],
        "rating": 4.8,
        "rating_count": 0,
        "price": 128.90,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/demeyere-industry-5-rvs-koekenpan-koekenpan-inductie-24-cm-ptfe-vrij/9200000011477842/?cid=1776659016213-2891462213274&bltgh=fc8594e9-73db-4b3b-a235-8a18ecf62dc4.ProductList_Middle.0.ProductImage",
        "award": "🏆 Beste keuze",
        "price_range": "€€€",
        "image": "demeyere-industry-5-24.jpg",
        "image_path": "images/products/rvs-koekenpannen",
        "pros": [
            "Zeer gelijkmatige warmteverdeling",
            "Sterke reputatie voor serieus dagelijks gebruik",
            "Volledig RVS-uitvoering",
        ],
        "cons": [
            "Hogere instapprijs",
            "Heeft wat leercurve vergeleken met keramisch",
        ],
        "verdict": "Sterke allround RVS-koekenpan voor wie duurzaam en controlegericht wil bakken.",
    },
    "demeyere_multiline_7_24": {
        "slug": "demeyere-multiline-7-24",
        "name": "Demeyere Multiline 7 Koekenpan 24 cm",
        "description": "Topklasse 7-lagen RVS koekenpan met volledige warmteverdeling tot aan de rand, ideaal voor intensief gebruik.",
        "brand": "Demeyere",
        "diameter": 24,
        "material": "RVS",
        "features": [
            "7-lagenmateriaal",
            "Sterk op inductie",
            "Geschikt voor hoge baktemperaturen",
            "Ovenbestendig",
            "Vaatwasserbestendig",
        ],
        "rating": 4.9,
        "rating_count": 0,
        "price": 131.32,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/demeyere-multiline-koekenpan-o-24-cm/9200000059194177/?bltgh=8ca144d7-f79e-4d0c-82de-9c9d7e7abae2.ProductList_Middle.0.ProductImage&cid=1776660409041-1660992847878",
        "award": "💎 Premium keuze",
        "price_range": "€€€",
        "image": "demeyere-multiline-7-24.jpg",
        "image_path": "images/products/rvs-koekenpannen",
        "pros": [
            "Zeer sterke reputatie op inductie",
            "Geschikt voor aanbakken en bruinen",
            "Duurzame RVS-constructie",
        ],
        "cons": [
            "Duidelijk premium geprijsd",
            "Minder vergevingsgezind dan keramisch",
        ],
        "verdict": "Sterke keuze voor wie vooral op inductie kookt en maximale bakprestaties zoekt.",
    },
    "bk_superior_tri_ply_24": {
        "slug": "bk-superior-tri-ply-24",
        "name": "BK Superior Tri-Ply Koekenpan 24 cm",
        "description": "Betaalbare 3-laagse RVS koekenpan met goede warmteverdeling en solide prestaties voor dagelijks koken.",
        "brand": "BK",
        "diameter": 24,
        "material": "RVS",
        "features": [
            "3-ply constructie",
            "Snelle warmteverdeling",
            "Inductie",
            "Ovenbestendig",
            "Vaatwasserbestendig",
        ],
        "rating": 4.5,
        "rating_count": 0,
        "price": 65.00,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.meesterslijpers.nl/bk-superior-3-ply-koekenpan-24cm?srsltid=AfmBOopi4ooLgvTkbJBP9EYkoPWs6Clxt5xefRgt1j68yio5pJFxHEvk",
        "award": "💰 Budget keuze",
        "price_range": "€€",
        "image": "bk-superior-tri-ply-24.jpg",
        "image_path": "images/products/rvs-koekenpannen",
        "pros": [
            "Mooie balans tussen prijs en prestaties",
            "Volledige RVS-positionering",
            "Geschikt voor dagelijks gebruik",
        ],
        "cons": [
            "Minder premium afgewerkt dan Demeyere",
            "Kortere staat van dienst dan klassieke toplijnen",
        ],
        "verdict": "Waarschijnlijk de interessantste keuze voor de gemiddelde koper die bewust naar RVS wil overstappen.",
    },
    "debuyer_affinity_24": {
        "slug": "debuyer-affinity-24",
        "name": "De Buyer Affinity Koekenpan 24 cm",
        "description": "Professionele 5-lagen RVS koekenpan met snelle warmtegeleiding en precieze controle voor veeleisende koks.",
        "brand": "De Buyer",
        "diameter": 24,
        "material": "RVS 18/10",
        "features": [
            "18/10 RVS",
            "5-laags constructie",
            "Snelle temperatuurrespons",
            "Inductie",
            "Ovenbestendig",
        ],
        "rating": 4.7,
        "rating_count": 0,
        "price": 126.51,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/debuyer-affinity-koekenpan-o-24-cm/9200000015324056/?bltgh=32989719-32ab-44ee-a0a1-726bc0d40229.BuyBlock_distinctive-feature.0.FeatureListItem",
        "award": None,
        "price_range": "€€€",
        "image": "debuyer-affinity-24.jpg",
        "image_path": "images/products/rvs-koekenpannen",
        "pros": [
            "Zeer responsieve pan",
            "Hoogwaardige 5-laags constructie",
            "Mooie optie voor serieus kookwerk",
        ],
        "cons": [
            "Duur",
            "Minder logisch voor de gemiddelde koper",
        ],
        "verdict": "Premium RVS-keuze voor wie bewust voor techniek, controle en bouwkwaliteit gaat.",
    },
    "wmf_profi_24": {
        "slug": "wmf-profi-24",
        "name": "WMF Profi Koekenpan 24 cm",
        "description": "Degelijke RVS koekenpan met TransTherm-bodem voor gelijkmatige warmteverdeling en dagelijks gebruik.",
        "brand": "WMF",
        "diameter": 24,
        "material": "Cromargan RVS 18/10",
        "features": [
            "Cromargan 18/10",
            "TransTherm-bodem",
            "Alle warmtebronnen",
            "Inductie",
            "Ovenbestendig",
            "Vaatwasserbestendig",
        ],
        "rating": 4.6,
        "rating_count": 0,
        "price": 59.49,
        "currency": "EUR",
        "availability": "OutOfStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/wmf-profi-koekenpan-o-24-cm/9200000077125803/?cid=1776660174950-8074701362565&bltgh=469a5356-5d2e-440a-88f0-f6d568dd0dee.ProductList_Middle.1.ProductImage",
        "award": None,
        "price_range": "€€",
        "image": "wmf-profi-24.jpg",
        "image_path": "images/products/rvs-koekenpannen",
        "pros": [
            "Degelijk merk met sterke RVS-basis",
            "Praktische keuze voor dagelijks gebruik",
            "Goede balans tussen kwaliteit en prijs",
        ],
        "cons": [
            "Minder exclusief dan de topmodellen van Demeyere",
            "Niet de meest verfijnde warmtespreiding in dit overzicht",
        ],
        "verdict": "Goede middenklasse RVS-koekenpan voor wie een degelijk merk zoekt zonder direct topsegmentprijzen.",
    },
    "demeyere_silverline_7_nanotouch_24": {
        "slug": "demeyere-silverline-7-nanotouch-24",
        "name": "Demeyere Silverline 7 Koekenpan 24 cm",
        "description": "Premium 7-lagen RVS koekenpan met maximale warmtecontrole en professionele prestaties.",
        "brand": "Demeyere",
        "diameter": 24,
        "material": "RVS",
        "features": [
            "7-lagenmateriaal",
            "Inductie",
            "Ovenbestendig",
            "Vaatwasserbestendig",
        ],
        "rating": 4.9,
        "rating_count": 0,
        "price": 209.00,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.pannenhuis.nl/products/demeyere-silverline-7-nano-touch-koekenpan?variant=54983851934072",
        "award": None,
        "price_range": "€€€€",
        "image": "demeyere-silverline-7-24.jpg",
        "image_path": "images/products/rvs-koekenpannen",
        "pros": [
            "Uitstekende warmtespreiding",
            "RVS-oppervlak met extra gebruiksgemak",
            "Sterke premium-positionering",
        ],
        "cons": [
            "Hoog geprijsd",
            "Voor veel thuiskoks meer dan nodig",
        ],
        "verdict": "Premium RVS-pan voor wie maximale prestaties en langdurige kwaliteit zoekt.",
    },
    "bk_bright_24": {
        "slug": "bk-bright-24",
        "name": "BK Bright Koekenpan 24 cm",
        "description": "Eenvoudige RVS koekenpan, geschikt als instapmodel voor basisgebruik.",
        "brand": "BK",
        "diameter": 24,
        "material": "RVS",
        "features": [
            "Toegankelijke prijspositie",
            "RVS greep",
            "Inductie",
            "Vaatwasserbestendig",
        ],
        "rating": 4.3,
        "rating_count": 0,
        "price": 34.63,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/bk-bright-koekenpan-24-cm-rvs/9300000111921944/?bltgh=6d7949f8-9d6e-41ab-8daf-a8741202be9e.BuyBlock_distinctive-feature.0.FeatureListItem",
        "award": None,
        "price_range": "€",
        "image": "bk-bright-24.jpg",
        "image_path": "images/products/rvs-koekenpannen",
        "pros": [
            "Toegankelijke instap in RVS",
            "Eenvoudig en praktisch",
            "Logische keuze voor wie wil testen of RVS bevalt",
        ],
        "cons": [
            "Minder verfijnde constructie dan tri-ply/topmodellen",
            "Niet de beste keuze voor maximale warmterespons",
        ],
        "verdict": "Goede budgetvriendelijke instapper voor wie een eenvoudige RVS-koekenpan zoekt.",
    },

    # 28 cm RVS koekenpannen
    "demeyere_industry_5_28": {
        "slug": "demeyere-industry-5-28",
        "name": "Demeyere Industry 5 Koekenpan 28 cm",
        "description": "Hoogwaardige 5-lagen RVS koekenpan met uitstekende warmteverdeling en duurzame constructie zonder coating.",
        "brand": "Demeyere",
        "diameter": 28,
        "material": "RVS",
        "features": [
            "5-lagenmateriaal",
            "Warmteverdeling tot aan de rand",
            "Inductie",
            "Ovenbestendig",
            "Vaatwasserbestendig",
        ],
        "rating": 4.8,
        "rating_count": 120,
        "price": 145.00,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://braadbaas.nl/products/koekenpan-industry-5-gesloten-rand?variant=48993168261468",
        "award": "🏆 Beste keuze",
        "price_range": "€€€",
        "image": "demeyere-industry-5-28.jpg",
        "image_path": "images/products/rvs-koekenpannen",
        "pros": [
            "Zeer gelijkmatige warmteverdeling",
            "Sterke reputatie voor serieus dagelijks gebruik",
            "Volledig RVS zonder antiaanbaklaag",
        ],
        "cons": [
            "Hogere instapprijs",
            "Heeft wat leercurve vergeleken met keramisch",
        ],
        "verdict": "Sterke allround RVS-koekenpan voor wie duurzaam en controlegericht wil bakken.",
    },
    "demeyere_silverline_7_nanotouch_28": {
        "slug": "demeyere-silverline-7-nanotouch-28",
        "name": "Demeyere Silverline 7 Koekenpan NanoTouch 28 cm",
        "description": "Premium 7-lagen RVS koekenpan met maximale warmtecontrole en professionele prestaties zonder antiaanbaklaag.",
        "brand": "Demeyere",
        "diameter": 28,
        "material": "RVS",
        "features": [
            "7-lagenmateriaal",
            "NanoTouch-oppervlak",
            "PFAS-vrij",
            "Inductie",
            "Ovenbestendig",
            "Vaatwasserbestendig",
        ],
        "rating": 4.9,
        "rating_count": 80,
        "price": 229.00,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.pannenhuis.nl/products/demeyere-silverline-7-nano-touch-koekenpan?gad_source=1&gad_campaignid=21432908150&gclid=CjwKCAjwspPOBhB9EiwATFbi5A149zJ9c_Phs3IG8xeBNJyBZPYjZpzkri4Xk1KJh0Hcd3arhLzlfBoCoEEQAvD_BwE",
        "award": "💎 Premium keuze",
        "price_range": "€€€€",
        "image": "demeyere-silverline-7-28.jpg",
        "image_path": "images/products/rvs-koekenpannen",
        "pros": [
            "Uitstekende warmtespreiding",
            "RVS-oppervlak met extra gebruiksgemak",
            "Sterke premium-positionering",
        ],
        "cons": [
            "Hoog geprijsd",
            "Voor veel thuiskoks meer dan nodig",
        ],
        "verdict": "Premium RVS-pan voor wie maximale prestaties en langdurige kwaliteit zoekt.",
    },
    "demeyere_multiline_7_28": {
        "slug": "demeyere-multiline-7-28",
        "name": "Demeyere Multiline 7 Koekenpan 28 cm",
        "description": "Topklasse 7-lagen RVS koekenpan met volledige warmteverdeling tot aan de rand, ideaal voor intensief gebruik.",
        "brand": "Demeyere",
        "diameter": 28,
        "material": "RVS",
        "features": [
            "7-lagenmateriaal",
            "Sterk op inductie",
            "Geschikt voor hoge baktemperaturen",
            "Ovenbestendig",
            "Vaatwasserbestendig",
        ],
        "rating": 4.9,
        "rating_count": 150,
        "price": 169.00,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/demeyere-multiline-7-koekenpan-28-cm/9300000192368989/?cid=1774512903816-6709989288509&bltgh=3100e097-0d5a-4cd0-a57b-a1a975111d65.ProductList_Middle.0.ProductTitle",
        "award": "⚡ Beste voor inductie",
        "price_range": "€€€",
        "image": "demeyere-multiline-7-28.jpg",
        "image_path": "images/products/rvs-koekenpannen",
        "pros": [
            "Zeer sterke reputatie op inductie",
            "Geschikt voor aanbakken en bruinen",
            "Duurzame RVS-constructie",
        ],
        "cons": [
            "Duidelijk premium geprijsd",
            "Minder vergevingsgezind dan keramisch",
        ],
        "verdict": "Sterke keuze voor wie vooral op inductie kookt en maximale bakprestaties zoekt.",
    },
    "debuyer_affinity_28": {
        "slug": "debuyer-affinity-28",
        "name": "De Buyer Affinity Koekenpan 28 cm",
        "description": "Professionele 5-lagen RVS koekenpan met snelle warmtegeleiding en precieze controle voor veeleisende koks.",
        "brand": "De Buyer",
        "diameter": 28,
        "material": "RVS 18/10",
        "features": [
            "18/10 RVS",
            "5-laags constructie",
            "Snelle temperatuurrespons",
            "Inductie",
            "Ovenbestendig",
        ],
        "rating": 4.7,
        "rating_count": 90,
        "price": 165.95,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/debuyer-affinity-koekenpan-o-28-cm/9200000015324060/?Referrer=ADVNLGOO002032-S--9200000015324060-PMAX-C-22285073469&gad_source=1&gad_campaignid=22295458996&gclid=CjwKCAjwhe3OBhABEiwA6392zKCzcUihW8X9OC1FqLrn1fWuyrjHmltZHAIzxaaczsQRdP6yxy0QRRoCWIoQAvD_BwE",
        "award": None,
        "price_range": "€€€",
        "image": "debuyer-affinity-28.jpg",
        "image_path": "images/products/rvs-koekenpannen",
        "pros": [
            "Zeer responsieve pan",
            "Hoogwaardige 5-laags constructie",
            "Mooie optie voor serieus kookwerk",
        ],
        "cons": [
            "Duur",
            "Minder logisch voor de gemiddelde koper",
        ],
        "verdict": "Premium RVS-keuze voor wie bewust voor techniek, controle en bouwkwaliteit gaat.",
    },
    "wmf_profi_28": {
        "slug": "wmf-profi-28",
        "name": "WMF Profi Koekenpan 28 cm",
        "description": "Degelijke RVS koekenpan met TransTherm-bodem voor gelijkmatige warmteverdeling en dagelijks gebruik.",
        "brand": "WMF",
        "diameter": 28,
        "material": "Cromargan RVS 18/10",
        "features": [
            "Cromargan 18/10",
            "TransTherm-bodem",
            "Alle warmtebronnen",
            "Inductie",
            "Ovenbestendig",
            "Vaatwasserbestendig",
        ],
        "rating": 4.6,
        "rating_count": 200,
        "price": 84.00,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/wmf-profi-koekenpan-o-28-cm/9200000055361082/?Referrer=ADVNLGOO002032-S--9200000055361082-PMAX-C-22285073469&gad_source=1&gad_campaignid=22295458996&gclid=CjwKCAjwhe3OBhABEiwA6392zC5p2lPz8Rjt14ZCaPm5caMM71Jns_9Fke0sQM60fTzjsfXQVleqJhoCGrsQAvD_BwE",
        "award": None,
        "price_range": "€€",
        "image": "wmf-profi-28.jpg",
        "image_path": "images/products/rvs-koekenpannen",
        "pros": [
            "Degelijk merk met sterke RVS-basis",
            "Praktische keuze voor dagelijks gebruik",
            "Goede balans tussen kwaliteit en prijs",
        ],
        "cons": [
            "Minder exclusief dan de topmodellen van Demeyere",
            "Niet de meest verfijnde warmtespreiding in dit overzicht",
        ],
        "verdict": "Goede middenklasse RVS-koekenpan voor wie een degelijk merk zoekt zonder direct topsegmentprijzen.",
    },
    "bk_superior_tri_ply_28": {
        "slug": "bk-superior-tri-ply-28",
        "name": "BK Superior Tri-Ply Koekenpan 28 cm",
        "description": "Betaalbare 3-laagse RVS koekenpan met goede warmteverdeling en solide prestaties voor dagelijks koken.",
        "brand": "BK",
        "diameter": 28,
        "material": "RVS",
        "features": [
            "3-ply constructie",
            "Snelle warmteverdeling",
            "PFAS-vrij",
            "Inductie",
            "Ovenbestendig",
            "Vaatwasserbestendig",
        ],
        "rating": 4.5,
        "rating_count": 140,
        "price": 89.90,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://bk.nl/products/superior-tri-ply-koekenpan?variant=43657412280569",
        "award": None,
        "price_range": "€€",
        "image": "bk-superior-tri-ply-28.jpg",
        "image_path": "images/products/rvs-koekenpannen",
        "pros": [
            "Mooie balans tussen prijs en prestaties",
            "Volledige RVS-positionering",
            "Geschikt voor dagelijks gebruik",
        ],
        "cons": [
            "Minder premium afgewerkt dan Demeyere",
            "Kortere staat van dienst dan klassieke toplijnen",
        ],
        "verdict": "Waarschijnlijk de interessantste keuze voor de gemiddelde koper die bewust naar RVS wil overstappen.",
    },
    "bk_bright_28": {
        "slug": "bk-bright-28",
        "name": "BK Bright Koekenpan 28 cm",
        "description": "Eenvoudige RVS koekenpan zonder coating, geschikt als instapmodel voor basisgebruik.",
        "brand": "BK",
        "diameter": 28,
        "material": "RVS",
        "features": [
            "Toegankelijke prijspositie",
            "RVS greep",
            "Inductie",
            "Vaatwasserbestendig",
        ],
        "rating": 4.3,
        "rating_count": 220,
        "price": 41.09,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/bk-bright-koekenpan-28-cm-rvs/9300000111596418/",
        "award": "💰 Budget keuze",
        "price_range": "€",
        "image": "bk-bright-28.jpg",
        "image_path": "images/products/rvs-koekenpannen",
        "pros": [
            "Toegankelijke instap in RVS",
            "Eenvoudig en praktisch",
            "Logische keuze voor wie wil testen of RVS bevalt",
        ],
        "cons": [
            "Minder verfijnde constructie dan tri-ply/topmodellen",
            "Niet de beste keuze voor maximale warmterespons",
        ],
        "verdict": "Goede budgetvriendelijke instapper voor wie een eenvoudige RVS-koekenpan zonder coating zoekt.",
    },
}
