PRODUCTS = {
    # 20CM GIETIJZEREN KOEKENPANNEN

    "petromax_fp20_20": {
        "slug": "petromax-fp20-20",
        "name": "Petromax Gietijzeren Skillet",
        "description": "Robuuste gietijzeren koekenpan die vooraf is ingebrand "
        "en geschikt is voor gebruik op het fornuis, de barbecue en open vuur.",
        "brand": "Petromax",
        "diameter": 20,
        "material": "Gietijzer, vooringebrand",
        "features": [
            "Geschikt voor inductie",
            "Vooringebrand en direct klaar voor gebruik",
            "Geschikt voor barbecue en open vuur",
        ],
        "rating": 4.8,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 34.64,
        "price_last_checked": "2026-09-03",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Fpetromax-gietijzeren-skillet-o20cm-steel%2F9200000069193918%2F&name=Petromax%20gietijzeren%20pan%20met%20steel%20-%2020%20cm",
        "retailer_url": "https://www.bol.com/nl/nl/p/petromax-gietijzeren-skillet-o20cm-steel/9200000069193918/",
        "award": "🏆 Beste keuze",
        "price_range": "€€",
        "image": "petromax-fp20-20cm.webp",
        "image_path": "images/products/gietijzeren-koekenpannen",
        "pros": [
            "Vooringebrand en direct klaar voor gebruik",
            "Veelzijdig te gebruiken binnen en buiten",
        ],
        "cons": [
            "Relatief zwaar voor een pan van 20 cm",
            "Gietijzeren handgreep kan tijdens gebruik heet worden",
        ],
        "verdict": "Onze beste allround keuze voor wie een traditionele en "
        "veelzijdige gietijzeren koekenpan in compact formaat zoekt.",
    },

    "le_creuset_signature_skillet_20": {
        "slug": "le-creuset-signature-skillet-20",
        "name": "Le Creuset Signature Skillet",
        "description": "Premium gietijzeren koekenpan met duurzame zwarte "
        "emaillelaag aan de binnenzijde, hulphandgreep en twee schenktuiten.",
        "brand": "Le Creuset",
        "diameter": 20,
        "material": "Geëmailleerd gietijzer",
        "features": [
            "Geschikt voor inductie",
            "Geschikt voor ovengebruik",
            "Geëmailleerde binnenzijde",
            "Twee schenktuiten",
        ],
        "rating": 4.9,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 119.95,
        "price_last_checked": "2026-09-03",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Fle-creuset-signature-skillet-koekenpan-steelpan-vaatwasserbestendig-hulphandvat-geemailleerd-gietijzer-20cm-zwart%2F9300000020700536%2F&name=Le%20Creuset%20Skillet%20Signature%20-%20Mat%20Zwart%20-%20%C3%98%2020%20cm%20-%20Ge%C3%ABmailleerde%20Anti-aanbaklaag%20-...",
        "retailer_url": "https://www.bol.com/nl/nl/p/le-creuset-signature-skillet-koekenpan-steelpan-vaatwasserbestendig-hulphandvat-geemailleerd-gietijzer-20cm-zwart/9300000020700536/",
        "award": "💎 Premium keuze",
        "price_range": "€€€€",
        "image": "le-creuset-signature-skillet-20cm.webp",
        "image_path": "images/products/gietijzeren-koekenpannen",
        "pros": [
            "Hoeft niet te worden ingebrand",
            "Uitstekende warmteopslag en gelijkmatige warmteverdeling",
        ],
        "cons": [
            "Hoge aanschafprijs",
            "Relatief zwaar",
            "Emaillelaag vraagt zorgvuldiger gebruik dan onbehandeld gietijzer",
        ],
        "verdict": "Onze premium keuze voor wie de warmte-eigenschappen van "
        "gietijzer wil combineren met het onderhoudsgemak van emaille.",
    },

    "hendi_cast_iron_skillet_20": {
        "slug": "hendi-cast-iron-skillet-20",
        "name": "HENDI Gietijzeren Skillet",
        "description": "Scherp geprijsde traditionele gietijzeren koekenpan "
        "met twee schenktuiten en een relatief ruime bodem voor het formaat.",
        "brand": "HENDI",
        "diameter": 20,
        "material": "Gietijzer",
        "features": [
            "Geschikt voor inductie",
            "Ovenbestendig tot 220 °C",
            "Twee schenktuiten",
            "Bodemdiameter van 17 cm",
        ],
        "rating": 4.4,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 18.50,
        "price_last_checked": "2026-09-03",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Fhendi-gietijzeren-skillet-2-schenktuiten-o-200-mm-zwart-ovenveilig%2F9300000190443434%2F&name=HENDI%20Gietijzeren%20skillet%20%E2%80%93%202%20schenktuiten%20%E2%80%93%20%C3%98%20200%20mm%20%E2%80%93%20zwart%20%E2%80%93%20ovenveilig",
        "retailer_url": "https://www.bol.com/nl/nl/p/hendi-gietijzeren-skillet-2-schenktuiten-o-200-mm-zwart-ovenveilig/9300000190443434/",
        "award": "💰 Budget keuze",
        "price_range": "€",
        "image": "hendi-cast-iron-skillet-20cm.webp",
        "image_path": "images/products/gietijzeren-koekenpannen",
        "pros": [
            "Zeer scherpe aanschafprijs",
            "Relatief grote bakbodem voor een pan van 20 cm",
            "Geschikt voor fornuis en oven",
        ],
        "cons": [
            "Moet goed worden ingebrand",
            "Lagere maximale oventemperatuur dan sommige alternatieven",
        ],
        "verdict": "Onze budgetkeuze voor wie voor weinig geld een eenvoudige "
        "en functionele gietijzeren koekenpan zonder coating zoekt.",
    },

    "ronneby_bruk_ultra_light_pro_20": {
        "slug": "ronneby-bruk-ultra-light-pro-20",
        "name": "Ronneby Bruk Ultra Light Professional",
        "description": "Opvallend lichte gietijzeren koekenpan met gesmede "
        "stalen handgreep en een voorbehandeling met biologische koolzaadolie.",
        "brand": "Ronneby Bruk",
        "diameter": 20,
        "material": "Lichtgewicht gietijzer, vooringebrand met koolzaadolie",
        "features": [
            "Geschikt voor inductie",
            "Geschikt voor ovengebruik",
            "Vooringebrand",
            "Gewicht van circa 1 kg",
        ],
        "rating": 4.7,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 79.95,
        "price_last_checked": "2026-09-03",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Fronneby-bruk-ultra-light-professional-koekenpan-20-cm%2F9200000065363402%2F&name=Ronneby%20Bruk%20-%20Ultra%20Light%20Professional%20Koekenpan%20-%2020%20cm",
        "retailer_url": "https://www.bol.com/nl/nl/p/ronneby-bruk-ultra-light-professional-koekenpan-20-cm/9200000065363402/",
        "award": None,
        "price_range": "€€€",
        "image": "ronneby-bruk-ultra-light-pro-20cm.webp",
        "image_path": "images/products/gietijzeren-koekenpannen",
        "pros": [
            "Aanzienlijk lichter dan traditioneel gietijzer",
            "Vooringebrand en snel klaar voor gebruik",
            "Natuurlijke baklaag zonder kunstmatige coating",
        ],
        "cons": [
            "Relatief hoge aanschafprijs",
            "Blijft onderhoud en periodiek inbranden vereisen",
        ],
        "verdict": "Een uitstekende keuze voor wie de bakeigenschappen van "
        "gietijzer zoekt maar een traditionele gietijzeren pan te zwaar vindt.",
    },

    "lava_cast_iron_20": {
        "slug": "lava-cast-iron-20",
        "name": "Lava Gietijzeren Koekenpan",
        "description": "Compacte geëmailleerde gietijzeren koekenpan die de "
        "warmteopslag van gietijzer combineert met relatief eenvoudig onderhoud.",
        "brand": "Lava",
        "diameter": 20,
        "material": "Geëmailleerd gietijzer",
        "features": [
            "Geschikt voor inductie",
            "Geëmailleerde afwerking",
            "Inhoud van 0,77 liter",
            "Geschikt voor alle gangbare warmtebronnen",
        ],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 59.95,
        "price_last_checked": "2026-09-03",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/lava-koekenpan-20-cm-0-77-liter-gietijzer-zwart/9300000288620968/",
        "award": None,
        "price_range": "€€€",
        "image": "lava-cast-iron-20cm.webp",
        "image_path": "images/products/gietijzeren-koekenpannen",
        "pros": [
            "Minder onderhoud nodig dan onbehandeld gietijzer",
            "Goede warmteopslag",
            "Betaalbaarder dan meerdere premium geëmailleerde alternatieven",
        ],
        "cons": [
            "Duurder dan traditionele onbehandelde gietijzeren pannen",
            "Emaillelaag kan bij onzorgvuldig gebruik beschadigen",
        ],
        "verdict": "Een interessant middenklasse alternatief voor wie een "
        "geëmailleerde gietijzeren pan zoekt zonder direct voor een premiummerk te kiezen.",
    },

    "blackwell_cast_iron_20": {
        "slug": "blackwell-cast-iron-20",
        "name": "Blackwell Gietijzeren Koekenpan",
        "description": "Eenvoudige traditionele gietijzeren koekenpan zonder "
        "synthetische antiaanbaklaag voor bakken op hoge temperaturen.",
        "brand": "Blackwell",
        "diameter": 20,
        "material": "Gietijzer",
        "features": [
            "Geschikt voor inductie",
            "Geschikt voor ovengebruik",
            "Geschikt voor barbecue en open vuur",
            "Bodemdiameter van 16 cm",
        ],
        "rating": 4.2,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 17.99,
        "price_last_checked": "2026-09-03",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Fblackwell-koekenpan-gietijzer-o-20-cm-zonder-anti-aanbaklaag%2F9300000102316296%2F&name=Blackwell%20Gietijzeren%20koekenpan%20-%20Skillet%20-%2020%20cm%20-%20Zonder%20anti-aanbaklaag",
        "retailer_url": "https://www.bol.com/nl/nl/p/blackwell-koekenpan-gietijzer-o-20-cm-zonder-anti-aanbaklaag/9300000102316296/",
        "award": None,
        "price_range": "€",
        "image": "blackwell-cast-iron-20cm.webp",
        "image_path": "images/products/gietijzeren-koekenpannen",
        "pros": [
            "Zeer lage aanschafprijs",
            "Breed inzetbaar op fornuis, barbecue en open vuur",
            "Relatief laag gewicht van circa 1,1 kg",
        ],
        "cons": [
            "Moet voor goed gebruik worden ingebrand",
        ],
        "verdict": "Een eenvoudige en goedkope keuze voor wie vooral de klassieke "
        "eigenschappen van onbehandeld gietijzer zoekt.",
    },

    # 24CM GIETIJZEREN KOEKENPANNEN

    "skottsberg_cast_iron_24": {
        "slug": "skottsberg-cast-iron-24",
        "name": "Skottsberg Cast Iron",
        "description": "Lichtgewicht gietijzeren koekenpan die vooraf is ingebrand "
        "met natuurlijke olie en aanzienlijk lichter is dan traditioneel gietijzer.",
        "brand": "Skottsberg",
        "diameter": 24,
        "material": "Lichtgewicht gietijzer, vooringebrand met natuurlijke olie",
        "features": [
            "Geschikt voor inductie",
            "Tweemaal vooringebrand",
            "Geschikt voor oven en barbecue",
            "Gewicht van circa 1,2 kg",
        ],
        "rating": 4.8,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 59.99,
        "price_last_checked": "2026-09-03",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Fskottsberg-koekenpan-cast-iron-24-cm-gietijzer-pfas-vrij%2F9300000032265993%2F&name=Skottsberg%20Koekenpan%20Cast%20Iron%20-%20Gietijzeren%20pan%20-%20Inductie%20-%20%C3%B8%2024%20cm",
        "retailer_url": "https://www.bol.com/nl/nl/p/skottsberg-koekenpan-cast-iron-24-cm-gietijzer-pfas-vrij/9300000032265993/",
        "award": "🏆 Beste keuze",
        "price_range": "€€",
        "image": "skottsberg-cast-iron-24cm.webp",
        "image_path": "images/products/gietijzeren-koekenpannen",
        "pros": [
            "Veel lichter dan traditioneel gietijzer",
            "Vooringebrand en direct klaar voor gebruik",
            "Breed inzetbaar op fornuis, oven, barbecue en open vuur",
        ],
        "cons": [
            "Natuurlijke baklaag vraagt regelmatig onderhoud",
            "Niet geschikt voor zure ingrediënten",
        ],
        "verdict": "Onze beste allround keuze voor wie de bakeigenschappen van "
        "gietijzer wil combineren met een relatief laag gewicht en veel gebruiksgemak.",
    },

    "combekk_cast_iron_24": {
        "slug": "combekk-cast-iron-24",
        "name": "Combekk Gietijzeren Koekenpan",
        "description": "Geëmailleerde gietijzeren skillet met twee handgrepen, "
        "gemaakt van gerecycled gietijzer en direct klaar voor gebruik.",
        "brand": "Combekk",
        "diameter": 24,
        "material": "Geëmailleerd gerecycled gietijzer",
        "features": [
            "Geschikt voor inductie",
            "Geschikt voor oven en barbecue tot 260 °C",
            "Twee handgrepen",
        ],
        "rating": 4.7,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 66.95,
        "price_last_checked": "2026-09-03",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Fcombekk-sous-chef-koekenpan-24cm-2-grepen-zwart%2F9300000043289505%2F&name=ComBekk%20Sous%20Chef%20Gietijzeren%20Koekenpan%20%C3%98%2024cm%20-%20100%25%20gerecycled%20-%20PFAS-vrij",
        "retailer_url": "https://www.bol.com/nl/nl/p/combekk-sous-chef-koekenpan-24cm-2-grepen-zwart/9300000043289505/",
        "award": None,
        "price_range": "€€€",
        "image": "combekk-cast-iron-24cm.webp",
        "image_path": "images/products/gietijzeren-koekenpannen",
        "pros": [
            "Gemaakt van gerecycled gietijzer",
            "Emaillelaag hoeft niet te worden ingebrand",
            "Geschikt voor oven en barbecue tot 260 °C",
        ],
        "cons": [
            "Geen lange steel zoals bij een traditionele koekenpan",
            "Relatief zwaar",
        ],
        "verdict": "Een duurzame en onderhoudsvriendelijke keuze voor wie "
        "geëmailleerd gietijzer en een compact ontwerp met twee grepen waardeert.",
    },

    "ronneby_bruk_maestro_24": {
        "slug": "ronneby-bruk-maestro-24",
        "name": "Ronneby Bruk Maestro",
        "description": "Traditionele Zweedse gietijzeren koekenpan die met "
        "plantaardige olie is vooringebrand en tijdens gebruik een steeds "
        "betere natuurlijke baklaag ontwikkelt.",
        "brand": "Ronneby Bruk",
        "diameter": 24,
        "material": "Gietijzer, vooringebrand met plantaardige olie",
        "features": [
            "Geschikt voor inductie",
            "Vooringebrand",
            "Geschikt voor ovengebruik",
            "RVS handgreep",
        ],
        "rating": 4.7,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 85.00,
        "price_last_checked": "2026-09-03",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.kookpunt.nl/ronneby-bruk-maestro-koekenpan-24cm",
        "award": None,
        "price_range": "€€€",
        "image": "ronneby-bruk-maestro-24cm.webp",
        "image_path": "images/products/gietijzeren-koekenpannen",
        "pros": [
            "Traditionele solide gietijzeren constructie",
            "Vooringebrand en direct klaar voor gebruik",
            "Natuurlijke baklaag wordt beter door gebruik",
        ],
        "cons": [
            "Met circa 2,4 kg relatief zwaar",
        ],
        "verdict": "Een hoogwaardige traditionele keuze voor wie bewust voor "
        "massief gietijzer en een natuurlijke, herstelbare baklaag kiest.",
    },

    "skeppshult_walnut_24": {
        "slug": "skeppshult-walnut-24",
        "name": "Skeppshult Walnut",
        "description": "Handgemaakte gietijzeren koekenpan met "
        "walnoothouten handgreep en een natuurlijke voorbehandeling met "
        "biologische koolzaadolie.",
        "brand": "Skeppshult",
        "diameter": 24,
        "material": "Gietijzer, vooringebrand met biologische koolzaadolie",
        "features": [
            "Geschikt voor inductie",
            "Vooringebrand",
            "Walnoothouten handgreep",
            "Bodemdiameter van 20 cm",
        ],
        "rating": 4.8,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 149.00,
        "price_last_checked": "2026-09-03",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Fkoekenpan-skeppshult-walnoothout-handgreep-24-cm%2F9300000225400272%2F&name=Koekenpan%20Skeppshult%20Walnoothout%20Handgreep%2024%20cm",
        "retailer_url": "https://www.bol.com/nl/nl/p/koekenpan-skeppshult-walnoothout-handgreep-24-cm/9300000225400272/",
        "award": None,
        "price_range": "€€€€",
        "image": "skeppshult-walnut-24cm.webp",
        "image_path": "images/products/gietijzeren-koekenpannen",
        "pros": [
            "Ruime bodemdiameter van circa 20 cm",
            "Vooringebrand met natuurlijke koolzaadolie",
            "Hoogwaardige walnoothouten handgreep",
        ],
        "cons": [
            "Hoge aanschafprijs",
            "Met circa 2 kg duidelijk zwaarder dan lichtgewicht gietijzer",
            "Houten handgreep beperkt het gebruik in de oven",
        ],
        "verdict": "Een hoogwaardige keuze voor liefhebbers van traditioneel "
        "Zweeds gietijzer, natuurlijke materialen en een luxe afwerking.",
    },

    "staub_cast_iron_24": {
        "slug": "staub-cast-iron-24",
        "name": "Staub Koekenpan met Houten Handvat",
        "description": "Premium Franse gietijzeren koekenpan met matzwarte "
        "emaillelaag en een comfortabele beukenhouten handgreep.",
        "brand": "Staub",
        "diameter": 24,
        "material": "Geëmailleerd gietijzer",
        "features": [
            "Geschikt voor inductie",
            "Matzwarte geëmailleerde binnenzijde",
            "Beukenhouten handgreep",
            "Bodemdiameter van 17,9 cm",
        ],
        "rating": 4.9,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 108.99,
        "price_last_checked": "2026-09-03",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.vantende.nl/koekenpan-met-houten-steel-24cm-gietijzer-staub-27.html",
        "award": "💎 Premium keuze",
        "price_range": "€€€€",
        "image": "staub-cast-iron-24cm.webp",
        "image_path": "images/products/gietijzeren-koekenpannen",
        "pros": [
            "Hoogwaardige geëmailleerde afwerking",
            "Hoeft niet te worden ingebrand",
            "Houten handgreep wordt minder snel heet",
        ],
        "cons": [
            "Hoge aanschafprijs",
            "Houten handgreep beperkt gebruik in de oven",
            "Emaillelaag kan bij onzorgvuldig gebruik beschadigen",
        ],
        "verdict": "Onze premium keuze voor wie hoogwaardig Frans gietijzer "
        "wil combineren met een onderhoudsvriendelijke emaillelaag en houten greep.",
    },

    "maysternya_cast_iron_24": {
        "slug": "maysternya-cast-iron-24",
        "name": "Maysternya Gietijzeren Koekenpan",
        "description": "Betaalbare traditionele gietijzeren koekenpan met "
        "metalen handgreep en een eenvoudige constructie zonder synthetische coating.",
        "brand": "Maysternya",
        "diameter": 24,
        "material": "Gietijzer",
        "features": [
            "Geschikt voor inductie",
            "Metalen handgreep",
            "Geschikt voor alle gangbare warmtebronnen",
        ],
        "rating": 4.4,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 37.50,
        "price_last_checked": "2026-09-03",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Fmaysternya-koekenpan-gietijzer-o-24-x-4-cm-gietijzeren-pan-voor-alle-warmtebronnen-metalen-handvat-zwart%2F9300000143820514%2F&name=MAYSTERNYA%20Koekenpan%20Gietijzer%20-%20%C3%B8%2024%20x%204%20cm%20-%20Geschikt%20Voor%20Inductie%20-%20Gietijzeren...",
        "retailer_url": "https://www.bol.com/nl/nl/p/maysternya-koekenpan-gietijzer-o-24-x-4-cm-gietijzeren-pan-voor-alle-warmtebronnen-metalen-handvat-zwart/9300000143820514/",
        "award": "💰 Budget keuze",
        "price_range": "€€",
        "image": "maysternya-cast-iron-24cm.webp",
        "image_path": "images/products/gietijzeren-koekenpannen",
        "pros": [
            "Relatief toegankelijke aanschafprijs",
            "Traditioneel gietijzer zonder synthetische coating",
            "Metalen handgreep maakt de pan breed inzetbaar",
        ],
        "cons": [
            "Eenvoudigere afwerking dan de premium modellen",
            "Vraagt meer onderhoud dan geëmailleerd gietijzer",
        ],
        "verdict": "Onze budgetkeuze voor wie een traditionele gietijzeren "
        "koekenpan van 24 cm zoekt zonder direct naar het hogere prijssegment te gaan.",
    },

    # 26CM GIETIJZEREN KOEKENPANNEN

    "lodge_logic_26": {
        "slug": "lodge-logic-26",
        "name": "Lodge Logic",
        "description": "Klassieke gietijzeren koekenpan uit één stuk "
        "die vooraf is ingebrand en door gebruik een steeds betere natuurlijke "
        "baklaag ontwikkelt.",
        "brand": "Lodge",
        "diameter": 26,
        "material": "Ongeëmailleerd gietijzer, vooringebrand",
        "features": [
            "Geschikt voor inductie",
            "Vooringebrand",
            "Geschikt voor oven en barbecue",
            "Twee schenktuiten",
        ],
        "rating": 4.9,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 59.99,
        "price_last_checked": "2026-09-04",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Flodge-logic-koekenpan-o-26cm-gietijzer%2F9200000049766154%2F&name=Lodge%20Logic%20Koekenpan%20-%20%C3%98%2026cm%20-%20Gietijzer%20-%20Geschikt%20voor%20alle%20warmtebronnen",
        "retailer_url": "https://www.bol.com/nl/nl/p/lodge-logic-koekenpan-o-26cm-gietijzer/9200000049766154/",
        "award": "🏆 Beste keuze",
        "price_range": "€€",
        "image": "lodge-logic-26cm.webp",
        "image_path": "images/products/gietijzeren-koekenpannen",
        "pros": [
            "Uitstekende warmteopslag en geschikt voor hoge baktemperaturen",
            "Vooringebrand en direct klaar voor gebruik",
            "Volledig uit gietijzer en zeer duurzaam",
        ],
        "cons": [
            "Relatief zwaar",
            "Handgreep wordt tijdens gebruik heet",
        ],
        "verdict": "Onze beste allround keuze voor wie een traditionele en "
        "beproefde gietijzeren koekenpan voor jarenlang gebruik zoekt.",
    },

    "maysternya_cast_iron_26": {
        "slug": "maysternya-cast-iron-26",
        "name": "Maysternya Gietijzeren Koekenpan",
        "description": "Betaalbare traditionele gietijzeren koekenpan zonder "
        "synthetische antiaanbaklaag en met een afneembare houten handgreep.",
        "brand": "Maysternya",
        "diameter": 26,
        "material": "Ongeëmailleerd gietijzer",
        "features": [
            "Geschikt voor inductie",
            "Geen synthetische antiaanbaklaag",
            "Afneembare houten handgreep",
            "Geschikt voor alle gangbare warmtebronnen",
        ],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 38.95,
        "price_last_checked": "2026-09-04",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Fmaysternya-koekenpan-gietijzer-o-26-x-4-cm-gietijzeren-pan-voor-alle-warmtebronnen-houten-handvat-zwart%2F9300000143820515%2F&name=MAYSTERNYA%20Gietijzeren%20Koekenpan%20-%20%C3%B8%2026%20x%204%20cm%20-%20Geschikt%20Voor%20Inductie%20-%20Houten...",
        "retailer_url": "https://www.bol.com/nl/nl/p/maysternya-koekenpan-gietijzer-o-26-x-4-cm-gietijzeren-pan-voor-alle-warmtebronnen-houten-handvat-zwart/9300000143820515/",
        "award": "💰 Budget keuze",
        "price_range": "€€",
        "image": "maysternya-cast-iron-26cm.webp",
        "image_path": "images/products/gietijzeren-koekenpannen",
        "pros": [
            "Scherpe aanschafprijs",
            "Afneembare houten handgreep",
            "Geen synthetische antiaanbaklaag",
        ],
        "cons": [
            "Met circa 2,8 kg behoorlijk zwaar",
            "Moet worden ingebrand",
            "Eenvoudigere afwerking dan premiumalternatieven",
        ],
        "verdict": "Onze budgetkeuze voor wie voor relatief weinig geld een "
        "traditionele gietijzeren koekenpan van 26 cm zoekt.",
    },

    "combekk_classic_skillet_26": {
        "slug": "combekk-classic-skillet-26",
        "name": "Combekk Classic Skillet",
        "description": "Duurzame geëmailleerde gietijzeren koekenpan van "
        "gerecycled gietijzer die direct klaar is voor gebruik en geen "
        "traditioneel inbrandproces nodig heeft.",
        "brand": "Combekk",
        "diameter": 26,
        "material": "100% gerecycled geëmailleerd gietijzer",
        "features": [
            "Geschikt voor inductie",
            "100% gerecycled gietijzer",
            "Oven- en barbecuebestendig tot 260 °C",
        ],
        "rating": 4.7,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 73.09,
        "price_last_checked": "2026-09-04",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Fcombekk-gietijzeren-koekenpan-26cm-classic-skillet-100-gerecycled-pfas-vrij-geschikt-voor-inductie-zwart%2F9300000291682209%2F&name=Combekk%20Gietijzeren%20Koekenpan%2026cm%20-%20100%25%20Gerecycled%20-%20PFAS%20vrij%20-%20Geschikt%20voor%20o.a....",
        "retailer_url": "https://www.bol.com/nl/nl/p/combekk-gietijzeren-koekenpan-26cm-classic-skillet-100-gerecycled-pfas-vrij-geschikt-voor-inductie-zwart/9300000291682209/",
        "award": None,
        "price_range": "€€€",
        "image": "combekk-classic-skillet-26cm.webp",
        "image_path": "images/products/gietijzeren-koekenpannen",
        "pros": [
            "Emaillelaag hoeft niet te worden ingebrand",
            "Geschikt voor oven en barbecue tot 260 °C",
        ],
        "cons": [
            "Duurder dan traditioneel ongeëmailleerd gietijzer",
            "Emaillelaag kan bij onzorgvuldig gebruik beschadigen",
        ],
        "verdict": "Een bijzonder passende keuze voor wie duurzaamheid, "
        "onderhoudsgemak en de eigenschappen van gietijzer wil combineren.",
    },

    "fissler_moments_26": {
        "slug": "fissler-moments-26",
        "name": "Fissler Moments Collection",
        "description": "Moderne geëmailleerde gietijzeren koekenpan met een "
        "licht ruwe bakbodem voor krachtig aanbraden.",
        "brand": "Fissler",
        "diameter": 26,
        "material": "Geëmailleerd gietijzer",
        "features": [
            "Geschikt voor inductie",
            "Ovenbestendig tot 250 °C",
            "Geëmailleerde binnen- en buitenzijde",
        ],
        "rating": 4.7,
        "rating_count": None,
        "rating_source": "editorial",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "",
        "award": None,
        "price_range": "€€",
        "image": "fissler-moments-26cm-white.webp",
        "image_path": "images/products/gietijzeren-koekenpannen",
        "variants": [
            {
                "name": "Ivory White",
                "image": "fissler-moments-26cm-white.webp",
                "hex": "#FFFFF0",
                "affiliate_url": "https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Ffissler-moments-collection-koekenpan-26cm-ivory-white%2F9300000228004665%2F&name=Fissler%20Moments%20Collection%20-%20Koekenpan%20-%2026cm%20-%20ivory%20white",
                "retailer_url": "https://www.bol.com/nl/nl/p/fissler-moments-collection-koekenpan-26cm-ivory-white/9300000228004665/",
                "price": 59.00,
                "price_last_checked": "2026-09-04",
            },
            {
                "name": "Burgundy Red",
                "image": "fissler-moments-26cm-red.webp",
                "hex": "#800020",
                "affiliate_url":"https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Ffissler-moments-collection-koekenpan-26cm-burgundy-red-geschikt-voor-alle-warmtebronnen%2F9300000228066107%2F&name=Fissler%20Moments%20Collection%20-%20Koekenpan%20-%2026cm%20%E2%80%93%20Burgundy%20Red%20%E2%80%93%20Geschikt%20voor%20alle...",
                "retailer_url":"https://www.bol.com/nl/nl/p/fissler-moments-collection-koekenpan-26cm-burgundy-red-geschikt-voor-alle-warmtebronnen/9300000228066107/",
                "price": 55.00,
                "price_last_checked": "2026-09-04",
            },
        ],
        
        "pros": [
            "Emaillelaag maakt inbranden overbodig",
            "Geschikt voor ovengebruik tot 250 °C",
        ],
        "cons": [
            "Met circa 3,2 kg een zware koekenpan",
        ],
        "verdict": "Een interessante middenklasse keuze voor wie een moderne "
        "gietijzeren pan met emaille en ruime ovengeschiktheid zoekt.",
    },

    "staub_cast_iron_26": {
        "slug": "staub-cast-iron-26",
        "name": "Staub Koekenpan met Houten Handvat",
        "description": "Hoogwaardige Franse gietijzeren koekenpan met een "
        "matzwarte geëmailleerde binnenzijde en een houten handgreep die "
        "comfortabel blijft tijdens gebruik op het fornuis.",
        "brand": "Staub",
        "diameter": 26,
        "material": "Geëmailleerd gietijzer",
        "features": [
            "Geschikt voor inductie",
            "Matzwarte geëmailleerde binnenzijde",
            "Houten handgreep",
            "Inhoud van circa 1,7 liter",
        ],
        "rating": 4.8,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 149.00,
        "price_last_checked": "2026-09-04",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Fstaub-koekenpan-houten-steel-26cm%2F9200000075499665%2F&name=Staub%20Koekenpan%20-%20Zwart%20-%20%C3%B8%2026%20cm%20-%20ge%C3%ABmailleerde%20anti-aanbaklaag",
        "retailer_url": "https://www.bol.com/nl/nl/p/staub-koekenpan-houten-steel-26cm/9200000075499665/",
        "award": None,
        "price_range": "€€€€",
        "image": "staub-cast-iron-26cm.webp",
        "image_path": "images/products/gietijzeren-koekenpannen",
        "pros": [
            "Hoogwaardige geëmailleerde afwerking",
            "Hoeft niet te worden ingebrand",
            "Houten handgreep wordt minder snel heet",
            "Met circa 2,1 kg relatief handelbaar voor gietijzer",
        ],
        "cons": [
            "Relatief hoge aanschafprijs",
            "Emaillelaag kan bij onzorgvuldig gebruik beschadigen",
        ],
        "verdict": "Een hoogwaardige keuze voor wie de warmte-eigenschappen van "
        "gietijzer wil combineren met een luxe afwerking en comfortabele houten greep.",
    },

    "le_creuset_signature_skillet_26": {
        "slug": "le-creuset-signature-skillet-26",
        "name": "Le Creuset Signature Skillet",
        "description": "Premium Franse skillet van geëmailleerd gietijzer met "
        "matzwarte binnenzijde, twee schenktuiten en een volledig gietijzeren "
        "constructie voor fornuis en oven.",
        "brand": "Le Creuset",
        "diameter": 26,
        "material": "Geëmailleerd gietijzer",
        "features": [
            "Geschikt voor inductie",
            "Geschikt voor ovengebruik",
            "Matzwarte geëmailleerde binnenzijde",
            "Twee schenktuiten",
        ],
        "rating": 4.9,
        "rating_count": None,
        "rating_source": "editorial",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "",
        "award": "💎 Premium keuze",
        "price_range": "€€€€",
        "image": "le-creuset-signature-skillet-26cm-zwart.webp",
        "image_path": "images/products/gietijzeren-koekenpannen",
        "variants": [
            {
                "name": "Zwart",
                "image": "le-creuset-signature-skillet-26cm-zwart.webp",
                "hex": "#000000",
                "affiliate_url": "https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Fle-creuset-hoge-ronde-skillet-mat-zwart-26cm%2F9200000110073508%2F&name=Le%20Creuset%20Signature%20Skillet%20Pan%20-%20Gietijzeren%20koekenpan%20-%2026%20cm%20-%20Mat%20Zwart",
                "retailer_url": "https://www.bol.com/nl/nl/p/le-creuset-hoge-ronde-skillet-mat-zwart-26cm/9200000110073508/",
                "price": 160.99,
                "price_last_checked": "2026-09-04",
            },
            {
                "name": "Kersenrood",
                "image": "le-creuset-signature-skillet-26cm-kersenrood.webp",
                "hex": "#D2042D",
                "affiliate_url":"https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Fle-creuset-hoge-ronde-skillet-26cm-kersenrood%2F9200000109485609%2F&name=Le%20Creuset%20Skillet%20Hoog%2026%20cm%20Signature%20-%20Gietijzer%20-%20BBQ%20-%20Kersenrood",
                "retailer_url":"https://www.bol.com/nl/nl/p/le-creuset-hoge-ronde-skillet-26cm-kersenrood/9200000109485609/",
                "price": 154.00,
                "price_last_checked": "2026-09-04",
            },
            {
                "name": "Nectar",
                "image": "le-creuset-signature-skillet-26cm-nectar.webp",
                "hex": "#FF8656",
                "affiliate_url":"https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Fle-creuset-signature-hoge-ronde-skillet-nectar-o-26cm-2-0l%2F9300000160886687%2F&name=Le%20Creuset%20Skillet%20Signature%20-%20Nectar%20-%20%C3%B8%2026%20cm%20-%20ge%C3%ABmailleerde%20anti-aanbaklaag",
                "retailer_url":"https://www.bol.com/nl/nl/p/le-creuset-signature-hoge-ronde-skillet-nectar-o-26cm-2-0l/9300000160886687/",
                "price": 164.95,
                "price_last_checked": "2026-09-04",
            },
        ],
        "pros": [
            "Hoogwaardige en duurzame geëmailleerde constructie",
            "Hoeft niet te worden ingebrand",
            "Volledig geschikt voor gebruik in de oven",
            "Twee praktische schenktuiten",
        ],
        "cons": [
            "Relatief hoge aanschafprijs",
            "Emaillelaag vraagt zorgvuldiger gebruik dan kaal gietijzer",
        ],
        "verdict": "Onze premium keuze voor wie maximale afwerking en "
        "onderhoudsgemak zoekt zonder de karakteristieke warmteopslag van "
        "gietijzer op te geven.",
    },

    # 28CM GIETIJZEREN KOEKENPANNEN

    "skottsberg_cast_iron_28": {
        "slug": "skottsberg-cast-iron-28",
        "name": "Skottsberg Cast Iron",
        "description": "Lichtgewicht gietijzeren koekenpan die tweemaal is "
        "vooringebrand met natuurlijke olie en daardoor direct klaar is "
        "voor gebruik.",
        "brand": "Skottsberg",
        "diameter": 28,
        "material": "Lichtgewicht gietijzer, vooringebrand met natuurlijke olie",
        "features": [
            "Geschikt voor inductie",
            "Tweemaal vooringebrand",
            "Geschikt voor oven, barbecue en open vuur",
            "Gewicht van circa 1,5 kg",
        ],
        "rating": 4.9,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 69.99,
        "price_last_checked": "2026-09-05",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Fskottsberg-koekenpan-cast-iron-28-cm-gietijzer-pfas-vrij%2F9300000000270615%2F&name=Skottsberg%20-%20Koekenpan%20-%20Cast%20Iron%20-%20Gietijzer%20-%20Inductie%20-%2028%20cm%20-%20Gietijzeren%20pan%20-...",
        "retailer_url": "https://www.bol.com/nl/nl/p/skottsberg-koekenpan-cast-iron-28-cm-gietijzer-pfas-vrij/9300000000270615/",
        "award": "🏆 Beste keuze",
        "price_range": "€€€",
        "image": "skottsberg-cast-iron-28cm.webp",
        "image_path": "images/products/gietijzeren-koekenpannen",
        "pros": [
            "Veel lichter dan traditioneel gietijzer",
            "Vooringebrand en direct klaar voor gebruik",
            "Breed inzetbaar op fornuis, oven, barbecue en open vuur",
        ],
        "cons": [
            "Natuurlijke baklaag vraagt regelmatig onderhoud",
            "Minder geschikt voor langdurige bereiding van zure ingrediënten",
        ],
        "verdict": "Onze beste allround keuze voor wie de warmte-eigenschappen "
        "van gietijzer wil combineren met een relatief laag gewicht en "
        "veelzijdig gebruik.",
    },

    "kela_calido_28": {
        "slug": "kela-calido-28",
        "name": "Kela Calido",
        "description": "Robuuste gietijzeren koekenpan van 28 cm met goede "
        "warmteopslag en een klassieke constructie voor dagelijks gebruik "
        "op verschillende warmtebronnen.",
        "brand": "Kela",
        "diameter": 28,
        "material": "Gietijzer",
        "features": [
            "Geschikt voor inductie",
            "Geschikt voor ovengebruik",
            "Geschikt voor alle gangbare warmtebronnen",
        ],
        "rating": 4.4,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 59.95,
        "price_last_checked": "2026-09-05",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Fkoekenpan-o-28-cm-gietijzer-zwart-kela-calido%2F9300000153859680%2F&name=Koekenpan%2C%20%C3%98%2028%20cm%2C%20Gietijzer%2C%20Zwart%20-%20Kela",
        "retailer_url": "https://www.bol.com/nl/nl/p/koekenpan-o-28-cm-gietijzer-zwart-kela-calido/9300000153859680/",
        "award": "💰 Budget keuze",
        "price_range": "€€",
        "image": "kela-calido-28cm.webp",
        "image_path": "images/products/gietijzeren-koekenpannen",
        "pros": [
            "Relatief aantrekkelijke aanschafprijs",
            "Geschikt voor fornuis en oven",
        ],
        "cons": [
            "Zwaarder dan lichtgewicht gietijzeren alternatieven",
        ],
        "verdict": "Onze budgetkeuze voor wie een degelijke gietijzeren "
        "koekenpan van 28 cm zoekt tegen een relatief toegankelijke prijs.",
    },

    "beka_stark_28": {
        "slug": "beka-stark-28",
        "name": "Beka Stark",
        "description": "Stevige gietijzeren koekenpan met extra "
        "zijgreep, ontworpen voor krachtig aanbraden op het fornuis, "
        "in de oven of op de barbecue.",
        "brand": "Beka",
        "diameter": 28,
        "material": "Gietijzer",
        "features": [
            "Geschikt voor inductie",
            "Geschikt voor oven en barbecue",
            "Extra zijgreep",
        ],
        "rating": 4.7,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 69.00,
        "price_last_checked": "2026-09-05",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Fbeka-stark-braadpan-koekenpan-o-28-cm-met-zijgreep-gietijzer-pfas-vrij-geschikt-voor-inductie-bbq%2F9300000232241261%2F&name=Beka%20Stark%20braadpan%2Fkoekenpan%20-%20%C3%98%2028%20cm%20-%20Met%20zijgreep%20-%20Gietijzer%20-%20PFAS-vrij%20-...",
        "retailer_url": "https://www.bol.com/nl/nl/p/beka-stark-braadpan-koekenpan-o-28-cm-met-zijgreep-gietijzer-pfas-vrij-geschikt-voor-inductie-bbq/9300000232241261/",
        "award": None,
        "price_range": "€€€",
        "image": "beka-stark-28cm.webp",
        "image_path": "images/products/gietijzeren-koekenpannen",
        "pros": [
            "Extra zijgreep maakt de zware pan beter hanteerbaar",
            "Geschikt voor oven en barbecue",
        ],
        "cons": [
            "Relatief zwaar",
            "Gietijzeren grepen kunnen tijdens gebruik heet worden",
        ],
        "verdict": "Een veelzijdige keuze voor wie een robuuste gietijzeren "
        "pan zoekt die zowel in de keuken als op de barbecue kan worden gebruikt.",
    },

    "wmf_flavour_28": {
        "slug": "wmf-flavour-28",
        "name": "WMF Flavour",
        "description": "Geëmailleerde gietijzeren koekenpan met uitstekende "
        "warmteopslag en een onderhoudsvriendelijke binnen- en buitenzijde.",
        "brand": "WMF",
        "diameter": 28,
        "material": "Geëmailleerd gietijzer",
        "features": [
            "Geschikt voor inductie",
            "Geschikt voor ovengebruik",
            "Geëmailleerde binnen- en buitenzijde",
            "Inhoud van circa 3,4 liter",
        ],
        "rating": 4.7,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 68.00,
        "price_last_checked": "2026-09-05",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Fwmf-flavour-koekenpan-28cm-inductie%2F9300000225502255%2F&name=WMF%20Flavour%20-%20Koekenpan%20-%20%C3%9828%20cm%20-%20Inductie%20-%20Ronde%20Vorm%20-%20Geschikt%20voor%20Alle...",
        "retailer_url": "https://www.bol.com/nl/nl/p/wmf-flavour-koekenpan-28cm-inductie/9300000225502255/",
        "award": None,
        "price_range": "€€€",
        "image": "wmf-flavour-28cm.webp",
        "image_path": "images/products/gietijzeren-koekenpannen",
        "pros": [
            "Emaillelaag hoeft niet te worden ingebrand",
            "Uitstekende warmteopslag en gelijkmatige warmteverdeling",
            "Geschikt voor alle gangbare warmtebronnen en de oven",
        ],
        "cons": [
            "Zwaarder dan koekenpannen van staal of aluminium",
            "Emaillelaag vraagt zorgvuldigheid bij stoten en vallen",
        ],
        "verdict": "Een onderhoudsvriendelijke allrounder voor wie gietijzer "
        "wil gebruiken zonder de extra verzorging van een natuurlijke patinalaag.",
    },

    "lava_cast_iron_28": {
        "slug": "lava-cast-iron-28",
        "name": "Lava Gietijzeren Koekenpan",
        "description": "Ruime gietijzeren koekenpan met een inhoud van circa "
        "2,3 liter en goede warmteopslag voor grotere dagelijkse bereidingen.",
        "brand": "Lava",
        "diameter": 28,
        "material": "Gietijzer",
        "features": [
            "Geschikt voor inductie",
            "Geschikt voor alle gangbare warmtebronnen",
            "Inhoud van circa 2,3 liter",
            "Vaatwasserbestendig volgens de fabrikant",
        ],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 79.95,
        "price_last_checked": "2026-09-05",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Flava-koekenpan-28-cm-2-3-liter-gietijzer-zwart%2F9300000288620955%2F&name=Lava%20Koekenpan%20-%2028%20cm%20-%202.3%20liter%20-%20Gietijzer%20-%20Zwart",
        "retailer_url": "https://www.bol.com/nl/nl/p/lava-koekenpan-28-cm-2-3-liter-gietijzer-zwart/9300000288620955/",
        "award": None,
        "price_range": "€€€",
        "image": "lava-cast-iron-28cm.webp",
        "image_path": "images/products/gietijzeren-koekenpannen",
        "pros": [
            "Ruime inhoud voor een koekenpan van 28 cm",
            "Geschikt voor alle gangbare warmtebronnen",
        ],
        "cons": [
            "Relatief zwaar",
            "Duurder dan enkele vergelijkbare gietijzeren alternatieven",
        ],
        "verdict": "Een ruime en degelijk geprijsde gietijzeren keuze voor "
        "wie regelmatig grotere porties bereidt.",
    },

    "skeppshult_traditional_28": {
        "slug": "skeppshult-traditional-28",
        "name": "Skeppshult Traditional",
        "description": "Handgemaakte gietijzeren koekenpan die vooraf "
        "is ingebrand met biologische koolzaadolie en voorzien is van een "
        "houten handgreep.",
        "brand": "Skeppshult",
        "diameter": 28,
        "material": "Gietijzer, vooringebrand met biologische koolzaadolie",
        "features": [
            "Geschikt voor inductie",
            "Vooringebrand",
            "Handgemaakt in Zweden",
            "Houten handgreep",
        ],
        "rating": 4.8,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 195.00,
        "price_last_checked": "2026-09-05",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "",
        "official_url": "https://skeppshult.com/products/frying-pan-28-cm-traditional",
        "award": "💎 Premium keuze",
        "price_range": "€€€€",
        "image": "skeppshult-traditional-28cm.webp",
        "image_path": "images/products/gietijzeren-koekenpannen",
        "pros": [
            "Vooringebrand met biologische koolzaadolie",
            "Zeer solide constructie",
        ],
        "cons": [
            "Zeer hoge aanschafprijs",
            "Zwaar in vergelijking met lichtgewicht gietijzer",
            "Houten handgreep beperkt het gebruik in de oven",
        ],
        "verdict": "Onze premium keuze voor wie traditioneel Zweeds vakmanschap, "
        "natuurlijke materialen en een zeer duurzame gietijzeren constructie "
        "belangrijk vindt.",
    },

    # 30CM GIETIJZEREN KOEKENPANNEN

    "lodge_logic_30": {
        "slug": "lodge-logic-30",
        "name": "Lodge Logic",
        "description": "Klassieke gietijzeren koekenpan van circa "
        "30,5 cm die vooraf is ingebrand met plantaardige olie en geschikt "
        "is voor intensief gebruik binnen en buiten.",
        "brand": "Lodge",
        "diameter": 30,
        "material": "Ongeëmailleerd gietijzer, vooringebrand met plantaardige olie",
        "features": [
            "Geschikt voor inductie",
            "Geschikt voor oven, barbecue en open vuur",
        ],
        "rating": 4.9,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 69.95,
        "price_last_checked": "2026-09-05",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Flodge-12-inch-cast-iron-skillet%2F9200000050123402%2F&name=Lodge%20Gietijzeren%20koekenpan%20-%20%C3%98%2030%20cm%20-%20Geschikt%20voor%20alle%20warmtebronnen",
        "retailer_url": "https://www.bol.com/nl/nl/p/lodge-12-inch-cast-iron-skillet/9200000050123402/",
        "award": "🏆 Beste keuze",
        "price_range": "€€€",
        "image": "lodge-logic-30cm.webp",
        "image_path": "images/products/gietijzeren-koekenpannen",
        "pros": [
            "Vooringebrand en direct klaar voor gebruik",
            "Zeer robuuste constructie",
            "Veelzijdig inzetbaar op fornuis, oven, barbecue en open vuur",
        ],
        "cons": [
            "Relatief zwaar",
            "Natuurlijke baklaag vraagt regelmatig onderhoud",
            "Gietijzeren handgreep wordt tijdens gebruik heet",
        ],
        "verdict": "Onze beste allround keuze voor wie een grote, traditionele "
        "gietijzeren koekenpan zoekt met een bewezen constructie en zeer "
        "brede inzetbaarheid.",
    },

    "valhal_outdoor_vh30_30": {
        "slug": "valhal-outdoor-vh30-30",
        "name": "Valhal Outdoor VH30",
        "description": "Robuuste gietijzeren skillet van 30 cm met lange steel, "
        "hulpgreep en twee schenktuiten, voorbehandeld met plantaardige olie.",
        "brand": "Valhal Outdoor",
        "diameter": 30,
        "material": "Gietijzer, voorbehandeld met plantaardige olie",
        "features": [
            "Geschikt voor alle warmtebronnen",
            "Geschikt voor barbecue en open vuur",
            "Twee schenktuiten",
        ],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 41.95,
        "price_last_checked": "2026-09-05",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Fvalhal-outdoor-skillet-koekenpan-met-steel-gietijzer-diameter-30cm-vh30%2F9300000003060327%2F&name=Valhal%20Outdoor%20Skillet%20-%20Gietijzeren%20koekenpan%20met%20steel%20-%2030cm%20-%20VH30",
        "retailer_url": "https://www.bol.com/nl/nl/p/valhal-outdoor-skillet-koekenpan-met-steel-gietijzer-diameter-30cm-vh30/9300000003060327/",
        "award": "💰 Budget keuze",
        "price_range": "€€",
        "image": "valhal-outdoor-vh30-30cm.webp",
        "image_path": "images/products/gietijzeren-koekenpannen",
        "pros": [
            "Relatief scherpe aanschafprijs",
            "Voorbehandeld met natuurlijke plantaardige olie",
            "Breed inzetbaar binnen en buiten",
            "Hulpgreep maakt de grote pan beter hanteerbaar",
        ],
        "cons": [
            "Met circa 3,1 kg behoorlijk zwaar",
            "Voor de beste baklaag is verder inbranden aan te raden",
            "Steel wordt tijdens gebruik heet",
        ],
        "verdict": "Onze budgetkeuze voor wie voor een toegankelijke prijs een "
        "grote, traditionele gietijzeren skillet met brede inzetbaarheid zoekt.",
    },

    "petromax_fp30_30": {
        "slug": "petromax-fp30-30",
        "name": "Petromax Fire Skillet fp30",
        "description": "Zware gietijzeren skillet van 30 cm met steel en "
        "hulpgreep, ontworpen voor hoge temperaturen op het fornuis, "
        "de barbecue en boven open vuur.",
        "brand": "Petromax",
        "diameter": 30,
        "material": "Gietijzer",
        "features": [
            "Geschikt voor inductie",
            "Vooringebrand en direct klaar voor gebruik",
            "Geschikt voor barbecue en open vuur",
            "Bodemdiameter van circa 25 cm",
        ],
        "rating": 4.8,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 44.99,
        "price_last_checked": "2026-09-05",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Fpetromax-fp30-t-skillet-28-cm-pan-met-steel-gietijzer-zwart%2F9200000052946577%2F&name=Petromax%20Skillet%20fp30%20-%20Gietijzeren%20pan%20met%20steel%20-%2030%20cm%20-%202.5%20liter",
        "retailer_url": "https://www.bol.com/nl/nl/p/petromax-fp30-t-skillet-28-cm-pan-met-steel-gietijzer-zwart/9200000052946577/",
        "award": None,
        "price_range": "€€",
        "image": "petromax-fp30-30cm.webp",
        "image_path": "images/products/gietijzeren-koekenpannen",
        "pros": [
            "Vooringebrand en direct klaar voor gebruik",
            "Grote bakbodem van circa 25 cm",
            "Zeer geschikt voor hoge baktemperaturen",
            "Ook geschikt voor barbecue en open vuur",
        ],
        "cons": [
            "Met circa 3,7 kg zeer zwaar",
            "Gietijzeren handgreep wordt heet",
        ],
        "verdict": "Een uitstekende keuze voor wie een bijzonder robuuste "
        "gietijzeren pan zoekt voor zowel de keuken als intensief buitengebruik.",
    },

    "beka_stark_30": {
        "slug": "beka-stark-30",
        "name": "Beka Stark",
        "description": "Koekenpan van ongeëmailleerd gietijzer met "
        "RVS steel en extra zijgreep, vooraf voorzien van een natuurlijke patina.",
        "brand": "Beka",
        "diameter": 30,
        "material": "Ongeëmailleerd gietijzer met RVS handgreep",
        "features": [
            "Geschikt voor inductie",
            "Vooringebrand",
            "Geschikt voor oven en barbecue",
        ],
        "rating": 4.8,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 75.00,
        "price_last_checked": "2026-09-05",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Fbeka-stark-braadpan-koekenpan-o-30-cm-met-zijgreep-gietijzer-pfas-vrij-geschikt-voor-inductie-bbq%2F9300000232241257%2F&name=Beka%20Stark%20braadpan%2Fkoekenpan%20-%20%C3%98%2030%20cm%20-%20Met%20zijgreep%20-%20Gietijzer%20-%20PFAS-vrij%20-...",
        "retailer_url": "https://www.bol.com/nl/nl/p/beka-stark-braadpan-koekenpan-o-30-cm-met-zijgreep-gietijzer-pfas-vrij-geschikt-voor-inductie-bbq/9300000232241257/",
        "award": None,
        "price_range": "€€€",
        "image": "beka-stark-30cm.webp",
        "image_path": "images/products/gietijzeren-koekenpannen",
        "pros": [
            "Vooringebrand en direct klaar voor gebruik",
            "RVS steel wordt minder snel heet dan een gietijzeren steel",
            "Relatief licht voor een gietijzeren pan van 30 cm",
        ],
        "cons": [
            "Duurder dan verschillende traditionele gietijzeren alternatieven",
            "Natuurlijke baklaag vraagt onderhoud",
        ],
        "verdict": "Een sterke keuze voor wie traditioneel gietijzer wil combineren "
        "met een comfortabelere RVS steel.",
    },

    "koock_amsterdam_skillet_30": {
        "slug": "koock-amsterdam-skillet-30",
        "name": "Koock Amsterdam Skillet",
        "description": "Zware gietijzeren skillet van 30 cm zonder synthetische "
        "antiaanbaklaag, voorbewerkt met plantaardige olie en geschikt voor "
        "zowel binnen- als buitengebruik.",
        "brand": "Koock Amsterdam",
        "diameter": 30,
        "material": "Gietijzer, voorbewerkt met plantaardige olie",
        "features": [
            "Geschikt voor inductie",
            "Geschikt voor oven, barbecue en open vuur",
            "Voorbewerkt met plantaardige olie",
        ],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 44.95,
        "price_last_checked": "2026-09-05",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Fkoock-amsterdam-skillet-gietijzer-koekenpan-geschikt-voor-alle-warmtebronnen-incl-bbq-en-inductie%2F9300000006241960%2F&name=Koock%20Amsterdam%20Gietijzeren%20pan%20-%20Skillet%20koekenpan%20-%2030%20cm%20-%20PFAS%20vrij",
        "retailer_url": "https://www.bol.com/nl/nl/p/koock-amsterdam-skillet-gietijzer-koekenpan-geschikt-voor-alle-warmtebronnen-incl-bbq-en-inductie/9300000006241960/",
        "award": None,
        "price_range": "€€",
        "image": "koock-amsterdam-skillet-30cm.webp",
        "image_path": "images/products/gietijzeren-koekenpannen",
        "pros": [
            "Scherpe prijs voor een grote gietijzeren skillet",
            "Voorbewerkt met plantaardige olie",
            "Geschikt voor vrijwel alle warmtebronnen",
            "Los glazen deksel verkrijgbaar",
        ],
        "cons": [
            "Met circa 3,5 kg zwaar",
        ],
        "verdict": "Een aantrekkelijk geprijsde allrounder voor wie een ruime "
        "gietijzeren skillet voor keuken én buitengebruik zoekt.",
    },

    "victoria_signature_polished_30": {
        "slug": "victoria-signature-polished-30",
        "name": "Victoria Signature Polished",
        "description": "Premium gietijzeren koekenpan met gepolijst bakoppervlak, "
        "vooringebrand met lijnzaadolie en een verfijnd handvatontwerp met "
        "messing details.",
        "brand": "Victoria",
        "diameter": 30,
        "material": "Gepolijst sferisch gietijzer",
        "features": [
            "Vooringebrand met 100% lijnzaadolie",
            "Gepolijst bakoppervlak",
            "Messing details in de handgreep",
        ],
        "rating": 4.9,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 184.00,
        "price_last_checked": "2026-09-05",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.nordicnest.nl/merken/victoria_919176/signature-koekenpan-gepolijst-gietijzer-30-cm/",
        "award": "💎 Premium keuze",
        "price_range": "€€€€",
        "image": "victoria-signature-polished-30cm.webp",
        "image_path": "images/products/gietijzeren-koekenpannen",
        "pros": [
            "Gepolijst bakoppervlak voor een verfijndere afwerking",
            "Vooringebrand met natuurlijke lijnzaadolie",
            "Hoogwaardige materiaal- en handgreepafwerking",
            "Sterke warmteopslag van traditioneel gietijzer",
        ],
        "cons": [
            "Zeer hoge aanschafprijs",
            "Met circa 4 kg zwaar",
        ],
        "verdict": "Onze premium keuze voor wie traditionele gietijzeren "
        "bakeigenschappen wil combineren met een bijzonder hoogwaardige "
        "en verfijnde afwerking.",
    },
}
