PRODUCTS = {
    "inventum_gf500hld_5l": {
        "slug": "inventum-gf500hld-5l",
        "name": "Inventum GF500HLD Airfryer \u2013 5 L",
        "brand": "Inventum",
        "material": "Keramische binnenmand",
        "features": ["5 L", "PFAS-vrije keramische binnenmand", "Stille werking", "8 programma\u2019s", "Eenvoudig te reinigen"],
        "image": "airfryer-inventum-gf500hld-5l-pfasvrij-keramisch.jpg",
        "image_path": "images",
        "description": "Robuuste en gebruiksvriendelijke PFAS-vrije airfryer met een ruime 5-liter keramische binnenmand en gelijkmatige bakprestaties voor dagelijks gebruik.",
        "pros": [
            "PFAS-vrije keramische binnenmand zonder klassieke antiaanbaklaag",
            "Gelijkmatige garing zonder hotspots",
            "Relatief stil tijdens gebruik",
        ],
        "cons": [
            "Buitenzijde wordt merkbaar warm bij langere sessies",
            "Minder uitgebreide presets dan premium smart-modellen",
        ],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 89.00,
        "price_last_checked": "2026-06-08",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.expert.nl/inventum-gf500hld-xxl-372566678",
        "price_range": "\u20ac\u20ac",
        "verdict": "Waarschijnlijk de beste balans tussen veilige materialen, gebruiksgemak en prijs in het middensegment.",
        "award": "🏆 Beste keuze",
    },
    "bourgini_slimfit_xl_5l": {
        "slug": "bourgini-slimfit-xl-5l",
        "name": "Bourgini Slimfit Airfryer XL \u2013 5 L",
        "brand": "Bourgini",
        "material": "Keramische binnenmand",
        "features": ["5 L", "PFAS-vrij keramisch", "Compact"],
        "image": "airfryer-bourgini-slimfit-5l-pfasvrij-keramisch.jpg",
        "image_path": "images",
        "description": "Betaalbare airfryer met PFAS-vrije keramische binnenmand en compact ontwerp voor dagelijks gebruik.",
        "pros": [
            "Keramische binnenmand zonder PFAS",
            "Compact formaat ondanks ruime inhoud",
            "Interessante instapper voor prijsbewuste kopers",
        ],
        "cons": [
            "Luchtcirculatie minder krachtig dan premium modellen",
            "Kunststof afwerking voelt minder stevig aan ",
        ],
        "rating": 3.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 52.00,
        "price_last_checked": "2026-06-08",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/bourgini-slimfit-airfryer-xl-hetelucht-friteuse-5-liter-1500w/9300000163583334/",
        "price_range": "\u20ac",
        "verdict": "Een toegankelijke budgetkeuze voor wie een eenvoudige airfryer zonder klassieke tefloncoating zoekt.",
        "award": "💰 Budget keuze",
    },
    "greenpan_silhouette_xl_5l": {
        "slug": "greenpan-silhouette-xl-5l",
        "name": "GreenPan Silhouette Airfryer XL \u2013 5 L",
        "brand": "GreenPan",
        "material": "Keramische binnenmand",
        "features": ["5 L", "Thermolon keramische coating", "PFAS-vrij" "12 automatische programma\u2019s", "Premium afwerking"],
        "image": "airfryer-greenpan-silhouette-xl-5l-pfasvrij.jpg",
        "image_path": "images",
        "description": "Een hoogwaardige PFAS-vrije airfryer met GreenPan\u2019s Thermolon\u2122 keramische coating. Ontworpen voor gelijkmatige bakresultaten, hoge temperaturen en een stijlvol design voor elke keuken.",
        "pros": [
            "Thermolon\u2122 keramische binnenzijde zonder PFAS",
            "Veel automatische programma\u2019s voor veelzijdig gebruik",
            "Premium uitstraling en hoogwaardige afwerking",
        ],
        "cons": [
            "Neemt relatief veel ruimte in op het aanrecht",
            "Relatief hoger geprijsd dan basis airfryers",
        ],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 116.00,
        # "price_last_checked": "2026-06-08",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/greenpan-silhouette-air-fryer-xl-5l-enkele-mand-tot-4-personen-pfas-vrij-12-programma-s-automatisch-uitschakelen-met-timerfunctie-moroccan-green/9300000241640428/",
        "price_range": "\u20ac\u20ac\u20ac",
        "verdict": "Een premium PFAS-vrije airfryer voor wie veilige materialen wil combineren met design en uitgebreide functies.",
        "award": "💎 Premium keuze",
    },
    "masterpro_rocket_cyclone_5l": {
        "slug": "masterpro-rocket-cyclone-5l",
        "name": "MasterPRO Rocket Cyclone 500 Airfryer \u2013 5 L",
        "brand": "MasterPRO",
        "material": "Keramische binnenmand",
        "features": ["5 L", "PFAS-vrij", "Cyclone-luchtcirculatie"],
        "image": "airfryer-masterpro-rocket-cyclone-500-5l-pfasvrij.jpg",
        "image_path": "images",
        "description": "Krachtige airfryer met PFAS-vrije  keramische binnenzijde en sterke luchtcirculatie voor krokante bakresultaten.",
        "pros": [
            "Sterke luchtcirculatie voor gelijkmatige bereiding",
            "Keramische binnenzijde zonder klassieke antiaanbaklaag",
            "Stevigere metalen constructie dan veel budgetmodellen",
        ],
        "cons": [
            "Bediening vraagt iets meer gewenning",
            "Ventilatorgeluid hoorbaar op maximale stand",
        ],
        "rating": 4,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 127.26,
        "price_last_checked": "2026-06-08",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.amazon.nl/-/en/MasterPRO-Cyclone-Capacity-Digital-Circulation/dp/B0F3P6FW2Y",
        "price_range": "\u20ac\u20ac",
        "verdict": "Een krachtige PFAS-vrije airfryer met opvallend goede luchtcircularie en stevige bouwkwaliteit.",
        "award": "",
    },
    "wartmann_wm2312af_5l": {
        "slug": "wartmann-wm2312af-5l",
        "name": "Wartmann WM-2312 AF \u2013 5 L",
        "brand": "Wartmann",
        "material": "Keramische binnenmand",
        "features": ["5 L", "PFAS-vrije keramische binnenmand", "Extra stille werking", "Kijkvenster"],
        "image": "airfryer-wartmann-wm2312af-5l-pfasvrij.jpg",
        "image_path": "images",
        "description": "Krachtige PFAS-vrije airfryer met een duurzame keramische binnenmand en stille werking. Ideaal voor dagelijks gebruik in middelgrote keukens.",
        "pros": [
            "Opvallend stil tijdens gebruik",
            "Keramische binnenmand zonder PFAS",
            "Stevige en stabiele bouwkwaliteit",
        ],
        "cons": [
            "Minder uitgebreide menu-instellingen",
            "Relatief zwaar apparaat",
        ],
        "rating": 4,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 109.00,
        "price_last_checked": "2026-06-08",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/wartmann-airfryer-pfas-vrije-heteluchtfriteuse-met-kijkvenster-nieuw-model-5-7-liter-10-programma-s-1700-watt-zwart/9300000180236809/",
        "price_range": "\u20ac\u20ac",
        "verdict": "Een stille endegelijk gebouwde PFAS-vrije airfryer die vooral uitblinkt in dagelijks comfort.",
        "award": "🤫 Stilste model",
    },
    "maison_kitchen_5l": {
        "slug": "maison-kitchen-5l",
        "name": "Maison & Kitchen Airfryer \u2013 5 L",
        "brand": "Maison & Kitchen",
        "material": "Keramische binnenmand",
        "features": ["5 L", "PFAS-vrij keramisch", "Compact"],
        "image": "airfryer-maison-kitchen-5l-pfasvrij.jpg",
        "image_path": "images",
        "description": "Compacte budget-airfryer met keramische binnenmand voor wie betaalbaar PFAS-vrij wil koken.",
        "pros": [
            "Keramische binnenmand zonder PFAS",
            "Compact formaat",
            "Eenvoudige bediening",
        ],
        "cons": [
            "Minder consistente bakresultaten dan premium modellen",
            "Meer kunststof onderdelen dan duurdere alternatieven",
        ],
        "rating": 3,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 69.95,
        "price_last_checked": "2026-06-08",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.maisonandkitchen.nl/products/airfryer-5l-pfas-vrij?srsltid=AfmBOor1UaCOXsL_GZuvCm0mbRu2K7AxM_uSeys4YgkzwAOYw-8y8hYr",
        "price_range": "\u20ac",
        "verdict": "Een eenvoudige budget-airfryer voor wie vooral een betaalbare PFAS-vrije binnenmand zoekt.",
        "award": "",
    },
}
