PRODUCTS = {
    "demeyere_industry_5_24": {
        "slug": "demeyere-industry-5-24",
        "name": "Demeyere Industry 5 Koekenpan 24 cm",
        "description": "Hoogwaardige 5-lagen RVS koekenpan met uitstekende warmteverdeling en duurzame constructie.",
        "brand": "Demeyere",
        "diameter": 24,
        "material": "RVS",
        "features": [
            "5-lagenmateriaal",
            "Warmteverdeling tot aan de rand",
            "Inductie",
            "Ovenbestendig",
            "Vaatwasserbestendig",
        ],
        "rating": 4.8,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 117.00,
        "price_last_checked": "2026-07-30",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.bol.com/nl/nl/p/demeyere-industry-5-rvs-koekenpan-koekenpan-inductie-24-cm-ptfe-vrij/9200000011477842/",
        "award": "🏆 Beste keuze",
        "price_range": "€€€",
        "image": "demeyere-industry-5-24.jpg",
        "image_path": "images/products/rvs-koekenpannen",
        "pros": [
            "5-lagenmateriaal tot aan de rand",
            "Zeer gelijkmatige warmteverdeling",
            "Sterke allround prestaties op inductie",
        ],
        "cons": [
            "Relatief hoge instapprijs",
            "Vergt wat techniek voor optimaal gebruik",
        ],
        "verdict": "Sterke allround keuze voor wie dagelijks met RVS wil koken en lang met dezelfde pan vooruit wil.",
    },
    "demeyere_multiline_7_24": {
        "slug": "demeyere-multiline-7-24",
        "name": "Demeyere Multiline 7 Koekenpan 24 cm",
        "description": "Topklasse 7-lagen RVS koekenpan met volledige warmteverdeling tot aan de rand, ideaal voor intensief gebruik.",
        "brand": "Demeyere",
        "diameter": 24,
        "material": "RVS",
        "features": [
            "7-lagenmateriaal",
            "Sterk op inductie",
            "Geschikt voor hoge baktemperaturen",
            "Ovenbestendig",
            "Vaatwasserbestendig",
        ],
        "rating": 4.9,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 123.00,
        "price_last_checked": "2026-05-20",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/demeyere-multiline-koekenpan-o-24-cm/9200000059194177/?bltgh=8ca144d7-f79e-4d0c-82de-9c9d7e7abae2.ProductList_Middle.0.ProductImage&cid=1776660409041-1660992847878",
        "award": "💎 Premium keuze",
        "price_range": "€€€",
        "image": "demeyere-multiline-7-24.jpg",
        "image_path": "images/products/rvs-koekenpannen",
        "pros": [
            "Zeer sterke reputatie op inductie",
            "Geschikt voor aanbakken en bruinen",
            "Duurzame RVS-constructie",
        ],
        "cons": [
            "Meer prestaties dan veel gebruikers nodig hebben",
            "Vergt iets meer gewenning dan keramisch",
        ],
        "verdict": "Sterke keuze voor wie vooral op inductie kookt en maximale bakprestaties zoekt.",
    },
    "bk_superior_tri_ply_24": {
        "slug": "bk-superior-tri-ply-24",
        "name": "BK Superior Tri-Ply Koekenpan 24 cm",
        "description": "Betaalbare 3-laagse RVS koekenpan met goede warmteverdeling en solide prestaties voor dagelijks koken.",
        "brand": "BK",
        "diameter": 24,
        "material": "RVS",
        "features": [
            "3-ply constructie",
            "Snelle warmteverdeling",
            "Inductie",
            "Ovenbestendig",
            "Vaatwasserbestendig",
        ],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 65.00,
        "price_last_checked": "2026-05-20",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.meesterslijpers.nl/bk-superior-3-ply-koekenpan-24cm?srsltid=AfmBOopi4ooLgvTkbJBP9EYkoPWs6Clxt5xefRgt1j68yio5pJFxHEvk",
        "award": "💰 Budget keuze",
        "price_range": "€€",
        "image": "bk-superior-tri-ply-24.jpg",
        "image_path": "images/products/rvs-koekenpannen",
        "pros": [
            "Mooie balans tussen prijs en prestaties",
            "Volledige RVS-positionering",
            "Geschikt voor dagelijks gebruik",
        ],
        "cons": [
            "Warmteverdeling minder verfijnd dan premium modellen",
            "Afwerking eenvoudiger dan topsegment",
        ],
        "verdict": "Waarschijnlijk de interessantste keuze voor de gemiddelde koper die bewust naar RVS wil overstappen.",
    },
    "debuyer_affinity_24": {
        "slug": "debuyer-affinity-24",
        "name": "De Buyer Affinity Koekenpan 24 cm",
        "description": "Professionele 5-lagen RVS koekenpan met snelle warmtegeleiding en precieze controle voor veeleisende koks.",
        "brand": "De Buyer",
        "diameter": 24,
        "material": "RVS 18/10",
        "features": [
            "18/10 RVS",
            "5-laags constructie",
            "Snelle temperatuurrespons",
            "Inductie",
            "Ovenbestendig",
        ],
        "rating": 4.7,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 126.51,
        "price_last_checked": "2026-05-20",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/debuyer-affinity-koekenpan-o-24-cm/9200000015324056/?bltgh=32989719-32ab-44ee-a0a1-726bc0d40229.BuyBlock_distinctive-feature.0.FeatureListItem",
        "award": None,
        "price_range": "€€€",
        "image": "debuyer-affinity-24.jpg",
        "image_path": "images/products/rvs-koekenpannen",
        "pros": [
            "Zeer responsieve pan",
            "Hoogwaardige 5-laags constructie",
            "Mooie optie voor serieus kookwerk",
        ],
        "cons": [
            "Relatief duur",
            "Vooral interessant voor liefhebbers van technisch kookgerei",
        ],
        "verdict": "Interessante keuze voor wie veel waarde hecht aan snelle temperatuurreactie en nauwkeurige controle.",
    },
    "wmf_profi_24": {
        "slug": "wmf-profi-24",
        "name": "WMF Profi Koekenpan 24 cm",
        "description": "Degelijke RVS koekenpan met TransTherm-bodem voor gelijkmatige warmteverdeling en dagelijks gebruik.",
        "brand": "WMF",
        "diameter": 24,
        "material": "Cromargan RVS 18/10",
        "features": [
            "Cromargan 18/10",
            "TransTherm-bodem",
            "Alle warmtebronnen",
            "Inductie",
            "Ovenbestendig",
            "Vaatwasserbestendig",
        ],
        "rating": 4.6,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 58.02,
        "price_last_checked": "2026-05-20",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/wmf-profi-koekenpan-o-24-cm/9200000077125803/?cid=1776660174950-8074701362565&bltgh=469a5356-5d2e-440a-88f0-f6d568dd0dee.ProductList_Middle.1.ProductImage",
        "award": None,
        "price_range": "€€",
        "image": "wmf-profi-24.jpg",
        "image_path": "images/products/rvs-koekenpannen",
        "pros": [
            "Degelijke Cromargan RVS-constructie",
            "Goede prijs-kwaliteitverhouding",
            "Breed inzetbaar voor dagelijks gebruik",
        ],
        "cons": [
            "Minder exclusief dan de topmodellen van Demeyere",
            "Niet de meest verfijnde warmtespreiding in dit overzicht",
        ],
        "verdict": "Goede middenklasse RVS-koekenpan voor wie een degelijk merk zoekt zonder direct topsegmentprijzen.",
    },
    "demeyere_silverline_7_nanotouch_24": {
        "slug": "demeyere-silverline-7-nanotouch-24",
        "name": "Demeyere Silverline 7 Koekenpan 24 cm",
        "description": "Premium 7-lagen RVS koekenpan met maximale warmtecontrole en professionele prestaties.",
        "brand": "Demeyere",
        "diameter": 24,
        "material": "RVS",
        "features": [
            "7-lagenmateriaal",
            "Inductie",
            "Ovenbestendig",
            "Vaatwasserbestendig",
        ],
        "rating": 4.9,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 209.00,
        "price_last_checked": "2026-05-20",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.pannenhuis.nl/products/demeyere-silverline-7-nano-touch-koekenpan?variant=54983851934072",
        "award": None,
        "price_range": "€€€€",
        "image": "demeyere-silverline-7-24.jpg",
        "image_path": "images/products/rvs-koekenpannen",
        "pros": [
            "Uitstekende warmteverdeling",
            "NanoTouch-oppervlak voor extra gebruiksgemak",
            "Hoogwaardige afwerking",
        ],
        "cons": [
            "Hoog geprijsd",
            "Voor veel thuiskoks meer dan nodig",
        ],
        "verdict": "Premium RVS-pan voor wie maximale prestaties en langdurige kwaliteit zoekt.",
    },
    "bk_bright_24": {
        "slug": "bk-bright-24",
        "name": "BK Bright Koekenpan 24 cm",
        "description": "Eenvoudige RVS koekenpan, geschikt als instapmodel voor basisgebruik.",
        "brand": "BK",
        "diameter": 24,
        "material": "RVS",
        "features": [
               "RVS constructie",
               "RVS greep",
               "Inductie",
               "Vaatwasserbestendig",
        ],
        "rating": 4.3,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 40.29,
        "price_last_checked": "2026-05-20",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/bk-bright-koekenpan-24-cm-rvs/9300000111921944/?bltgh=6d7949f8-9d6e-41ab-8daf-a8741202be9e.BuyBlock_distinctive-feature.0.FeatureListItem",
        "award": None,
        "price_range": "€",
        "image": "bk-bright-24.jpg",
        "image_path": "images/products/rvs-koekenpannen",
        "pros": [
            "Toegankelijke instap in RVS",
            "Eenvoudig en praktisch",
            "Logische keuze voor wie wil testen of RVS bevalt",
        ],
        "cons": [
            "Minder verfijnde constructie dan tri-ply/topmodellen",
            "Niet de beste keuze voor maximale warmterespons",
        ],
        "verdict": "Goede budgetvriendelijke instapper voor wie een eenvoudige RVS-koekenpan zoekt.",
    },

    # 28 cm RVS koekenpannen
    "demeyere_industry_5_28": {
        "slug": "demeyere-industry-5-28",
        "name": "Demeyere Industry 5 Koekenpan 28 cm",
        "description": "Hoogwaardige 5-lagen RVS koekenpan met warmteverdeling tot aan de rand, geschikt voor dagelijks intensief gebruik.",
        "brand": "Demeyere",
        "diameter": 28,
        "material": "RVS",
        "features": [
            "5-lagenmateriaal",
            "Warmteverdeling tot aan de rand",
            "Inductie",
            "Ovenbestendig",
            "Vaatwasserbestendig",
        ],
        "rating": 4.8,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 145.00,
        "price_last_checked": "2026-05-20",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://braadbaas.nl/products/koekenpan-industry-5-gesloten-rand?variant=48993168261468",
        "award": "🏆 Beste keuze",
        "price_range": "€€€",
        "image": "demeyere-industry-5-28.jpg",
        "image_path": "images/products/rvs-koekenpannen",
        "pros": [
            "5-lagenmateriaal tot aan de rand",
            "Zeer gelijkmatige warmteverdeling",
            "Sterke allround prestaties op inductie",
        ],
        "cons": [
            "Relatief hoge instapprijs",
            "Vergt wat techniek voor optimaal gebruik",
        ],
        "verdict": "Sterke allround keuze voor wie dagelijks met RVS wil koken en lang met dezelfde pan vooruit wil.",
    },
    "demeyere_silverline_7_nanotouch_28": {
        "slug": "demeyere-silverline-7-nanotouch-28",
        "name": "Demeyere Silverline 7 Koekenpan NanoTouch 28 cm",
        "description": "Premium 7-lagen RVS koekenpan met maximale warmtecontrole en professionele prestaties zonder antiaanbaklaag.",
        "brand": "Demeyere",
        "diameter": 28,
        "material": "RVS",
        "features": [
            "7-lagenmateriaal",
            "NanoTouch-oppervlak",
            "PFAS-vrij",
            "Inductie",
            "Ovenbestendig",
            "Vaatwasserbestendig",
        ],
        "rating": 4.9,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 229.00,
        "price_last_checked": "2026-05-20",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.pannenhuis.nl/products/demeyere-silverline-7-nano-touch-koekenpan?gad_source=1&gad_campaignid=21432908150&gclid=CjwKCAjwspPOBhB9EiwATFbi5A149zJ9c_Phs3IG8xeBNJyBZPYjZpzkri4Xk1KJh0Hcd3arhLzlfBoCoEEQAvD_BwE",
        "award": "💎 Premium keuze",
        "price_range": "€€€€",
        "image": "demeyere-silverline-7-28.jpg",
        "image_path": "images/products/rvs-koekenpannen",
        "pros": [
            "Uitstekende warmteverdeling",
            "NanoTouch-oppervlak voor extra gebruiksgemak",
            "Hoogwaardige afwerking",
        ],
        "cons": [
            "Hoog prijsniveau",
            "Voor veel thuiskoks uitgebreider dan nodig",
        ],
        "verdict": "Topsegment keuze voor wie maximale prestaties, hoogwaardige afwerking en langdurige kwaliteit zoekt.",
    },
    "demeyere_multiline_7_28": {
        "slug": "demeyere-multiline-7-28",
        "name": "Demeyere Multiline 7 Koekenpan 28 cm",
        "description": "Topklasse 7-lagen RVS koekenpan met volledige warmteverdeling tot aan de rand, ideaal voor intensief gebruik.",
        "brand": "Demeyere",
        "diameter": 28,
        "material": "RVS",
        "features": [
            "7-lagenmateriaal",
            "Sterk op inductie",
            "Geschikt voor hoge baktemperaturen",
            "Ovenbestendig",
            "Vaatwasserbestendig",
        ],
        "rating": 4.9,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 169.00,
        "price_last_checked": "2026-05-20",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/demeyere-multiline-7-koekenpan-28-cm/9300000192368989/?cid=1774512903816-6709989288509&bltgh=3100e097-0d5a-4cd0-a57b-a1a975111d65.ProductList_Middle.0.ProductTitle",
        "award": None,
        "price_range": "€€€",
        "image": "demeyere-multiline-7-28.jpg",
        "image_path": "images/products/rvs-koekenpannen",
        "pros": [
            "Zeer sterk op inductie",
            "Geschikt voor krachtig aanbraden",
            "Duurzame 7-lagenconstructie",
        ],
        "cons": [
            "Meer prestaties dan veel gebruikers nodig hebben",
            "Vergt iets meer gewenning dan keramisch",
        ],
        "verdict": "Sterke keuze voor wie vooral op inductie kookt en veel controle over temperatuur wil.",
    },
    "debuyer_affinity_28": {
        "slug": "debuyer-affinity-28",
        "name": "De Buyer Affinity Koekenpan 28 cm",
        "description": "Professionele 5-lagen RVS koekenpan met snelle warmtegeleiding en precieze controle voor veeleisende koks.",
        "brand": "De Buyer",
        "diameter": 28,
        "material": "RVS 18/10",
        "features": [
            "18/10 RVS",
            "5-laags constructie",
            "Snelle temperatuurrespons",
            "Inductie",
            "Ovenbestendig",
        ],
        "rating": 4.7,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 165.95,
        "price_last_checked": "2026-05-20",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/debuyer-affinity-koekenpan-o-28-cm/9200000015324060/?Referrer=ADVNLGOO002032-S--9200000015324060-PMAX-C-22285073469&gad_source=1&gad_campaignid=22295458996&gclid=CjwKCAjwhe3OBhABEiwA6392zKCzcUihW8X9OC1FqLrn1fWuyrjHmltZHAIzxaaczsQRdP6yxy0QRRoCWIoQAvD_BwE",
        "award": None,
        "price_range": "€€€",
        "image": "debuyer-affinity-28.jpg",
        "image_path": "images/products/rvs-koekenpannen",
        "pros": [
            "Zeer responsieve pan",
            "Hoogwaardige 5-laags constructie",
            "Mooie optie voor serieus kookwerk",
        ],
        "cons": [
            "Relatief duur",
            "Vooral interessant voor liefhebbers van technisch kookgerei",
        ],
        "verdict": "Interessante keuze voor wie snelle temperatuurreactie en nauwkeurige controle belangrijk vindt.",
    },
    "wmf_profi_28": {
        "slug": "wmf-profi-28",
        "name": "WMF Profi Koekenpan 28 cm",
        "description": "Degelijke RVS koekenpan met TransTherm-bodem voor gelijkmatige warmteverdeling en dagelijks gebruik.",
        "brand": "WMF",
        "diameter": 28,
        "material": "Cromargan RVS 18/10",
        "features": [
            "Cromargan 18/10",
            "TransTherm-bodem",
            "Alle warmtebronnen",
            "Inductie",
            "Ovenbestendig",
            "Vaatwasserbestendig",
        ],
        "rating": 4.6,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 63.59,
        "price_last_checked": "2026-05-20",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/wmf-profi-koekenpan-o-28-cm/9200000055361082/?Referrer=ADVNLGOO002032-S--9200000055361082-PMAX-C-22285073469&gad_source=1&gad_campaignid=22295458996&gclid=CjwKCAjwhe3OBhABEiwA6392zC5p2lPz8Rjt14ZCaPm5caMM71Jns_9Fke0sQM60fTzjsfXQVleqJhoCGrsQAvD_BwE",
        "award": None,
        "price_range": "€€",
        "image": "wmf-profi-28.jpg",
        "image_path": "images/products/rvs-koekenpannen",
        "pros": [
            "Degelijke Cromargan RVS-constructie",
            "Goede prijs-kwaliteitverhouding",
            "Breed inzetbaar voor dagelijks koken",
        ],
        "cons": [
            "Warmteverdeling minder verfijnd dan meerlagen-RVS",
            "Minder gericht op intensief professioneel gebruik",
        ],
        "verdict": "Goede middenklasse RVS-koekenpan voor wie een degelijk merk zoekt zonder direct topsegmentprijzen.",
    },
    "bk_superior_tri_ply_28": {
        "slug": "bk-superior-tri-ply-28",
        "name": "BK Superior Tri-Ply Koekenpan 28 cm",
        "description": "Betaalbare 3-laagse RVS koekenpan met goede warmteverdeling en solide prestaties voor dagelijks koken.",
        "brand": "BK",
        "diameter": 28,
        "material": "RVS",
        "features": [
            "3-ply constructie",
            "Snelle warmteverdeling",
            "PFAS-vrij",
            "Inductie",
            "Ovenbestendig",
            "Vaatwasserbestendig",
        ],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 89.90,
        "price_last_checked": "2026-05-20",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://bk.nl/products/superior-tri-ply-koekenpan?variant=43657412280569",
        "award": None,
        "price_range": "€€",
        "image": "bk-superior-tri-ply-28.jpg",
        "image_path": "images/products/rvs-koekenpannen",
        "pros": [
            "Goede balans tussen prijs en prestaties",
            "Tri-ply constructie voor gelijkmatige warmte",
            "Geschikt voor dagelijks gebruik",
        ],
        "cons": [
            "Warmteverdeling minder verfijnd dan premium modellen",
            "Afwerking eenvoudiger dan topsegment",
        ],
        "verdict": "Waarschijnlijk de interessantste keuze voor de gemiddelde koper die bewust naar RVS wil overstappen.",
    },

    "bk_bright_28": {
        "slug": "bk-bright-28",
        "name": "BK Bright Koekenpan 28 cm",
        "description": "Eenvoudige RVS koekenpan zonder coating, geschikt als instapmodel voor basisgebruik.",
        "brand": "BK",
        "diameter": 28,
        "material": "RVS",
        "features": [
            "RVS constructie",
            "RVS greep",
            "Inductie",
            "Vaatwasserbestendig",
        ],
        "rating": 4.3,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 36.48,
        "price_last_checked": "2026-05-20",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/bk-bright-koekenpan-28-cm-rvs/9300000111596418/",
        "award": "💰 Budget keuze",
        "price_range": "€",
        "image": "bk-bright-28.jpg",
        "image_path": "images/products/rvs-koekenpannen",
        "pros": [
            "Zeer toegankelijke prijs",
            "Eenvoudige RVS-instapper",
            "Geschikt om RVS-koken uit te proberen",
        ],
        "cons": [
             "Minder verfijnde constructie dan tri-ply modellen",
             "Niet ideaal voor maximale warmterespons",
        ],
        "verdict": "Betaalbare instapkeuze voor wie een eenvoudige RVS-koekenpan zonder coating zoekt.",
    },
    
    # 20 cm RVS koekenpannen
    "demeyere_industry_5_20": {
        "slug": "demeyere-industry-5-20",
        "name": "Demeyere Industry 5 Koekenpan 20 cm",
        "description": "Compacte 5-lagen RVS koekenpan met warmteverdeling tot aan de rand, geschikt voor kleine porties en dagelijks intensief gebruik.",
        "brand": "Demeyere",
        "diameter": 20,
        "material": "RVS",
        "features": [
            "5-lagenmateriaal",
            "Warmteverdeling tot aan de rand",
            "Inductie",
            "Ovenbestendig",
            "Vaatwasserbestendig",
        ],
        "rating": 4.8,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 115.99,
        "price_last_checked": "2026-05-20",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://kookgigant.nl/products/demeyere-industry-5-koekenpan-20-cm?_abr=1&pb=0&srsltid=AfmBOoogkezb5DJpq5RO5nJKyFhgQOMp5g7IBoOTUcUlTXcBxW4FnSe0",
        "award": "🏆 Beste keuze",
        "price_range": "€€€",
        "image": "demeyere-industry-5-20.jpg",
        "image_path": "images/rvs-koekenpannen",
        "pros": [
            "Zeer gelijkmatige warmteverdeling",
            "5-lagenmateriaal tot aan de rand",
            "Sterke prestaties op inductie",
        ],
        "cons": [
            "Relatief hoge prijs voor een 20 cm-pan",
            "Vergt wat techniek voor optimaal gebruik",
        ],
        "verdict": "Sterke allround keuze voor wie een compacte RVS-pan zoekt met uitstekende prestaties en lange levensduur.",
    },
    "bk_superior_tri_ply_20": {
        "slug": "bk-superior-tri-ply-20",
        "name": "BK Superior Tri-Ply Koekenpan 20 cm",
        "description": "Compacte 3-laagse RVS koekenpan met snelle warmteopbouw en een goede balans tussen prijs en prestaties.",
        "brand": "BK",
        "diameter": 20,
        "material": "RVS",
        "features": [
            "3-ply constructie",
            "Snelle warmteverdeling",
            "Inductie",
            "Ovenbestendig",
            "Vaatwasserbestendig",
        ],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 55.29,
        "price_last_checked": "2026-05-20",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/bk-koekenpan-superior-tri-ply-o-20-cm-zonder-anti-aanbaklaag/9300000113331181/?Referrer=NLGOOFS&utm_source=google&utm_medium=free_shopping",
        "award": None,
        "price_range": "€€",
        "image": "bk-superior-tri-ply-20.jpg",
        "image_path": "images/rvs-koekenpannen",
        "pros": [
            "Goede prijs-kwaliteitverhouding",
            "Tri-ply constructie voor gelijkmatige warmte",
            "Geschikt voor dagelijks gebruik",
        ],
        "cons": [
            "Minder verfijnde afwerking dan premium modellen",
            "Warmteverdeling minder gelijkmatig dan 5- of 7-lagenconstructies",
        ],
        "verdict": "Goede instapkeuze voor wie wil overstappen naar RVS zonder direct in het topsegment te investeren.",
    },
    "sola_green_cooking_plus_20": {
        "slug": "sola-green-cooking-plus-20",
        "name": "Sola Green Cooking+ Koekenpan 20 cm",
        "description": "Betaalbare RVS koekenpan zonder coating, geschikt als toegankelijke instap voor PFAS-vrij koken.",
        "brand": "Sola",
        "diameter": 20,
        "material": "RVS (Tri-ply)",
        "features": [
            "Tri-ply constructie",
            "PFAS-vrij",
            "Inductie",
            "Ovenbestendig tot 200 °C",
            "Vaatwasserbestendig",
        ],
        "rating": 4.4,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 41.00,
        "price_last_checked": "2026-05-20",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/sola-koekenpan-green-cooking-o-20-cm-zilver-rvs-dubbelwandige-bodem/9300000038159469/",
        "award": "💰 Budget keuze",
        "price_range": "€",
        "image": "sola-green-cooking-plus-20.jpg",
        "image_path": "images/rvs-koekenpannen",
        "pros": [
            "Toegankelijke prijs",
            "Geen coating die kan slijten",
            "Breed verkrijgbaar",
        ],
        "cons": [
            "Minder verfijnde warmteverdeling dan premium modellen",
            "Minder geschikt voor zeer hoge bakprestaties",
        ],
        "verdict": "Geschikte budgetkeuze voor wie kennis wil maken met koken in een RVS-pan.",
    },
    "demeyere_multiline_7_20": {
        "slug": "demeyere-multiline-7-20",
        "name": "Demeyere Multiline 7 Koekenpan 20 cm",
        "description": "Premium 7-lagen RVS koekenpan met zeer nauwkeurige warmtecontrole en sterke prestaties op inductie.",
        "brand": "Demeyere",
        "diameter": 20,
        "material": "RVS",
        "features": [
            "7-lagenmateriaal",
            "Sterk op inductie",
            "Geschikt voor hoge baktemperaturen",
            "Ovenbestendig",
            "Vaatwasserbestendig",
        ],
        "rating": 4.9,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 145.00,
        "price_last_checked": "2026-05-20",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.zwilling.com/nl/demeyere-multiline-7-koekenpan-20-cm-40850-948-0/40850-948-0.html",
        "award": "💎 Premium keuze",
        "price_range": "€€€",
        "image": "demeyere-multiline-7-20.jpg",
        "image_path": "images/rvs-koekenpannen",
        "pros": [
            "Uitstekende warmteverdeling",
            "Sterke prestaties op inductie",
            "Duurzame meerlagenconstructie",
        ],
        "cons": [
            "Premium geprijsd",
            "Meer prestaties dan veel gebruikers nodig hebben",
        ],
        "verdict": "Premium keuze voor gebruikers die maximale controle en hoogwaardige afwerking zoeken.",
    },
    "wmf_profi_20": {
        "slug": "wmf-profi-20",
        "name": "WMF Profi Koekenpan 20 cm",
        "description": "Compacte RVS koekenpan met TransTherm-bodem voor gelijkmatige warmteverdeling en dagelijks gebruik.",
        "brand": "WMF",
        "diameter": 20,
        "material": "Cromargan RVS 18/10",
        "features": [
            "Cromargan 18/10",
            "TransTherm-bodem",
            "Alle warmtebronnen",
            "Inductie",
            "Ovenbestendig",
            "Vaatwasserbestendig",
        ],
        "rating": 4.6,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 40.54,
        "price_last_checked": "2026-05-20",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/wmf-profi-koekenpan-o-20-cm/9200000131544211/?cid=1779269128225-6537848141645&bltgh=d8e2b404-3e51-4082-8bed-89f797a4185e.ProductList_Middle.0.ProductImage",
        "award": None,
        "price_range": "€€",
        "image": "wmf-profi-20.jpg",
        "image_path": "images/rvs-koekenpannen",
        "pros": [
            "Goede balans tussen kwaliteit en prijs",
            "Degelijke Cromargan RVS-constructie",
            "Breed inzetbaar voor dagelijks koken",
        ],
        "cons": [
            "Warmteverdeling minder verfijnd dan meerlagen-RVS",
            "Minder gericht op intensief professioneel gebruik",
        ],
        "verdict": "Sterke middenklasse keuze voor wie een betrouwbare RVS-pan zoekt zonder premium prijsniveau.",
    },
    "debuyer_affinity_20": {
        "slug": "debuyer-affinity-20",
        "name": "De Buyer Affinity Koekenpan 20 cm",
        "description": "Professionele 5-lagen RVS koekenpan met snelle temperatuurrespons en nauwkeurige controle.",
        "brand": "De Buyer",
        "diameter": 20,
        "material": "RVS 18/10",
        "features": [
            "18/10 RVS",
            "5-laags constructie",
            "Snelle temperatuurrespons",
            "Inductie",
            "Ovenbestendig",
        ],
        "rating": 4.7,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 110.00,
        "price_last_checked": "2026-05-20",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/debuyer-affinity-koekenpan-o-20-cm/9200000015324040/?Referrer=ADVNLGOO002032-S--9200000015324040-PMAX-C-23800634150&gad_source=1&gad_campaignid=23805116566&gclid=CjwKCAjwt7XQBhBkEiwAtStpp30E3IRJ4kzvAtlWotTzMJm25w7hBzp16Uod1wyHP5Ccdrw19tpIMRoCIa8QAvD_BwE",
        "award": None,
        "price_range": "€€€",
        "image": "debuyer-affinity-20.jpg",
        "image_path": "images/rvs-koekenpannen",
        "pros": [
            "Snelle reactie op temperatuurveranderingen",
            "Hoogwaardige 5-laags constructie",
            "Sterke prestaties voor aanbraden",
        ],
        "cons": [
            "Relatief duur voor een kleine pan",
            "Minder interessant voor incidenteel gebruik",
        ],
        "verdict": "Interessante keuze voor gebruikers die professioneel kookgerei zoeken met veel controle.",
    },
    "demeyere_silverline_7_nanotouch_20": {
        "slug": "demeyere-silverline-7-nanotouch-20",
        "name": "Demeyere Silverline 7 Koekenpan NanoTouch 20 cm",
        "description": "Premium 7-lagen RVS koekenpan met NanoTouch-oppervlak en nauwkeurige warmtecontrole.",
        "brand": "Demeyere",
        "diameter": 20,
        "material": "RVS",
        "features": [
            "7-lagenmateriaal",
            "NanoTouch-oppervlak",
            "PFAS-vrij",
            "Inductie",
            "Ovenbestendig",
            "Vaatwasserbestendig",
        ],
        "rating": 4.9,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 189.00,
        "price_last_checked": "2026-05-20",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.zwilling.com/nl/demeyere-silverline-7-koekenpan-nanotouch-20-cm-60620/1032983.html?srsltid=AfmBOoqnaSWOk5cX7jBzakokfvHp9mCsl6u30-VlSpQJD4FcSnA3faHB",
        "award": None,
        "price_range": "€€€€",
        "image": "demeyere-silverline-7-20.jpg",
        "image_path": "images/rvs-koekenpannen",
        "pros": [
            "Uitstekende warmtespreiding",
            "NanoTouch-oppervlak voor extra gebruiksgemak",
            "Hoogwaardige afwerking",
        ],
        "cons": [
             "Hoog prijsniveau",
            "Voor veel gebruikers uitgebreider dan nodig",
        ],
        "verdict": "Topsegment keuze voor wie maximale prestaties en hoogwaardige afwerking belangrijk vindt.",
    }   
}
