PRODUCTS = {
    "inventum_gf500hld_5l": {
        "slug": "inventum-gf500hld-5l",
        "name": "Inventum GF500HLD Airfryer \u2013 5 L",
        "brand": "Inventum",
        "material": "Keramische binnenmand",
        "features": ["5 L", "PFAS-vrije keramische binnenmand", "Stille werking", "8 programma\u2019s", "Eenvoudig te reinigen"],
        "image": "airfryer-inventum-gf500hld-5l-pfasvrij-keramisch.jpg",
        "image_path": "images/airfryers",
        "description": "Robuuste en gebruiksvriendelijke PFAS-vrije airfryer met een ruime 5-liter keramische binnenmand en gelijkmatige bakprestaties voor dagelijks gebruik.",
        "pros": [
            "PFAS-vrije keramische binnenmand zonder klassieke antiaanbaklaag",
            "Gelijkmatige garing zonder hotspots",
            "Relatief stil tijdens gebruik",
        ],
        "cons": [
            "Buitenzijde wordt merkbaar warm bij langere sessies",
            "Minder uitgebreide presets dan premium smart-modellen",
        ],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 89.00,
        "price_last_checked": "2026-06-08",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.expert.nl/inventum-gf500hld-xxl-372566678",
        "price_range": "\u20ac\u20ac",
        "verdict": "Waarschijnlijk de beste balans tussen veilige materialen, gebruiksgemak en prijs in het middensegment.",
        "award": "🏆 Beste keuze",
    },
    "bourgini_slimfit_xl_5l": {
        "slug": "bourgini-slimfit-xl-5l",
        "name": "Bourgini Slimfit Airfryer XL \u2013 5 L",
        "brand": "Bourgini",
        "material": "Keramische binnenmand",
        "features": ["5 L", "PFAS-vrij keramisch", "Compact"],
        "image": "airfryer-bourgini-slimfit-5l-pfasvrij-keramisch.jpg",
        "image_path": "images/airfryers",
        "description": "Betaalbare airfryer met PFAS-vrije keramische binnenmand en compact ontwerp voor dagelijks gebruik.",
        "pros": [
            "Keramische binnenmand zonder PFAS",
            "Compact formaat ondanks ruime inhoud",
            "Interessante instapper voor prijsbewuste kopers",
        ],
        "cons": [
            "Luchtcirculatie minder krachtig dan premium modellen",
            "Kunststof afwerking voelt minder stevig aan ",
        ],
        "rating": 3.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 52.00,
        "price_last_checked": "2026-06-08",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/bourgini-slimfit-airfryer-xl-hetelucht-friteuse-5-liter-1500w/9300000163583334/",
        "price_range": "\u20ac",
        "verdict": "Een toegankelijke budgetkeuze voor wie een eenvoudige airfryer zonder klassieke tefloncoating zoekt.",
        "award": "💰 Budget keuze",
    },
    "greenpan_silhouette_xl_5l": {
        "slug": "greenpan-silhouette-xl-5l",
        "name": "GreenPan Silhouette Airfryer XL \u2013 5 L",
        "brand": "GreenPan",
        "material": "Keramische binnenmand",
        "features": ["5 L", "Thermolon keramische coating", "PFAS-vrij", "12 automatische programma\u2019s", "Premium afwerking"],
        "image": "airfryer-greenpan-silhouette-xl-5l-pfasvrij.jpg",
        "image_path": "images/airfryers",
        "variants": [
            {
                "name": "Moroccan Green",
                "image": "airfryer-greenpan-silhouette-xl-5l-pfasvrij.jpg",
                "hex": "#3a5a40",
                "affiliate_url": "https://www.bol.com/nl/nl/p/greenpan-silhouette-air-fryer-xl-5l-enkele-mand-tot-4-personen-pfas-vrij-12-programma-s-automatisch-uitschakelen-met-timerfunctie-moroccan-green/9300000241640428/",
                "price": 116.00,
                "price_last_checked": "2026-06-10",
            },
            {
                "name": "Cr\u00e8me",
                "image": "airfryer-greenpan-silhouette-xl-5l-pfasvrij-creme.jpg",
                "hex": "#e9dfd1",
                "affiliate_url":"https://www.kitchenandmore.nl/airfryer-silhouette-xl-greenpan-5l-creme?srsltid=AfmBOooCsBbsJd_gNW77z05-ls-X1qlR_GJOrEnivsIthvHuTDQZy9yG",
                "price": 139.90,
                "price_last_checked": "2026-06-10",
            },
            {
                "name": "Smokey Blue",
                "image": "airfryer-greenpan-silhouette-xl-5l-pfasvrij-smokey-blue.jpg",
                "hex": "#6b8a93",
                "affiliate_url":"https://greenpan.nl/products/silhouette-xl-air-fryer-5l-smokey-blue",
                "price": 129.90,
                "price_last_checked": "2026-06-10",
            },
        ],
        "description": "Een hoogwaardige PFAS-vrije airfryer met GreenPan\u2019s Thermolon\u2122 keramische coating. Ontworpen voor gelijkmatige bakresultaten, hoge temperaturen en een stijlvol design voor elke keuken.",
        "pros": [
            "Thermolon\u2122 keramische binnenzijde zonder PFAS",
            "Veel automatische programma\u2019s voor veelzijdig gebruik",
            "Premium uitstraling en hoogwaardige afwerking",
        ],
        "cons": [
            "Neemt relatief veel ruimte in op het aanrecht",
            "Relatief hoger geprijsd dan basis airfryers",
        ],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 129.90,
        "price_last_checked": "2026-06-10",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/greenpan-silhouette-air-fryer-xl-5l-enkele-mand-tot-4-personen-pfas-vrij-12-programma-s-automatisch-uitschakelen-met-timerfunctie-moroccan-green/9300000241640428/",
        "price_range": "\u20ac\u20ac\u20ac",
        "verdict": "Een premium PFAS-vrije airfryer voor wie veilige materialen wil combineren met design en uitgebreide functies.",
        "award": "💎 Premium keuze",
    },
    "masterpro_rocket_cyclone_5l": {
        "slug": "masterpro-rocket-cyclone-5l",
        "name": "MasterPRO Rocket Cyclone 500 Airfryer \u2013 5 L",
        "brand": "MasterPRO",
        "material": "Keramische binnenmand",
        "features": ["5 L", "PFAS-vrij", "Cyclone-luchtcirculatie"],
        "image": "airfryer-masterpro-rocket-cyclone-500-5l-pfasvrij.jpg",
        "image_path": "images/airfryers",
        "description": "Krachtige airfryer met PFAS-vrije  keramische binnenzijde en sterke luchtcirculatie voor krokante bakresultaten.",
        "pros": [
            "Sterke luchtcirculatie voor gelijkmatige bereiding",
            "Keramische binnenzijde zonder klassieke antiaanbaklaag",
            "Stevigere metalen constructie dan veel budgetmodellen",
        ],
        "cons": [
            "Bediening vraagt iets meer gewenning",
            "Ventilatorgeluid hoorbaar op maximale stand",
        ],
        "rating": 4,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 127.26,
        "price_last_checked": "2026-06-08",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.amazon.nl/-/en/MasterPRO-Cyclone-Capacity-Digital-Circulation/dp/B0F3P6FW2Y",
        "price_range": "\u20ac\u20ac",
        "verdict": "Een krachtige PFAS-vrije airfryer met opvallend goede luchtcircularie en stevige bouwkwaliteit.",
        "award": "",
    },
    "wartmann_wm2312af_5l": {
        "slug": "wartmann-wm2312af-5l",
        "name": "Wartmann WM-2312 AF \u2013 5 L",
        "brand": "Wartmann",
        "material": "Keramische binnenmand",
        "features": ["5 L", "PFAS-vrije keramische binnenmand", "Extra stille werking", "Kijkvenster"],
        "image": "airfryer-wartmann-wm2312af-5l-pfasvrij.jpg",
        "image_path": "images/airfryers",
        "description": "Krachtige PFAS-vrije airfryer met een duurzame keramische binnenmand en stille werking. Ideaal voor dagelijks gebruik in middelgrote keukens.",
        "pros": [
            "Opvallend stil tijdens gebruik",
            "Keramische binnenmand zonder PFAS",
            "Stevige en stabiele bouwkwaliteit",
        ],
        "cons": [
            "Minder uitgebreide menu-instellingen",
            "Relatief zwaar apparaat",
        ],
        "rating": 4,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 109.00,
        "price_last_checked": "2026-06-08",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/wartmann-airfryer-pfas-vrije-heteluchtfriteuse-met-kijkvenster-nieuw-model-5-7-liter-10-programma-s-1700-watt-zwart/9300000180236809/",
        "price_range": "\u20ac\u20ac",
        "verdict": "Een stille endegelijk gebouwde PFAS-vrije airfryer die vooral uitblinkt in dagelijks comfort.",
        "award": "🤫 Stilste model",
    },
    "maison_kitchen_5l": {
        "slug": "maison-kitchen-5l",
        "name": "Maison & Kitchen Airfryer \u2013 5 L",
        "brand": "Maison & Kitchen",
        "material": "Keramische binnenmand",
        "features": ["5 L", "PFAS-vrij keramisch", "Compact"],
        "image": "airfryer-maison-kitchen-5l-pfasvrij.jpg",
        "image_path": "images/airfryers",
        "description": "Compacte budget-airfryer met keramische binnenmand voor wie betaalbaar PFAS-vrij wil koken.",
        "pros": [
            "Keramische binnenmand zonder PFAS",
            "Compact formaat",
            "Eenvoudige bediening",
        ],
        "cons": [
            "Minder consistente bakresultaten dan premium modellen",
            "Meer kunststof onderdelen dan duurdere alternatieven",
        ],
        "rating": 3,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 69.95,
        "price_last_checked": "2026-06-08",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.maisonandkitchen.nl/products/airfryer-5l-pfas-vrij?srsltid=AfmBOor1UaCOXsL_GZuvCm0mbRu2K7AxM_uSeys4YgkzwAOYw-8y8hYr",
        "price_range": "€€",
        "verdict": "Een eenvoudige budget-airfryer voor wie vooral een betaalbare PFAS-vrije binnenmand zoekt.",
        "award": None,
    },
    "princess_182244_6l": {
       "slug": "princess-182244-6l",
       "name": "Princess 182244 Steam Aerofryer XXL – 6 L",
       "brand": "Princess",
       "material": "Keramische binnenmand",
       "features": [
           "6 L",
           "PFAS-vrije keramische coating",
           "Steam-functie",
           "XXL uitvoering"
       ],
       "image": "airfryer-princess-182244-6l.jpg",
       "image_path": "images/airfryers",
       "description": "Bijzonder veelzijdige PFAS-vrije airfryer met stoomfunctie en keramische binnenmand voor sappigere bereidingen en gezonder koken.",
       "pros": [
           "Steam-functie voor malsere resultaten",
           "PFAS-vrije keramische coating",
           "Veelzijdige bereidingsmogelijkheden",
       ],
       "cons": [
           "Complexer in gebruik dan standaard modellen",
           "Waterreservoir vraagt extra onderhoud",
       ],
       "rating": 4,
       "rating_count": None,
       "rating_source": "editorial",
       "price": 44.99,
       "price_last_checked": "2026-06-12",
       "currency": "EUR",
       "availability": "InStock",
       "affiliate_url": "https://www.bol.com/nl/nl/p/princess-01-182244-01-001-digitale-airfryer-6-l-zwart/9300000139335997/",
       "price_range": "€",
       "verdict": "Een innovatieve PFAS-vrije airfryer die stomen en airfryen combineert voor veelzijdiger en sappiger koken.",
       "award": None,
    },


# XL PFAS-VRIJE AIRFRYERS
    "inventum_gf730hldb_7_3l": {
       "slug": "inventum-gf730hldb-7-3l",
       "name": "Inventum GF730HLDB Airfryer – 7,3 L",
       "brand": "Inventum",
       "material": "Keramische binnenmand",
       "features": [
           "7,3 L",
           "PFAS-vrije keramische binnenmand",
           "XL capaciteit",
           "8 automatische programma’s"
       ],
       "image": "airfryer-inventum-gf730hldb-7-3l-pfasvrij.jpg",
       "image_path": "images/airfryers",
       "description": "Ruime PFAS-vrije airfryer met keramische binnenmand en krachtige luchtcirculatie, ontworpen voor gezinnen en grotere porties.",
       "pros": [
           "PFAS-vrije keramische binnenmand",
           "Ruime inhoud geschikt voor gezinnen",
           "Gelijkmatige bakprestaties",
       ],
       "cons": [
           "Neemt relatief veel aanrechtruimte in",
           "Display en menu ogen eenvoudig",
       ],
       "rating": 5,
       "rating_count": None,
       "rating_source": "editorial",
       "price": 109.00,
        "price_last_checked": "2026-06-12",
       "currency": "EUR",
       "availability": "InStock",
       "affiliate_url": "https://www.bol.com/nl/nl/p/inventum-gf730hldb-airfryer-hetelucht-friteuse-7-3-liter-stoomfunctie-crispfunctie-kijkvenster-40-tot-200-graden-timer-1450-watt-zwart/9300000243165173/?suggestionType=featured_product&cid=1781237455408-5164887014754",
       "price_range": "€€",
       "verdict": "Een van de beste XL PFAS-vrije airfryers dankzij de ruime inhoud, veilige keramische mand en betrouwbare dagelijkse prestaties.",
       "award": "🏆 Beste keuze",
    },
    "bourgini_slimfit_pure_8l": {
       "slug": "bourgini-slimfit-pure-8l",
       "name": "Bourgini Slimfit Health Fryer Pure – 8 L",
       "brand": "Bourgini",
       "material": "Keramische binnenmand",
       "features": [
           "8 L",
           "PFAS-vrije keramische binnenmand",
           "Compact XL ontwerp",
           "Digitale bediening"
       ],
       "image": "airfryer-bourgini-slimfit-pure-8l_zwart.jpg",
       "image_path": "images/airfryers",
        "variants": [
            {
                "name": "Zwart",
                "image": "airfryer-bourgini-slimfit-pure-8l_zwart.jpg",
                "hex": "#000000",
                "affiliate_url": "https://www.mediamarkt.nl/nl/product/_bourgini-slim-fit-health-fryer-pure-heteluchtfriteuse-zwart-1870234.html",
                "price": 113.99,
                "price_last_checked": "2026-06-12",
            },
            {
                "name": "Blauw",
                "image": "airfryer-bourgini-slimfit-pure-8l_blauw.jpg",
                "hex": "#0000ff",
                "affiliate_url":"https://www.mediamarkt.nl/nl/product/_bourgini-slim-fit-health-fryer-8l-pure-heteluchtfriteuse-blauw-1877202.html",
                "price": 139.99,
                "price_last_checked": "2026-06-12",
            },
            {
                "name": "Beige",
                "image": "airfryer-bourgini-slimfit-pure-8l_beige.jpg",
                "hex": "#f5f5dc",
                "affiliate_url":"https://www.mediamarkt.nl/nl/product/_bourgini-slim-fit-health-fryer-8l-pure-heteluchtfriteuse-beige-1877203.html",
                "price": 139.99,
                "price_last_checked": "2026-06-12",
            },
        ],
       "description": "Extra ruime PFAS-vrije airfryer met keramische binnenmand en relatief compact ontwerp voor zijn inhoud.",
       "pros": [
           "Zeer ruime 8 liter inhoud",
           "PFAS-vrije keramische binnenmand",
           "Relatief compact ontwerp voor XL formaat",
       ],
       "cons": [
           "Behuizing voelt minder premium aan",
           "Ventilatorgeluid hoorbaar op hogere standen",
       ],
       "rating": 4,
       "rating_count": None,
       "rating_source": "editorial",
       "price": 113.99,
       "currency": "EUR",
       "availability": "InStock",
       "affiliate_url": "https://www.mediamarkt.nl/nl/product/_bourgini-slim-fit-health-fryer-pure-heteluchtfriteuse-zwart-1870234.html",
       "price_range": "€€",
       "verdict": "Een aantrekkelijke XL keuze voor grotere huishoudens die veel capaciteit zoeken zonder premium prijskaartje.",
       "award": "💰 Budget keuze",
    },
    "greenpan_bistro_xl_7_2l": {
       "slug": "greenpan-bistro-xl-7-2l",
       "name": "GreenPan Bistro XL Airfryer – 7,2 L",
       "brand": "GreenPan",
       "material": "Keramische binnenmand",
       "features": [
           "7,2 L",
           "Thermolon™ keramische coating",
           "PFAS-vrij",
           "Meerdere automatische programma’s"
       ],
       "image": "airfryer-greenpan-bistro-xl-7-2l.jpg",
       "image_path": "images/airfryers",
       "description": "Stijlvolle PFAS-vrije XL airfryer met GreenPan’s Thermolon™ keramische coating en ruime capaciteit voor dagelijks gezinskoken.",
       "pros": [
           "Hoogwaardige Thermolon™ keramische coating",
           "Ruime XL inhoud",
           "Stijlvolle premium afwerking",
       ],
       "cons": [
           "Hoger geprijsd dan veel concurrenten",
           "Breder ontwerp vraagt meer ruimte",
       ],
       "rating": 4.5,
       "rating_count": None,
       "rating_source": "editorial",
       "price": 136.00,
       "price_last_checked": "2026-06-12",
       "currency": "EUR",
       "availability": "InStock",
       "affiliate_url": "https://www.bol.com/nl/nl/p/greenpan-bistro-xl-airfryer-7-2l-11-programma-s-zwart-pfas-vrij/9300000157443808/",
       "price_range": "€€€",
       "verdict": "Een premium PFAS-vrije XL airfryer met uitstekende bouwkwaliteit en sterke bakprestaties voor dagelijks gebruik.",
       "award": "💎 Premium keuze",
    },
    "greenpan_bistro_xxl_7_2l": {
       "slug": "greenpan-bistro-xxl-7-2l",
       "name": "GreenPan Bistro XXL Airfryer – 7,2 L",
       "brand": "GreenPan",
       "material": "Keramische binnenmand",
       "features": [
           "7,2 L",
           "PFAS-vrije Thermolon™ coating",
           "Verkrijgbaar in meerdere kleuren",
           "Digitale programma’s"
       ],
       "image": "airfryer-greenpan-bistro-xxl-7-2l_black.jpg",
       "image_path": "images/airfryers",
        "variants": [
            {
                "name": "Black",
                "image": "airfryer-greenpan-bistro-xxl-7-2l_black.jpg",
                "hex": "#000000",
                "affiliate_url": "https://greenpan.nl/products/bistro-xl-airfryer?srsltid=AfmBOorOuCNcc7SFpLKMs52T9UnfzVXB6coMjmak4OnufZpD_1ZIWrg_",
                "price": 159.90,
                "price_last_checked": "2026-06-12",
            },
            {
                "name": "Pine Green",
                "image": "airfryer-greenpan-bistro-xxl-7-2l_pine_green.jpg",
                "hex": "#01796f",
                "affiliate_url":"https://www.bol.com/nl/nl/p/greenpan-bistro-xxl-airfryer-pine-green-cc008959-001/9300000224669079/?bltgh=1d8475ad-fa04-46cc-b90c-3478bf6729ec.ProductList_Middle.0.ProductImage&cid=1781239297923-6502024321964",
                "price": 129.08,
                "price_last_checked": "2026-06-12",
            },
            {
                "name": "Smokey Blue",
                "image": "airfryer-greenpan-bistro-xxl-7-2l_smokey_blue.jpg",
                "hex": "#6b8a93",
                "affiliate_url":"https://greenpan.nl/products/bistro-xl-airfryer-sky-blue?pr_prod_strat=e5_desc&pr_rec_id=e8663ed5a&pr_rec_pid=9467875852618&pr_ref_pid=8510246682954&pr_seq=uniform",
                "price": 159.90,
                "price_last_checked": "2026-06-12",
            },
        ],
       "description": "Premium PFAS-vrije airfryer met ruime keramische binnenmand, moderne uitstraling en meerdere kleurvarianten voor een stijlvolle keuken.",
       "pros": [
           "PFAS-vrije keramische binnenmand",
           "Beschikbaar in meerdere kleuren",
           "Premium uitstraling en afwerking",
       ],
       "cons": [
           "Duurder dan gemiddelde XL airfryers",
           "Neemt veel ruimte in op het aanrecht",
       ],
       "rating": 5,
       "rating_count": None,
       "rating_source": "editorial",
       "price": 159.90,
       "currency": "EUR",
       "availability": "InStock",
       "affiliate_url": "https://greenpan.nl/products/bistro-xl-airfryer?srsltid=AfmBOorOuCNcc7SFpLKMs52T9UnfzVXB6coMjmak4OnufZpD_1ZIWrg_",
       "price_range": "€€€",
       "verdict": "Een van de mooiste PFAS-vrije XL airfryers op de markt, met sterke prestaties en een hoogwaardige keramische afwerking.",
       "award": None,
    },
    "maison_kitchen_8l": {
       "slug": "maison-kitchen-8l",
       "name": "Maison & Kitchen Airfryer – 8 L",
       "brand": "Maison & Kitchen",
       "material": "Keramische binnenmand",
       "features": [
           "8 L",
           "PFAS-vrije keramische binnenmand",
           "XL capaciteit",
           "Digitaal display"
       ],
       "image": "airfryer-maison-kitchen-8l.jpg",
       "image_path": "images/airfryers",
       "description": "Ruime PFAS-vrije airfryer met keramische binnenmand en eenvoudige bediening, geschikt voor gezinnen en grotere maaltijden.",
       "pros": [
           "Ruime 8 liter capaciteit",
           "PFAS-vrije keramische binnenmand",
           "Gebruiksvriendelijke bediening",
       ],
       "cons": [
           "Bouwkwaliteit minder premium",
           "Ventilatorgeluid iets luider dan gemiddeld",
       ],
       "rating": 3.5,
       "rating_count": None,
       "rating_source": "editorial",
       "price": 59.95,
       "currency": "EUR",
       "availability": "InStock",
       "affiliate_url": "https://www.bol.com/nl/nl/p/maison-kitchen-airfryer-heteluchtfriteuse-pfas-vrij-1850w-8l-inhoud-80-c-tot-200-c-zwart/9300000198145387/?cid=1781289528168-4277897137979&bltgh=e49cbcee-f55c-4390-add9-7078730c9b51.ProductList_Middle.0.ProductTitle",
       "price_range": "€",
       "verdict": "Een betaalbare PFAS-vrije XL airfryer met veel inhoud en eenvoudige bediening voor dagelijks gebruik.",
       "award": "",
    },    
    "princess_182280_8l": {
       "slug": "princess-182280-8l",
       "name": "Princess 182280 Airfryer XXL – 8 L",
       "brand": "Princess",
       "material": "Keramische binnenmand",
       "features": [
           "8 L",
           "PFAS-vrije keramische coating",
           "XL capaciteit",
           "Digitale bediening",
           "Meerdere automatische programma’s"
       ],
       "image": "airfryer-princess-182280-8l-pfasvrij.jpg",
       "image_path": "images/airfryers",
       "description": "Ruime PFAS-vrije airfryer met keramische binnenmand en krachtige luchtcirculatie, ontworpen voor gezinnen en grotere maaltijden.",
       "pros": [
           "Expliciet PFAS-vrije keramische coating",
           "Ruime 8 liter inhoud voor grotere porties",
           "Gebruiksvriendelijke digitale bediening",
       ],
       "cons": [
           "Neemt relatief veel ruimte in op het aanrecht",
           "Bouwkwaliteit minder premium dan topsegment",
       ],
       "rating": 4,
       "rating_count": None,
       "rating_source": "editorial",
       "price": 53.99,
       "price_last_checked": "2026-06-12",
       "currency": "EUR",
       "availability": "InStock",
       "affiliate_url": "https://www.bol.com/nl/nl/p/princess-182280-digitale-airfryer-8l-dual-heating-digitaal-led-touchscreen-pfas-vrij-makkelijk-schoon-te-maken/9300000221571449/",
       "price_range": "€€",
       "verdict": "Een ruime en toegankelijke PFAS-vrije XL airfryer met keramische coating en sterke prijs-kwaliteitverhouding voor dagelijks gezinsgebruik.",
       "award": None,
    },

# DUAL-LADE PFAS-VRIJE AIRFRYERS
    "inventum_gf800hld_dual_8l": {
       "slug": "inventum-gf800hld-dual-8l",
       "name": "Inventum GF800HLD Dual Airfryer – 2 x 4 L",
       "brand": "Inventum",
       "material": "Keramische binnenmanden",
       "features": [
           "2 x 4 L",
           "PFAS-vrije keramische binnenmanden",
           "Dual-zone technologie",
           "Synchroniseerfunctie",
           "8 automatische programma’s"
       ],
       "image": "airfryer-inventum-gf800hld-dual-8l.jpg",
       "image_path": "images/airfryers",
       "description": "Ruime PFAS-vrije dual airfryer met twee afzonderlijke keramische bakzones voor gelijktijdig bereiden van verschillende gerechten.",
       "pros": [
           "Twee aparte PFAS-vrije keramische manden",
           "Gelijktijdig bereiden van verschillende gerechten",
           "Goede prijs-kwaliteitverhouding binnen dual-zone modellen",
       ],
       "cons": [
           "Neemt relatief veel ruimte in op het aanrecht",
           "Display oogt functioneel maar eenvoudig",
       ],
       "rating": 5,
       "rating_count": None,
       "rating_source": "editorial",
       "price": 84.49,
       "price_last_checked": "2026-06-12",
       "currency": "EUR",
       "availability": "InStock",
       "affiliate_url": "https://www.bol.com/nl/nl/p/inventum-gf800hld-dubbele-airfryer-heteluchtfriteuse-inhoud-2-x-4-liter-zwart-rvs/9300000118712931/?cid=1781292539074-5483409334166&bltgh=4ff64c05-1b1d-413b-bcb2-bbfc2dddca76.ProductList_Middle.0.ProductImage",
       "price_range": "€€",
       "verdict": "Een van de beste PFAS-vrije dual airfryers dankzij de combinatie van twee keramische manden, gebruiksgemak en sterke dagelijkse prestaties.",
       "award": "🏆 Beste keuze",
    },
    "bourgini_duo_8l": {
       "slug": "bourgini-duo-8l",
       "name": "Bourgini Duo Heteluchtfriteuse – 2 x 4 L",
       "brand": "Bourgini",
       "material": "Keramisch",
       "features": [
           "2 x 4 L",
           "PFAS-vrije keramische coating",
           "Dual-zone bereiding",
           "Digitaal display"
       ],
       "image": "airfryer-bourgini-duo-8l.jpg",
       "image_path": "images/airfryers",
       "description": "Betaalbare PFAS-vrije dual airfryer met twee afzonderlijke bakzones en keramische coating voor flexibel gezinskoken.",
       "pros": [
           "Twee aparte bakzones voor verschillende gerechten",
           "PFAS-vrije keramische coating",
           "Sterke prijs-kwaliteitverhouding",
       ],
       "cons": [
           "Behuizing voelt minder premium aan",
           "Ventilatorgeluid hoorbaar op hogere standen",
       ],
       "rating": 4,
       "rating_count": None,
       "rating_source": "editorial",
       "price": 89.00,
       "price_last_checked": "2026-06-12",
       "currency": "EUR",
       "availability": "InStock",
       "affiliate_url": "https://www.bol.com/nl/nl/p/bourgini-duo-heteluchtfriteuse-2-x-4-0l-pfas-vrij-airfryer-xxl-2-laden-met-synchronisatie-functie-touchscreen-8l-2600w-zwart/9300000237172411/?cid=1781292763236-5099980372381&bltgh=16bac619-f455-4934-91b0-460532911421.ProductList_Middle.0.ProductImage",
       "price_range": "€€",
       "verdict": "Een aantrekkelijke dual-zone airfryer voor gezinnen die PFAS-vrij willen koken zonder direct naar het premiumsegment te gaan.",
       "award": "💰 Budget keuze",
    },
    "greenpan_bistro_dual_8l": {
       "slug": "greenpan-bistro-dual-8l",
       "name": "GreenPan Bistro Dual Airfryer – 2 x 4 L",
       "brand": "GreenPan",
       "material": "Keramische binnenmanden",
       "features": [
           "2 x 4 L",
           "Thermolon™ keramische coating",
           "PFAS-vrij",
           "Synchroniseerfunctie",
           "Premium afwerking"
       ],
       "image": "airfryer-greenpan-bistro-dual-8l.jpg",
       "image_path": "images/airfryers",
       "description": "Premium PFAS-vrije dual airfryer met twee keramische bakzones, hoogwaardige afwerking en gebruiksvriendelijke programma’s.",
       "pros": [
           "Hoogwaardige Thermolon™ keramische coating",
           "Twee afzonderlijke bakzones",
           "Stijlvolle premium uitstraling",
       ],
       "cons": [
           "Duidelijk duurder dan instapmodellen",
           "Vrij groot ontwerp",
       ],
       "rating": 5,
       "rating_count": None,
       "rating_source": "editorial",
       "price": 143.00,
       "price_last_checked": "2026-06-12",
       "currency": "EUR",
       "availability": "InStock",
       "affiliate_url": "https://www.bol.com/nl/nl/p/greenpan-bistro-dubbele-airfryer-4l-4l-9-programma-s-zwart-pfas-vrij/9300000157443810/?cid=1781292992359-3169594473202&bltgh=2f108dae-fe92-48b5-8650-6a69eed020b8.ProductList_Middle.1.ProductImage",
       "price_range": "€€€",
       "verdict": "Een premium PFAS-vrije dual airfryer met uitstekende afwerking, sterke bakprestaties en hoogwaardige keramische binnenmanden.",
       "award": "💎 Premium keuze",
    },
    "wartmann_wm2511af_11l": {
       "slug": "wartmann-wm2511af-11l",
       "name": "Wartmann WM-2511 AF Airfryer – 11 L",
       "brand": "Wartmann",
       "material": "Keramische binnenmanden",
       "features": [
           "11 L",
           "PFAS-vrije keramische coating",
           "Extra grote inhoud",
           "Dual-cook functionaliteit",
           "Kijkvenster"
       ],
       "image": "airfryer-wartmann-wm2511af-11l.jpg",
       "image_path": "images/airfryers",
       "description": "Zeer ruime PFAS-vrije airfryer met keramische binnenzijde en extra grote capaciteit voor grotere gezinnen en uitgebreide maaltijden.",
       "pros": [
           "Zeer grote capaciteit van 11 liter",
           "PFAS-vrije keramische coating",
           "Kijkvenster voor controle tijdens het bakken",
       ],
       "cons": [
           "Neemt veel ruimte in op het aanrecht",
           "Hoger energieverbruik dan compacte modellen",
       ],
       "rating": 4.5,
       "rating_count": None,
       "rating_source": "editorial",
       "price": 195.00,
       "price_last_checked": "2026-06-12",
       "currency": "EUR",
       "availability": "InStock",
       "affiliate_url": "https://www.bol.com/nl/nl/p/dubbele-airfryer-xxl-11l-pfas-vrije-heteluchtfriteuse-infrarood-dual-zone-2-x-5-5l-40-200-c-8-kookprogramma-s-2850w-wm-2511-af-zwart/9300000264941766/?Referrer=ADVNLGOO002028-S--9300000264941766-PMAX-C-23794862284&gad_source=1&gad_campaignid=23794874386&gclid=Cj0KCQjw3K7RBhDJARIsAKRtP5QCFxshGlUE0pg63xdazmtU1JkvBhvDZA85oFMbXEtxZ2itbHexgNYaAuVzEALw_wcB",
       "price_range": "€€€€",
       "verdict": "Een uitzonderlijk ruime PFAS-vrije airfryer voor grote gezinnen en gebruikers die maximale capaciteit en flexibiliteit zoeken.",
       "award": None,
    },
}
