PRODUCTS = {
    # 20CM KOOLSTOFSTALEN / PLAATSTALEN KOEKENPANNEN

    "debuyer_mineral_b_20": {
        "slug": "debuyer-mineral-b-20",
        "name": "De Buyer Mineral B",
        "description": "Robuuste plaatstalen koekenpan met beschermende "
        "bijenwasafwerking die door inbranden en gebruik een natuurlijke "
        "patinalaag ontwikkelt.",
        "brand": "De Buyer",
        "diameter": 20,
        "material": "Koolstofstaal met beschermende bijenwasafwerking",
        "features": [
            "Geschikt voor inductie",
            "Ontwikkelt een natuurlijke patinalaag",
            "Kort ovenbestendig tot 200 °C",
        ],
        "rating": 4.8,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 36.95,
        "price_last_checked": "2026-09-02",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Fdebuyer-mineral-b-element-koekenpan-o-20-cm%2F9200000002756840%2F&name=De%20Buyer%20Mineral%20B%20Element%20Koekenpan%20-%2020%20cm%20-%2099%25%20zuiver%20ijzer%20-%20Natuurlijke%20antiaanbak",
        "retailer_url": "https://www.bol.com/nl/nl/p/debuyer-mineral-b-element-koekenpan-o-20-cm/9200000002756840/",
        "award": "🏆 Beste keuze",
        "price_range": "€€",
        "image": "debuyer-mineral-b-20cm.webp",
        "image_path": "images/products/koolstofstalen-koekenpannen",
        "pros": [
            "Uitstekend geschikt voor bakken op hoge temperatuur",
            "Patinalaag wordt beter naarmate de pan vaker wordt gebruikt",
            "Stevige constructie",
        ],
        "cons": [
            "Moet voor optimaal gebruik worden ingebrand",
            "Alleen kortdurend geschikt voor de oven",
        ],
        "verdict": "Onze beste allround keuze voor wie een duurzame en veelzijdige "
        "koolstofstalen koekenpan in compact formaat zoekt.",
    },

    "debuyer_mineral_b_pro_20": {
        "slug": "debuyer-mineral-b-pro-20",
        "name": "De Buyer Mineral B Pro",
        "description": "Premium plaatstalen koekenpan met bijenwasafwerking, "
        "RVS handgreep en volledige geschiktheid voor ovengebruik.",
        "brand": "De Buyer",
        "diameter": 20,
        "material": "Koolstofstaal met beschermende bijenwasafwerking",
        "features": [
            "Geschikt voor inductie",
            "Volledig ovenbestendig",
            "RVS handgreep",
        ],
        "rating": 4.9,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 46.99,
        "price_last_checked": "2026-09-02",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Fdebuyer-mineral-b-pro-koekenpan-20cm%2F9200000060271502%2F&name=de%20Buyer%20Mineral%20B%20Pro%20Koekenpan%20%C3%98%2020%20cm%20%E2%80%93%20Plaatstaal%20%E2%80%93%20PFAS-vrij%20%E2%80%93%20Geschikt%20voor...",
        "retailer_url": "https://www.bol.com/nl/nl/p/debuyer-mineral-b-pro-koekenpan-20cm/9200000060271502/",
        "award": "💎 Premium keuze",
        "price_range": "€€",
        "image": "debuyer-mineral-b-pro-20cm.webp",
        "image_path": "images/products/koolstofstalen-koekenpannen",
        "pros": [
            "Volledig geschikt voor gebruik in de oven",
            "Duurzame RVS handgreep",
            "Uitstekende prestaties bij hoge baktemperaturen",
        ],
        "cons": [
            "Moet worden ingebrand",
            "Relatief hogere aanschafprijs",
            "Relatief zwaar voor een pan van 20 cm",
        ],
        "verdict": "Onze premium keuze voor wie de bakeigenschappen van plaatstaal "
        "wil combineren met een hoogwaardige RVS greep en onbeperkter ovengebruik.",
    },

    "skottsberg_carbon_steel_20": {
        "slug": "skottsberg-carbon-steel-20",
        "name": "Skottsberg Carbon Steel",
        "description": "Vooringebrande plaatstalen koekenpan met 2,5 mm dikke bodem "
        "en holle steel voor comfortabel dagelijks gebruik.",
        "brand": "Skottsberg",
        "diameter": 20,
        "material": "Koolstofstaal, vooringebrand met natuurlijke plantaardige olie",
        "features": [
            "Geschikt voor inductie",
            "Tweemaal vooringebrand",
            "Ovenbestendig",
            "Holle steel",
        ],
        "rating": 4.7,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 49.99,
        "price_last_checked": "2026-09-02",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Fskottsberg-koekenpan-carbon-steel-20-cm-plaatstaal-pfas-vrij%2F9300000070422483%2F&name=Skottsberg%20-%20Carbon%20Steel%20-%20Koekenpan%20-%20Plaatstaal%20-%20Inductie%20-%20%C3%B8%2020%20cm%20-%20Alle...",
        "retailer_url": "https://www.bol.com/nl/nl/p/skottsberg-koekenpan-carbon-steel-20-cm-plaatstaal-pfas-vrij/9300000070422483/",
        "award": None,
        "price_range": "€€",
        "image": "skottsberg-carbon-steel-20cm.webp",
        "image_path": "images/products/koolstofstalen-koekenpannen",
        "pros": [
            "Vooringebrand en direct klaar voor gebruik",
            "Holle steel wordt minder snel heet",
        ],
        "cons": [
            "Hogere aanschafprijs dan meerdere alternatieven",
        ],
        "verdict": "Een gebruiksvriendelijke keuze voor wie de voordelen van "
        "koolstofstaal wil zonder de pan eerst volledig zelf te hoeven inbranden.",
    },

    "bk_black_steel_20": {
        "slug": "bk-black-steel-20",
        "name": "BK Black Steel",
        "description": "Betaalbare plaatstalen koekenpan die snel opwarmt en tijdens "
        "gebruik een natuurlijke patinalaag met antiaanbakeigenschappen ontwikkelt.",
        "brand": "BK",
        "diameter": 20,
        "material": "Plaatstaal",
        "features": [
            "Geschikt voor inductie",
            "Ovenbestendig tot 230 °C",
            "Geschikt voor barbecue",
        ],
        "rating": 4.3,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 32.90,
        "price_last_checked": "2026-09-02",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://bk.nl/products/black-steel-koekenpan?variant=43657411068153",
        "award": None,
        "price_range": "€€",
        "image": "bk-black-steel-20cm.webp",
        "image_path": "images/products/koolstofstalen-koekenpannen",
        "pros": [
            "Snelle en efficiënte warmtegeleiding",
            "Geschikt voor oven en barbecue",
            "Relatief toegankelijke aanschafprijs",
        ],
        "cons": [
            "Handgreep kan tijdens gebruik heet worden",
        ],
        "verdict": "Een toegankelijke plaatstalen allrounder voor wie zonder "
        "synthetische antiaanbaklaag op hoge temperatuur wil bakken.",
    },

    "forged_essentials_20": {
        "slug": "forged-essentials-20",
        "name": "Forged Essentials",
        "description": "Handgesmede carbonstalen koekenpan zonder synthetische "
        "antiaanbaklaag, geschikt voor zowel fornuis als oven.",
        "brand": "Forged",
        "diameter": 20,
        "material": "Carbonstaal",
        "features": [
            "Geschikt voor inductie",
            "Geschikt voor ovengebruik",
            "Handgesmede afwerking",
        ],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 45.00,
        "price_last_checked": "2026-09-02",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Fforged-essentials-koekenpan-20cm-carbon-staal%2F9300000241539502%2F&name=Forged%20Essentials%20Koekenpan%20-%2020%20cm%20-%20Carbon%20staal%20-%20Geschikt%20voor%20inductie",
        "retailer_url": "https://www.bol.com/nl/nl/p/forged-essentials-koekenpan-20cm-carbon-staal/9300000241539502/",
        "award": None,
        "price_range": "€€",
        "image": "forged-essentials-20cm.webp",
        "image_path": "images/products/koolstofstalen-koekenpannen",
        "pros": [
            "Handgesmede en onderscheidende afwerking",
            "Volledig geschikt voor gebruik in de oven",
        ],
        "cons": [
            "Moet worden ingebrand",
            "Relatief hogere aanschafprijs",
        ],
        "verdict": "Een aantrekkelijke designkeuze voor wie traditioneel carbonstaal "
        "wil combineren met een robuuste handgesmede uitstraling.",
    },

    "blackwell_carbon_steel_20": {
        "slug": "blackwell-carbon-steel-20",
        "name": "Blackwell Carbon Steel",
        "description": "Scherp geprijsde carbonstalen koekenpan zonder synthetische "
        "antiaanbaklaag voor kleinere dagelijkse bereidingen.",
        "brand": "Blackwell",
        "diameter": 20,
        "material": "Carbonstaal",
        "features": [
            "Geschikt voor inductie",
            "Geschikt voor ovengebruik",
        ],
        "rating": 4.1,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 29.99,
        "price_last_checked": "2026-09-02",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.cookinglife.nl/products/blackwell-koekenpan-carbon-staal-20cm",
        "award": "💰 Budget keuze",
        "price_range": "€€",
        "image": "blackwell-carbon-steel-20cm.webp",
        "image_path": "images/products/koolstofstalen-koekenpannen",
        "pros": [
            "Relatief lage aanschafprijs",
            "Geschikt voor alle gangbare warmtebronnen",
        ],
        "cons": [
            "Eenvoudigere afwerking dan de premium modellen",
        ],
        "verdict": "Onze budgetkeuze voor wie voordelig kennis wil maken met "
        "koolstofstaal zonder een synthetische antiaanbaklaag.",
    },

    # 24CM KOOLSTOFSTALEN / PLAATSTALEN KOEKENPANNEN

    "debuyer_mineral_b_24": {
        "slug": "debuyer-mineral-b-24",
        "name": "De Buyer Mineral B",
        "description": "Robuuste plaatstalen koekenpan met beschermende "
        "bijenwasafwerking die door inbranden en gebruik een natuurlijke "
        "patinalaag ontwikkelt.",
        "brand": "De Buyer",
        "diameter": 24,
        "material": "Koolstofstaal met beschermende bijenwasafwerking",
        "features": [
            "Geschikt voor inductie",
            "Ontwikkelt een natuurlijke patinalaag",
            "Kort ovenbestendig",
        ],
        "rating": 4.8,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 32.30,
        "price_last_checked": "2026-09-02",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Fdebuyer-mineral-b-element-koekenpan-zilver-rond-o-24-cm%2F9200000002756842%2F&name=de%20Buyer%20Mineral%20B%20Koekenpan%2024%20cm%20%E2%80%93%20Plaatstaal%20%E2%80%93%20PFAS-vrij%20%E2%80%93%20Natuurlijk%20Antiaanbak...",
        "retailer_url": "https://www.bol.com/nl/nl/p/debuyer-mineral-b-element-koekenpan-zilver-rond-o-24-cm/9200000002756842/",
        "award": "🏆 Beste keuze",
        "price_range": "€€",
        "image": "debuyer-mineral-b-24cm.webp",
        "image_path": "images/products/koolstofstalen-koekenpannen",
        "pros": [
            "Uitstekend geschikt voor bakken op hoge temperatuur",
            "Stevige constructie",
        ],
        "cons": [
            "Moet voor optimaal gebruik worden ingebrand",
            "Alleen kortdurend geschikt voor de oven",
        ],
        "verdict": "Onze beste allround keuze dankzij de sterke bakeigenschappen, "
        "duurzame constructie en goede prijs-kwaliteitverhouding.",
    },

    "debuyer_mineral_b_pro_24": {
        "slug": "debuyer-mineral-b-pro-24",
        "name": "De Buyer Mineral B Pro",
        "description": "Premium plaatstalen koekenpan met bijenwasafwerking, "
        "ergonomische RVS handgreep en volledige geschiktheid voor ovengebruik.",
        "brand": "De Buyer",
        "diameter": 24,
        "material": "Koolstofstaal met beschermende bijenwasafwerking",
        "features": [
            "Geschikt voor inductie",
            "Volledig ovenbestendig",
            "Ergonomische RVS handgreep",
        ],
        "rating": 4.9,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 58.00,
        "price_last_checked": "2026-09-02",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Fdebuyer-mineral-b-pro-koekenpan-o-24-cm%2F9200000060271488%2F&name=De%20Buyer%20Mineral%20B%20Pro%20Koekenpan%20-%2024%20cm%20-%20Plaatstaal%20-%20PFAS-vrij%20-%20RVS%20handgreep",
        "retailer_url": "https://www.bol.com/nl/nl/p/debuyer-mineral-b-pro-koekenpan-o-24-cm/9200000060271488/",
        "award": "💎 Premium keuze",
        "price_range": "€€€",
        "image": "debuyer-mineral-b-pro-24cm.webp",
        "image_path": "images/products/koolstofstalen-koekenpannen",
        "pros": [
            "Volledig geschikt voor gebruik in de oven",
            "Hoogwaardige en comfortabele RVS handgreep",
        ],
        "cons": [
            "Relatief hogere aanschafprijs",
             "Moet worden ingebrand",
            "Relatief zwaar voor het formaat",
        ],
        "verdict": "Onze premium keuze voor wie professionele bakeigenschappen wil "
        "combineren met een hoogwaardige RVS greep en veelzijdig ovengebruik.",
    },
    
    "skottsberg_carbon_steel_24": {
        "slug": "skottsberg-carbon-steel-24",
        "name": "Skottsberg Carbon Steel",
        "description": "Vooringebrande plaatstalen koekenpan met 2,5 mm dikke bodem "
        "en holle steel, direct klaar voor dagelijks gebruik.",
        "brand": "Skottsberg",
        "diameter": 24,
        "material": "Koolstofstaal, vooringebrand met natuurlijke plantaardige olie",
        "features": [
            "Geschikt voor inductie",
            "Tweemaal vooringebrand",
            "Ovenbestendig tot 250 °C",
            "Holle steel",
        ],
        "rating": 4.7,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 59.99,
        "price_last_checked": "2026-09-02",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Fskottsberg-koekenpan-carbon-steel-24-cm-plaatstaal%2F9300000070422479%2F&name=Skottsberg%20-%20Carbon%20Steel%20-%20Koekenpan%20-%20Plaatstaal%20-%20Inductie%20-%20%C3%B8%2024%20cm%20-%20Alle...",
        "retailer_url": "https://www.bol.com/nl/nl/p/skottsberg-koekenpan-carbon-steel-24-cm-plaatstaal/9300000070422479/",
        "award": None,
        "price_range": "€€€",
        "image": "skottsberg-carbon-steel-24cm.webp",
        "image_path": "images/products/koolstofstalen-koekenpannen",
        "pros": [
            "Vooringebrand en direct klaar voor gebruik",
            "Holle steel wordt minder snel heet",
        ],
        "cons": [
            "Relatief hogere aanschafprijs",
        ],
        "verdict": "Een bijzonder gebruiksvriendelijke keuze dankzij de vooringebrande "
        "patinalaag, stevige bodem en comfortabele holle steel.",
    },

    "forged_essentials_24": {
        "slug": "forged-essentials-24",
        "name": "Forged Essentials",
        "description": "Handgesmede koekenpan van 3 mm dik carbonstaal zonder "
        "synthetische antiaanbaklaag en met een karakteristieke hamerslag.",
        "brand": "Forged",
        "diameter": 24,
        "material": "3 mm dik DT4C carbonstaal",
        "features": [
            "Geschikt voor inductie",
            "Geschikt voor oven, barbecue en open vuur",
            "Handgesmede afwerking",
        ],
        "rating": 4.6,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 64.95,
        "price_last_checked": "2026-09-02",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Fforged-essentials-koekenpan-24cm%2F9300000185739322%2F&name=Forged%20Essentials%20Koekenpan%2024cm%20-%20Staal%20-%20PFAS-vrij%20-%20Alle%20warmtebronnen%20incl.%20inductie",
        "retailer_url": "https://www.bol.com/nl/nl/p/forged-essentials-koekenpan-24cm/9300000185739322/",
        "award": None,
        "price_range": "€€€",
        "image": "forged-essentials-24cm.webp",
        "image_path": "images/products/koolstofstalen-koekenpannen",
        "pros": [
            "Dikke en robuuste constructie van 3 mm carbonstaal",
            "Geschikt voor oven, barbecue en open vuur",
            "Onderscheidende handgesmede afwerking",
        ],
        "cons": [
            "Relatief hoge aanschafprijs",
            "Moet zelf worden ingebrand",
            "Relatief zwaar",
        ],
        "verdict": "Een robuuste designkeuze voor wie dikke materiaalconstructie, "
        "veelzijdige inzetbaarheid en een handgesmede uitstraling waardeert.",
    },

    "blackwell_carbon_steel_24": {
        "slug": "blackwell-carbon-steel-24",
        "name": "Blackwell Carbon Steel",
        "description": "Betaalbare carbonstalen koekenpan zonder synthetische "
        "antiaanbaklaag die door inbranden een natuurlijke patinalaag ontwikkelt.",
        "brand": "Blackwell",
        "diameter": 24,
        "material": "2 mm dik carbonstaal",
        "features": [
            "Geschikt voor inductie",
            "Ovenbestendig tot 220 °C",
            "Geschikt voor barbecue",
        ],
        "rating": 4.2,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 34.99,
        "price_last_checked": "2026-09-02",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.cookinglife.nl/products/blackwell-koekenpan-carbon-staal-24cm",
        "award": None,
        "price_range": "€€",
        "image": "blackwell-carbon-steel-24cm.webp",
        "image_path": "images/products/koolstofstalen-koekenpannen",
        "pros": [
            "Toegankelijke aanschafprijs",
            "Geschikt voor alle gangbare warmtebronnen",
            "Relatief licht voor een koolstofstalen pan",
        ],
        "cons": [
            "Relatief dunnere constructie",
            "Moet zelf worden ingebrand",
        ],
        "verdict": "Een toegankelijke keuze voor wie een veelzijdige carbonstalen "
        "koekenpan zoekt zonder veel extra te betalen voor merk of afwerking.",
    },

    "hendi_traditioneel_24": {
        "slug": "hendi-traditioneel-24",
        "name": "HENDI Traditioneel",
        "description": "Eenvoudige professionele koekenpan van zwaar carbonstaal "
        "met naadloos gelaste stalen handgreep en hoge hittebestendigheid.",
        "brand": "HENDI",
        "diameter": 24,
        "material": "Carbonstaal",
        "features": [
            "Geschikt voor inductie",
            "Naadloos gelaste stalen handgreep",
            "Hoge hittebestendigheid",
        ],
        "rating": 4.3,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 24.95,
        "price_last_checked": "2026-09-02",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Fhendi-stalen-koekenpan-o24cm%2F9200000046565033%2F&name=HENDI%20Traditionele%20koekenpan%20%E2%80%93%20plaatstaal%20%E2%80%93%20gelast%20handvat%20%E2%80%93%20%E2%8C%80240%20mm%20%E2%80%93%20hoge...",
        "retailer_url": "https://www.bol.com/nl/nl/p/hendi-stalen-koekenpan-o24cm/9200000046565033/",
        "award": "💰 Budget keuze",
        "price_range": "€",
        "image": "hendi-traditioneel-24cm.webp",
        "image_path": "images/products/koolstofstalen-koekenpannen",
        "pros": [
            "Zeer scherpe aanschafprijs",
            "Robuuste professionele constructie",
            "Geschikt voor hoge baktemperaturen",
        ],
        "cons": [
            "Stalen handgreep kan tijdens gebruik heet worden",
            "Moet zelf worden ingebrand",
        ],
        "verdict": "Onze budgetkeuze voor wie vooral een eenvoudige en robuuste "
        "koolstofstalen pan met professionele basisconstructie zoekt.",
    },

    # 28CM KOOLSTOFSTALEN / PLAATSTALEN KOEKENPANNEN

    "debuyer_mineral_b_28": {
        "slug": "debuyer-mineral-b-28",
        "name": "De Buyer Mineral B",
        "description": "Robuuste plaatstalen koekenpan met beschermende "
        "bijenwasafwerking die door inbranden en gebruik een natuurlijke "
        "patinalaag ontwikkelt.",
        "brand": "De Buyer",
        "diameter": 28,
        "material": "Koolstofstaal met beschermende bijenwasafwerking",
        "features": [
            "Geschikt voor inductie",
            "Ontwikkelt een natuurlijke patinalaag",
            "Geschikt voor ovengebruik",
        ],
        "rating": 4.8,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 41.79,
        "price_last_checked": "2026-09-02",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Fdebuyer-mineral-b-element-koekenpan-zilver-rond-o-28-cm%2F9200000002756846%2F&name=De%20Buyer%20Mineral%20B%20Element%20Koekenpan%20-%20Staal%20-%2028%20cm%20-%20Rond",
        "retailer_url": "https://www.bol.com/nl/nl/p/debuyer-mineral-b-element-koekenpan-zilver-rond-o-28-cm/9200000002756846/",
        "award": "🏆 Beste keuze",
        "price_range": "€€",
        "image": "debuyer-mineral-b-28cm.webp",
        "image_path": "images/products/koolstofstalen-koekenpannen",
        "pros": [
            "Uitstekend geschikt voor bakken op hoge temperatuur",
            "Sterke prijs-kwaliteitverhouding",
        ],
        "cons": [
            "Moet voor optimaal gebruik worden ingebrand",
            "Relatief zwaar",
        ],
        "verdict": "Onze beste allround keuze dankzij de sterke bakeigenschappen, "
        "duurzame constructie en uitstekende prijs-kwaliteitverhouding.",
    },

    "skottsberg_carbon_steel_28": {
        "slug": "skottsberg-carbon-steel-28",
        "name": "Skottsberg Carbon Steel",
        "description": "Vooringebrande plaatstalen koekenpan met stevige bodem "
        "en holle steel, direct klaar voor dagelijks gebruik.",
        "brand": "Skottsberg",
        "diameter": 28,
        "material": "Koolstofstaal, vooringebrand met natuurlijke plantaardige olie",
        "features": [
            "Geschikt voor inductie",
            "Tweemaal vooringebrand",
            "Ovenbestendig tot 250 °C",
            "Holle steel",
        ],
        "rating": 4.7,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 69.99,
        "price_last_checked": "2026-09-02",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Fskottsberg-koekenpan-carbon-steel-28-cm-plaatstaal-pfas-vrij%2F9300000070422484%2F&name=Skottsberg%20Carbon%20Steel%20Koekenpan%20-%20Plaatstaal%20-%20%C3%B8%2028%20cm%20-%20Inductie%20-%20PFAS-vrij",
        "retailer_url": "https://www.bol.com/nl/nl/p/skottsberg-koekenpan-carbon-steel-28-cm-plaatstaal-pfas-vrij/9300000070422484/",
        "award": None,
        "price_range": "€€€",
        "image": "skottsberg-carbon-steel-28cm.webp",
        "image_path": "images/products/koolstofstalen-koekenpannen",
        "pros": [
            "Vooringebrand en direct klaar voor gebruik",
            "Holle steel wordt minder snel heet",
        ],
        "cons": [
            "Relatief hogere aanschafprijs",
        ],
        "verdict": "Een gebruiksvriendelijke keuze voor wie de voordelen van "
        "koolstofstaal wil zonder de pan eerst volledig zelf te hoeven inbranden.",
    },

    "debuyer_mineral_b_pro_28": {
        "slug": "debuyer-mineral-b-pro-28",
        "name": "De Buyer Mineral B Pro",
        "description": "Premium plaatstalen koekenpan met bijenwasafwerking, "
        "ergonomische RVS handgreep en volledige geschiktheid voor ovengebruik.",
        "brand": "De Buyer",
        "diameter": 28,
        "material": "Koolstofstaal met beschermende bijenwasafwerking",
        "features": [
            "Geschikt voor inductie",
            "Volledig ovenbestendig",
            "Ergonomische RVS handgreep",
        ],
        "rating": 4.9,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 54.49,
        "price_last_checked": "2026-09-02",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Fdebuyer-mineral-b-pro-koekenpan-o-28-cm%2F9200000060271486%2F&name=De%20Buyer%20Mineral%20B%20Pro%20Koekenpan%20-%2028cm%20-%20Plaatstaal%20-%20PFAS-vrij%20-%20RVS%20handgreep",
        "retailer_url": "https://www.bol.com/nl/nl/p/debuyer-mineral-b-pro-koekenpan-o-28-cm/9200000060271486/",
        "award": "💎 Premium keuze",
        "price_range": "€€€",
        "image": "debuyer-mineral-b-pro-28cm.webp",
        "image_path": "images/products/koolstofstalen-koekenpannen",
        "pros": [
            "Volledig geschikt voor gebruik in de oven",
            "Hoogwaardige RVS handgreep",
            "Uitstekende prestaties bij hoge baktemperaturen",
        ],
        "cons": [
            "Duurder dan de standaard Mineral B",
            "Moet worden ingebrand",
            "Met ruim 2 kg relatief zwaar",
        ],
        "verdict": "Onze premium keuze voor wie professionele bakeigenschappen "
        "wil combineren met een hoogwaardige RVS greep en veelzijdig ovengebruik.",
    },

    "beka_nomad_28": {
        "slug": "beka-nomad-28",
        "name": "Beka Nomad",
        "description": "Koolstofstalen koekenpan zonder coating met een "
        "hittewerende handgreep van acaciahout en natuurlijke patinalaag.",
        "brand": "Beka",
        "diameter": 28,
        "material": "Koolstofstaal met handgreep van acaciahout",
        "features": [
            "Geschikt voor inductie",
            "Geschikt voor barbecue",
            "Acaciahouten handgreep",
            "10 jaar garantie",
        ],
        "rating": 4.5,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 45.00,
        "price_last_checked": "2026-09-02",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Fbeka-nomad-carbon-steel-frying-pan-28-cm%2F9200000120682239%2F&name=Beka%20Nomad%20braadpan%2Fkoekenpan%20-%20%C3%98%2028%20cm%20-%20Staal%20-%20PFAS-vrij%20-%20Houten%20greep%20-%20Geschikt...",
        "retailer_url": "https://www.bol.com/nl/nl/p/beka-nomad-carbon-steel-frying-pan-28-cm/9200000120682239/",
        "award": None,
        "price_range": "€€",
        "image": "beka-nomad-28cm.webp",
        "image_path": "images/products/koolstofstalen-koekenpannen",
        "pros": [
            "Comfortabele hittewerende houten handgreep",
            "Relatief licht voor een koolstofstalen pan",
            "Geschikt voor inductie en barbecue",
        ],
        "cons": [
            "Niet geschikt voor ovengebruik",
            "Moet zelf worden ingebrand",
        ],
        "verdict": "Een comfortabele en onderscheidende keuze voor wie koolstofstaal "
        "wil combineren met een relatief laag gewicht en houten handgreep.",
    },

    "forged_essentials_28": {
        "slug": "forged-essentials-28",
        "name": "Forged Essentials",
        "description": "Handgesmede koekenpan van 3 mm dik carbonstaal zonder "
        "synthetische antiaanbaklaag en met karakteristieke hamerslag.",
        "brand": "Forged",
        "diameter": 28,
        "material": "3 mm dik DT4C carbonstaal",
        "features": [
            "Geschikt voor inductie",
            "Geschikt voor oven, barbecue en open vuur",
            "Handgesmede afwerking",
        ],
        "rating": 4.6,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 74.95,
        "price_last_checked": "2026-09-02",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Fforged-essentials-koekenpan-28cm%2F9300000185739316%2F&name=Forged%20Essentials%20koekenpan%2028cm%20-%20Staal%20-%20PFAS-vrij%20-%20Alle%20warmtebronnen%20incl.%20inductie",
        "retailer_url": "https://www.bol.com/nl/nl/p/forged-essentials-koekenpan-28cm/9300000185739316/",
        "award": None,
        "price_range": "€€€",
        "image": "forged-essentials-28cm.webp",
        "image_path": "images/products/koolstofstalen-koekenpannen",
        "pros": [
            "Dikke en robuuste constructie van 3 mm carbonstaal",
            "Geschikt voor oven, barbecue en open vuur",
            "Onderscheidende handgesmede afwerking",
        ],
        "cons": [
            "Relatief hogere aanschafprijs",
            "Met ongeveer 2 kg relatief zwaar",
            "Moet zelf worden ingebrand",
        ],
        "verdict": "Een robuuste designkeuze voor wie dikke materiaalconstructie, "
        "veelzijdige inzetbaarheid en een handgesmede uitstraling waardeert.",
    },

    "bk_black_steel_28": {
        "slug": "bk-black-steel-28",
        "name": "BK Black Steel",
        "description": "Robuuste plaatstalen koekenpan die snel opwarmt en tijdens "
        "gebruik een natuurlijke patinalaag met antiaanbakeigenschappen ontwikkelt.",
        "brand": "BK",
        "diameter": 28,
        "material": "Koolstofstaal / plaatstaal",
        "features": [
            "Geschikt voor inductie",
            "Geschikt voor oven en barbecue",
        ],
        "rating": 4.3,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 43.90,
        "price_last_checked": "2026-09-02",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://bk.nl/products/black-steel-koekenpan?variant=43657411002617",
        "award": None,
        "price_range": "€€",
        "image": "bk-black-steel-28cm.webp",
        "image_path": "images/products/koolstofstalen-koekenpannen",
        "pros": [
            "Snelle en efficiënte warmtegeleiding",
            "Geschikt voor oven en barbecue",
        ],
        "cons": [
            "Handgreep kan tijdens gebruik heet worden",
        ],
        "verdict": "Een toegankelijke allrounder voor wie een traditionele "
        "koolstofstalen pan van een bekend Nederlands merk zoekt.",
    },

    "ikea_vardagen_28": {
        "slug": "ikea-vardagen-koolstofstaal-28",
        "name": "IKEA VARDAGEN",
        "description": "Betaalbare koolstofstalen koekenpan die na inbranden een "
        "natuurlijke patinalaag ontwikkelt en volledig in de oven kan worden gebruikt.",
        "brand": "IKEA",
        "diameter": 28,
        "material": "Koolstofstaal met stalen handgreep",
        "features": [
            "Geschikt voor inductie",
            "Ovenbestendig",
            "Volledig metalen constructie",
        ],
        "rating": 4.3,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 29.99,
        "price_last_checked": "2026-09-02",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.ikea.com/nl/nl/p/vardagen-koekenpan-koolstofstaal-20581333/",
        "award": "💰 Budget keuze",
        "price_range": "€",
        "image": "ikea-vardagen-koolstofstaal-28cm.webp",
        "image_path": "images/products/koolstofstalen-koekenpannen",
        "pros": [
            "Zeer scherpe aanschafprijs",
            "Volledig ovenbestendig",
        ],
        "cons": [
            "Moet voor gebruik worden ingebrand",
            "Met ruim 2 kg relatief zwaar",
        ],
        "verdict": "Onze budgetkeuze voor wie voor weinig geld een volwaardige "
        "koolstofstalen koekenpan voor fornuis en oven zoekt.",
    },

    # 30CM KOOLSTOFSTALEN / PLAATSTALEN KOEKENPANNEN

    "debuyer_carbone_plus_30": {
        "slug": "debuyer-carbone-plus-30",
        "name": "De Buyer Carbone Plus",
        "description": "Professionele plaatstalen koekenpan van 3 mm dik staal "
        "voor bakken en aanbraden op hoge temperaturen.",
        "brand": "De Buyer",
        "diameter": 30,
        "material": "3 mm dik koolstofstaal / plaatstaal",
        "features": [
            "Geschikt voor inductie",
            "Geschikt voor ovengebruik",
            "3 mm dikke constructie",
        ],
        "rating": 4.8,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 59.99,
        "price_last_checked": "2026-09-03",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Fde-buyer-carbone-plus-koekenpan-o-bovenaan-30cm-plaatstaal%2F9200000065493184%2F&name=De%20Buyer%20Carbone%20Plus%20Koekenpan%20-%2030cm%20-%20Plaatstaal%20-%20Geschikt%20voor%20inductie",
        "retailer_url": "https://www.bol.com/nl/nl/p/de-buyer-carbone-plus-koekenpan-o-bovenaan-30cm-plaatstaal/9200000065493184/",
        "award": "🏆 Beste keuze",
        "price_range": "€€",
        "image": "debuyer-carbone-plus-30cm.webp",
        "image_path": "images/products/koolstofstalen-koekenpannen",
        "pros": [
            "Robuuste constructie van 3 mm dik plaatstaal",
        ],
        "cons": [
            "Met ongeveer 2,35 kg relatief zwaar",
            "Moet voor gebruik worden ingebrand",
        ],
        "verdict": "Onze beste keuze voor wie een ruime en bijzonder robuuste "
        "koolstofstalen koekenpan met professionele bakeigenschappen zoekt.",
    },

    "netherton_foundry_induction_30": {
        "slug": "netherton-foundry-induction-30",
        "name": "Netherton Foundry Induction",
        "description": "Handgemaakte plaatstalen koekenpan met extra dikke "
        "3 mm constructie, vooringebrande lijnzaadolielaag en houten greep.",
        "brand": "Netherton Foundry",
        "diameter": 30,
        "material": "3 mm dik plaatstaal, voorbehandeld met lijnzaadolie",
        "features": [
            "Geschikt voor inductie",
            "Vooringebrand met lijnzaadolie",
            "Handgemaakt",
            "Eikenhouten handgreep",
        ],
        "rating": 4.8,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 119.95,
        "price_last_checked": "2026-09-03",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.greenjump.nl/Product/Eten-en-Drinken/Koken/Koekenpannen/Koekenpan-plaatstaal-Inductie/Maat.30%20cm",
        "award": "💎 Premium keuze",
        "price_range": "€€€€",
        "image": "netherton-foundry-induction-30cm.webp",
        "image_path": "images/products/koolstofstalen-koekenpannen",
        "pros": [
            "Handgemaakte hoogwaardige constructie",
            "Vooringebrand en vrijwel direct klaar voor gebruik",
            "Extra dikke 3 mm uitvoering speciaal geschikt voor inductie",
        ],
        "cons": [
            "Relatief hoge aanschafprijs",
            "Met ongeveer 2,25 kg relatief zwaar",
            "Houten handgreep beperkt de inzetbaarheid in de oven",
        ],
        "verdict": "Onze premium keuze voor wie handgemaakt plaatstaal, een dikke "
        "inductiegeschikte constructie en hoogwaardige afwerking belangrijk vindt.",
    },

    "bk_black_steel_30": {
        "slug": "bk-black-steel-30",
        "name": "BK Black Steel",
        "description": "Plaatstalen koekenpan die snel opwarmt en tijdens gebruik "
        "een natuurlijke patinalaag met antiaanbakeigenschappen ontwikkelt.",
        "brand": "BK",
        "diameter": 30,
        "material": "Plaatstaal",
        "features": [
            "Geschikt voor inductie",
            "Ovenbestendig tot 230 °C",
            "Geschikt voor barbecue",
            "Geen synthetische antiaanbaklaag",
        ],
        "rating": 4.3,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 43.95,
        "price_last_checked": "2026-09-03",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Fbk-black-steel-koekenpan-o-30-cm-inductie%2F9300000001596254%2F&name=BK%20Black%20Steel%20Koekenpan%20-%20%C3%98%2030%20cm%20-%20Koolstofstaal%20-%20Inductie%20-%20PFAS-vrij",
        "retailer_url": "https://www.bol.com/nl/nl/p/bk-black-steel-koekenpan-o-30-cm-inductie/9300000001596254/",
        "award": None,
        "price_range": "€€",
        "image": "bk-black-steel-30cm.webp",
        "image_path": "images/products/koolstofstalen-koekenpannen",
        "pros": [
            "Snelle en efficiënte warmtegeleiding",
            "Geschikt voor oven en barbecue",
        ],
        "cons": [
            "Handgreep wordt tijdens gebruik heet",
            "Relatief dunnere constructie",
        ],
        "verdict": "Een toegankelijke allrounder voor wie een ruime plaatstalen "
        "koekenpan van een bekend Nederlands merk zoekt.",
    },

    "blackwell_carbon_steel_30": {
        "slug": "blackwell-carbon-steel-30",
        "name": "Blackwell Carbon Steel",
        "description": "Relatief lichte carbonstalen koekenpan zonder synthetische "
        "antiaanbaklaag die door inbranden een natuurlijke patinalaag ontwikkelt.",
        "brand": "Blackwell",
        "diameter": 30,
        "material": "2 mm dik carbonstaal",
        "features": [
            "Geschikt voor inductie",
            "Ovenbestendig tot 220 °C",
            "Geschikt voor barbecue",
        ],
        "rating": 4.2,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 44.99,
        "price_last_checked": "2026-09-03",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://cookinglife.nl/products/blackwell-koekenpan-carbon-staal-30cm",
        "award": None,
        "price_range": "€€",
        "image": "blackwell-carbon-steel-30cm.webp",
        "image_path": "images/products/koolstofstalen-koekenpannen",
        "pros": [
            "Met ongeveer 1,5 kg relatief licht voor het formaat",
            "Geschikt voor oven en barbecue",
        ],
        "cons": [
            "Dunnere 2 mm constructie dan meerdere alternatieven",
            "Moet zelf worden ingebrand",
        ],
        "verdict": "Een praktische keuze voor wie een ruime carbonstalen pan zoekt "
        "die duidelijk lichter is dan de zwaarste 30 cm-modellen.",
    },

    "bk_solid_steel_30": {
        "slug": "bk-solid-steel-30",
        "name": "BK Solid Steel",
        "description": "Robuuste plaatstalen koekenpan met gietijzeren handgreep "
        "voor bakken op hoge temperatuur, ovengebruik en barbecue.",
        "brand": "BK",
        "diameter": 30,
        "material": "Plaatstaal met gietijzeren handgreep",
        "features": [
            "Geschikt voor inductie",
            "Ovenbestendig tot 230 °C",
            "Geschikt voor barbecue",
            "Gietijzeren handgreep",
        ],
        "rating": 4.2,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 29.59,
        "price_last_checked": "2026-09-03",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Fbk-solid-steel-koekenpan-o-30-cm-plaatstaal-inductie-bbq%2F9300000104755541%2F&name=BK%20Solid%20Steel%20BBQ%20koekenpan%2030cm%20-%20Plaatstaal%20-%20ovengeschikt%20tot%20230%C2%B0C",
        "retailer_url": "https://www.bol.com/nl/nl/p/bk-solid-steel-koekenpan-o-30-cm-plaatstaal-inductie-bbq/9300000104755541/",
        "award": None,
        "price_range": "€",
        "image": "bk-solid-steel-30cm.webp",
        "image_path": "images/products/koolstofstalen-koekenpannen",
        "pros": [
            "Scherpe aanschafprijs",
            "Geschikt voor oven en barbecue",
            "Robuuste volledig metalen constructie",
        ],
        "cons": [
            "Gietijzeren handgreep wordt heet",
        ],
        "verdict": "Een scherp geprijsde en robuuste volledig metalen pan voor wie "
        "veelzijdigheid op fornuis, barbecue en in de oven belangrijk vindt.",
    },

    "hendi_traditioneel_30": {
        "slug": "hendi-traditioneel-30",
        "name": "HENDI Traditioneel",
        "description": "Traditionele professionele koekenpan van 3 mm dik zwaar "
        "carbonstaal met een naadloos gelaste stalen handgreep.",
        "brand": "HENDI",
        "diameter": 30,
        "material": "3 mm dik carbonstaal / plaatstaal",
        "features": [
            "Geschikt voor inductie",
            "3 mm dikke constructie",
            "Naadloos gelaste stalen handgreep",
            "Hoge hittebestendigheid",
        ],
        "rating": 4.4,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 25.66,
        "price_last_checked": "2026-09-03",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Fhendi-stalen-koekenpan-o30cm%2F9200000046565039%2F&name=HENDI%20Traditionele%20koekenpan%20%E2%80%93%20plaatstaal%20%E2%80%93%20hoge%20hittebestendigheid%20%E2%80%93%20%E2%8C%80300%20mm",
        "retailer_url": "https://www.bol.com/nl/nl/p/hendi-stalen-koekenpan-o30cm/9200000046565039/",
        "award": "💰 Budget keuze",
        "price_range": "€",
        "image": "hendi-traditioneel-30cm.webp",
        "image_path": "images/products/koolstofstalen-koekenpannen",
        "pros": [
            "Zeer scherpe aanschafprijs",
            "Robuuste 3 mm dikke professionele constructie",
            "Naadloos gelaste handgreep",
        ],
        "cons": [
            "Met ongeveer 2,36 kg relatief zwaar",
            "Moet zelf worden ingebrand",
        ],
        "verdict": "Onze budgetkeuze voor wie voor weinig geld een zware en "
        "professioneel uitgevoerde koolstofstalen koekenpan zoekt.",
    },

    # 32CM KOOLSTOFSTALEN / PLAATSTALEN KOEKENPANNEN

    "debuyer_mineral_b_32": {
        "slug": "debuyer-mineral-b-32",
        "name": "De Buyer Mineral B",
        "description": "Royale plaatstalen koekenpan met beschermende "
        "bijenwasafwerking, tegengreep en een natuurlijke patinalaag "
        "die zich tijdens gebruik ontwikkelt.",
        "brand": "De Buyer",
        "diameter": 32,
        "material": "Koolstofstaal met beschermende bijenwasafwerking",
        "features": [
            "Geschikt voor inductie",
            "Tegengreep voor extra houvast",
            "Kortdurend geschikt voor ovengebruik",
        ],
        "rating": 4.8,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 44.89,
        "price_last_checked": "2026-09-03",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Fdebuyer-mineral-b-element-koekenpan-o-32-cm%2F9200000002756848%2F&name=De%20Buyer%20Mineral%20B%20Element%20Koekenpan%20-%2032%20cm%20-%20Natuurlijke%20antiaanbakbescherming",
        "retailer_url": "https://www.bol.com/nl/nl/p/debuyer-mineral-b-element-koekenpan-o-32-cm/9200000002756848/",
        "award": "🏆 Beste keuze",
        "price_range": "€€",
        "image": "debuyer-mineral-b-32cm.webp",
        "image_path": "images/products/koolstofstalen-koekenpannen",
        "pros": [
            "Geschikt voor hoge baktemperaturen",
            "Stevige constructie",
            "Tegengreep maakt de grote pan beter hanteerbaar",
        ],
        "cons": [
            "Met ongeveer 2,63 kg relatief zwaar",
            "Moet voor optimaal gebruik worden ingebrand",
            "Alleen kortdurend geschikt voor de oven",
        ],
        "verdict": "Onze beste keuze voor wie een ruime, robuuste en relatief "
        "betaalbare koolstofstalen koekenpan voor grotere bereidingen zoekt.",
    },

    "debuyer_mineral_b_pro_32": {
        "slug": "debuyer-mineral-b-pro-32",
        "name": "De Buyer Mineral B Pro",
        "description": "Premium plaatstalen koekenpan met bijenwasafwerking, "
        "ergonomische RVS handgreep, tegengreep en volledige "
        "geschiktheid voor ovengebruik.",
        "brand": "De Buyer",
        "diameter": 32,
        "material": "Koolstofstaal met beschermende bijenwasafwerking",
        "features": [
            "Geschikt voor inductie",
            "Volledig ovenbestendig",
            "Ergonomische RVS handgreep",
            "Tegengreep voor extra houvast",
        ],
        "rating": 4.9,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 95.49,
        "price_last_checked": "2026-09-03",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.knivesandtools.nl/nl/pt/-de-buyer-mineral-b-pro-element-koekenpan-32-cm-deb5680-32.htm",
        "award": "💎 Premium keuze",
        "price_range": "€€€",
        "image": "debuyer-mineral-b-pro-32cm.webp",
        "image_path": "images/products/koolstofstalen-koekenpannen",
        "pros": [
            "Volledig geschikt voor gebruik in de oven",
            "Hoogwaardige RVS handgreep en praktische tegengreep",
        ],
        "cons": [
            "Hoge aanschafprijs",
            "Met ongeveer 3,19 kg zeer zwaar",
            "Moet worden ingebrand",
        ],
        "verdict": "Onze premium keuze voor wie maximale bouwkwaliteit, "
        "ovenbestendigheid en een hoogwaardige RVS greep belangrijk vindt.",
    },

    "blackwell_carbon_steel_32": {
        "slug": "blackwell-carbon-steel-32",
        "name": "Blackwell Carbon Steel",
        "description": "Relatief lichte carbonstalen koekenpan van 2 mm dik staal "
        "zonder synthetische antiaanbaklaag voor royale dagelijkse bereidingen.",
        "brand": "Blackwell",
        "diameter": 32,
        "material": "2 mm dik carbonstaal",
        "features": [
            "Geschikt voor inductie",
            "Ovenbestendig tot 220 °C",
            "Geschikt voor barbecue",
        ],
        "rating": 4.2,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 49.99,
        "price_last_checked": "2026-09-03",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "",
        "retailer_url": "https://www.cookinglife.nl/products/blackwell-koekenpan-carbon-staal-32cm",
        "award": None,
        "price_range": "€€",
        "image": "blackwell-carbon-steel-32cm.webp",
        "image_path": "images/products/koolstofstalen-koekenpannen",
        "pros": [
            "Met ongeveer 1,82 kg relatief licht voor een pan van 32 cm",
            "Geschikt voor oven en barbecue",
            "Grote bodemdiameter van circa 25,4 cm",
        ],
        "cons": [
            "Dunnere 2 mm constructie",
            "Moet zelf worden ingebrand",
        ],
        "verdict": "Een praktische keuze voor wie veel bakoppervlak zoekt maar "
        "een zware 32 cm-pan zo veel mogelijk wil vermijden.",
    },

    "hendi_traditioneel_32": {
        "slug": "hendi-traditioneel-32",
        "name": "HENDI Traditioneel",
        "description": "Zware professionele koekenpan van 3 mm dik plaatstaal "
        "met naadloos gelaste stalen handgreep en royale bodem.",
        "brand": "HENDI",
        "diameter": 32,
        "material": "3 mm dik koolstofstaal / plaatstaal",
        "features": [
            "Geschikt voor inductie",
            "3 mm dikke constructie",
            "Naadloos gelaste stalen handgreep",
            "Bodemdiameter van 26 cm",
        ],
        "rating": 4.4,
        "rating_count": None,
        "rating_source": "editorial",
        "price": 23.47,
        "price_last_checked": "2026-09-03",
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://partner.bol.com/click/click?p=2&t=url&s=1454330&f=TXL&url=https%3A%2F%2Fwww.bol.com%2Fnl%2Fnl%2Fp%2Fkoekenpan-gesmeed-32cm%2F9200000046565047%2F&name=HENDI%20Traditionele%20koekenpan%20%E2%80%93%20plaatstaal%20%E2%80%93%20%C3%9832%20cm%20%E2%80%93%20gelast%20handvat%20%E2%80%93%20veelzijdig%20gebruik",
        "retailer_url": "https://www.bol.com/nl/nl/p/koekenpan-gesmeed-32cm/9200000046565047/",
        "award": "💰 Budget keuze",
        "price_range": "€",
        "image": "hendi-traditioneel-32cm.webp",
        "image_path": "images/products/koolstofstalen-koekenpannen",
        "pros": [
            "Zeer scherpe aanschafprijs",
            "Robuuste constructie van 3 mm dik plaatstaal",
            "Grote bodemdiameter van 26 cm",
        ],
        "cons": [
            "Met ongeveer 2,62 kg relatief zwaar",
            "Moet meerdere keren worden ingebrand voor het eerste gebruik",
        ],
        "verdict": "Onze budgetkeuze voor wie voor weinig geld een grote en "
        "bijzonder robuuste professionele plaatstalen koekenpan zoekt.",
    },
}
