PRODUCTS = {
    "greenpan_barcelona_pro_28": {
        "slug": "greenpan-barcelona-pro-28",
        "name": "GreenPan Barcelona Pro",
        "description": "Premium keramische hapjespan zonder PFAS met Thermolon™ Infinity Pro-coating en stevig glazen deksel.",
        "brand": "GreenPan",
        "diameter": 28,
        "material": "Keramisch",
        "features": [
            "PFAS-vrij",
            "Thermolon Infinity Pro coating",
            "Inductie- en ovenbestendig",
            "Inclusief glazen deksel",
        ],
        "rating": 5,
        "rating_count": 230,
        "price": 159.90,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.greenpan.nl/products/barcelona-pro-hapjespan-met-deksel-28cm",
        "price_range": "€€€€",
        "image": "hapjespan01.jpg",
        "image_path": "images/hapjespannen",
        "pros": [
            "Zeer duurzame keramische coating",
            "Met glazen deksel",
            "Inductie- en ovenbestendig",
        ],
        "cons": [
            "Hogere prijsklasse",
            "Iets zwaarder door RVS buitenwand",
        ],
        "verdict": "De beste allround PFAS-vrije hapjespan dankzij de combinatie van duurzaamheid, bakresultaten en bouwkwaliteit.",
        "award": "🏆 Beste keuze",
    },
    "bk_enjoy_28": {
        "slug": "bk_enjoy_28",
        "name": "BK Enjoy Keramische Hapjespan",
        "description": "Betaalbare PFAS-vrije keramische hapjespan in 28 cm, ontworpen als instapmodel voor dagelijks gebruik.",
        "brand": "BK",
        "diameter": 28,
        "material": "Keramisch",
        "features": [
            "Keramische antiaanbaklaag",
            "Geschikt voor inductie",
        ],
        "rating": 4.0,
        "rating_count": 140,
        "price": 41.93,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/bk-enjoy-hapjespan-o-28cm-deksel-pfas-vrij-zwart-koelgreep-ovenbestendig-tot-160/9300000196237263/?s2a=#productTitle",
        "price_range": "€",
        "image": "hapjespan_bk_enjoy_28cm.jpg",
        "image_path": "images/hapjespannen",
        "pros": [
            "Zeer betaalbaar",
            "PFAS-vrije keramische coating",
            "Geschikt voor dagelijks gebruik",
        ],
        "cons": [
            "Minder duurzaam dan midden- en premiumklasse",
            "Niet bedoeld voor intensief of professioneel gebruik",
        ],
        "verdict": "Een toegankelijke en betaalbare PFAS-vrije hapjespan van 28 cm, ideaal voor wie gezond wil koken zonder veel uit te geven.",
        "award": "💰 Budget keuze",
    },
    "woll_ecolite_qxr_28": {
        "slug": "woll-ecolite-qxr-28",
        "name": "WOLL Eco Lite QXR",
        "description": "Premium PFAS-vrije hapjespan met QXR-keramische antiaanbaklaag, lichtgewicht body en stevige inductiebodem.",
        "brand": "WOLL",
        "diameter": 28,
        "material": "Keramisch",
        "features": [
            "PFAS-vrij",
            "QXR-keramische coating",
            "Lichtgewicht premium constructie",
        ],
        "rating": 5,
        "rating_count": 140,
        "price": 104.90,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/hapjespan-o-28-cm-3-3-l-gerecycled-aluminium-qxr-non-stick-inductie-woll-ecolite-qxr/9300000180122490/",
        "price_range": "€€€",
        "image": "hapjespan03.jpg",
        "image_path": "images/hapjespannen",
        "pros": [
            "QXR-keramische coating zonder PFAS",
            "Uitstekende warmteverdeling",
            "Lichtgewicht voor een premium pan",
        ],
        "cons": [
            "Hogere prijsklasse",
            "Handwas aanbevolen",
        ],
        "verdict": "Een hoogwaardige hapjespan met uitstekende antiaanbakprestaties en duurzame afwerking.",
        "award": "💎 Premium keuze",
    },
    "greenchef_diamond_28": {
        "slug": "greenchef-diamond-28",
        "name": "GreenChef Diamond Induction",
        "description": "PFAS-vrije keramische hapjespan met diamantversterkte coating en deksel.",
        "brand": "GreenChef",
        "diameter": 28,
        "material": "Keramisch",
        "features": [
            "PFAS-vrij",
            "Diamantversterkte keramische coating",
            "Inclusief deksel",
        ],
        "rating": 4.5,
        "rating_count": 150,
        "price": 40.57,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/greenchef-diamond-inductie-hapjespan-o28-cm-keramisch-pfas-vrij/9200000131435585/",
        "price_range": "€€",
        "award": "🥇 Meest gekozen",
        "image": "hapjespan04.jpg",
        "image_path": "images/hapjespannen",
        "pros": [
            "Zeer goede prijs-kwaliteitverhouding",
            "Diamantversterkte coating",
            "Inclusief deksel",
        ],
        "cons": [
            "Niet ovenbestendig",
            "Niet geschikt voor metalen spatels",
        ],
        "verdict": "Een uitstekende middenklasser die verrassend goede prestaties levert voor zijn prijs.",
    },
    "bk_easy_induction_28": {
        "slug": "bk-easy-induction-28",
        "name": "BK Easy Induction Ceramic",
        "description": "Betaalbare PFAS-vrije hapjespan met keramische antiaanbaklaag en stevige koudgreep.",
        "brand": "BK",
        "diameter": 28,
        "material": "Keramisch",
        "features": [
            "PFAS-vrij",
            "Keramische antiaanbaklaag",
            "Inclusief glazen deksel",
        ],
        "rating": 4,
        "rating_count": 95,
        "price": 59.99,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/bk-easy-induction-ceramic-hapjespan-met-deksel-o28cm-4-6l-inductie-pfas-vrij/9300000032891765/",
        "price_range": "€",
        "image": "hapjespan02.jpg",
        "image_path": "images/hapjespannen",
        "pros": [
            "Scherpe prijs",
            "Keramische PFAS-vrije laag",
            "Met glazen deksel",
        ],
        "cons": [
            "Niet ovenbestendig",
            "Coating slijt sneller bij intensief gebruik",
        ],
        "verdict": "Een uitstekende keuze voor dagelijks gebruik tegen een vriendelijke prijs.",
    },
    "be_living_28": {
        "slug": "be-living-28",
        "name": "BE Living",
        "description": "Toegankelijke PFAS-vrije hapjespan met glazen deksel en keramische coating.",
        "brand": "BE Living",
        "diameter": 28,
        "material": "Keramisch",
        "features": [
            "PFAS-vrij",
            "Inclusief glazen deksel",
            "Betaalbaar",
        ],
        "rating": 3.5,
        "rating_count": 60,
        "price": 46.95,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/be-living-hapjespan-met-deksel-o-28-cm-sauteerpan-keramisch-inductie-pfas-vrij-anti-aanbak-delight-series/9300000236794346/",
        "price_range": "€€",
        "image": "hapjespan06.jpg",
        "image_path": "images/hapjespannen",
        "pros": [
            "Met glazen deksel",
            "PFAS-vrije coating",
            "Vriendelijk geprijsd",
        ],
        "cons": [
            "Coating minder duurzaam",
            "Niet geschikt voor metalen spatels",
        ],
        "verdict": "Een voordelige keuze voor wie een complete PFAS-vrije hapjespan zoekt.",
    },
    "greenpan_torino_28": {
        "slug": "greenpan-torino-28",
        "name": "GreenPan Torino",
        "description": "Solide PFAS-vrije hapjespan met Thermolon-keramische coating.",
        "brand": "GreenPan",
        "diameter": 28,
        "material": "Keramisch",
        "features": [
            "PFAS-vrij",
            "Thermolon coating",
            "Lichtgewicht",
        ],
        "rating": 4,
        "rating_count": 80,
        "price": 64.00,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.coolblue.nl/product/819625/greenpan-torino-keramische-hapjespan-met-deksel-28-cm.html",
        "price_range": "€€",
        "image": "hapjespan07.jpg",
        "image_path": "images/hapjespannen",
        "pros": [
            "Goede prijs-kwaliteitverhouding",
            "Fijne antiaanbakeigenschappen",
            "Relatief licht",
        ],
        "cons": [
            "Niet geschikt voor hoge temperaturen",
            "Coating vraagt voorzichtig gebruik",
        ],
        "verdict": "Een toegankelijke PFAS-vrije hapjespan voor regelmatig gebruik.",
    },
    "le_creuset_tns_pro_28": {
        "slug": "le-creuset-tns-pro-28",
        "name": "Le Creuset Toughened Non-Stick PRO",
        "description": "Zeer duurzame PFAS-vrije hapjespan met professionele antiaanbaklaag.",
        "brand": "Le Creuset",
        "diameter": 28,
        "material": "Non-stick (PFAS-vrij)",
        "features": [
            "PFAS-vrije TNS PRO coating",
            "Oven- en inductiegeschikt",
            "Professionele duurzaamheid",
        ],
        "rating": 5.0,
        "rating_count": 70,
        "price": 135.00,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.stijlvolinhuis.nl/sauteerpan-le-creuset-les-forgees-mat-zwart-28-cm?utm_source=bing&utm_medium=cpc&utm_campaign=shopping&etrias_source=1&etrias_source=4&etrias_campaign=37&msclkid=10cbf3b6cc911a848a399a13d51a5b7a",
        "price_range": "€€€€",
        "image": "hapjespan08.jpg",
        "image_path": "images/hapjespannen",
        "pros": [
            "Zeer duurzame coating",
            "Uitstekende warmteverdeling",
            "Ovenbestendig",
        ],
        "cons": [
            "Geen deksel",
            "Hoge prijs",
        ],
        "verdict": "Een uitzonderlijk hoogwaardige hapjespan voor wie duurzaamheid en prestaties zoekt.",
    },
    "de_buyer_mineral_b_28": {
        "slug": "de-buyer-mineral-b-28",
        "name": "De Buyer Mineral B Element",
        "description": "Coatingvrije hapjespan van koolstofstaal, volledig PFAS-vrij.",
        "brand": "De Buyer",
        "diameter": 28,
        "material": "Koolstofstaal",
        "features": [
            "Volledig PFAS-vrij",
            "Natuurlijke antiaanbaklaag (patina)",
            "Zeer hittebestendig",
        ],
        "rating": 4.5,
        "rating_count": 150,
        "price": 93.95,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/debuyer-mineral-b-black-hapjespan-staal-o-28cm/9300000013627556/?cid=1767589614793-2639539760505&bltgh=8c226bd5-9cdc-477e-9b82-0946f98e9286.ProductList_Middle.0.ProductImage",
        "price_range": "€€€",
        "award": "🥇 Meest duurzaam",
        "image": "hapjespan09.jpg",
        "image_path": "images/hapjespannen",
        "pros": [
            "Volledig coatingvrij",
            "Zeer duurzaam",
            "Geschikt voor hoge temperaturen",
        ],
        "cons": [
            "Onderhoud vereist",
            "Niet vaatwasserbestendig",
        ],
        "verdict": "Een natuurlijke en duurzame hapjespan voor liefhebbers van traditioneel bakken.",
    },
    "beka_cicla_28": {
        "slug": "beka-cicla-28",
        "name": "Beka Cicla",
        "description": "PFAS-vrije hapjespan van gerecycled aluminium met keramische coating en glazen deksel.",
        "brand": "Beka",
        "diameter": 28,
        "material": "Keramisch",
        "features": [
            "PFAS-vrij",
            "Gerecycled aluminium",
            "Inclusief glazen deksel",
        ],
        "rating": 4.5,
        "rating_count": 55,
        "price": 85.00,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/beka-cicla-sauteerpan-hapjespan-o-28cm-met-deksel-uit-glas-gerecycleerd-rvs-pfas-vrij-2-stevige-handvaten-geschikt-voor-inductie-vaatwasser/9300000226669764/",
        "price_range": "€€",
        "image": "hapjespan10.jpg",
        "image_path": "images/hapjespannen",
        "pros": [
            "PFAS-vrije keramische laag",
            "Duurzaam materiaal",
            "Inclusief glazen deksel",
        ],
        "cons": [
            "Niet geschikt voor metalen spatels",
            "Gevoelig voor schuurmiddelen",
        ],
        "verdict": "Een duurzame en complete hapjespan met focus op gezond koken.",
    },

# 24 CM HAPJESPANNEN
    "greenpan_barcelona_pro_24": {
        "slug": "greenpan-barcelona-pro-24",
        "name": "GreenPan Barcelona Pro",
        "description": "Premium keramische hapjespan zonder PFAS met Thermolon™ Infinity Pro-coating en stevig glazen deksel.",
        "brand": "GreenPan",
        "diameter": 24,
        "material": "Keramisch",
        "features": [
            "PFAS-vrij",
            "Thermolon Infinity Pro coating",
            "Inductie- en ovenbestendig",
            "Inclusief glazen deksel",
        ],
        "rating": 5,
        "rating_count": 230,
        "price": 149.90,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://greenpan.nl/products/barcelona-pro-hapjespan-met-deksel-24cm?pr_prod_strat=e5_desc&pr_rec_id=d6a75f47e&pr_rec_pid=7939103457538&pr_ref_pid=7939103490306&pr_seq=uniform",
        "price_range": "€€€€",
        "image": "greenpan-barcelona-pro-24cm.jpg",
        "image_path": "images/hapjespannen",
        "pros": [
            "Zeer duurzame keramische coating",
            "Met glazen deksel",
            "Inductie- en ovenbestendig",
        ],
        "cons": [
            "Hogere prijsklasse",
            "Iets zwaarder door RVS buitenwand",
        ],
        "verdict": "De beste allround PFAS-vrije hapjespan dankzij de combinatie van duurzaamheid, bakresultaten en bouwkwaliteit.",
        "award": "🏆 Beste keuze",
    },

"bk_brilliant_24": {
   "slug": "bk_brilliant_24",
   "name": "BK Brilliant Keramische Hapjespan",
   "description": "PFAS-vrije keramische hapjespan met moderne afwerking en solide bouwkwaliteit, geschikt voor dagelijks gebruik in het 24 cm formaat.",
   "brand": "BK",
   "diameter": 24,
   "material": "Keramisch",
   "features": [
       "Keramische antiaanbaklaag",
       "Geschikt voor inductie",
   ],
   "rating": 4.5,
   "rating_count": 110,
   "price": 54.00,
   "currency": "EUR",
   "availability": "InStock",
   "affiliate_url": "https://www.bol.com/nl/nl/p/bk-brilliant-hapjespan-met-deksel-o24-cm-inductie-anti-aanbak-pfas-vrij/9300000121455778/?Referrer=ADVNLGOO002032-S--9300000121455778-PMAX-C-22285073517&gad_source=1&gad_campaignid=22295465893&gclid=CjwKCAiAmePKBhAfEiwAU3Ko3OygxSFQwGval1nZKIn9QxgspnYgE-63JvBsO63YAPmx7CXaY9Lx9RoCVF4QAvD_BwE",
   "price_range": "€€",
   "image": "hapjespan_bk_brilliant_24cm.jpg",
   "image_path": "images/hapjespannen",
   "pros": [
       "PFAS-vrije keramische coating",
       "Degelijke bouwkwaliteit",
       "Geschikt voor alle warmtebronnen",
   ],
   "cons": [
       "Duurder dan instapmodellen",
       "Niet bedoeld voor zeer hoge temperaturen",
   ],
   "verdict": "Een uitstekende keuze voor dagelijks gebruik tegen een vriendelijke prijs.",
   "award": "💰 Budget keuze",
},

"woll_ecolite_qxr_24": {
        "slug": "woll_ecolite_qxr_24",
        "name": "WOLL Eco Lite QXR",
        "description": "Premium PFAS-vrije hapjespan met QXR-keramische antiaanbaklaag, lichtgewicht body en stevige inductiebodem.",
        "brand": "WOLL",
        "diameter": 24,
        "material": "Keramisch",
        "features": [
            "PFAS-vrij",
            "QXR-keramische coating",
            "Lichtgewicht premium constructie",
        ],
        "rating": 5,
        "rating_count": 140,
        "price": 94.90,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/hapjespan-o-24-cm-2-4-l-gerecycled-aluminium-qxr-non-stick-inductie-woll-ecolite-qxr/9300000180122500/?cid=1767450391596-5574999328314&bltgh=eba0b497-dab2-4648-be8b-2dfd1bf55a25.ProductList_Middle.0.ProductImage",
        "price_range": "€€€",
        "image": "woll_ecolite_qxr_24cm.jpg",
        "image_path": "images/hapjespannen",
        "pros": [
            "QXR-keramische coating zonder PFAS",
            "Uitstekende warmteverdeling",
            "Lichtgewicht voor een premium pan",
        ],
        "cons": [
            "Hogere prijsklasse",
            "Handwas aanbevolen",
        ],
        "verdict": "Een hoogwaardige hapjespan met uitstekende antiaanbakprestaties en duurzame afwerking.",
        "award": "💎 Premium keuze",
    },

    "greenchef_prime_24": {
        "slug": "greenchef_prime_24",
        "name": "GreenChef Prime Keramische Hapjespan",
        "description": "Hoogwaardige PFAS-vrije keramische hapjespan met duurzame Thermolon™-coating, ontworpen voor dagelijks gebruik met betere slijtvastheid dan instapmodellen.",
        "brand": "GreenChef",
        "diameter": 24,
        "material": "Keramisch",
        "features": [
            "Thermolon™ keramische coating",
            "Geschikt voor inductie",
        ],
        "rating": 4.5,
        "rating_count": 120,
        "price": 49.90,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/greenchef-prime-stoofpan-24cm-pfas-vrij-hapjespan-met-deksel-geschikt-voor-inductie/9300000223447989/?cid=1767452810223-1744813173782&bltgh=38d19bd4-c329-4b75-8405-3ae4a72c708b.ProductList_Middle.0.ProductTitle",
        "price_range": "€€",
        "image": "greenchef_prime_24cm.jpg",
        "image_path": "images/hapjespannen",
        "pros": [
            "PFAS-vrije Thermolon™ keramische coating",
            "Geschikt voor inductie en andere warmtebronnen",
            "Duurzamer dan instap-keramische pannen",
        ],
        "cons": [
            "Hoger geprijsd dan budgetalternatieven",
            "Niet bedoeld voor extreem hoge temperaturen",
        ],
        "verdict": "Een solide en betrouwbare keuze voor wie in het 24 cm formaat net wat meer kwaliteit zoekt dan een budget hapjespan, zonder direct naar het premiumsegment te gaan.",
    },

    "bk_easy_induction_24": {
        "slug": "bk_easy_induction_24",
        "name": "BK Easy Induction Ceramic",
        "description": "Betaalbare PFAS-vrije hapjespan met keramische antiaanbaklaag en stevige koudgreep.",
        "brand": "BK",
        "diameter": 24,
        "material": "Keramisch",
        "features": [
            "PFAS-vrij",
            "Keramische antiaanbaklaag",
            "Inclusief glazen deksel",
        ],
        "rating": 4,
        "rating_count": 95,
        "price": 54.15,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/bk-easy-induction-ceramic-hapjespan-met-deksel-o24cm-4-6l-inductie-pfas-vrij/9300000032891767/?cid=1767450147956-7052647805877&bltgh=0d58b783-f3b3-4dbf-9f31-7fa1913df23c.ProductList_Middle.0.ProductImage",
        "price_range": "€",
        "image": "bk_easy_induction_24cm.jpg",
        "image_path": "images/hapjespannen",
        "pros": [
            "Scherpe prijs",
            "Keramische PFAS-vrije laag",
            "Met glazen deksel",
        ],
        "cons": [
            "Niet ovenbestendig",
            "Coating slijt sneller bij intensief gebruik",
        ],
        "verdict": "Een sterke middenklasse hapjespan voor wie in het 24 cm formaat een duurzame, PFAS-vrije keuze "
                   "zoekt zonder naar het premiumsegment te gaan.",

    },

"greenpan_cambridge_24": {
   "slug": "greenpan_cambridge_24",
   "name": "GreenPan Cambridge Keramische Hapjespan",
   "description": "PFAS-vrije keramische hapjespan met klassieke vormgeving en Thermolon™-coating, geschikt voor dagelijks koken in het 24 cm formaat.",
   "brand": "GreenPan",
   "diameter": 24,
   "material": "Keramisch",
   "features": [
       "Thermolon™ keramische coating",
       "Geschikt voor inductie",
   ],
   "rating": 4.5,
   "rating_count": 95,
   "price": 69.90,
   "currency": "EUR",
   "availability": "InStock",
   "affiliate_url": "https://www.bol.com/nl/nl/p/greenpan-cambridge-kookpan-met-deksel-24cm-zwart-inductie-pfas-vrij/9200000083444317/?s2a=&bltgh=sKRfWhkVCWmIs6ruYgZLjw.4_98_99.100.FeatureOptionButton#productTitle",
   "price_range": "€€",
   "image": "hapjespan_greenpan_cambridge_24cm.jpg",
   "image_path": "images/hapjespannen",
   "pros": [
       "PFAS-vrije Thermolon™ keramische coating",
       "Goede warmteverdeling",
       "Betrouwbare kwaliteit voor dagelijks gebruik",
   ],
   "cons": [
       "Minder robuust dan premium modellen",
       "Niet bedoeld voor extreem hoge temperaturen",
   ],
   "verdict": "Een solide en toegankelijke PFAS-vrije hapjespan in 24 cm, ideaal voor dagelijks koken zonder naar het premiumsegment te hoeven uitwijken.",
},

"kochstar_essenz_24": {
   "slug": "kochstar_essenz_24",
   "name": "Kochstar Essenz Keramische Hapjespan",
   "description": "Betaalbare PFAS-vrije keramische hapjespan in 24 cm, geschikt voor dagelijks gebruik en kleinere huishoudens.",
   "brand": "Kochstar",
   "diameter": 24,
   "material": "Keramisch",
   "features": [
       "Keramische antiaanbaklaag",
       "Geschikt voor inductie",
   ],
   "rating": 4,
   "rating_count": 80,
   "price": 19.99,
   "currency": "EUR",
   "availability": "OutStock",
   "affiliate_url": "https://www.bol.com/nl/nl/p/kochstar-essenz-keramische-inductie-kookpan-met-deksel-24cm-3-5l-pfas-vrij-inductie-kookpan-keramische-anti-aanbaklaag-koelgreep-zwart/9300000231848098/?Referrer=ADVNLGOO002032-S--9300000231848098-PMAX-C-22285073469&gad_source=1&gad_campaignid=22295458996&gclid=CjwKCAiAmePKBhAfEiwAU3Ko3PbjtpCOVAExYnEfH75G497ZL-kFq6FUyGkc8QtiFHiOEEpN8nh23BoCUUcQAvD_BwE",
   "price_range": "€",
   "image": "hapjespan_kochstar_essenz_24cm.jpg",
   "image_path": "images/hapjespannen",
   "pros": [
       "Zeer scherpe prijs",
       "PFAS-vrije keramische coating",
       "Geschikt voor dagelijks gebruik",
   ],
   "cons": [
       "Minder duurzaam dan midden- en premiumklasse",
       "Niet bedoeld voor intensief of professioneel gebruik",
   ],
   "verdict": "Een eenvoudige maar functionele PFAS-vrije hapjespan in 24 cm, ideaal voor wie betaalbaar en gezond wil koken zonder extra luxe.",
},


"le_creuset_tns_pro_24": {
        "slug": "le_creuset_tns_pro_24",
        "name": "Le Creuset Toughened Non-Stick PRO",
        "description": "Zeer duurzame PFAS-vrije hapjespan met professionele antiaanbaklaag.",
        "brand": "Le Creuset",
        "diameter": 24,
        "material": "Non-stick (PFAS-vrij)",
        "features": [
            "PFAS-vrije TNS PRO coating",
            "Oven- en inductiegeschikt",
            "Professionele duurzaamheid",
        ],
        "rating": 5,
        "rating_count": 70,
        "price": 117.99,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.knivesandtools.nl/nl/pt/-le-creuset-tns-sauteerpan-24-cm.htm",
        "price_range": "€€€€",
        "image": "le_creuset_tns_pro_24cm.jpg",
        "image_path": "images/hapjespannen",
        "pros": [
            "Zeer duurzame coating",
            "Uitstekende warmteverdeling",
            "Ovenbestendig",
        ],
        "cons": [
            "Geen deksel",
            "Hoge prijs",
        ],
        "verdict": "Een uitzonderlijk hoogwaardige hapjespan voor wie duurzaamheid en prestaties zoekt.",
    },

"de_buyer_mineral_b_24": {
        "slug": "de_buyer_mineral_b_24",
        "name": "De Buyer Mineral B Element",
        "description": "Coatingvrije hapjespan van koolstofstaal, volledig PFAS-vrij.",
        "brand": "De Buyer",
        "diameter": 24,
        "material": "Koolstofstaal",
        "features": [
            "Volledig PFAS-vrij",
            "Natuurlijke antiaanbaklaag (patina)",
            "Zeer hittebestendig",
        ],
        "rating": 4.5,
        "rating_count": 150,
        "price": 46.79,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/debuyer-mineral-b-element-hapjespan-o-24-cm/9200000002756864/?s2a=#productTitle",
        "price_range": "€€€",
        "award": "🥇 Meest duurzaam",
        "image": "de_buyer_mineral_b_24cm.jpg",
        "image_path": "images/hapjespannen",
        "pros": [
            "Volledig coatingvrij",
            "Zeer duurzaam",
            "Geschikt voor hoge temperaturen",
        ],
        "cons": [
            "Onderhoud vereist",
            "Niet vaatwasserbestendig",
        ],
        "verdict": "Een natuurlijke en duurzame hapjespan voor liefhebbers van traditioneel bakken.",
    },

"beka_cicla_24": {
        "slug": "beka_cicla_24",
        "name": "Beka Cicla",
        "description": "PFAS-vrije hapjespan van gerecycled aluminium met keramische coating en glazen deksel.",
        "brand": "Beka",
        "diameter": 24,
        "material": "Keramisch",
        "features": [
            "PFAS-vrij",
            "Gerecycled aluminium",
            "Inclusief glazen deksel",
        ],
        "rating": 4.5,
        "rating_count": 55,
        "price": 74.95,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/beka-cicla-sauteerpan-hapjespan-o-24cm-met-deksel-uit-glas-gerecycleerd-rvs-pfas-vrij-geschikt-voor-inductie-vaatwasser/9300000226669762/?cid=1767452436854-1101371090835&bltgh=baae5d98-154a-4850-bc75-a75a1fd8abce.ProductList_Middle.0.ProductImage",
        "price_range": "€€",
        "image": "beka_cicla_24cm.jpg",
        "image_path": "images/hapjespannen",
        "pros": [
            "PFAS-vrije keramische laag",
            "Duurzaam materiaal",
            "Inclusief glazen deksel",
        ],
        "cons": [
            "Niet geschikt voor metalen spatels",
            "Gevoelig voor schuurmiddelen",
        ],
        "verdict": "Een duurzame en complete hapjespan met focus op gezond koken.",
    },


# 30 CM HAPJESPANNEN
    "greenpan_barcelona_pro_30": {
        "slug": "greenpan_barcelona_pro_30",
        "name": "GreenPan Barcelona Pro",
        "description": "Premium keramische hapjespan zonder PFAS met Thermolon™ Infinity Pro-coating en stevig glazen deksel.",
        "brand": "GreenPan",
        "diameter": 30,
        "material": "Keramisch",
        "features": [
            "PFAS-vrij",
            "Thermolon Infinity Pro coating",
            "Inductie- en ovenbestendig",
            "Inclusief glazen deksel",
        ],
        "rating": 5,
        "rating_count": 230,
        "price": 59.90,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.bol.com/nl/nl/p/greenpan-barcelona-infinity-pro-hapjespan-met-deksel-30cm-zwart-inductie-pfas-vrij/9200000091127472/?s2a=&bltgh=gN-u-bkRofLyScIL--JPkw.4_90_91.92.FeatureOptionButton#productTitle",
        "price_range": "€€",
        "image": "greenpan-barcelona-pro-30cm.jpg",
        "image_path": "images/hapjespannen",
        "pros": [
            "Zeer duurzame keramische coating",
            "Met glazen deksel",
            "Inductie- en ovenbestendig",
        ],
        "cons": [
            "Hogere prijsklasse",
            "Iets zwaarder door RVS buitenwand",
        ],
        "verdict": "De beste allround PFAS-vrije hapjespan dankzij de combinatie van duurzaamheid, bakresultaten en bouwkwaliteit.",
        "award": "🏆 Beste keuze",
    },

"le_creuset_tns_pro_30": {
        "slug": "le_creuset_tns_pro_30",
        "name": "Le Creuset Toughened Non-Stick PRO",
        "description": "Zeer duurzame PFAS-vrije hapjespan met professionele antiaanbaklaag.",
        "brand": "Le Creuset",
        "diameter": 30,
        "material": "Non-stick (PFAS-vrij)",
        "features": [
            "PFAS-vrije TNS PRO coating",
            "Oven- en inductiegeschikt",
            "Professionele duurzaamheid",
        ],
        "rating": 5,
        "rating_count": 70,
        "price": 156.49,
        "currency": "EUR",
        "availability": "InStock",
        "affiliate_url": "https://www.knivesandtools.nl/nl/pt/-le-creuset-tns-sauteerpan-30-cm.htm",
        "price_range": "€€€€",
        "image": "le_creuset_tns_pro_30cm.jpg",
        "image_path": "images/hapjespannen",
        "pros": [
            "Zeer duurzame coating",
            "Uitstekende warmteverdeling",
            "Ovenbestendig",
        ],
        "cons": [
            "Geen deksel",
            "Hoge prijs",
        ],
        "verdict": "Een uitzonderlijk hoogwaardige hapjespan voor wie duurzaamheid en prestaties zoekt.",
    },
}
