RANKINGS = {
    20: [
        "greenpan_barcelona_pro_20",
        "demeyere_alu_pro_5_ceraforce_20",
        "kochstar_essenz_20",
        "bk_easy_induction_20",
        "greenchef_diamond_20",
        "tefal_renew_20",
        "greenpan_mayflower_20",
        "bk_enjoy_20",
        "hema_milano_20",
        "berndes_b_green_20",
    ],
    24: [
        "greenpan_barcelona_pro_24",
        "demeyere_alu_pro_5_ceraforce_24",
        "kochstar_essenz_24",
        "bk_easy_induction_24",
        "greenchef_diamond_24",
        "tefal_renew_24",
        "greenpan_torino_24",
        "bk_enjoy_24",
        "ikea_hemlagad_keramisch_24",
        "berndes_b_green_24",
    ],
    26: [
        "greenpan_barcelona_pro_26",
        "greenchef_vintage_26",
        "demeyere_alu_pro_5_ceraforce_26",
        "bk_easy_induction_26",
        "fissler_cenit_ceramic_26",
        "greenpan_venice_pro_26",
        "scanpan_ceramic_26",
    ],
    28: [
        "greenpan_barcelona_pro_28",
        "demeyere_alu_pro_5_28",
        "kochstar_essenz_28",
        "bk_easy_induction_28",
        "greenchef_diamond_28",
        "tefal_renew_28",
        "greenpan_mayflower_28",
        "brabantia_dusk_28",
        "bk_enjoy_28",
        "debuyer_ceranoa_28",
    ],
    30: [
        "greenpan_barcelona_pro_30",
        "kochstar_stein_30",
        "demeyere_alu_pro_5_ceraforce_30",
        "greenchef_diamond_30",
        "bk_easy_induction_30",
        "greenpan_torino_30",
        "tefal_renew_30",
        "brabantia_indu_plus_r_30",
        "scanpan_techniq_30",
    ],
    32: [
        "greenpan_barcelona_pro_32",
        "demeyere_alu_pro_5_ceraforce_32",
        "combekk_ceramic_pro_32",
        "bk_easy_induction_32",
        "greenpan_torino_32",
        "tefal_renew_32",
        "primecook_32",
        # "blue_diamond_32",  # vervangen door primecook_32 (Blue Diamond niet leverbaar)
        "ikea_hemlagad_keramisch_32",
        "scanpan_ceramic_32",
    ],
}
