# Generated by Django 5.2.6 on 2026-08-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateProductState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Actuele prijs in EUR. Leeg = nog niet ingevuld.', max_digits=10, null=True)),
                ('availability', models.CharField(blank=True, choices=[('InStock', 'Op voorraad'), ('OutOfStock', 'Uitverkocht'), ('PreOrder', 'Binnenkort beschikbaar'), ('BackOrder', 'Nabestelling mogelijk'), ('Discontinued', 'Niet meer leverbaar')], default='', help_text='Actuele beschikbaarheid. Leeg = nog niet ingevuld.', max_length=20)),
                ('price_last_checked', models.DateField(blank=True, help_text='Datum van laatste handmatige verificatie. NULL = nog nooit gecontroleerd.', null=True)),
            ],
            options={
                'verbose_name': 'Affiliate productstate',
                'verbose_name_plural': 'Affiliate product maintenance',
            },
        ),
    ]
